### ISSUE TITLE
Documentation:  Add example to filter_extreme for pre-filtering the input dataset

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#1000]
### Please select a category the issue is focused on?

Function Documentation

### Let us know where something needs a refresh or put your idea here!

Add example to filter_extreme for pre-filtering the input dataset

**Comment by raqpau** [comment]
Hi, is this request require adding example of the ex dataset before filtering first/last?

**Comment by bundfussr** [comment]
The issue was created to address the following tester feedback.

> Passed, but one comment. I felt having one more argument like 'filter' would allow to get the extreme observations within the filtering conditions.

The admiral team decided not to add a `filter` parameter as the input dataset can be easily restricted by calling `filter()` before `filter_extreme()`. An example should be added to demonstrate it. Something like
```
ex %>%
  filter(<a condition>) %>%
  filter_extreme(...)
```
