### ISSUE TITLE
Documentation:  Add more details to min_dates and max_dates parameter

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#1001]
### Please select a category the issue is focused on?

Function Documentation

### Let us know where something needs a refresh or put your idea here!

Add more details to min_dates and max_dates parameter. Explain why
```
impute_dtc(
  "2020",
  max_dates = list(ymd_hms("2020-07-06T12:12:12"),
                   ymd_hms("2020-08-11T11:11:11")),
  date_imputation = "last"
) 
```
results in `"2020-07-06T12:12:12"`.

**Comment by rossfarrugia** [comment]
@bundfussr could this issue be suitable for good first issue label if you add a bit more detail to help a new contributor?

**Comment by bundfussr** [comment]
@rossfarrugia , I think this should be included in the update of the imputation functions, which is of course no good first issue.

**Comment by thomas-neitmann** [comment]
@bundfussr @rossfarrugia Has this been addressed as part of the date imputation refactor?

**Comment by rossfarrugia** [comment]
i just double-checked and i think the documentation across the function page and the vignette look pretty solid now so will close this issue
