### ISSUE TITLE
Documentation:  Typo in derive_vars_suppqual()

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1003]
### Please select a category the issue is focused on?

Function Documentation

### Let us know where something needs a refresh or put your idea here!

![image](https://user-images.githubusercontent.com/10111024/157272729-c0f7e340-3b89-4a43-b5da-cb3eb63eb6d6.png)

Remove the So and need spacing between two character and domain

**Comment by rossfarrugia** [comment]
@bms63 dont worry with fixing this one as this function needs to be deprecated, as will move to metatools. see https://github.com/pharmaverse/admiral/issues/950
