### ISSUE TITLE
Documentation:  Incorrect TRTs in ADSL Template

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1004]
### Please select a category the issue is focused on?

User Guides

### Let us know where something needs a refresh or put your idea here!

![image](https://user-images.githubusercontent.com/10111024/157325809-1ccc5ce5-66a7-46e3-9195-690e2a7d4f65.png)

**Comment by bms63** [comment]
They should be ARM and ACTARM like in the ADSL Vignette

**Comment by bms63** [comment]
![image](https://user-images.githubusercontent.com/10111024/157329297-aa3ea4f6-3ee5-4d06-a4fb-49d4c307d2c0.png)

Using deprecated function

**Comment by thomas-neitmann** [comment]
@makropoa Maybe another one for you to pick up?

**Comment by rossfarrugia** [comment]
i can work on this one, i just took another ADSL template issue, so can work through both
