### ISSUE TITLE
Documentation:  Get Started has incorrect trt variables in mutate

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1005]
### Please select a category the issue is focused on?

User Guides

### Let us know where something needs a refresh or put your idea here!

![image](https://user-images.githubusercontent.com/10111024/157339179-c4b6565b-5da4-46d4-8de3-be9ac4cf9d74.png)

Treatment variables are not correct.  Should be TRT01P = ARM and TRT01A = ACTARM

**Comment by thomas-neitmann** [comment]
@makropoa This would be a nice little issue to get started with.

**Comment by thomas-neitmann** [comment]
The `vignettes/adsl.Rmd` file would need to be updated.

**Comment by bundfussr** [comment]
Both options `TRT01P = ARM, TRT01A = ACTARM` and `TRT01P = ARMCD, TRT01A = ACTARMCD` are valid (for parallel studies).

Thus I am wondering if it is worth updating the vignette.

**Comment by thomas-neitmann** [comment]
While both might be valid I would preder the long-form `ARM` and `ACTARM` text over just the short tern `--CD` variables. Plus it's a nice first issue for some of our contributors to pick up.
