### ISSUE TITLE
Documentation:  add DTHCAUS extra example

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiral#1016]
### Please select a category the issue is focused on?

Function Documentation

### Let us know where something needs a refresh or put your idea here!

https://pharmaverse.github.io/admiral/reference/derive_var_dthcaus.html - could benefit from a non-standard and bit more complex example with 3 different sources and using DS twice with different filters. I had to figure this out when comparing it against such an option that exists in the Roche standard specs, so happy to add this example.

Also at https://pharmaverse.github.io/admiral/articles/adsl.html#derive-death-variables – “`dthcause_source()`  specifications” should be `dthcaus_source()`

**Comment by koegerr** [comment]
@rossfarrugia do you think this needs to go into the next release?

**Comment by rossfarrugia** [comment]
@koegerr can't harm - i'll try and make a PR for it this week
