### ISSUE TITLE
Documentation: Update default filter_ex shown in documentation for derive_var_trtsdtm / derive_var_trtedtm

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiral#1017]
### Please select a category the issue is focused on?

Function Documentation

### Let us know where something needs a refresh or put your idea here!

https://pharmaverse.github.io/admiral/reference/derive_var_trtsdtm.html - at top says:
``filter_ex = (EXDOSE > 0 | (EXDOSE == 0 & str_detect(EXTRT, "PLACEBO"))) &
    nchar(EXSTDTC) >= 10,``

But instruction in the Arguments section below says:
``Default: EXDOSE > 0 | (EXDOSE == 0 & str_detect(EXTRT, 'PLACEBO')``

And the code does include: `& nchar(EXSTDTC) >= 10`, so this should be included in the Arguments default shown in the documentation.

Same issue as above exists for https://pharmaverse.github.io/admiral/reference/derive_var_trtedtm.html

**Comment by JMcGavigan32** [comment]
Have updated the documentation on **derive_var_trtsdtm.R** and pushed it to the 1017 Update branch. Will message somebody about it tomorrow morning and confirm whether everything looks okay and can go from there! If I have done everything alright happy to make similar change for **derive_var_trtedtm.R**!

**Comment by bms63** [comment]
Hi Jack.  You can just do a Pull Request and that will alert folks to any issues in the code.  You can assign me as a reviewer.

**Comment by JMcGavigan32** [comment]
Great. I will do that tomorrow morning, thanks Ben.
________________________________

**Comment by rossfarrugia** [comment]
Thanks @JMcGavigan32 for your contribution! Just a heads up that we usually have convention to keep the issues open until the update gets merged into main for a release - this way users are less likely to re-raise issues already fixed in devel. You can add "closes then # and issue number" in your PR and this gets done automatically when merged with main later.

**Comment by bms63** [comment]
Hi Jack,

The Issues will automatically close once we pull the `dev `branch into `main` - fingers crossed.  No need to close them yourself.  :)

**Comment by rossfarrugia** [comment]
great minds @bms63 ...

**Comment by bms63** [comment]
This process better work or I am going to riot!

**Comment by rossfarrugia** [comment]
:D "...and breathe"
