### ISSUE TITLE
Feature Request:  Investigate Hy's Law function for ADLB

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1018]
### Feature Idea

Investigate Hays Law function for ADLB

### Relevant Input

N/A

### Relevant Output

N/A

### Reproducible Example/Pseudo Code

N/A

**Comment by millerg23** [comment]
Initial investigation found this: https://www.fda.gov/media/116737/download
In particular:
**4. Assessment of Hy’s Law Cases in the Clinical Trials Database**
_NDA and BLA submissions should include a listing of possible Hy’s Law cases identified by
treatment group (e.g., subjects with any elevated AT of >3xULN, ALP <2xULN, and associated
with an increase in bilirubin ≥2xULN)._
