### ISSUE TITLE
Documentation:  ADSL Vignette and template script updates

### ISSUE THREAD

**Issue by millerg23** [pharmaverse/admiral#1019]
### Please select a category the issue is focused on?

User Guides

### Let us know where something needs a refresh or put your idea here!

ADSL vignette needs updated to replace function `derive_agegrp_fda` with `derive_var_agegrp_fda`.
Also make use of new function `derive_var_merged_exist_flag()` for population flags.
Review anywhere else the new `derive_var_merged_xxxxx` functions may be used.

**Comment by kabis-ops** [comment]
@rossfarrugia - just noticed also that the argument `filter` in  `derive_var_disposition_xxx()`  should be replaced by `filter_ds`

**Comment by rossfarrugia** [comment]
thanks @kabis-ops - hoping to get to this one this week so will make that update too

**Comment by rossfarrugia** [comment]
Also i noticed ADSL template needs updating for deprecated lstalvdt function as per #753 - will update this too (the ADSL vignette was updated already in devel)
