### ISSUE TITLE
Feature Request:  Enable imputing day only

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#1020]
### Feature Idea

The imputation functions should allow to impute the day only, i.e., if only the day is missing, it is imputed, if month and day are missing, `NA` is returned.

### Relevant Input

```
convert_dtc_to_dt(
  c("2020-12", "2020),
  date_imputation = "n-l")
```

### Relevant Output

```
"2020-12-31"
NA
```

### Reproducible Example/Pseudo Code

We love example code and it will speed up the process! REMINDER: no patient level data or company sensitive information should be shared via this open public issue

**Comment by bundfussr** [comment]
Other imputation related issues: #1001, #907, #879, #761, #727

**Comment by rossfarrugia** [comment]
@bundfussr I personally feel like this request is getting way too specific and rare to warrant being covered by admiral. it would just make the function code even more difficult to maintain. i would prefer a user just uses restrict_derivation here and checks the DTC variable to see that this only gets applied for case when missing day. if you agree please close this one.

**Comment by bundfussr** [comment]
@rossfarrugia , I would not close the issue. On the contrary, I would extend at in the way that the specification of the imputation should be more granular. There are more use cases, e.g., for ADAE.ASDTM year should be imputed (taking `min_dates` into account) while for ADAE.AENDTM year should not be imputed but `max_dates` should be considered for imputing months and days. I think it is also reasonable to impute seconds but not minutes and hours.
Thus I would update the imputation parameters such that it is possible to specify the imputation for each component (years, months, days, hours, minutes, seconds) separately.

**Comment by rossfarrugia** [comment]
now superseded by https://github.com/pharmaverse/admiral/issues/1300 so will close
