### ISSUE TITLE
Feature Request:  Implement `derive_param_merged()`

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#1022]
### Feature Idea

Implement
```
derive_param_merged(
  dataset,
  dataset_base,
  dataset_add,
  by_vars,
  order = NULL,
  new_vars = NULL,
  mode = NULL,
  filter_add = NULL,
  match_flag = NULL,
  check_type = "warning",
  duplicate_msg = NULL,
  set_values_to
)
```
The derive_param_merged function:

1. calls `derive_vars_merged()` with `dataset = dataset_base`,
2.  adds the variables specified by `set_values_to` (ideally `set_value_to` should accept expression on the right hand side),
3.  adds the observations to `dataset`

### Relevant Input

What should the input look like? REMINDER: no patient level data or company sensitive information should be shared via this open public issue

### Relevant Output

What should the output look like? REMINDER: no patient level data or company sensitive information should be shared via this open public issue

### Reproducible Example/Pseudo Code

```
derive_param_merged(
  adrs,
  dataset_base = adsl,
  dataset_add = ovr_cens,
  filter_add = AVALC %in% c("CR", "PR"),
  new_vars = vars(ADT),
  by_vars = vars(STUDYID, USUBJID),
  order = ADT,
  mode = "first",
  set_values_to = vars(
    AVALC = if_else(is.na(ADT), "N", "Y"),
    AVAL = compute_yn_order(AVALC),
    PARAMCD = "RSP",
    PARAM = "Response by Investigator (confirmation not required)",
    PARCAT1 = "Tumor Response",
    PARCAT2 = "Investigator",
    PARCAT3 = "Recist 1.1",
    ANL01FL = "Y")
)
```

**Comment by bundfussr** [comment]
Sorry, I missed the DEATH parameter.

However, we can not implement the function as it is proposed in this issue because the `set_values_to` parameter accept expressions. We could add a `date_var` parameter to `derive_param_first_event()`. Then we could use it for deriving DEATH.

What do you think?

**Comment by bundfussr** [comment]
If we set `AVALC = "Y"` in `set_values_to`, it is set for *all* observations. We could use a `mutate()` call after the `derive_param_merged()` call to rederive `AVALC`. But this would not look nice.

I would prefer a function which derives the parameter completely.

**Comment by bundfussr** [comment]
`DTHFL` is `"Y"` or null, i.e., we can not use it directly for `AVALC`.

If we add `date_var` and `dataset_source` parameter to `derive_param_first_event()` and use `DTHDT` instead of `DTHDTC`, the following call should work.
```
derive_param_first_event(
  adrs,
  dataset_adsl = adsl,
  dataset_source = adsl,
  filter_source = !is.na(DTHDT),
  date_var = DTHDT,
  set_values_to = vars(
    PARAMCD = "DEATH",
    PARAM = "Death",
    PARCAT1 = "Reference Event",
    ANL01FL = "Y"
  )
)
```
`AVALC` is set to `"Y"` for all subjects with an observation in `dataset_source` fulfilling `filter_source` condition. For all other subjects it is set to `"N"`.

**Comment by rossfarrugia** [comment]
i like your suggestion @bundfussr - will close this issue and update #1063
