### ISSUE TITLE
Onboarding:  New GSK contributors

### ISSUE THREAD

**Issue by teckla-gsk** [pharmaverse/admiral#1026]
### Onboarding tasks for Core (Roche-GSK) Team Members

- [x] Given a tour of Github from a Core member
- [x] Understand how to Create Issues and do a Pull Request
- [x] Understand the Programming Strategy
- [x] Read and understand [Developer Guides Articles](https://pharmaverse.github.io/admiral/index.html)
- [x] Invited to all relevant meetings - Stand Ups, Retrospective, Sprint Planning, Question/Comments, Backlog, Community Meeting
- [x] Given access to Box and relevant documents
- [x] Given write access to Github Repository
- [x] Slack channel invites to admiral and admiral_dev
- [x] Introduction to Teams ways of working

### Onboarding tasks for non-Core Team Members

- [x] Given a tour of Github from a Core member
- [x] Understand how to Create Issues and do a Pull Request
- [x] Understand the Programming Strategy
- [x] Read and understand [Developer Guides Articles](https://pharmaverse.github.io/admiral/index.html)
- [ ] Invited to all relevant meetings - Question/Comments, Community Meeting
- [x] Given write access to Github Repository
- [x] Slack channel invites to admiral
- [x] Introduction to Teams ways of working

**Comment by bms63** [comment]
I can't find Vishnu, Ramesh or Mary yet on GitHub

**Comment by bms63** [comment]
Vishnu is added, but I think Mary needs to accept invite

**Comment by bms63** [comment]
Does anyone else have questions, concerns comments about any of the above items?  Let us know if you want us to help pick out an issue for you.  Definitely want something easy as the process is a little overwhelming - even if you are an R expert!  

If no questions I would like to close this issue.
