### ISSUE TITLE
Discuss Hy's Law Implementation in admiral

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#1041]
Discuss if and how Hy's Law derivations should be implemented in admiral.

For Roche's implementation see ADHY tab in https://exbpbox.box.com/s/np6azqgyjewa2zzlwdt7ehykjxpvyfze

FDA document regarding Hy's Law:  https://www.fda.gov/media/116737/download
(thanks Gordon for finding it)

In particular:
4. Assessment of Hy’s Law Cases in the Clinical Trials Database
NDA and BLA submissions should include a listing of possible Hy’s Law cases identified by
treatment group (e.g., subjects with any elevated AT of >3xULN, ALP <2xULN, and associated
with an increase in bilirubin ≥2xULN).

**Comment by bms63** [comment]
#824

**Comment by bms63** [comment]
I believe this is going to be made into a separate programming workflow as both Roche and GSK create adlbhy datasets.  I'm working on getting adlbhy specs from GSK.

@millerg23  or @upadhyor anything to add?  I was going to close this issue and open as a **_Create Programming Workflow_** once we secure the GSK specs.

**Comment by upadhyor** [comment]
> I believe this is going to be made into a separate programming workflow as both Roche and GSK create adlbhy datasets. I'm working on getting adlbhy specs from GSK.
> 
> @millerg23 or @upadhyor anything to add? I was going to close this issue and open as a **_Create Programming Workflow_** once we secure the GSK specs.

I agree with above, Ben.

**Comment by bms63** [comment]
@millerg23 @yangc71 here are the adlbhy specs, vml and computational methods from gsk.

**Comment by bms63** [comment]
I made the skeleton for the ADLBHY workflow as well.  https://app.box.com/file/968108766329

**Comment by rossfarrugia** [comment]
@yangc71 @millerg23 FYI that Hinal mentioned @oreillb1 (Barbara) had been looking into Hy's Law extensively on her molecule recently and comparing Roche implementation vs industry guidelines. May be worth running our workflow past her for consideration, given she's very familiar with admiral as one of our explorers.

**Comment by yangc71** [comment]
Hy’s Law Criteria (FDA Guidance https://www.fda.gov/media/116737/download): 
(1) Alanine aminotransferase (ALT) or aspartate aminotransferase (AST) elevation of >3× the upper limit of normal (ULN). 
(2) Among trial subjects showing such ALT/AST elevations, also show elevation of serum bilirubin (TBL) elevation of >2× ULN without initial findings of cholestasis (ie, absence of elevation of alkaline phosphatase (ALP) to >2× ULN); 
(3) No other reason can be found to explain the combination of increased ALT and TBL, such as viral hepatitis A through E; other preexisting or acute liver disease; or another drug capable of causing the observed injury.

**Comment by yangc71** [comment]
Thank you Ross! We can certainly discuss more with Barbara later (I think Gordon may have already been talking with her). 
@millerg23 I started to populate the workflow document, but mostly I think we can use mutate() to derive the new variables (though it can be a lot of conditions to specify manually)? We can discuss more on the approach during our meeting next week too.

**Comment by rossfarrugia** [comment]
Thanks @yangc71 - i took the release tag off this one as Gordon mentioned more time will be needed, but appreciate if ADHY could be covered in next release for March. If you need dev support then this would be a good area for @zdz2101 and @sadchla-codes to help with after we make the Dec release.

**Comment by millerg23** [comment]
@yangc71 the information from FDA is a great start for us, and could form the initial template that @bms63 discussed.
We can build up these parameters, maybe using a function where you pass in condition, and name of PARAMCD to be created??
I think in Roche (and GSK), we look at different mulitples of ULN, so if we can get a nice way of creating the PARAMCDs described in FDA, then we can extend to Company specific derivations.
Need to wiork out when to create a PARAMCD, or when to use MCRITx derivations.

**Comment by yangc71** [comment]
> 
Thanks Gordon! Yes the ULN cutoffs are different across companies, so I'm not sure if `mutate()` would be the easiest to keep things flexible, but we can discuss more in the meeting. For the question on PARAMCD vs. MCRITx, it seems to me PARAMCD is derived when the condition depends on multiple parameters (e.g. ALT > 3xULN and BIL >= 2xULN and ALP < 2xULN), but MCRITx is derived when condition only involves one lab parameter (e.g. ALT > 3xULN -< 5xULN; ALT > 5xULN -< 10xULN etc.). We may also want to consider parameters incorporating other conditions outside of labs (e.g. like injuries, clinical jaundice from ADAE etc.). For time windowing, do you mean the window for AST/ALT elevation, or is there some other windowing we need to consider? 

I started the [ADHY workflow document](https://exbpbox.ent.box.com/file/968108766329?s=c8aqao081refyq62ebjjojkz371jn828) and we need to discuss more, but feel free to edit and make any comments in the meantime.

**Comment by bundfussr** [comment]
It seems that the situation for ADHY is similar to ADTR in admiralonco. I.e., all companies derive something similar but how the endpoints are derived and how the datasets are structured (one vs two datasets, parameter vs variables) is very different. In admiralonco we plan to create a vignette first where we show for each step some options how it could be done. It is not clear yet if and how we create a template script. It is unlikely that we will implement any endpoint specific functions for ADTR because they would be to complex due to the variations across companies.

We also discussed the `CRITx` variables. Even within Roche there is no agreement when they should be used. So the only guidance I am aware off is from the ADaMIG. I.e., for the derivation of `CRITx` and `MCRITx` you must use only variables from the current observation. So if you can't derive them by a `mutate()` call, they are not ADaM compliant.

**Comment by bms63** [comment]
Closing as being implemented in #1674 and #1637
