### ISSUE TITLE
Documentation:  Create a vignette for call_derivation(), restrict_derivation() and slice_derivation()

### ISSUE THREAD

**Issue by kabis-ops** [pharmaverse/admiral#1047]
### Please select a category the issue is focused on?

Function Documentation

### Let us know where something needs a refresh or put your idea here!

Create a vignette to showcase the use of the functions mentioned above. See also discussion in #701.

**Comment by rossfarrugia** [comment]
See example that should be referenced here: https://github.com/pharmaverse/admiral/issues/699

**Comment by thomas-neitmann** [comment]
We put all vignettes that are listed in the "Developer Guides" section on the website into `.Rbuildignore`. As this one is meant for user please do **not** add it.
