### ISSUE TITLE
Remove workarounds for R v3.5 compatibility

### ISSUE THREAD

**Issue by thomas-neitmann** [pharmaverse/admiral#1049]
Now that we no longer test {admiral} on R v3.5 let's remove the workarounds we had to introduce to be compatible with this R version (and the old package versions).

- [x] Identify all workaround
- [ ] Remove the workarounds

**Comment by thomas-neitmann** [comment]
- `deprecate_warn()` and `deprecated()` in `R/lifecycle.R`
- `as_hms()` in `R/hms.R`
- Usage of `tidyr::spread()` and `tidyr::gather()`

**Comment by bms63** [comment]
Not sure why I can't link the PR, but https://github.com/pharmaverse/admiral/pull/1078 closed this issue
