### ISSUE TITLE
Documentation:  list out options for use_ad_template for adam_name

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1053]
### Please select a category the issue is focused on?

Function Documentation

### Let us know where something needs a refresh or put your idea here!

I was messing around with the `use_ad_template`.

First thing I noticed is if I run the `use_ad_template` without any input it auto generates the adsl template.  I like that, but maybe that should be declared in the documentation, i.e. running without any agruments filled out auto-generates adsl.  Or we should require an input and ask users to put in a template option?  

Can we list out in the arguments for the possible values for the templates?  adsl, adae, etc.  Hoping adlb could be an option as well.

**Comment by bms63** [comment]
Hey Andrew.  Were you going to take this on or is this from a demo session?

**Comment by amsmith214** [comment]
demo session, i think. apologies

**Comment by wqrena** [comment]
@bms63 Hi Ben, I will work on this issue. Thanks!
