### ISSUE TITLE
Increase Testing Coverage to 90% for 0.7.0 Release

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1055]
Goal is to get that coveted green code coverage badge!  

This is coverage goal currently in devel branch on April 1st.  

![image](https://user-images.githubusercontent.com/10111024/161268475-492d379d-8f8d-4030-a0f4-3c6188118dd5.png)

Increasing coverage for any of the above 15 files could help bump us up to 90%.

**Comment by thomas-neitmann** [comment]
I would focus on our efforts first and foremost to the `derive_*()` function. Once these have 100% coverage we can move on to the other functions.
