### ISSUE TITLE
Onboarding of new USERS (as opposed to new DEVELOPERS)

### ISSUE THREAD

**Issue by esimms999-gsk** [pharmaverse/admiral#1057]
@pharmaverse/admiral

We have recordings and a slack channel for onboarding new developers, but do we have this for new users? A user should not need to know there is a thing called github or anything about developing packages ... they only need to know how to use admiral to take SDTM data and create ADSL, ADAE, etc.

Perhaps the slack channel I am looking for is the "admiral" channel? And there are vignettes on creating ADSL, etc. I know there have been presentations/demos on how to use admiral, but do we have a recording?

What else is/should be available for new users?

**Comment by bms63** [comment]
I would tag the @pharmaverse/admiral  team and see if there is any interest from folks in creating additional materials for new users.  Maybe @rossfarrugia has an opinion on creating videos and such for the https://[pharmaverse.org](https://pharmaverse.org/)/ for new users.

I feel like our vignettes are pretty thorough for a new user and should form the backbone of any recordings.  No need to re-create the wheel and this way we keep our vignettes up to date and fresh when they are presented to new users.

Unfortunately, I'm pretty tapped out for time and can't dedicate anything to creating materials for new users.  I'm sure @thomas-neitmann  is in the same boat.

**Comment by esimms999-gsk** [comment]
No need for you or Thomas to create anything such as a recording. I did want your view on if this was necessary or not.

**Comment by rossfarrugia** [comment]
@esimms999-gsk @bms63 good timing - have been discussing similar with the folks here working on admiralroche. i do personally feel like some bitesize recordings would help people quickly intro and grasp the admiral strategy. we just have to be careful to do this in a way that won't become out-dated quickly. as we were thinking of something similar to go on our internal Roche training catalog i'm happy to take this one on and then share with Eric and others for review? we'll aim to keep any Roche specifics separate so easy to share the recordings relevant to open up. timing wise i'm imagining to have something available ~June time after PHUSE US Connect and some holiday i have. Julian from the admiralroche team will be helping me.

**Comment by rossfarrugia** [comment]
p.s. on the point around pharmaverse i would like to cover this connection in one of the recordings and show the slack channel and the e2e ADaM vignette but focus would be on admiral context.

**Comment by rossfarrugia** [comment]
agree Eric! we do have some pharmaverse level slides for this level of audience covering admiral and more, e.g. we'll present the day after PHUSE US to the programming head council. we can consider over time whether we need to record such a presentation and also make available, but usually if a new company VP reaches out to any of the pharmaverse council reps with interest to get involved with open source then we tend to set up a 1:1 so we can personalise the discussion to their interest areas.
