### ISSUE TITLE
Feature Request: Implement `derive_param_first_event()`

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#1063]
### Feature Idea

```
derive_param_first_event(
  dataset,
  dataset_adsl,
  dataset_source,
  filter_source,
  date_var,
  subject_keys = vars(STUDYID, USUBJID),
  set_values_to)
```
adds a new parameter to the input dataset. `AVALC` is set to `"Y"` if an observations exists in the input dataset where `PARAMCD == source_param` and `cond == TRUE`. Otherwise `AVALC` is set to `"N"`. `AVAL` is set to `1` or `0`. `ADT` is set to the first date where the condition is fulfilled.

### Relevant Input

What should the input look like? REMINDER: no patient level data or company sensitive information should be shared via this open public issue

### Relevant Output

What should the output look like? REMINDER: no patient level data or company sensitive information should be shared via this open public issue

### Reproducible Example/Pseudo Code

```
derive_param_first_event(
  dataset = adrs,
  dataset_adsl = adsl,
  dataset_source = adrs,
  filter_source = PARAMCD == "OVR" & AVALC == "PD" & ANL01FL=”Y”,
  date_var = ADT,
  subject_keys = vars(STUDYID, USUBJID),
  set_values_to= vars(
    PARAMCD = "PD",
    PARAM = "Disease Progression by Investigator",
    PARCAT1 = "Tumor Response",
    PARCAT2 = "Investigator",
    PARCAT3 = "Recist 1.1",
    ANL01FL = "Y"))

derive_param_first_event(
  dataset = adrs,
  dataset_adsl = adsl,
  dataset_source = adsl,
  filter_source = !is.na(DTHDT),
  date_var = DTHDT,
  set_values_to = vars(
    PARAMCD = "DEATH",
    PARAM = "Death",
    PARCAT1 = "Reference Event",
    ANL01FL = "Y"
  )
)
```

**Comment by rossfarrugia** [comment]
@bundfussr given how we recently updated the {admiralonco} functions shouldn't we replace `source_param` and `condition` with a single `filter_source` argument?

e.g. in the example above you'd have `filter_source = PARAMCD == "OVR" & AVALC == "PD" & ANL01FL=”Y”`

**Comment by bundfussr** [comment]
@rossfarrugia , yes, makes sense.

**Comment by rossfarrugia** [comment]
@bundfussr issue now updated accordingly - please do the same for the code.

**Comment by rossfarrugia** [comment]
@bundfussr also updated to add `date_var` and `dataset_source` as discussed in issue 1022.
