### ISSUE TITLE
Documentation:  Add to programming strategy more examples on how we design a function

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiral#1069]
### Please select a category the issue is focused on?

Developer Guides

### Let us know where something needs a refresh or put your idea here!

Add to programming strategy: More of the good, the bad and the ugly examples of what we are aiming for with new functions in relation to all the guidance added for #954. Examples will help people to better visualize the points.

@bms63 @thomas-neitmann - @koegerr suggested best one of you guys take this on later as technical co-leads (fine to do this after the upcoming April release).

**Comment by statasaurus** [comment]
One thing I have noticed about admiral (and I don't know if this was intentional or not), is that it often wraps the tidyverse. So rather than call functions within mutate statements you will have a new_parm parameter. If this is intentional then, it should be added to the guidance, if it isn't intentional then we should probably discuss it. {metatools} does have some function like create_var_from_codelist that is like this, but also there are some smaller functions like create_subgrp which is vectorized.

**Comment by bms63** [comment]
I started working on a package template for pharmaverse packages.  Just a skeleton!  Nothign set in stone.   Maybe this issue should be moved over there https://github.com/pharmaverse/pharmaverse_templates

**Comment by rossfarrugia** [comment]
@bms63 i think your comment relates more to https://github.com/pharmaverse/admiral/issues/949 doesn't it? and for that i would suggest we make it more admiral specific (rather than pharmaverse) as we want to add in our specific pieces like our PR checklist and common package dependencies etc. happy to work with you on that one after the upcoming release, as i had it on my list to come back to this with learnings from admiralonco so far.

the issue here more relates to building on what we're adding for https://github.com/pharmaverse/admiral/issues/954 by adding some more examples to better explain how we want our new functions to be designed.

**Comment by bms63** [comment]
I was thinking that the functions that are used in all pharmaverse packages try to adhere to the similar design philosophy.  So the template would be a great spot to have these example functions.  A template within a template.  :)  This could still live inside our development guides in the admiral site or other guides with pharmaverse universe.

**Comment by rossfarrugia** [comment]
I'd say let's focus on the admiral family of packages for this bit and then we can always pick the best bits towards new pharmaverse collabs in future. we're trying not to influence too much around package design decisions etc via pharmaverse as the dev leads should feel still in control, but we can point to good examples like admiral to help.

**Comment by bms63** [comment]
@rossfarrugia @thomas-neitmann  Can we close this issue?  I think our programming strategy captures most of our needs for "designing" a function to adhere to our admiral standards.

**Comment by rossfarrugia** [comment]
OK by me, sure this is something that will always continue to improve over time.
