### ISSUE TITLE
Onboaring:  Gayatri from GSK

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1073]
### Onboarding tasks for Core (Roche-GSK) Team Members

- [x] Given a tour of Github from a Core member
- [x] Understand how to Create Issues and do a Pull Request
- [x] Understand the Programming Strategy
- [x] Read and understand [Developer Guides Articles](https://pharmaverse.github.io/admiral/index.html)
- [x] Invited to all relevant meetings - Stand Ups, Retrospective, Sprint Planning, Question/Comments, Backlog, Community Meeting
- [x] Given access to Box and relevant documents
- [x] Given write access to Github Repository
- [x] Slack channel invites to admiral and admiral_dev
- [x] Introduction to Teams ways of working

### Onboarding tasks for non-Core Team Members

- [ ] Given a tour of Github from a Core member
- [ ] Understand how to Create Issues and do a Pull Request
- [ ] Understand the Programming Strategy
- [ ] Read and understand [Developer Guides Articles](https://pharmaverse.github.io/admiral/index.html)
- [ ] Invited to all relevant meetings - Question/Comments, Community Meeting
- [ ] Given write access to Github Repository
- [ ] Slack channel invites to admiral
- [ ] Introduction to Teams ways of working

**Comment by bms63** [comment]
Hi @gg106046 I sent you slack invite.  Please sign up (this is how we communicate for general announcements and issues and such)  Recommend the other slack channels in the pharmaverse.

**Comment by bms63** [comment]
Send me your username for slack once you sign up and I will add you to admiral_dev channel

**Comment by bms63** [comment]
Hi @gg106046 HAve you had time to go through all the above tasks.  Do we need to clarify any of them?

**Comment by gg106046** [comment]
Hi @bms63! I have gone through the 'Programming strategy' and 'Developer guide articles'. I've marked them complete above. And I have been invited to the stand ups and sprint backlog meetings - should I mark "invited to all relevant meetings" as check?
And I'm not aware of what the "Box and relevant documents" contain.
Is the "Teams way of working" the same as what I followed for the Issue #972 ?

**Comment by bms63** [comment]
@duniek Can we give access to Gayatri the box files?

**Comment by duniek** [comment]
Done. @gg106046 pleas confirm

**Comment by gg106046** [comment]
@duniek @bms63 I have access to box files now. Thanks!

**Comment by bms63** [comment]
Thanks all!  Going to close this one down.
