### ISSUE TITLE
derive_var_ontrtfl - issue with example

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiral#1074]
### What happened?

https://pharmaverse.github.io/admiral/reference/derive_var_ontrtfl.html shows in the examples: 

![image](https://user-images.githubusercontent.com/82581364/162998709-aa3a72ed-7fc2-41b5-8a37-2e2016463cb6.png)

My best guess is `ymd("2020-01-02T12:00")` should be replaced with `ymd_hm("2020-01-02T12:00")`

### Session Information

NA

### Reproducible Example

NA

**Comment by rossfarrugia** [comment]
thanks @jtvrdon!

**Comment by thomas-neitmann** [comment]
@jtvrdon Are you still eager to work on this?

**Comment by bms63** [comment]
Hey @JMcGavigan32 I think we can assume that you can take this one over.

**Comment by thomas-neitmann** [comment]
@JMcGavigan32 Did you start working on this issue? If not, would it be OK if we reserve the issue for Roche's hackRthon next week?

**Comment by yli110-stat697** [comment]
Hi @thomas-neitmann and @rossfarrugia yes the issue is with `ymd()` function cannot process the time with hour and min. See test code below

```
ymd("2020-01-02T12:00")
```
gives the same warning message.

Should I simply replace `ymd` with `ymd_hm`?

**Comment by thomas-neitmann** [comment]
That looks just right 👍
