### ISSUE TITLE
Polls in Discussions

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1085]
Does this link to the poll #1084

**Comment by bms63** [comment]
@pharmaverse/admiral Maybe these polls are helpful?  #1084

**Comment by rossfarrugia** [comment]
@bms63 couldn't we just do that directly in Slack? like Christina did before around the package naming convention

**Comment by bms63** [comment]
yes i was just having fun with github - it is easier to link the poll but slack is more visible to us
