### ISSUE TITLE
Suggestion: Rename {admiral} packaged ADaM Dataset

### ISSUE THREAD

**Issue by mstackhouse** [pharmaverse/admiral#1088]
You've package ADaM data within {admiral}, which is great - but I have some concerns about keeping standard ADaM dataset names for these dataset within the package. For example - this is the issue that I've just run into:

- Reviewing code from someone else
- Dataset named advs_temp is created and read from external source
- Subsequent code references advs, not advs_temp
- All code runs without error

So, this would be a potentially common scenario within a clinical workflow. A user might try to reference advs directly, or any other adam dataset named within {admiral}, and the data will be found. But for novice users - or even experienced users like myself that weren't considering the ADaM data in admiral - this can cause some confusion. With the stack of the namespaces, the data are found and there's no inherent message that the data being referenced are pulled from {admiral}. The object is just found.

So my suggestion is to alter the names of the data so that they're unique and obviously belong within {admiral}. While packaging data is common within other pages (i.e. ggplot and the mpg dataset), within our industry specific workflows, it's pretty likely that you'll be working with datasets by these names exactly.

**Comment by rossfarrugia** [comment]
makes sense to me! @thomas-neitmann & @bms63 do you agree? maybe an "admiral_" prefix would make these more obviously dummy data? would the same be needed for {admiraltest} SDTMs?

**Comment by bms63** [comment]
I'm in favor of renaming the datasets - this happened to me as well while doing ADaM programming at GSK lol.  I guess we should get this into the next release?

**Comment by millerg23** [comment]
I can pick it up, but I am off on Monday, so Tuesday would be earliest I would look at this. Just to clarify, the following changes are required:
1) Rename all ADaM data sets in admiral/data area to have prefix of `admiral_`.
2) for each template script that creates an ADaM dataset, update final data set outputted to have prefix of `admiral_`, and make sure any ADaM data sets read in, have prefix of `admiral_`.
3) Check if any other vignettes/examples read in {admiral} ADaM datasets, and rename accordingly.

We DO NOT need to rename intermediate data sets created within templates?
We DO NOT need to change names of SDTM datasets in {admiraltest}?

**Comment by bms63** [comment]
Those steps make sense to me and timeline seems good to me!  

Maybe we should rename data in the `admiraltest `package as well.  @bundfussr @thomas-neitmann @rossfarrugia what do you all think??

...
`admiral_dm`
`admiral_vs`
...

**Comment by rossfarrugia** [comment]
@bms63 i guess the same argument holds for admiraltest too and would be safer to just rename in both. can't harm and if it makes things clearer for users and less potential risk of accidentally inputting test data instead of the required real data then makes sense to me.

**Comment by thomas-neitmann** [comment]
I agree that we should rename the datasets in both packages. `admiral_` sounds like a reasonable prefix for both packages to me.

**Comment by thomas-neitmann** [comment]
I created a [issue](https://github.com/pharmaverse/admiraltest/issues/30) for this in {admiraltest}.

**Comment by sophie-gem** [comment]
I have created an [issue](https://github.com/pharmaverse/admiral/issues/1108) to update {admiraltest} references and will work on this tomorrow. 

I was wondering if I should also update the names of data within the {admiral} package within that issue also or whether it would be best to do this separately?

**Comment by rossfarrugia** [comment]
@sophie-gem thanks for picking this up! as it's all closely connected i'd be happy for you to self-assign to this issue as well and just do 1 admiral PR for both these. that probably contravenes our best practice but in this case it makes sense to me.

**Comment by sophie-gem** [comment]
Right ok, I'll do it all in one then - thanks @rossfarrugia! 

(I'll make the changes as part of the 1108_update_references_to_admiraltest_data branch and then link both these issues to the subsequent PR).

**Comment by sophie-gem** [comment]
Can I just confirm, for the example_scripts, is the following ok

```
data("admiral_ae")
data("admiral_suppae")

ae <- convert_blanks_to_na(admiral_ae)
suppae <- convert_blanks_to_na(admiral_suppae)
```

Or would you prefer me to also change the variable names throughout the program?

**Comment by bundfussr** [comment]
@sophie-gem , I would not change the variable names throughout the program because then the users would need to change them back when they copy the code.

**Comment by sophie-gem** [comment]
Makes sense, I shall just do as above then - many thanks @bundfussr.

**Comment by thomas-neitmann** [comment]
I'm not quite sure about that. Wasn't part of the motivation for renaming the datasets to not have the same names as "real" datasets. @bms63 Can you comment?

**Comment by bms63** [comment]
What was the original problem?  #1088

Is the template causing the issue or how we have these datasets in the package??

**Comment by bundfussr** [comment]
I think the problem was that if a user used the dataset name `adsl` but did not have such dataset in the study, the ADSL dataset from admiral was used silently. As we have renamed the datasets in admiral, this should no longer happen.

**Comment by thomas-neitmann** [comment]
> I think the problem was that if a user used the dataset name adsl but did not have such dataset in the study, the ADSL dataset from admiral was used silently. As we have renamed the datasets in admiral, this should no longer happen.

Ah, I see so that was the original problem. In that case I think it's fine to leave the variable names as is in the template programs.

**Comment by sophie-gem** [comment]
I'll go with that then - thanks all!
