### ISSUE TITLE
Update all references to {admiraltest} data with prefix `admiral_`.

### ISSUE THREAD

**Issue by sophie-gem** [pharmaverse/admiral#1108]
As discussed in this [issue](https://github.com/pharmaverse/admiral/issues/1088) and subsequently in this [issue and associated PR](https://github.com/pharmaverse/admiraltest/issues/30):

- Data in {admiraltest} has been updated to `admiral_xx` and therefore any reference to data from {admiraltest} in vignettes, example scripts, etc. will need to be updated accordingly.
For example, `data('ae')` will need to become `data('admiral_ae')`.

- ADaM Datasets packaged as part of {admiral} need to be prefixed with `admiral_`, e.g. `adsl` becomes `admiral_adsl`

- As a result, any scripts that reference (or create) these programs need to be updated also.

**Comment by sophie-gem** [comment]
(Apologies for not using one of the pre-defined issue templates - I didn't know which one this suited best - but hopefully this is clear)

**Comment by sophie-gem** [comment]
I will get started on this tomorrow.

**Comment by sophie-gem** [comment]
Files that need altering (found by searching for the string `admiraltest`):

- [ ] tests/testthat/test-assertions.R
- [ ] tests/testthat/test-call_derivation.R
- [ ] tests/testthat/test-warnings.R
- [ ] inst/templates/ad_adae.R
- [ ] inst/templates/ad_adcm.R
- [ ] inst/templates/ad_adeg.R
- [ ] inst/templates/ad_adex.R
- [ ] inst/templates/ad_adsl.R
- [ ] inst/templates/ad_advs.R
- [ ] R/assertions.R
- [ ] R/call_derivation.R
- [ ] R/create_query_data.R
- [ ] R/dataset_vignette.R
- [ ] R/derive_last_dose.R
- [ ] R/derive_merged.R
- [ ] R/derive_var_anrind.R
- [ ] R/derive_var_disposition_dt.R
- [ ] R/derive_var_disposition_status.R
- [ ] R/derive_var_extreme_date.R
- [ ] R/derive_var_extreme_flag.R
- [ ] R/derive_var_last_dose_amt.R
- [ ] R/derive_var_last_dose_date.R
- [ ] R/derive_var_last_dose_grp.R
- [ ] R/derive_var_obs_number.R
- [ ] R/derive_var_trtedtm.R
- [ ] R/derive_var_trtsdtm.R
- [ ] R/derive_vars_aage.R
- [ ] R/derive_vars_disposition_reason.R
- [ ] R/derive_vars_last_dose.R
- [ ] R/dev_utils.R
- [ ] R/filter_extreme.R
- [ ] R/user_utils.R
- [ ] R/warnings.R
- [ ] vignettes/admiral.Rmd
- [ ] vignettes/adsl.Rmd
- [ ] vignettes/bds_exposure.Rmd
- [ ] vignettes/bds_finding.Rmd
- [ ] vignettes/bds_tte.Rmd
- [ ] vignettes/occds.Rmd
- [ ] vignettes/writing_vignettes.Rmd

**Comment by sophie-gem** [comment]
Hi @thomas-neitmann , before I go on to change the ADaM dataset names I was planning on running `devtools::check()` to make sure it doesn't all fall apart with the new references - but obviously I get errors because it can't find `admiral_dm` (as it's in the devel branch of admiraltest) - any ideas on what I should do?

**Comment by thomas-neitmann** [comment]
You could install the old version of admiraltest where the names are not changed, yet, by running `remotes::install_github("pharmaverse/admiraltest@main", upgrade = "never")`.

**Comment by bms63** [comment]
Hey Sophie.  Will you be able to finish this soon?  Unfortunately, this update to admiraltest is causing everything to fall over again.  I can help if needed.

**Comment by sophie-gem** [comment]
Hey Ben, I am almost done with the updates of the {admiraltest} references. I was going to do the ADAM dataset renaming in here also, however if it would be easier (so that everything doesn't fall over) I can do the ADAM updates in a separate issue? [Apologies, some project work has come up which meant that this fell behind a little...]. I am in the process of running devtools::check() to make sure I haven't missed anything.

**Comment by bms63** [comment]
It makes sense to do the ADaM renames in this branch.  Thanks!!  I can review when completed.

**Comment by sophie-gem** [comment]
Right, as of the commit above [378d477](https://github.com/pharmaverse/admiral/commit/378d4771573073ac8c71e92cc6177fd1af49b95d), all references to `admiraltest` data within `admiral` have been updated and `devtools::check()` runs with no errors. Moving forward, I'll now do exactly the same for the ADaM data within `admiral` . That is, prefix the dataset names with `admiral_` and then identify and change all references to this data within `admiral` scripts, vignettes, etc. (Advance warning: there will be more checklists! 😆)

**Comment by sophie-gem** [comment]
datasets to update:
- [ ] adae
- [ ] adcm
- [ ] adeg
- [ ] adex
- [ ] adsl
- [ ] advs

What is the consensus - do I also update `ex_single.rda` and `queries.rda`? Or as these are not 'standard' ADaM names are these ok as is?

**Comment by sophie-gem** [comment]
Files that need altering (found by searching for the string of each of the above data sets) [second pass - admiral ADaM data]:
- [ ] inst/example_scripts/example_query_source.R
- [ ] inst/templates/ad_adae.R
- [ ] inst/templates/ad_adcm.R
- [ ] inst/templates/ad_adeg.R
- [ ] inst/templates/ad_adex.R
- [ ] inst/templates/ad_adsl.R
- [ ] inst/templates/ad_advs.R
- [ ] R/assertions.R
- [ ] R/call_derivation.R
- [ ] R/create_query_data.R
- [ ] R/create_single_dose_data.R
- [ ] R/data.R
- [ ] R/derive_adeg_params.R
- [ ] R/derive_advs_params.R
- [ ] R/derive_date_vars.R
- [ ] R/derive_derived_param.R
- [ ] R/derive_last_dose.R
- [ ] R/derive_merged.R
- [ ] R/derive_param_doseint.R
- [ ] R/derive_param_exposure.R
- [ ] R/derive_param_tte.R
- [ ] R/derive_summary_records.R
- [ ] R/derive_var_atirel.R
- [ ] R/derive_var_chg.R
- [ ] R/derive_var_disposition_dt.R
- [ ] R/derive_var_disposition_status.R
- [ ] R/derive_var_dthcaus.R
- [ ] R/derive_var_extreme_date.R
- [ ] R/derive_var_extreme_flag.R
- [ ] R/derive_var_ontrtfl.R
- [ ] R/derive_var_pchg.R
- [ ] R/derive_var_trtdurd.R
- [ ] R/derive_var_trtedtm.R
- [ ] R/derive_var_trtsdtm.R
- [ ] R/derive_vars_disposition_reason.R
- [ ] R/derive_vars_dtm_to_dt.R
- [ ] R/derive_vars_dtm_to_tm.R
- [ ] R/derive_vars_query.R
- [ ] R/derive_vars_transposed.R
- [ ] R/duplicates.R
- [ ] R/slice_derivation.R
- [ ] R/tte_sources.R
- [ ] R/user_helpers.R
- [ ] R/user_utils.R
- [ ] R/warnings.R
- [ ] tests/testthat/test-call_derivation.R
- [ ] tests/testthat/test-dataset_vignette.R
- [ ] tests/testthat/test-deprecation.R
- [ ] tests/testthat/test-derive_merged.R
- [ ] tests/testthat/test-derive_param_tte.R
- [ ] tests/testthat/test-derive_var_disposition_dt.R
- [ ] tests/testthat/test-derive_var_dthcaus.R
- [ ] tests/testthat/test-derive_var_extreme_date.R
- [ ] tests/testthat/test-derive_var_trtedtm.R
- [ ] tests/testthat/test-derive_var_trtsdtm.R
- [ ] tests/testthat/test-derive_vars_query.R
- [ ] tests/testthat/test-slice_derivation.R
- [ ] tests/testthat/test-user_helpers.R
- [ ] tests/testthat/test-utils.R
- [ ] vignettes/admiral.Rmd
- [ ] vignettes/adsl.Rmd
- [ ] vignettes/bds_exposure.Rmd
- [ ] vignettes/bds_finding.Rmd
- [ ] vignettes/bds_tte.Rmd
- [ ] vignettes/occds.Rmd
- [ ] vignettes/programming_strategy.Rmd
- [ ] vignettes/writing_vignettes.Rmd

**Comment by sophie-gem** [comment]
Given the volume of scripts etc. that need editing (see above checklist) - I may need an extra hand, as I don't think it will be possible for me to achieve this by next Friday (as it would have to be outside of work hours...) otherwise. @thomas-neitmann / @bms63 - do you think that'll be possible? (I'll keep the remote branch up-to-date with my local branch and tick off those I have managed to do...). Thanks and apologies.

**Comment by bms63** [comment]
I wonder if there is a way to use grep in the terminal to find and replace these datasets in the entire admiral codebase?

**Comment by bms63** [comment]
https://stackoverflow.com/questions/15402770/how-to-grep-and-replace

`grep -rl matchstring somedir/ | xargs sed -i 's/string1/string2/g'`

**Comment by sophie-gem** [comment]
That's a fair point - I didn't think of doing it that way (was literally going to go in and do it by hand). Will take a look into that (will have to be Sunday evening / early Monday now). Thanks @bms63 !

**Comment by bms63** [comment]
ill test it out looks fun!

**Comment by sophie-gem** [comment]
Let me know how it goes - I'm really interested to find out! (Love learning new ways to code!)

**Comment by bms63** [comment]
Made some headway, but having problems with building some of the rmd file, e.g ‘bds_exposure.Rmd’ ‘bds_finding.Rmd’ ‘bds_tte.Rmd’

I used this code to go through the different folders and change from data(xxxx) to data(admiral_xxxx) as well as the calls to data("xxxx") to data("admiral_xxxx")

Just need to figure out the three Rmd files and how those functions use the package data.  I couldn't figure it out.  Maybe @bundfussr  will know the trick.

```
find /cloud/project/R -type f -exec sed -i 's/data(adsl)/data(admiral_adsl)/g' {} \;
find /cloud/project/R -type f -exec sed -i 's/data(adae)/data(admiral_adae)/g' {} \;
find /cloud/project/R -type f -exec sed -i 's/data(advs)/data(admiral_advs)/g' {} \;
find /cloud/project/R -type f -exec sed -i 's/data(adex)/data(admiral_adex)/g' {} \;
find /cloud/project/R -type f -exec sed -i 's/data(adcm)/data(admiral_adcm)/g' {} \;
find /cloud/project/R -type f -exec sed -i 's/data(adeg)/data(admiral_adeg)/g' {} \;

find /cloud/project/R -type f -exec sed -i 's/data("adsl")/data("admiral_adsl")/g' {} \;
find /cloud/project/R -type f -exec sed -i 's/data("adae")/data("admiral_adae")/g' {} \;
find /cloud/project/R -type f -exec sed -i 's/data("advs")/data("admiral_advs")/g' {} \;
find /cloud/project/R -type f -exec sed -i 's/data("adex")/data("admiral_adex")/g' {} \;
find /cloud/project/R -type f -exec sed -i 's/data("adcm")/data("admiral_adcm")/g' {} \;
find /cloud/project/R -type f -exec sed -i 's/data("adeg")/data("admiral_adeg")/g' {} \;
```

**Comment by bundfussr** [comment]
Shouldn't we replace
```
data(adsl)
```
with
```
data(admiral_adsl)
adsl <- admiral_adsl
```
?
Or did I misunderstand the issue?

**Comment by sophie-gem** [comment]
Yes, I believe that should do the job. Many thanks @bundfussr! Unless anyone else gets chance to do this before hand, I'll take a look at this after work this evening.

**Comment by bms63** [comment]
@bundfussr Do you know how to correct this error?   This is from `bds_tte_Rmd`
![image](https://user-images.githubusercontent.com/10111024/167407760-b072713d-bfc1-414d-97ac-a388cc72dd1a.png)

**Comment by bundfussr** [comment]
@bms63 , why did you change the name in the derivations? If users copy the code, they need to change it back. And if they forget it somewhere, they'll use the admiral data instead of their study data.

I think renaming the admiral data where it is read in, e.g.,
```
data("admiral_dm")
dm <- admiral_dm
data("admiral_ds")
ds <- admiral_ds
```
is less error prone.

The TTE vignette is failing because you renamed the dataset name in the definition of `death` and `lstalv` to `"admiral_adsl"`. So you would need to specify `source_datasets = list(admiral_adsl = admiral_adsl)` (the left hand side is the dataset name as specified in the source object and the right hand side the data to use). However, I would not rename the datasets in the code at all.

**Comment by bms63** [comment]
That makes sense for the users copying code.  I will update

**Comment by bms63** [comment]
I have the devel version installed in my RStudio.  I would think it would work when doing a Check?  I will investigate later.
