### ISSUE TITLE
Documentation: e2e ADaM pharmaverse vignette

### ISSUE THREAD

**Issue by duniek** [pharmaverse/admiral#1128]
### Please select a category the issue is focused on?

User Guides, Other

### Let us know where something needs a refresh or put your idea here!

Need admiral support for the e2e ADaM pharmaverse vignette with Christina

**Comment by rossfarrugia** [comment]
i'll work with @statasaurus on this

**Comment by rossfarrugia** [comment]
updates made for admiral sections and will close this issue now as i'll work with @statasaurus offline to get this vignette on the pharmaverse site to share with the community for input
