### ISSUE TITLE
Fix styler findings

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#1129]
Fix styler findings to pass check.

**Comment by bundfussr** [comment]
@thomas-neitmann , @bms63 , I noticed that the current version of `styler` (1.3.2) removes the alignment within `tribble()`. This was fixed in version 1.5.1.

Do you have any concerns moving to version 1.5.1 for `styler` and to version 2.0.3 of `magrittr` (required by `styler`)?

**Comment by thomas-neitmann** [comment]
I think it's fine to upgrade 👍
