### ISSUE TITLE
Community Outsourcing of documenation for devel to main PR

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1139]
Thanks for helping us!!
If you choose to review any of the vignettes listed here, please edit the list and **replace "admiral-non-core-dev" with your name**

## General Check List for Each Section Below

- [ ] Free of spelling and grammar mistakes
- [ ] Links Work and directs you to intended place
- [ ] R code returns expected results
- [ ] Deprecated or soon to be deprecated functions are not used in code

## Readme and Get Started
- [x]  Readme / Readme.md  (Reviewed by:  @thomas-neitmann)
- [x]  Get Started / admiral.Rmd  (Reviewed by:  Eric Simms)

##  User Guides

- [ ]  Creating ADSL / admiral.Rmd  (Reviewed by:  Pooja)
- [x]  Creating an OCCDS ADaM / occds.Rmd  (Reviewed by:  Gordon Miller)
- [x]  Creating a BDS Finding ADaM /  bds_finding.Rmd  (Reviewed by: Nathan Kosiba)
- [x]  Creating a BDS Exposure ADAm / - bds_exposure.Rnd  (Reviewed by:  Nathan Kosiba)
- [x]  Creating a BDS Time-to-Event ADaM - bds_tte.Rmd  (Reviewed by:  Nathan Kosiba)
- [x]  Date and Time Imputation / imputation.Rmd  (Reviewed by:  Ross Farrugia)
- [x]   Queries Dataset Documentation /  queries_dataset.Rmd  (Reviewed by: Stefan)
- [x]  FAQ /  faq.Rmd   (Reviewed by:  Ross Farrugia)

## Developer Guides

- [x]  Contirubtion to admiral / contribution_model.Rmd  (Reviewed by:  Ross Farrugia)
- [x]  Development Process / development_process.Rmd  (Reviewed by:  Ross Farrugia)
- [x] Programming Strategy / programming_strategy.Rmd  (Reviewed by:  Ben Straub)
- [ ] Guidance for git and GitHub Usage / git_usage.Rmd  (Reviewed by:  Ben Straub)
- [x]  Writing Vignettes / writing_vignettes.Rmd  (Reviewed by:  @thomas-neitmann)
- [x]  Pull Request Review Guidance / pr_review_guidance.Rmd  (Reviewed by:  @thomas-neitmann)
- [x]  Unit Test Test Guidance / unit_test_guidance.Rmd  (Reviewed by:  @thomas-neitmann)

## References
- [x] Randomly Select ten Reference links  (Reviewed by:  Stefan Bundfuss)
- [ ] Randomly Select ten Reference links  (Reviewed by:  Eric Simms)

**Comment by thomas-neitmann** [comment]
If you choose to review any of the vignettes listed above, please edit the list and replace "admiral-non-core-dev" with your name.

**Comment by rossfarrugia** [comment]
i feel bad asking others and then not putting my hand up myself, so i signed up to 4 of the above :)

**Comment by kodesiba** [comment]
Happy to take the three BDS ones, I can't edit the post so if someone else wants to update that would be awesome

**Comment by bundfussr** [comment]
Thanks @kodesiba , I have added your name to the items.

**Comment by bms63** [comment]
I grabbed two

**Comment by bms63** [comment]
@pharmaverse/admiral hi all - the community passion for vignette review seems to be a bit lacking.  hoping we can call upon our core developers to take on these remaining reviews.  Anyone have time to do a quick pass on these?  7 remaining

Also, if anyone is willing to do some random sampling (Elon Musk style) of our Reference pages to check examples/formats that is a another good one to tackle.  @teckla-gsk already spotted something strange for `filter_if`

**Comment by kodesiba** [comment]
Checked out the BDS ones and all three looked pretty solid.  

In bds_Finding, the adeg dataset is used in the section derive_param but the dataset itself was never loaded in from {admiraltest} in the vignette.  Additionally it looks as though the PARAM the example is creating already exists in the adeg test data so it would need to be removed to not trigger `assert_param_does_not_exist()`.  Not sure if this should be using a tribble similar to the adlb example below it or if it should be using the provided test data.

The depreciated filter argument is used in bds_Finding 
![image](https://user-images.githubusercontent.com/40005705/169144839-0a73a8b1-c0dd-4576-b93a-0ab7035c8b17.png)
![image](https://user-images.githubusercontent.com/40005705/169145092-97c152b4-afa1-410b-bcd3-ba5f80804f8e.png)



One slight thing in Exposure/Finding is the wording of the ADSL merge section.  Dropped a screenshot below but adding the word variables when saying "The rest of the
relevant `ADSL` **variables** would be added later."
![image](https://user-images.githubusercontent.com/40005705/169144949-a406b035-c87b-482a-a579-cc1dbcbc6ec3.png)

Additionally, something I noticed reading through is inconsistent casing of datasets such as `adex` being used some places and `ADEX` used in others.  While this is not necessarily an issue it is something I noticed that could be addressed, I have no answers as to which casing should be used but being consistent is always nice.

**Comment by bms63** [comment]
From Eric Simms @esimms999-gsk and his Review of Get Started
 
- When creating the ADSL as per the instructions, the documentation's display of the content of the dataset shows only a few variables instead of all variables. This had me confused for a couple of minutes. The documentation's initial display of the content of ADSL should show all variables. (Note: further down under Computations, only 3 variables are shown but this is OK because we are just interested in seeing a new variable on each row.)

- The documentation's display of ADSL shows TRTSDTM as a datetime, e.g. 2014-01-02T00:00:00Z but when I ran the code it only shows the date, e.g. 2014-01-02. (Perhaps the dataframe viewer in RStudio drops the time portion if it is all zeros?)

- The Computations section has a link to #section-computations, which does not exist, so the linked webpage opens at the top where the content is Derivations. The link should be #computations.

- Missing values section's code needs library("haven").

- list_all_templates example in the documentation has two more results then I get when running the code. I get "ADAE" "ADCM" "ADEG" "ADEX" "ADSL" "ADVS" and documentations shows "ADAE" "ADCM" "ADEG" "ADEX" "ADLB" "ADPP" "ADSL" "ADVS".

**Comment by rossfarrugia** [comment]
@esimms999-gsk for the last bullet it is correct that ADLB and ADPP templates are available in this release, so the documentation is fine but something up with why `list_all_templates` is not showing those when you run.

**Comment by rossfarrugia** [comment]
Date and Time Imputation vignette issues:
- 06-15 example needs a bit more explanation why we included it, otherwise it looks like a repeat of 01-01 example. i.e. update the text as: `If you wanted to achieve a similar result by replacing any missing part of the date with a fixed value `06-15`, this is also possible, but note the difference in days for cases when month is missing:`
- In the first example use `derive_vars_dtm_to_dt()` instead of mutate: 
The imputed date variable can be derived by ~~a simple mutate() call~~using the `derive_vars_dtm_to_dt()` function.
~~mutate(ASTDT = date(ASTDTM))~~derive_vars_dtm_to_dt(vars(ASTDTM))
- Example that says "Create an Imputed Date Variable **and Imputation Flag Variable**" currently doesn't create the imputation flag:
```
    date_imputation = "first",
    flag_imputation = "none"
```
should be:
```
    date_imputation = "first"
```

I can make these updates.

**Comment by thomas-neitmann** [comment]
Thanksa lot for taking such a detailed look @kodesiba! Is this something you would be willing and able to fix today or tomorrow? If not, I can take it on myself.

**Comment by millerg23** [comment]
> Thanks a lot for taking such a detailed look @kodesiba! Is this something you would be willing and able to fix today or tomorrow? If not, I can take it on myself.

I can take this on today, thanks so much @kodesiba for reviewing the Vignette, and for highlighting these issues.

**Comment by rossfarrugia** [comment]
FAQ vignette looks ok except one link broken: "(see Admiral offers a toolbox of functions to facilitate ADaM. What does that mean?)". I'll fix this now.

**Comment by rossfarrugia** [comment]
Development process vignette is fine, but Contribution one has some old Slack links that link to now archived channels which i'll update.

**Comment by bms63** [comment]
# Programming Strategy

* Links to depracated function 
![image](https://user-images.githubusercontent.com/10111024/169299620-c67ebbfc-81d7-4d1a-a1f7-fac9c5698f5a.png)

* Enforece style through lintr and styler package?  not just lintr
![image](https://user-images.githubusercontent.com/10111024/169300404-d352c111-f8c9-4195-8c63-3f055eb1dce2.png)

* Links to assertions examples
![image](https://user-images.githubusercontent.com/10111024/169300685-3a96a784-e2bb-4abb-96f9-cb8935b76b8a.png)

* Deprecated example - shoudl be derive_vars_dy()
![image](https://user-images.githubusercontent.com/10111024/169300961-91e9014f-d565-4c61-ad20-1418ff8f0f85.png)

* `derive_suppqual `referenced
![image](https://user-images.githubusercontent.com/10111024/169301341-9be37a2f-772d-4adc-8ce8-400e8a2e01a4.png)


Hi all Programming Strategy has links and examples of deprecated functions.  I will update.

**Comment by bms63** [comment]
@esimms999-gsk 
> From Eric Simms @esimms999-gsk and his Review of Get Started
> 
> * When creating the ADSL as per the instructions, the documentation's display of the content of the dataset shows only a few variables instead of all variables. This had me confused for a couple of minutes. The documentation's initial display of the content of ADSL should show all variables. (Note: further down under Computations, only 3 variables are shown but this is OK because we are just interested in seeing a new variable on each row.)

I think this was done so a user can just see the variables that were derived.  Showing the entire dataset means a user has to scroll all the way over to see them.  I can make small note that we are only displaying the derived variables.  

> * The documentation's display of ADSL shows TRTSDTM as a datetime, e.g. 2014-01-02T00:00:00Z but when I ran the code it only shows the date, e.g. 2014-01-02. (Perhaps the dataframe viewer in RStudio drops the time portion if it is all zeros?)

This is just an artifact of the RStudio Console.  Not sure if we can address it.

> * The Computations section has a link to #section-computations, which does not exist, so the linked webpage opens at the top where the content is Derivations. The link should be #computations.

Will update

> * Missing values section's code needs library("haven").
I think this is okay as it has `haven::read_sas()`

> * list_all_templates example in the documentation has two more results then I get when running the code. I get "ADAE" "ADCM" "ADEG" "ADEX" "ADSL" "ADVS" and documentations shows "ADAE" "ADCM" "ADEG" "ADEX" "ADLB" "ADPP" "ADSL" "ADVS".
You might need to do devtools::load_all() to get the latest updates loaded into your environment.  - I was able to list them all out.

**Comment by bundfussr** [comment]
Example on `impute_dtc()` reference page is not rendered:
![image](https://user-images.githubusercontent.com/80953585/169319950-99ac77a5-7c7a-44dc-8711-b87b33610a9d.png)

**Comment by bundfussr** [comment]
There is a typo on some reference pages referring to `derive_var_dt()` instead of `derive_vars_dt()`:
```
compute_duration.R:#'   Refer to `derive_var_dt()` to impute and derive a date from a date
compute_duration.R:#'   Refer to `derive_var_dt()` to impute and derive a date from a date
create_single_dose_dataset.R:#'   Refer to `derive_var_dt()` to impute and derive a date from a date
create_single_dose_dataset.R:#'   Refer to `derive_var_dt()` to impute and derive a date from a date
derive_param_tte.R:#'   Refer to `derive_var_dt()` to impute and derive a date from a date
derive_var_ady.R:#'   Refer to `derive_var_dt()` to impute and derive a date from a date character vector to a date object.
derive_var_ady.R:#'   Refer to `derive_var_dt()` to impute and derive a date from a date character vector to a date object.
derive_var_aendy.R:#'   Refer to `derive_var_dt()` to impute and derive a date from a date character vector to a date object.
derive_var_aendy.R:#'   Refer to `derive_var_dt()` to impute and derive a date from a date character vector to a date object.
derive_var_astdy.R:#'   Refer to `derive_var_dt()` to impute and derive a date from a date character vector to a date object.
derive_var_astdy.R:#'   Refer to `derive_var_dt()` to impute and derive a date from a date character vector to a date object.
derive_var_ontrtfl.R:#'   Refer to `derive_var_dt()` to impute and derive a date from a date
derive_var_ontrtfl.R:#'   Refer to `derive_var_dt()` to impute and derive a date from a date
derive_var_ontrtfl.R:#'   Refer to `derive_var_dt()` to impute and derive a date from a date
derive_var_ontrtfl.R:#'   Refer to `derive_var_dt()` to impute and derive a date from a date
derive_vars_aage.R:#'   Refer to `derive_var_dt()` to impute and derive a date from a date character
derive_vars_aage.R:#'   Refer to `derive_var_dt()` to impute and derive a date from a date character
derive_vars_duration.R:#'   Refer to `derive_var_dt()` to impute and derive a date from a date
derive_vars_duration.R:#'   Refer to `derive_var_dt()` to impute and derive a date from a date
derive_vars_dy.R:#'   Refer to `derive_var_dt()` to impute and derive a date from a date
derive_var_trtdurd.R:#'   Refer to `derive_var_dt()` to impute and derive a date from a date
derive_var_trtdurd.R:#'   Refer to `derive_var_dt()` to impute and derive a date from a date
```

**Comment by bundfussr** [comment]
The second example for `assert_list_element()` is failing with the wrong error message.

**Comment by bundfussr** [comment]
`extract_unit()` is defined in both `dev_utils.R` and `user_utils.R`.

**Comment by bms63** [comment]
Looks like everyhting is inheriting the rmarkdown chunk properly.  I'll put this in my update.

**Comment by bms63** [comment]
> The example for `get_many_to_one_dataset()` is failing. It is still using `adsl` instead of `admiral_adsl`.
> 
> Same issue for `assert_one_to_one()`, `get_one_to_many_dataset()`, and `get_many_to_one_dataset()`.

I fixed these in my PR - https://github.com/pharmaverse/admiral/pull/1153 .  Assumign `assert_one_to_one()` should have an error.

**Comment by bms63** [comment]
> There is a typo on some reference pages referring to `derive_var_dt()` instead of `derive_vars_dt()`:
> 
> ```
> compute_duration.R:#'   Refer to `derive_var_dt()` to impute and derive a date from a date
> compute_duration.R:#'   Refer to `derive_var_dt()` to impute and derive a date from a date
> create_single_dose_dataset.R:#'   Refer to `derive_var_dt()` to impute and derive a date from a date
> create_single_dose_dataset.R:#'   Refer to `derive_var_dt()` to impute and derive a date from a date
> derive_param_tte.R:#'   Refer to `derive_var_dt()` to impute and derive a date from a date
> derive_var_ady.R:#'   Refer to `derive_var_dt()` to impute and derive a date from a date character vector to a date object.
> derive_var_ady.R:#'   Refer to `derive_var_dt()` to impute and derive a date from a date character vector to a date object.
> derive_var_aendy.R:#'   Refer to `derive_var_dt()` to impute and derive a date from a date character vector to a date object.
> derive_var_aendy.R:#'   Refer to `derive_var_dt()` to impute and derive a date from a date character vector to a date object.
> derive_var_astdy.R:#'   Refer to `derive_var_dt()` to impute and derive a date from a date character vector to a date object.
> derive_var_astdy.R:#'   Refer to `derive_var_dt()` to impute and derive a date from a date character vector to a date object.
> derive_var_ontrtfl.R:#'   Refer to `derive_var_dt()` to impute and derive a date from a date
> derive_var_ontrtfl.R:#'   Refer to `derive_var_dt()` to impute and derive a date from a date
> derive_var_ontrtfl.R:#'   Refer to `derive_var_dt()` to impute and derive a date from a date
> derive_var_ontrtfl.R:#'   Refer to `derive_var_dt()` to impute and derive a date from a date
> derive_vars_aage.R:#'   Refer to `derive_var_dt()` to impute and derive a date from a date character
> derive_vars_aage.R:#'   Refer to `derive_var_dt()` to impute and derive a date from a date character
> derive_vars_duration.R:#'   Refer to `derive_var_dt()` to impute and derive a date from a date
> derive_vars_duration.R:#'   Refer to `derive_var_dt()` to impute and derive a date from a date
> derive_vars_dy.R:#'   Refer to `derive_var_dt()` to impute and derive a date from a date
> derive_var_trtdurd.R:#'   Refer to `derive_var_dt()` to impute and derive a date from a date
> derive_var_trtdurd.R:#'   Refer to `derive_var_dt()` to impute and derive a date from a date
> ```

I did a `find /cloud/project/R -type f -exec sed -i 's/derive_var_dt/derive_vars_dt/g' {} \;` and think I got them all.  I put this in the #1153 as well

**Comment by bms63** [comment]
> The second example for `assert_list_element()` is failing with the wrong error message.

I'm not sure how to fix this one.

**Comment by PoojaKumari05** [comment]
REVIEW comments for ADSL

1. Derive/Impute Numeric Treatment Date/Time and Duration (TRTSDTM, TRTEDTM, TRTDURD)
    -  Along with TRTSDTM & TRTEDTM , TRTSTMF and TRTETMF is also added. The text should be modified to include these two variables.
       ![image](https://user-images.githubusercontent.com/90273880/169354611-76a8db34-3b90-4752-ab36-5d0a83e540f2.png)

2. Disposition Status (e.g. EOSTT)
    -   Typo - variable name is EOSSTT	

3. Derive Groupings and Populations
    - _**For others, the user can create his/her own function to meet his/her study requirement**_. This line can be generalized to  "For others, users can create their own function to meet the study requirement."		

4. GENERAL : For all the date variable derivation the IMPUTATED variable is added by default - For DHTDT  the following sentence is written "**_by default, the associated date imputation flag (DTHDTF) populated with the controlled terminology outlined in the ADaM IG for date imputations. If the imputation flag is not required, the user must set the argument flag_imputation to “none”_**." Should we write a similar sentence for other date variable? For eg: in point 1?

**Comment by bundfussr** [comment]
@bms63 , I have fixed the `assert_list_element()` example.

**Comment by bms63** [comment]
> REVIEW comments for ADSL
> 
> 1. Derive/Impute Numeric Treatment Date/Time and Duration (TRTSDTM, TRTEDTM, TRTDURD)
>    
>    * Along with TRTSDTM & TRTEDTM , TRTSTMF and TRTETMF is also added. The text should be modified to include these two variables.
>      ![image](https://user-images.githubusercontent.com/90273880/169354611-76a8db34-3b90-4752-ab36-5d0a83e540f2.png)
> 2. Disposition Status (e.g. EOSTT)
>    
>    * Typo - variable name is EOSSTT
> 3. Derive Groupings and Populations
>    
>    * _**For others, the user can create his/her own function to meet his/her study requirement**_. This line can be generalized to  "For others, users can create their own function to meet the study requirement."
> 4. GENERAL : For all the date variable derivation the IMPUTATED variable is added by default - For DHTDT  the following sentence is written "**_by default, the associated date imputation flag (DTHDTF) populated with the controlled terminology outlined in the ADaM IG for date imputations. If the imputation flag is not required, the user must set the argument flag_imputation to “none”_**." Should we write a similar sentence for other date variable? For eg: in point 1?

Hey @PoojaKumari05 I updated item 3, but the rest I think we should do for the next release

**Comment by PoojaKumari05** [comment]
> > REVIEW comments for ADSL
> > 
> > 1. Derive/Impute Numeric Treatment Date/Time and Duration (TRTSDTM, TRTEDTM, TRTDURD)
> >    
> >    * Along with TRTSDTM & TRTEDTM , TRTSTMF and TRTETMF is also added. The text should be modified to include these two variables.
> >      ![image](https://user-images.githubusercontent.com/90273880/169354611-76a8db34-3b90-4752-ab36-5d0a83e540f2.png)
> > 2. Disposition Status (e.g. EOSTT)
> >    
> >    * Typo - variable name is EOSSTT
> > 3. Derive Groupings and Populations
> >    
> >    * _**For others, the user can create his/her own function to meet his/her study requirement**_. This line can be generalized to  "For others, users can create their own function to meet the study requirement."
> > 4. GENERAL : For all the date variable derivation the IMPUTATED variable is added by default - For DHTDT  the following sentence is written "**_by default, the associated date imputation flag (DTHDTF) populated with the controlled terminology outlined in the ADaM IG for date imputations. If the imputation flag is not required, the user must set the argument flag_imputation to “none”_**." Should we write a similar sentence for other date variable? For eg: in point 1?
> 
> Hey @PoojaKumari05 I updated item 3, but the rest I think we should do for the next release

Hey @bms63 - item 2 is also a minor one, should we update that as well? for rest yes - even I think we can discuss and update in next release if needed. Thanks for updating! :)

**Comment by bms63** [comment]
Sorry I updated item 2 not 3.  whoops!
