### ISSUE TITLE
create a bitesized video to explain how to use admiral (4h)

### ISSUE THREAD

**Issue by koegerr** [pharmaverse/admiral#114]
goal:
prepare a video explaining to users how to create their ADaMs via admiral.

**Comment by bms63** [comment]
Since we have a bunch of videos from conferences showing how to use admiral can we say this is done?  

Or do want to wait until admiral is a better state to make this type of video?

**Comment by thomas-neitmann** [comment]
Unless anyone from the team feels inclined to record such a video I think linking to existing videos from our presentations suffices.
