### ISSUE TITLE
Documentation:  Contribution guideline not as a vignette

### ISSUE THREAD

**Issue by pawelru** [pharmaverse/admiral#1140]
### Please select a category the issue is focused on?

Developer Guides

### Let us know where something needs a refresh or put your idea here!

It's quite unusual to place a contribution guidelines into a vignette. Usually it's living in `CONTRIBUTING.md` file in a root of the project. This is what it's being recommended by GitHub as per [manual](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors). This is where open-source community would look into.

Please consider move some materials into that file as I feel it won't be a single article in your case.

PS. I also found contribution guidelines in a wiki for a well known `data.table` - but again - not in the vignettes.

**Comment by bms63** [comment]
Thanks Pawel.   This is my first big open source project so I was not aware of this practice.  

Do you have any interest in working on and driving this issue for us?  I believe most of the materials are available - just moving to the CONTRIBUTING.md.  

What do others think? @pharmaverse/admiral
 
Might be a good one for our template repo as well?? @dinakar29

**Comment by dinakar29** [comment]
@bms63 - Yes, definitely, we should be adding the contribution guidelines, code of conduct, and issue templates all to the template repository.

**Comment by bms63** [comment]
ooh code of conduct

**Comment by pawelru** [comment]
> Do you have any interest in working on and driving this issue for us? I believe most of the materials are available - just moving to the CONTRIBUTING.md.

I am afraid that it's not that easy (at least for me - not a frequent contributor to `admiral`). I can spot few vignettes regarding contribution as a whole - namely: `"contribution_model"`, `"development_process"`, `"programming_strategy"`, `"git_usage"`, `"writing_vignettes"`, `"pr_review_guidance"`, `"unit_test_guidance"`. All of them are very rich in content and very specific to what you are doing. That's actually nothing bad. Combining them into one document with appropriate order addressing potential overlaps etc sounds big to me :(

**Comment by bundfussr** [comment]
I would just move the contribution_model vignette to CONTRIBUTING.md. I think it provides a good overview and links to the details of contributing. If we put all developer guides into CONTRIBUTING.md, it becomes very large and hard to read.

**Comment by bms63** [comment]
Hi @pawelru Please see #1180 .  If you have any suggestions please let us know.
