### ISSUE TITLE
Bug: filter_if is falling over in Example on Website

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1147]
### What happened?

Examples looks like it is falling over on website

![image](https://user-images.githubusercontent.com/10111024/169068865-0c516cd5-e8fa-49f3-99ce-dda3ba893a3b.png)

### Session Information

Found on website

### Reproducible Example

Unsure on the first one example

If I change filter_if(admiral_vs, rlang::quo(VSTESTCD == "Weight")) to filter_if(admiral_vs, rlang::quo(VSTESTCD == "WEIGHT")) it produces a results.

**Comment by thomas-neitmann** [comment]
If I run these examples in the console they produce a result without error (altough the second one returns 0 rows as it should indeed be `"WEIGHT"`):

![image](https://user-images.githubusercontent.com/11788080/169075724-a452cd0f-3798-4a7a-a837-b7d4c7ce56bd.png)

**Comment by bms63** [comment]
Maybe is doesn't like the size of the data that it is being asked to display?

**Comment by bundfussr** [comment]
I would try adding
```
library(admiral)
```
I could reproduce the error by not loading admrial but loading dplyr.

**Comment by bms63** [comment]
Works!  @bundfussr Thanks!!

![image](https://user-images.githubusercontent.com/10111024/169324163-840c1a8e-4fdb-423a-98fd-d781e2a5b631.png)
