### ISSUE TITLE
Documentation:  Get Started needs some nice flowery words before derive_vars_merged_dtm calls

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1167]
### Please select a category the issue is focused on?

User Guides

### Let us know where something needs a refresh or put your idea here!

@pharmaverse/admiral Anyone take this on for this release?

We kind of just throw users into the deep-end with these derive_vars_merged_dtm calls.  I think we should have some nice flowerly language about what we are doing here and then with dtm_to_dt and duration functions.  This is the Get Started page so I feel like we should be nice to the users.

Be good to point out to users they can click on the function and be taken to the documentation as well.     

![image](https://user-images.githubusercontent.com/10111024/169883801-5e197da5-c19b-4802-9a0b-ae6835dc8d1a.png)

https://pharmaverse.github.io/admiral/articles/admiral.html

**Comment by wqrena** [comment]
Maybe it is more clear to add description here:

![image](https://user-images.githubusercontent.com/51412450/170145072-d72f2ff2-035b-4ccc-a028-e9c08ea06da7.png)

with the following description.
"Here is an example of using function calls to create a simple ADSL dataset by adding treatment variables from DM and EX input datasets. The added treatment variables in this example include TRT01P, TRT01A, TRTSDTM, TRTSTMF, TRTEDTM, TRTSDT, TRTEDT, TRTDURD. 

You may click on the function call, which will take you to the documentation manual directly."

**Comment by bms63** [comment]
I think that is great to go in between the library/dataset section and the derive treatment section.

Could we also have something saying like, First we load our libraries and datsets, admiral has available the admiraltest package which has sdtm data from the CDISC pilot study.  Maybe even a link out to it?  Need to wordsmith it.

Can the comments also start with Read...  and Derive...

I'm just thinking a Get Started page should be super friendly and do some hand-holding for new users.  I think it is okay to a little overly simplistic and rah-rah.

**Comment by bms63** [comment]
ummm.. should we mention derive_vars_  as well ? 
![image](https://user-images.githubusercontent.com/10111024/170160643-2be0a10a-e25d-4e5b-9af4-c8cf19181493.png)
