### ISSUE TITLE
Bug: derive_var_extreme_flag() returns dataset with changed order of rows

### ISSUE THREAD

**Issue by waldemarmiller** [pharmaverse/admiral#1171]
### What happened?

I expected that the function preserves the input dataset's row order. Unfortunately, it changes it.

```
all(ADAE$USUBJID == REF_ADAE$USUBJID) # --> TRUE
ADAE <- ADAE %>%
  derive_var_extreme_flag(
    by_vars = vars(USUBJID),
    order = vars(TEAESDT, ACHGDT, AESEQ),
    new_var = AOCCFL,
    filter = (TRTEMFL == "Y"),
    mode = "first"
  ) 
all(ADAE$USUBJID == REF_ADAE$USUBJID) # -->FALSE
```

**Comment by bundfussr** [comment]
admiral functions does not preserve the order of the rows (see https://pharmaverse.github.io/admiral/articles/admiral.html#input-and-output). We decided for this approach because preserving the order would require an additional sort step and this would increase the run-time.

**Comment by waldemarmiller** [comment]
Ah, I see @bundfussr. I was surprised as I somewhat assumed that. Thank you for this clarification!
