### ISSUE TITLE
Onboarding:  Syed and Shan

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1172]
### Onboarding tasks for Core (Roche-GSK) Team Members

- [x] Given a tour of Github from a Core member
- [x] Understand how to Create Issues and do a Pull Request
- [x] Understand the Programming Strategy
- [x] Read and understand [Developer Guides Articles](https://pharmaverse.github.io/admiral/index.html)
- [x] Invited to all relevant meetings - Stand Ups, Question/Comments, Backlog, Community Meeting
- [x] Given access to Box and relevant documents
- [x] Given write access to Github Repository
- [x] Slack channel invites to admiral and admiral_dev
- [x] Introduction to Teams ways of working

### Onboarding tasks for non-Core Team Members

- [ ] Given a tour of Github from a Core member
- [ ] Understand how to Create Issues and do a Pull Request
- [ ] Understand the Programming Strategy
- [ ] Read and understand [Developer Guides Articles](https://pharmaverse.github.io/admiral/index.html)
- [ ] Invited to all relevant meetings - Question/Comments, Community Meeting
- [ ] Given write access to Github Repository
- [ ] Slack channel invites to admiral
- [ ] Introduction to Teams ways of working

**Comment by PoojaKumari05** [comment]
@sm519479 - Onboarding completed

**Comment by bms63** [comment]
@fshanlee I wasn't sure where Teckla left you with onboarding.  Do we need to cover any of this stuff above?
