### ISSUE TITLE
General Issue: dataset_add being seen as grouped dataframe rather than arugment

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1186]
### Background Information

![image](https://user-images.githubusercontent.com/10111024/171167913-6da44685-1561-4d74-b423-eec5b2fbc457.png)

**Comment by bundfussr** [comment]
I think it is not an admiral issue but an admiral.test issue. There is an `ungroup()` missing at line 54 of [inst/data_scripts/update_ds.R](https://github.com/pharmaverse/admiral.test/blob/devel/inst/data_scripts/update_ds.R)

**Comment by bundfussr** [comment]
I think if you install locally the latest devel version of admiral.test, the local check should fail as well.

**Comment by bms63** [comment]
haha i was just arriving at that so the workflows use devel

**Comment by bms63** [comment]
wait that change is in devel

**Comment by thomas-neitmann** [comment]
Oh, that's great then we don't need to re-submit 🥳

**Comment by bundfussr** [comment]
Yes, makes sense.

**Comment by thomas-neitmann** [comment]
Closing as this is being fixed in https://github.com/pharmaverse/admiral.test/pull/48.
