### ISSUE TITLE
General Issue: Unit presented on all rows when new_var_unit is specified in derive_vars_duration

### ISSUE THREAD

**Issue by LucyW39** [pharmaverse/admiral#1207]
### Background Information

When using function **derive_vars_duration** and the **new_var_unit** is specified, the unit variable created is populated on all rows of the dataframe, even when the duration variable is missing (i.e. due to missing dates). This causes issues for certain Unit variables (e.g. ADURU, ARELTMU, DOSECUMU) which are P21 validation errors. 

![image](https://user-images.githubusercontent.com/107196353/172865814-7a3aa82d-5938-43ae-ae97-0f8a38ce7bb2.png)

### Definition of Done

Update to either only populate when duration is not missing, or add a new argument to make this an option.

**Comment by thomas-neitmann** [comment]
Thanks a lot for reporting this @LucyW39! Would you be interested and willing to contribute to {admiral} by fixing this issue?

**Comment by LucyW39** [comment]
Hi @thomas-neitmann, I would love to contribute to this but currently do not have the time (with DBF today). If the issue still hasn't been picked up in the next few weeks I can check back in and assign myself. 
@bms63, certainly! Again, no time for this today but I can try and add in a reproducible example next week using the admiral data.
