### ISSUE TITLE
Include create_single_dose_dataset processing in  derive_var_last_dose_date

### ISSUE THREAD

**Issue by oreillb1** [pharmaverse/admiral#1213]
### Feature Idea

In ADaM datasets e.g. ADAE, function derive_var_last_dose_date has single_dose_condition that cannot be met when a single EX row covers multiple doses [EX.EXENDTC] greater than [EX.EXSTDTC]. Could function create_single_dose_dataset processing be included in function derive_var_last_dose_date either instead of single_dose_condition or within single_dose_condition? Or is there a better way to process these data?

**Comment by bundfussr** [comment]
@oreillb1 , thanks for creating this issue.

We discussed this topic before in the development team and decided not to integrate the creation of the single dose dataset into the `derive_var_last_dose_*()` functions. The reasons are:
- The single dose dataset may be required by more than one derivation. In this case it is more efficient to derive it once.
- The derivation is hard to review if the singe dose dataset is derived within the last dose date derivation.
- The result of `create_single_dose_dataset()` should be reviewed carefully if it meets the study's needs. If `create_single_dose_dataset()` is called within the `derive_var_last_dose_*()` functions, it may be missed that the exposure dataset is transformed.
- The `create_single_dose_dataset()` function covers only some simple scenarios. If a study requires a more complex derivation of the single dose dataset, it is easier to implement and review if it is derived in a separate step.

If you really want to derive the single dose dataset within the last dose date derivation, you could call
```
derive_var_last_dose_date(
  dataset_ex = create_single_dose_dataset(ex),
  ...
)
```

@pharmaverse/admiral , any thoughts?

**Comment by oreillb1** [comment]
Please would you provide an example of the complete section code?
