### ISSUE TITLE
Feature Request:  Produce BMI records for more visits with derive_param_bmi() 

### ISSUE THREAD

**Issue by chengwei88** [pharmaverse/admiral#1228]
### Feature Idea

I expect `derive_param_bmi` to generate BMI records for each weight records of USUBJID, VISITNUM, ADT, and VSTPT in ADVS. However, it only generate the BMI records correponding to the height records. Taking the admiral_advs dataset in the admiral package (0.7.0) as an example, I expect to see 4309 BMI records, just like WEIGHT, not 508 records as HEIGHT. Thanks

**Comment by thomas-neitmann** [comment]
@chengwei88 Please take a look at the second example from the [`derive_derived_param()`](https://pharmaverse.github.io/admiral/reference/derive_derived_param.html?q=derive_derived#ref-examples) reference page. Does that fullfill your needs?

**Comment by bundfussr** [comment]
It seems that `derive_param_bmi()` is not well designed. I think for non pediatric studies usually height is measured only once because it is unlikely to change. So maybe we should update the code. 

We could

- update `derive_param_bmi()` such that it assumes that height is measured only once,
- update `derive_param_bmi()` such that it covers both cases height is measure only once and height is measured at each visit, or
- deprecate `derive_param_bmi()` in favor of `derive_derived_param()`.

We have the same issue for `derive_param_bsa()`.

What do you think?

**Comment by thomas-neitmann** [comment]
@bundfussr I would prefer option number 2. Might be a good issue for our hackRthon.

**Comment by bundfussr** [comment]
Fine with me.

I think we would need to add some more details for hackR.

**Comment by thomas-neitmann** [comment]
Awesone, go HoneybadgerRs 🎉

**Comment by sreeral1** [comment]
Hi @thomas-neitmann The link above for `derive_derived_param` seems broken. Can you please update the link and share more details/context for this issue? 

Thanks,
Lasya

**Comment by bms63** [comment]
https://pharmaverse.github.io/admiral/main/reference/derive_derived_param.html

**Comment by thomas-neitmann** [comment]
@sreeral1 So, `derive_param_bmi()` and `derive_param_bsa()` have to be updated such that they can handle the case where `HEIGHT` is only measured once but `WEIGHT` at every visit. Basically, `HEIGHT` would have to be retained in all other records. Ideally the functions are able to handle both cases, i.e. `HEIGHT` being measured only once or at every visit. I could think of adding a logical parameter `retain_height` to these function which allows users to specify the desired behaviour.

**Comment by sreeral1** [comment]
Hi @thomas-neitmann 
When retaining `height`, do we just retain the latest `height` value (for pediatric studies this may change every visit) so we can use the `fill` function from `tidyr` to populate all rows with `height` value == NA as the last available height value? 

![image](https://user-images.githubusercontent.com/108090381/176556944-3a751200-e04d-4edf-9a88-1b87249427ad.png)

**Comment by thomas-neitmann** [comment]
I would not just carry forward the last observation all the time. In a pedeatric study where "HEIGHT" is missing at one reason I don't think it's approriate to just impute it that way. We should properly discern the two cases: (1) "HEIGHT" only measured once and carried forward for all visits and (2) "HEIGHT" supposed to be measures at each visit. Anything to add @bundfussr @bms63?
