### ISSUE TITLE
Move out developer utilities into a separate dependency package - {admiraldev}

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiral#1231]
### Background Information

development utilities: we agreed that this makes sense to move out into a separate package, so that users don't need to see all these util functions on the reference page (which is already so long!), and we can make admiral documentation more user-focused over time. reason being only a minority of these will ever become developers. 

**timing: probably not for release 0.8.0, but maybe 0.9.0 by end of the year.**

### Definition of Done

new {admiraldev} package on CRAN and becomes a dependency of all admiral family of packages. would need to agree a maintainer from the core team.

Steps to get there:

- [ ] Moving the developer facing functions from admiral core to admiraldev.
- [ ] Moving the developer facing function tests from admiral core to admiraldev.
- [ ] Updating Description file
- [ ] Rebuilding the documentation
- [ ] Creating the packagedown site with updated logo (ours is blue butterfly – happy to change if you have a better color idea 😊)
- [ ] Aligning the workflows 
- [ ] Aligning the badges
- [ ] Updating readme with developer specific needs/questions
- [ ] Publishing admiraldev to CRAN
- [ ] Initiating a PR into admiral-core that removes all the developer functions and tests and makes admiraldev a dependency
- [ ] Checking that admiral-core works seamlessly with admiraldev

**Comment by thomas-neitmann** [comment]
I would say:

- `dev_utils.R`
- `test_helpers.R`
- `assertions.R`

As the file name suggests `user_utils.R` is intended for users not developers.

**Comment by bms63** [comment]
If only we had a template to quickly set up this new package...

**Comment by bundfussr** [comment]
So the package should include all functions which are not called directly by users with the exception of helper functions used by 
a single function only (e.g., `filte_date_sources()` and `extend_source_datasets()` defined in `derive_param_tte.R` remain in admiral core). 
Then I guess admiraldev should include
- `assertthat_checks.R`
- `call_user_fun.R`
- `compat_friendly_type.R`
- `dataset_vignette.R`
- most of `duplicates.R`
- `joins.R`
- `warnings.R`

as well.

**Comment by bms63** [comment]
See #1105 for additional discussion on moving things around.

**Comment by rossfarrugia** [comment]
If you or any of the others have capacity @bms63 but i think fine even for release 0.9.0, as there's lots already on the list for 0.8.0 with higher priority than this one: https://github.com/pharmaverse/admiral/issues/1211

**Comment by bms63** [comment]
i was thinking someone from the `admiral_dev` channel so its Roche or GSK.  Happy to be listed as the maintainer

**Comment by rossfarrugia** [comment]
@bms63 from the chat i think you said you'll work on this so i assigned your name in case anyone else starts it. i think it makes sense for you given all the past admiraltemplate experience etc, but if anyone else volunteers along the way it could be a good learning experience for them working with you on this

**Comment by bundfussr** [comment]
There are a lot of broken links in README.md and NEWS.md due to moving the developer vignettes to admiraldev.

@bms63 , could you fix it?
