### ISSUE TITLE
General Issue: Remove all admiral_adxx datasets except admiral_adsl

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1234]
### Background Information

We have decided to only keep `admiral_adsl` as a permanent dataset in the `data` folder.  All other datasets will be removed from the `data` folder.  Users wishing to have access to these datasets can just run the scripts available in the template script.

This will reduce the size of the `data` and the overall package.

I believe only `admiral_adsl` is used in our examples and vignettes.  Before starting on this issue, please do a Find in Files and verify that none of the `admiral_adxx` datasets are used.  If they are used, then we might keep decide to keep it in the `data` folder.

Previous discussion on this topic can be found here #1133 

### Definition of Done

* Verified that examples, vignettes and test files only use `admiral_adsl` 
* Datasets (except `admiral_adsl`) have been removed from the `data` folder

**Comment by JunseKim1159** [comment]
Programs affected by removal of admiral_adxx datasets 


~/R/admiral/vignettes/bds_tte.Rmd - Uses adae dataset
~/R/admiral/R/assertions.R - Uses advs dataset (data(admiral_advs) is in a comment so it's actually not used at the end)
~/R/admiral/man/assert_param_does_not_exist.Rd - Uses advs dataset
~/R/admiral/man/assert_unit.Rd - Uses advs dataset

Myself and Claudia will look at adapting the programs to only use ADSL

**Comment by thomas-neitmann** [comment]
Thanks a lot for taking this on!

**Comment by ClaudiaCarlucci** [comment]
Hi Ben/Thomas,

just wondering if you want us to look at making programs  #1, #3 and #4 works without using other datasets or we should delete all other admiral_adxx except for advs, adae and adsl.

Thanks

**Comment by JunseKim1159** [comment]
Hi @thomas-neitmann! With the file ~/R/admiral/R/data.R what is the purpose of this file exactly and will we need to delete it if we are deleting all of the admiral datasets from data? We have tried to delete the admiral data and the error that pops up is Error: 'admiral_adex' is not an exported object from 'namespace:admiral'

**Comment by thomas-neitmann** [comment]
@JunseKim1159 This file includes the documentation for the various datasets. For each dataset in the `data` folder you would have to delete the corresponding entry in that file. Also, as I indicated on the PR please make sure to only delete the datasets but keep the template scripts that created them.

**Comment by ClaudiaCarlucci** [comment]
Hi, we unassigned ourselves to this issue as we are not able to work on this anymore this week. If nobody else will be assigned to this until next week, we will give a look to it again
