### ISSUE TITLE
Documentation:  Consistent use of library() in examples and Unit Tests

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1235]
### Please select a category the issue is focused on?

Developer Guides

### Let us know where something needs a refresh or put your idea here!

There is uses of `pkg_name::function()`  and `library(pkg_name)` within examples and tests.  In order to keep consistency across the code-base we first need to update our developer guides with our recommended practice.

The recommended practice is to just use `library(pkg_name)` rather than  `pkg_name::function()`.  We feel this reduces the cluttering of the examples and tests.

DoD:
Updates made to the following:
- [x] https://pharmaverse.github.io/admiral/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-
- [x] https://pharmaverse.github.io/admiral/articles/programming_strategy.html#function-header-documentation
- [ ] Ensure no other documentation gives inconsistent advice
- [x] examples and tests using `pkg_name::function()` are updated with `library(pkg_name)`

### Issue to fix in Unit Test Guide
![image](https://user-images.githubusercontent.com/10111024/175076209-88baa687-358a-4f66-90aa-59d3e4139a29.png)

### Issue to fix in Programming Strategy
![image](https://user-images.githubusercontent.com/10111024/175076440-02bc6386-f0da-42ef-b911-c45c5c95a93d.png)

**Comment by bms63** [comment]
Focus on `derive` and `compute` functions.  Anything developer-wise will be moved to `admiraldev`

**Comment by fshanlee** [comment]
Hi @bms63 , in the unit_test_guidance.Rmd, I'm assuming you don't want to use `library` when we're instructing the user to type a single command in the Console, so, for example, we can leave `usethis::use_test("all_funcs")`; I'm also assuming we don't need to use `library` for code that the user will not see, such as 
```
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

**Comment by bms63** [comment]
are you talking about this one? 
![image](https://user-images.githubusercontent.com/10111024/182672621-b29bb8f7-64e7-44ec-8ddf-26fade2d6bf1.png)
yes lets leave things like that alone.

knitr:: can be left alone as well.

**Comment by fshanlee** [comment]
Yes, that's the kind of thing I was thinking of. Thanks for confirming--I'll leave things like that and knitr:: alone.

**Comment by esimms999-gsk** [comment]
I have made changes for tibble::, dplyr::, lubridate:: and maybe a couple of others. I have not touched any rlang::, knitr::, pkgdown::, admiral:::, etc.
Getting through devtools::document(), devtools::check(), devtools::test() without errors.

**Comment by esimms999-gsk** [comment]
@fshanlee There are four chackboxes at the top of the Issue; I have checked the "examples and tests using pkg_name::function() are updated with library(pkg_name)". Did you already complete the first three items?

**Comment by bms63** [comment]
Hey Eric, I would go ahead and put a PR in.  Then we can compare and contrast a little easier.

**Comment by fshanlee** [comment]
> @fshanlee There are four checkboxes at the top of the Issue; I have checked the "examples and tests using pkg_name::function() are updated with library(pkg_name)". Did you already complete the first three items?

Hi Eric, I think I completed the first two items.

**Comment by bms63** [comment]
This has been split into separate issues.  Closing
