### ISSUE TITLE
Documentation:  Admiral/Legal approved platform for recorded videos: training, conference presentations

### ISSUE THREAD

**Issue by esimms999-gsk** [pharmaverse/admiral#1236]
### Please select a category the issue is focused on?

User Guides, I have a new documentation idea! Yay!

### Let us know where something needs a refresh or put your idea here!

Instead of having a live demo at GSK on how to create ADAE (following the example in the article "Creating an OCCDS ADaM"), I am working on creating a training video for new users which does not mention me, anyone else, Roche, GSK  (except for whatever is already there on CRAN, e.g. authors, contributors, etc.).

I am hoping that we can create a series of such training videos and have them available to the general public. In order to make these videos available, we need a platform: a YouTube channel? a Slack channel? We need someone with some experience with this to evaluate which platform would be best (there may be size and cost constraints) and set up the platform.

We would also need to ensure that there is not any company-specific branding, etc. and get Legal to give their approval. Since these specific series of videos would be nothing more than what is already publicly available on GitHub, I expect the approval would be straight-forward.

**Comment by MichaelRimler** [comment]
@mstackhouse @skalappu @rossfarrugia 
I think it's fine - as long as the videos do not contain anything corporate or proprietary. I saw a video @esimms999-gsk created on ADAE creation and it seemed sterilized enough that I think there is no issue.

**Comment by rossfarrugia** [comment]
Thanks for the input! I'll look to get something set up for this soon and will share it out

**Comment by rossfarrugia** [comment]
YouTube channel now available: https://www.youtube.com/channel/UCxQFEv8HNqM01DXzdQLCy6Q

Reminder @thomas-neitmann or @bms63 to add this link to our README please and then it would be fine to close this issue.

**Comment by rossfarrugia** [comment]
thanks @bms63 - we can close this one then as you made a new issue
