### ISSUE TITLE
derive_param_first_event() - Variables to outputs

### ISSUE THREAD

**Issue by kabis-ops** [pharmaverse/admiral#1242]
### Feature Idea

Currently `derive_param_first_event()` output a new record where AVALC, AVAL and ADT are populated.
Even if AVAL/ADT does not exist in the input datasets, they will be created in the outputs datasets.
Is that what we really want? Should we allow some flexibility around the date and what variables to output?
See: https://github.com/pharmaverse/admiral/pull/1240

### Reproducible Example/Pseudo Code

Please refer to the example in the `derive_param_first_event()` documentation where AVAL is derived in the output datasets while not present in the input dataset.

**Comment by thomas-neitmann** [comment]
@sadchla-codes @zdz2101 Yet another issue to look into.

**Comment by sophie-gem** [comment]
Hi @bundfussr / @rossfarrugia, is this something else you want me to incorporate into #1317 ? (As I know you are eagerly awaiting this completion in order to make updates further down the line). I'm happy to do this - it would just take me a bit longer (otherwise the PR is pretty much ready to go)? [FYI - ADT is now only provided if you give it in the `set_values_to`. It is now only AVAL and AVALC that are created automatically]. Let me know your thoughts!

**Comment by sophie-gem** [comment]
I may be able to fit it in - but realistically, if I did it would not be ready until the end of this Sunday...does that work?

**Comment by rossfarrugia** [comment]
ok by me Sophie, if you're happy to. appreciate it!

**Comment by thomas-neitmann** [comment]
I think that's still very much OK 🙂

**Comment by sophie-gem** [comment]
Right ok, thanks both. I'll keep you posted on progress. Do I link this issue to the same PR (does that work)?

**Comment by thomas-neitmann** [comment]
Yes, that should work on the right side of the PR.

**Comment by sophie-gem** [comment]
Ok, so my current thoughts on how to approach this are:

- Add three more arguments to the function call:
  - `new_var_event` (default `AVALC`) which states the name of the variable which indicates whether an event happened or not
  - `value_had_event` (default `Y`) which states the value `new_var_event` should have if the event occurred
  - `value_no_event` (default `N`) which states the value `new_var_event` should have if the event did not occur

Does anyone have any thoughts on this?

**Comment by sophie-gem** [comment]
Thinking again, another potential option is that we instead add another two `set_values_to` arguments, one specific for those records that have an event, and another one specific for those records that don't have the event. So something like:

- `set_values_to_with_event` which will be the name-value pairs for those records which have the event
- `set_values_to_no_event` which will be the name-value pairs for those records which don't have the event

(Obviously we would still have the generic `set_values_to` which would be applied to both types of record as it currently does). 

Let me know if you have a preference or a different idea!

**Comment by rossfarrugia** [comment]
@bundfussr what do you think of Sophie's proposal? i don't know the full background on this but I'm starting to wonder if we're over-complicating this function by adding extra arguments? i don't remember seeing such flexibility on the other `derive_param_*` functions. on reflection i'm feeling like we shouldn't add this but then i wasn't part of the earlier discussions so i may be missing something.

**Comment by bundfussr** [comment]
@sophie-gem , @rossfarrugia , I would use the first proposal but rename the arguments such that they are in line with similar functions:
- `new_var` (default `AVALC`) which states the name of the variable which indicates whether an event happened or not
- `true_value` (default `"Y"`) which states the value `new_var` should have if the event occurred
- `false_value` (default `"N"`) which states the value `new_var` should have if the event did not occur

If we need additional variables whose value depend on whether an event occurred or not, a `mutate()` call can be used to add them. For example:
```
derive_param_extreme_event(
  ...
) %>%
mutate(
  AVAL = if_else(AVALC == "Y", 1, 0)
)

**Comment by sophie-gem** [comment]
Many thanks @bundfussr , @rossfarrugia - I will work on implementing it this evening / tomorrow morning!

**Comment by sophie-gem** [comment]
Within the function, I'm thinking that we need to assert that both `true_value` and `false_value` are scalar (length 1) and that they are both of the same 'type' using `class` or `typeof`. Are there any other assertions I should be checking for in the function?

**Comment by bundfussr** [comment]
@sophie-gem , we do not have an assertion for such a requirement. I would suggest to implement `asssert_same_type(...)` (in admiraldev). It could be useful for other functions as well, for example `derive_var_merged_exist_flag()`, where three arguments (`true_value`, `false_value`, and `missing_value`) must be of the same type.

**Comment by bundfussr** [comment]
@sophie-gem , I have implemented `assert_same_type()` in admiraldev (see https://github.com/pharmaverse/admiraldev/pull/177).

**Comment by sophie-gem** [comment]
Great, thanks @bundfussr! Will check it out now.
