### ISSUE TITLE
Bug: `list_tte_source_objects()` does not work correctly if an object is defined in admiral and an admiral extension package

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#1255]
### What happened?

`list_tte_source_objects()` does not work correctly if an object is defined in both admiral and an admiral extension package

**Comment by thomas-neitmann** [comment]
What exactly happens in that situation? Do you have an example?

**Comment by bundfussr** [comment]
It lists the object from `admiral` rather than the one from the extension package. Render the ADTTE vignette in https://github.com/pharmaverse/admiralonco/pull/51 for an example and consider the `death_event` object listed in the vignette.
