### ISSUE TITLE
Documentation:  Typo on derive_vars_dtm

### ISSUE THREAD

**Issue by morrishj** [pharmaverse/admiral#1261]
### Let us know where something needs a refresh or put your idea here!

On the [documentation page ](https://pharmaverse.github.io/admiral/reference/derive_vars_dtm.html) for this function, there is a an example given: impute_dtc(
"2020-11",
min_dates = list(
 ymd_hms("2020-12-06T12:12:12"),
 ymd_hms("2020-11-11T11:11:11")
),
date_imputation = "first"
)
I think "first" should be changed to "FIRST" as per the rest of the documentation on that page? The same example is also given on [this page](https://pharmaverse.github.io/admiral/reference/derive_vars_dt.html)

**Comment by bundfussr** [comment]
The `date_imputation` argument is case insensitive. I.e., both `date_imputation = "first"` and `date_imputation = "FIRST"` work.

**Comment by thomas-neitmann** [comment]
While both work I would like to be consistent and use lower-case everywhere.

**Comment by PuzzledFace** [comment]
There are several instances of `date_imputation = "FIRST"` in the documentation.  if consistency is required.  These should be changd.  Suggest linking to #1251.

**Comment by PuzzledFace** [comment]
Presumably, this applies to `"LAST"` and `"MID"` as well?  And to `time_imputation` as well as `date_imputation`?

Also note that function internals convert to UPPERCASE rather than lowercase, so writing `"first"`, `"mid"` and "last"` in documentation is at least partially inconsistent.
