### ISSUE TITLE
Find a license free questionnaire usable in ADQS vignette

### ISSUE THREAD

**Issue by thomas-neitmann** [pharmaverse/admiral#1266]

**Comment by esimms999-gsk** [comment]
VFQ-25: https://www.cdisc.org/standards/foundational/qrs/visual-functioning-questionnaire-25-interviewer-administered

See v 1.1 - 2014 (no changes in 8 years!). Has a section on copyright status. Full SDTM specs for QS and SUPPQS.

**Comment by esimms999-gsk** [comment]
https://www.cdisc.org/standards/foundational/qrs

![image](https://user-images.githubusercontent.com/85294667/176461377-b44e415f-23c6-4ea7-941d-bb770feccf40.png)

**Comment by PuzzledFace** [comment]
I believe the IIEF is license free.  You can find it [here](https://www.pfizerpcoa.com/international-index-erectile-function-iief) and the terms [here](https://www.pfizerpcoa.com/sites/default/files/Term_20AUG2018.pdf)

**Comment by rossfarrugia** [comment]
@koegerr as discussed the other day, see possible options above

**Comment by esimms999-gsk** [comment]
I think this issue is related to Issue #374 ?

While I have heard of COSA (CDISC Open-Source Alliance), I don't think I have heard of CORE (CDISC Open Rules Engine) before. There was mention of it, wrt a PharmaSUG 2022 presentation having to do with QRS (Questionnaires, Ratings, and Scales) at a GSK meeting this morning. I will try to find more info.

**Comment by esimms999-gsk** [comment]
I have been pointed towards:

- https://www.cdisc.org/core
- https://www.cdisc.org/standards/foundational/qrs

The PharmaSUG presentations were made by CDISC members and are not made available on the PharmaSUG website. But much of the content of the presentations can be found in the above links.

I do not know if we are still searching for a license-free questionnaire for our ADQS work in admiral but, if so, maybe COSA/CORE can give some guidance?

**Comment by rossfarrugia** [comment]
thanks Eric! @koegerr please can you check the above options with PCOR and let us know a decision on which to use? Can you do this before next release early Dec, as I'd like to put ADQS on the list for the March release then.

**Comment by bundfussr** [comment]
Nancy Brucken was in the questionnaires meeting last week. She is leader of the QRS subteam which develops ADaM QRS supplements. So far they have released two ADaM QRS supplements:
- [Generalized Anxiety Disorder-7 Version 2 (GAD-7 V2)](https://www.cdisc.org/system/files/members/standard/foundational/qrs/Supp%20v1.0%20ADaM%20GAD-7%20V2.pdf)
- [Geriatric Depression Scale Short Form (GDS SHORT FORM)](https://www.cdisc.org/system/files/members/standard/foundational/qrs/ADaM%20GDS%20Short%20Form%20Questionnaire%20Supplement-FINAL.pdf)

The documents above also include example data, which we could use in our examples.

**Comment by bms63** [comment]
We feel that we have enough resources for now and can close this issue.
