### ISSUE TITLE
Feature Request:  Create Proposal for Deriving ADQS Parameter of Original Items

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#1277]
### Feature Idea

A proposal for creating the following type of ADQS parameter should be created.

*Original items*: SDTM variables are mapped to `AVAL`, `AVALC`, `PARAMCD`. Variables like `CHG`, `CHGCAT1`, ... are derived.

The proposal should include
- a workflow,
- admiral functions which could be used,
- definition of new functions (name, arguments, description, example calls), and
- metadata supporting the derivation.

See also https://github.com/pharmaverse/admiral/issues/374.

**Comment by koegerr** [comment]
Is that not something that is covered already by BDS datasets in general?
