### ISSUE TITLE
Feature Request:  Create Proposal for Deriving ADQS Parameter of Worst Answer

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#1279]
### Feature Idea

A proposal for creating the following type of ADQS parameter should be created.

*Worst answer*: From certain original items the worst answered with yes is selected.

The proposal should include

- a workflow,
- admiral functions which could be used,
- definition of new functions (name, arguments, description, example calls), and
- metadata supporting the derivation.

See also https://github.com/pharmaverse/admiral/issues/374.

**Comment by bundfussr** [comment]
I have added a proposal to box: [ADQS Workflows (no metata)](https://exbpbox.box.com/s/m7doaqloo9d5ahvl4iiqls5dk38k4x6p)

**Comment by kaz462** [comment]
I wonder if we could use the existing function `derive_extreme_records()` with some pre-processing /add arguments?

1. pre-processing: order by AVALC and PARAM, user can specify the order of values (not necessarily ascending or descending order)
``` r
library(tibble)
library(dplyr)
library(admiral)
adqs <- tribble(
  ~USUBJID, ~PARAM,  ~AVALC, ~QSEQ,
  "1",      "SUICIDE",                      "N",      1,
  "1",      "Suicide Attempt",              "N",      2,
  "1",      "Preparation Suicide",          "Y",      3,
  "1",      "No Suicidal Behaviour",        "N",      4,
  "2",      "SUICIDE",                      "N",      1,
  "2",      "Suicide Attempt",              "Y",      2,
  "2",      "Preparation Suicide",          "N",      3,
  "2",      "No Suicidal Behaviour",        "N",      4,
)

adqs_order <- adqs %>%
  arrange(USUBJID, AVALC == "N",
          case_when(PARAM == "SUICIDE" ~ 1,
                    PARAM == "Suicide Attempt" ~ 2,
                    PARAM == "Preparation Suicide" ~ 3,
                    PARAM == "No Suicidal Behaviour" ~ 4
                    )
          ) %>% group_by(USUBJID) %>%
  mutate(new_order = row_number()) %>%
  ungroup()

adqs_order
#> # A tibble: 8 x 5
#>   USUBJID PARAM                 AVALC  QSEQ new_order
#>   <chr>   <chr>                 <chr> <dbl>     <int>
#> 1 1       Preparation Suicide   Y         3         1
#> 2 1       SUICIDE               N         1         2
#> 3 1       Suicide Attempt       N         2         3
#> 4 1       No Suicidal Behaviour N         4         4
#> 5 2       Suicide Attempt       Y         2         1
#> 6 2       SUICIDE               N         1         2
#> 7 2       Preparation Suicide   N         3         3
#> 8 2       No Suicidal Behaviour N         4         4
```

<sup>Created on 2023-01-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

The above `arrange`+`mutate` + `group_by` part can be replaced by `derive_var_obs_number()` when below issues are resolved, so that we can use functions of variables in the `order` argument like above `arrange`
https://github.com/pharmaverse/admiral/issues/1561
https://github.com/pharmaverse/admiraldev/issues/195

2. specify `order` by using `new_order` created above
``` r
derive_extreme_records(
  adqs_order,
  by_vars = vars(USUBJID),
  order = vars(new_order),
  mode = "first",
  set_values_to = vars(
    AVALC = PARAM,
    PARAMCD = "HSB",
    PARAM = "Highest Suicidal Behavior"
  )
)
#> # A tibble: 10 x 6
#>    USUBJID PARAM                     AVALC                QSEQ new_order PARAMCD
#>    <chr>   <chr>                     <chr>               <dbl>     <int> <chr>  
#>  1 1       Preparation Suicide       Y                       3         1 <NA>   
#>  2 1       SUICIDE                   N                       1         2 <NA>   
#>  3 1       Suicide Attempt           N                       2         3 <NA>   
#>  4 1       No Suicidal Behaviour     N                       4         4 <NA>   
#>  5 2       Suicide Attempt           Y                       2         1 <NA>   
#>  6 2       SUICIDE                   N                       1         2 <NA>   
#>  7 2       Preparation Suicide       N                       3         3 <NA>   
#>  8 2       No Suicidal Behaviour     N                       4         4 <NA>   
#>  9 1       Highest Suicidal Behavior Preparation Suicide     3         1 HSB    
#> 10 2       Highest Suicidal Behavior Suicide Attempt         2         1 HSB
```

<sup>Created on 2023-01-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>


3. in cases of no obs, add argument `dataset_expected_obs` in `derive_extreme_records()`

**Comment by kaz462** [comment]
* The above pre-processing part `arrange`+`mutate` + `group_by` part can be replaced by `derive_var_obs_number()` when below issues are resolved, so that we can use functions of variables in the `order` argument like `arrange`?
https://github.com/pharmaverse/admiral/issues/1561
https://github.com/pharmaverse/admiraldev/issues/195

* maybe the pre-processing part can be incorporated into a new argument in  `derive_extreme_records()`, or separated from `derive_extreme_records()` as a new function?

* [ADQS Workflows (no metata)](https://exbpbox.box.com/s/m7doaqloo9d5ahvl4iiqls5dk38k4x6p) has an additional consideration of `dataset_source` I didn't include in the above example

**Comment by bundfussr** [comment]
@kaz462 , I think your approach does not work for all scenarios.

For example, if "suicide" and "attempt" were answered with "N" and "preparation" and "no behavior" with `NA`, the result is "suicide" but it should be "missing" or "no behavior".

Another example is the case where there is no "no behavior" question. The result "no behavior" may be used if all questions were answered with no or alternatively all questions were answered with no or `NA`.

It might be possible to cover these scenarios by adding records to the input dataset and modify the sort order. However, this could get complicated and hard to use.

What do you think?

**Comment by kaz462** [comment]
Thanks, @bundfussr ! what do you think of `set_values_to = vars(AVALC = ANSWER)` instead of setting it to `PARAM`? so that no need to add records to the input data. `ANSWER` can be derived as below:
```r
mutate(ANSWER = case_when(AVALC == "Y"        ~ PARAM,
                          AVALC != "Y"        ~ "No Behavior"))
```

**Comment by kaz462** [comment]
> for the case that "No Suicidal Behaviour" is defined as all questions were answered with no?
And for the case that "No Suicidal Behaviour" is defined as all questions were answered with no or NA and at least one with no:

Yes, and `derive_expected_records()` could be used as pre/or post-processing to add "Missing" records

**Comment by bundfussr** [comment]
@kaz462 , it works but I am not sure if it is user friendly. We should discuss it on Friday to get some feedback from the others.

**Comment by bundfussr** [comment]
For ADQS parameters which select the worst answer of yes/no questions we have two options:

### Option 1: Use existing admiral function with pre-/post-processing
```
adqs %>%
  mutate(
    ANSWER = case_when(
      AVALC == "Y" ~ PARAM,
      is.na(AVALC) ~ "Missing",
      AVALC != "Y" ~ "No Suicidal Behavior"
  )) %>%
  derive_extreme_records(
    by_vars = exprs(USUBJID, AVISIT),
    order = exprs(case_when(
      ANSWER == "Completed Suicide" ~ 1,
      ANSWER == "Suicide Attempt" ~ 2,
      ANSWER == "Preparation of Suicide Attempt" ~ 3,
      ANSWER == "Missing" ~ 4,
      ANSWER == "No Suicidal Behaviour" ~ 5
    )),
    mode = "first",
    set_values_to = vars(
      AVALC = ANSWER,
      AVALN = case_when(
        ANSWER == "Completed Suicide" ~ 1,
        ANSWER == "Suicide Attempt" ~ 2,
        ANSWER == "Preparation of Suicide Attempt" ~ 3,
        ANSWER == "No Suicidal Behaviour" ~ 4,
        ANSWER == "Missing" ~ 99),       
      PARAMCD = "HSB",
      PARAM = "Highest Suicidal Behavior"
    )
  ) %>%
  select(-ANSWER)
```
### Option 2: Implement new admiral function
```
derive_param_??(
  adqs,
  by_vars = exprs(USUBJID, AVISIT),
  events = list(
    event(
      condition = PARAMCD == "SUICIDE" & AVALC == "Y",
      set_values_to = exprs(
        AVALC = "Completed Suicide",
        AVAL = 1)),
    event(
      condition = PARAMCD == "ATTEMPT" & AVALC == "Y",
      set_values_to = exprs(
        AVALC = "Suicide Attempt",
        AVAL = 2)),
    event(
      condition = PARAMCD == "PREPARE" & AVALC == "Y",
      set_values_to = exprs(
        AVALC = "Preparation of Suicide Attempt",
        AVAL = 3)),
    event(
      condition = all(AVALC == "N"),
      set_values_to = exprs(
        AVALC = "No Suicidal Behaviour",
        AVAL = 4)),
    event(
      condition = TRUE,
      set_values_to = exprs(
        AVALC = "Missing",
        AVAL = 99))
  ),
  set_values_to = exprs(
    PARAMCD = "HSB",
    PARAM = "Highest Suicidal Behavior"
  )
)
```
The function goes through the list of events. For each by group (e.g., subject and visit) AVALC and AVAL are set to the specified value for the first event where the condition is fulfilled.

@thomas-neitmann , @bms63 , @kaz462 , @DeclanHodges , @nbrucken17 , @esimms999-gsk , please have a look. I would like to discuss it at the meeting tomorrow and hopefully reach a decision.

**Comment by bms63** [comment]
**Decision**:  Implement Option 2.

**Comment by bms63** [comment]
Change Text in Examples to be generic and specific to a Questionnaire.
