### ISSUE TITLE
Feature Request: Create Proposal for Deriving ADQS Parameter of Completion

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#1280]
### Feature Idea

A proposal for creating the following type of ADQS parameter should be created.

*Completion*: Parameter indicating if at least n questions or p% of all questions were answered.

The proposal should include

- a workflow,
- admiral functions which could be used,
- definition of new functions (name, arguments, description, example calls), and
- metadata supporting the derivation.

See also https://github.com/pharmaverse/admiral/issues/374.

**Comment by kaz462** [comment]
admiral functions which could be used: `derive_summary_records()`
below code used the example data `adeg` from [derive_summary_records() documentation](https://pharmaverse.github.io/admiral/reference/derive_summary_records.html)
```r
derive_summary_records(
  adeg,
  by_vars = vars(USUBJID, PARAM, AVISIT),
  filter = TRTA != "",
  analysis_var = AVAL,
  summary_fun = function(x) n()/6 >= 0.5,
  set_values_to = vars(PARAMCD = "COMPL50P")
)
```

for the cases when 

> The parameter should also be created for subjects without observations in the qs dataset, e.g., for subjects who did not fill out the questionnaire.

 add argument `dataset_expected_obs`

**Comment by bundfussr** [comment]
@kaz462 , I think your suggestion is a good idea!

I wonder if we should implement a function for adding expected records to a dataset instead of adding argument `dataset_epected_obs`. For example `derive_expected_records()`. It would work like `derive_locf_records()` but without the fill part. Then we could derive completion parameters by
```
derive_summary_records(
  dataset = derive_expected_records(
    adqs,
    dataset_expected_obs = parm_visit_ref,
    by_vars = vars(USUBJID),
    set_values_to = vars(
      filledin = TRUE,
      PARCAT1 = "Original Item",
      ANL01FL = "Y"
    )
  ),
  filter = PARCAT1 == "Original Items" & ANL01FL == "Y",
  by_vars = vars(USUBJID, AVISIT),
  analysis_var = AVAL
  summary_fun = function(x) sum(!is.na(x))/13 >= 0.5,
  ),
  set_values_to = vars(
    PARAMCD = "COMPL50P",
    PARAM = "Completed at least 50% of questions",
    PARCAT1 = "Completion",
    AVALC = if_else(
      AVAL == 1,
      "Completed at least 50% of questions",
      "Completed less than 50% of questions"
    )
  )
) %>%
filter(!filledin)
```

What do you think?

**Comment by kaz462** [comment]
Thanks, @bundfussr ! I like the function idea, `derive_expected_records()` would be more flexible than an argument -
1. pre-processing the input data like your example above;
2. post-processing the output data as below
```r
output.data <- derive_summary_records(...)

derive_expected_records(
  output.data,
  dataset_expected_obs = parm_visit_ref,
  by_vars = vars(USUBJID),
  set_values_to = vars(
    AVAL= 0,
    AVALC = "Completed less than 50% of questions",
    ANL01FL = "Y"
  )
```
3. add functionality without modifying existing functions, it is also applicable to other scenarios, e.g., pre/post-processing `derive_extreme_records()`
