### ISSUE TITLE
There is a typo in one of the document code snippets that leads to an error when you copy the code and attempt to run

### ISSUE THREAD

**Issue by chebonday** [pharmaverse/admiral#1288]
### Please select a category the issue is focused on?

User Guides

### Let us know where something needs a refresh or put your idea here!

![Admiral documentation code error](https://user-images.githubusercontent.com/33558936/177354550-bce7de73-ad9d-4db5-a69d-95e7d6dcc0bb.jpg)

the function name needs to be corrected or the call needs to match the name of the function which is format_dctreas not format_dcsreas.

**Comment by bms63** [comment]
Close as part of version 8 release
