### ISSUE TITLE
debug_list()

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1297]
@sgorm123 hey Stephen.  Thought it would be great to have a discussion thread on your debug idea.  Do you mind putting your example code in here for all to see?

**Comment by thomas-neitmann** [comment]
@sgorm123 It would be great if you could provide us your code here. I'm very curious!

**Comment by bms63** [comment]
@sgorm123 Do you have a chance to write up any code or ideas you have around a debug_list.  If not, no problem, we can close this issue out.  I'm sure this idea/topic will circle back at a later time.

**Comment by bms63** [comment]
Closing as no feedback has been given
