### ISSUE TITLE
Partial Date Imputation derivations should only be done by derive_vars_dt/dtm functions

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiral#1299]
### Feature Idea

**Problem:** We have some downstream functions which rely on a date input and we end up repeating the imputation arguments to allow for DTC inputs. There is a risk they may not always be consistently added, so that different functions could include different imputation arguments. It also makes maintenance challenging, as any change to the underlying imputation function impacts many places. You could argue that it’s not always so transparent as well, as imputations get hidden away in intermediary steps within a derivation function.

**Agreed Solution:** Only allow imputations to be done using the derive_date_vars.R functions (which would only accept DTC dates), and make users do this as a step before feeding in the DT/DTM variable into any downstream derivation function. This means all the downstream derivation functions that allow for DTC would now be updated to only use DT or DTM and to remove any arguments related to date imputation. The strategy should be explained in the date imputation vignette / admiral programming strategy.

**As a result of this strategy, we will deprecate derive_vars_merged_dt() and derive_vars_merged_dtm().**

Tasklist:
- [ ]  remove date/time_imputation parameters from any `derive_`/`_source` functions except for `derive_vars_dt` & `derive_vars_dtm`, e.g. `date_source` or `dthcaus_source` (see #1125 - FYI @tamarasenior)
- [ ]  remove mentions of DTC variables in any other derivation functions - they should only ever accept dates or datetimes, e.g. see `derive_vars_last_dose` details section
- [ ]  update the date imputation vignette & programming strategy to clarify this approach
- [ ]  deprecate `derive_vars_merged_dt` and `derive_vars_merged_dtm`
- [ ]  update any such usages in templates & vignettes to match the approach given in the examples below

### Relevant Input

See examples below

### Relevant Output

See examples below

### Reproducible Example/Pseudo Code

**Examples:**

- For last known alive date (LSTALVDT), code that selects the date source could change as follows:
![image](https://user-images.githubusercontent.com/82581364/177749978-b61f992f-eee2-4997-bb8c-ee6ae912aaac.png)

- For first treatment date (TRTSDT), the call would change as follows:
![image](https://user-images.githubusercontent.com/82581364/177749896-9c87a05c-1cbc-41e9-ac30-8c6744b0223a.png)

**Comment by rossfarrugia** [comment]
@bms63 @thomas-neitmann @bundfussr - this is the first of the partial date refactor issues - please can you sanity check!

**Comment by bundfussr** [comment]
I assume "remove date/time_imputation parameters from any `derive_`/`_source` functions" means we remove these parameters but do not deprecate them.

@rossfarrugia , @thomas-neitmann , @bms63 , do you agree?

**Comment by rossfarrugia** [comment]
Personally i'm happy to just remove the arguments and accept the backward compatibility break given such a major change anyway, or otherwise will be a lot more work for you to try and update everywhere given the partial date re-factor connected update. @thomas-neitmann @bms63 feel free to over-rule me if a strong preference.

**Comment by thomas-neitmann** [comment]
I would not want to follow our usual practice of first deprecating the arguments with a warning but still keeping the functionality working. Rather, I'd opt for keeping the arguments for the moment but using `deprecate_stop()` to issue an error and let users know what to do. If we just remove the arguments all together then people will get a cryptic error telling them that argument xyz does not exist but no advice on how to mitigate this issue.

**Comment by bundfussr** [comment]
Makes sense to me, too. So I'm going to use `deprecate_stop()`.
