### ISSUE TITLE
Partial Date Imputation refactor

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiral#1300]
### Feature Idea

**Problem:** We need to reduce the cyclometric complexity of `derive_date_vars.R` and increase readability (#879), whilst also enabling further enhancements and features (as detailed below) to meet all the requests from the external testers. 
Allow to impute up to day only and not months (#1020) or up to any highest part of the datetime, e.g. could be everything up to years or only up to seconds (#879)

**Agreed Solution:** 
Firstly, the code needs to be refactored to reduce the cyclometric complexity.
To cover the enhancements, the following new `derive_date_vars.R` function argument is needed & this needs to be covered in the Date and Time Imputation vignette:

- `highest_imputation` – would be the highest part of the date/time that we want imputation to be applied to – year/month/day/hours/minutes/seconds. Options are “Y”, “M”, “D”, “h”, “m”, or “s”. For DT functions would only be “D”, “M”, or “Y”.

Important notes to consider for this update:
- If `highest_imputation=“Y”` is used for year imputation meaning we are imputing fully missing dates then this can only be used with `date_imputation=”first”` or `“last”` (as otherwise what would we set for `“mid”`?!) and it requires `min_dates`/`max_dates` to be used respectively as if `"first"` we'd set the missing year to min_date and if `"last"` set to max_date.
- We would have to make clear that the users could never pick and choose which sections of the datetime are imputed, e.g. impute months but not days - but this seems an unrealistic need and not something we should need to cater for anyway.
- Note this should then allow for cases where only missing hours, only missing minutes, or missing day/month/year but valid time. These examples didn't work for a user previously: `2003-12-15T-:15:18`, `2003-12-15T13:-:19`, `2020-07--T00:00`, so let’s cover them in our unit tests.
- We also need to test for the following user feedback: If `time_imputation=NULL` then you should still get the behaviour that a complete DTC with time gets set as the DTM, and only those with missing time get set as `NA`. Currently all get set as `NA` in this case (#879)
- Stefan spotted a bug:  `impute_dtc(dtc = "2020-02-02", time_imputation = "last", max_dates = list(lubridate::ymd("2020-02-02")))` gives `"2020-02-02T00:00:00"`, but should really be `"2020-02-02T23:59:59"`
- Need to add more documentation to `max_dates` argument from `derive_vars_dtm` - as specifying a DT for max_dates does not make sense if you impute time only as it will be ignored (recommend to use DTM instead), but a DT could make sense if date is imputed as well.

### Relevant Input

See examples below

### Relevant Output

See examples below

### Reproducible Example/Pseudo Code

**Examples:**

- Only impute up to DAYS:

```
  "2019-02-15",
  "2019-02",
  "2019",
  ""

derive_vars_dtm(
  highest_imputation = "D",  
  date_imputation = "FIRST",
  time_imputation = "FIRST"
)

```
Would give imputed DTMs as: 

```
  "2019-02-15T00:00:00",
  "2019-02-01T00:00:00",
  "",
  ""

```

- Only impute up to MONTHS:

```
  "2019-02-15",
  "2019-02",
  "2019",
  ""

derive_vars_dtm(
  highest_imputation = "M",  
  date_imputation = "FIRST",
  time_imputation = "FIRST"
)

```
Would give imputed DTMs as: 

```
  "2019-02-15T00:00:00",
  "2019-02-01T00:00:00",
  "2019-01-01T00:00:00",
  ""
```

- Impute up to YEARS:

```
  "2019-02-15",
  "2019-02",
  "2019",
  ""

derive_vars_dtm(
  highest_imputation = "Y",  
  date_imputation = "FIRST",
  time_imputation = "FIRST",
  min_dates =  ymd_hms("2018-01-01T00:00:00")
)
```
Would give imputed DTMs as: 

```
  "2019-02-15T00:00:00",
  "2019-02-01T00:00:00",
  "2019-01-01T00:00:00",
  "2018-01-01T00:00:00"

```

- Only impute up to MINUTES:

```
  "2019-07-18T15:25",
  "2019-07-18T15",
  "2019-07-18",

derive_vars_dtm(
  highest_imputation = "m",  
  date_imputation = "FIRST",
  time_imputation = "FIRST"
)
```
Would give imputed DTMs as: 
```
  "2019-07-18T15:25:00",
  "2019-07-18T15:00:00",
  ""
```

**Comment by rossfarrugia** [comment]
Whoever takes this on also makes sense to take https://github.com/pharmaverse/admiral/issues/1001

**Comment by bundfussr** [comment]
I am not sure if we can separate the imputation update into two issues. I think if we have two issues, we would need to update many files twice. If we do this issue first, we would need to add the new `highest_imputation` parameter in all calls of `derive_vars_dt(m)()` in all functions which use imputation. When we implement the second issue (https://github.com/pharmaverse/admiral/issues/1299) we would remove all the calls.

If we do https://github.com/pharmaverse/admiral/issues/1299 first we would first update all examples and templates without the `highest_imputation` parameter and then when we implement this issue we would need to update them again for adding the parameter.

Thus I wonder if we should have only one issue.

@rossfarrugia , @thomas-neitmann , @bms63 , what do you think?

**Comment by rossfarrugia** [comment]
@bundfussr i prefer 2 issues but maybe fine to tackle both in one branch by one person as you suggest. having all this in one massive issue i felt would be more difficult for our community to follow.

**Comment by billdenney** [comment]
My opinion is that we need a partial date-time object that we can then layer imputation on top of.  I think that a partial date-time object (including partial date objects and partial time objects) would reduce a lot of the complexity.  With a partial date-time object, `"FIRST"`, `"MID"`, and `"LAST"` imputation could become very simple, in general with `min()`, `median()`, or `max()`  (and `pmin()`, `pmedian()`, and `pmax()`-- though `pmedian()` doesn't exist) generics for the object.

The parallel versions could solve some issues that I have seen with imputation like:  "This adverse event occurred after visit 2 and before visit 3", where the date of visit 2 is "2022-07-02", the date of visit 3 is "2022-07-09", so we want to impute the date of the adverse event to be within that range while it's recorded in the SDTM as "2022-07".

**Comment by rossfarrugia** [comment]
@billdenney we're careful with the scope of admiral to cover majority of industry needs for ADaM, but accepting that we'll never cover all. The imputation you mention is such a rare scenario that we would leave that to companies to solve in their own extension package, as it is uncommon and overly complex. If my study clinical scientist were to request this then I would negotiate against, as the analysis impact wouldn't justify the effort.

Therefore we don't plan to go further than allowing the user to supply the missing part directly, e.g. "06-15", or use "FIRST", "MID", or "LAST" options. In this case "MID" doesn't relate to median it just simply picks 15 for missing day and 06-30 for missing month and day. 

Look forward to discussing later your ideas on a ISO8601 datetime parsing package.

**Comment by dgkf** [comment]
Seeing this after it was linked from #1315

A lot of these features are already implemented or would be rather simple additions to [`parttime`](https://github.com/dgkf/parttime). 

The package has been a bit underloved and could use a bit of polish, but it aims to solve a lot of these exact challenges. It parses iso8601 (largely borrowed from the `parsedate` package) already has `impute_time_max`, `impute_time_min` and `impute_time_mid`, and @billdenney has proposed a few additional helpers that would solve the date imputation and imputation to a certain field (imputing up until "year", "month", "date", etc). Its goal is to be a partial datetime type that requires minimal gymnastics to handle and propagate datetime missingness.

The imputation is the simplest part of the package so you can pretty reliably use those pieces. It also handles date arithmetic and comparisons for cases that get a bit messy with partial datetimes.
