### ISSUE TITLE
General Issue: Move function yn_to_numeric() to user_utils

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1303]
### Background Information

In the `derive_param_exist_flag.R` there is a `yn_to_numeric` function that I feel should get moved to the `user_utils` file.  @bundfussr what do you think?  

![image](https://user-images.githubusercontent.com/10111024/178028043-d6c506fe-0dcd-4983-817e-2a02456d885b.png)

### Definition of Done

Move function to `user_utils` file and update relevant tests

**Comment by bundfussr** [comment]
Fine with me
