### ISSUE TITLE
General Issue: derive_vars_dt, date_imputation keywords case difference

### ISSUE THREAD

**Issue by oreillb1** [pharmaverse/admiral#1307]
### Background Information

Case of keywords in derive_vars_dt, date_imputation in reference are  "FIRST", "MID", "LAST" but are used in lowercase in some vignettes, e.g. ADRS.  Unsure if documentation or vignette codes need updating.
adrs <- adrs %>%
  derive_vars_dt(
    dtc = RSDTC,
    new_vars_prefix = "A",
    date_imputation = "last")

**Comment by thomas-neitmann** [comment]
Keywords are **not** case-sensitive but @PuzzledFace already made sure that we use lowercase consistently in #1286.

**Comment by rossfarrugia** [comment]
I think this one can be closed given it's addressed in the PR above - and I checked ADRS vignette in admiralonco and that uses lowercase too so we should be all good. @oreillb1 do shout if i'm missing anything though and we could re-open.
