### ISSUE TITLE
Feature Request:  derive_vars_dt enhancement to include processing same date different visit names

### ISSUE THREAD

**Issue by oreillb1** [pharmaverse/admiral#1313]
### Feature Idea

derive_vars_dt needs additional option code so that it can process valid duplicates, same date but different visit names, as this can be expected for some domains. For example [RS.RSDTC] can be identical e.g. when [RS.VISIT] = 'Tumor Assessment Week' and [RS.VISIT] ='Treatment Discontinuation'

**Comment by oreillb1** [comment]
Could use the domain sequence number to find first or last

**Comment by bundfussr** [comment]
Thanks for creating the issue.

I am not sure what you want to add to `derive_vars_dt()`. Could you provide an example?

Do you want to use different values for the imputation arguments depending on `VISIT`? Could `slice_derivation()` solve the issue (see [Using More Than One Imputation Rule for a Variable](https://pharmaverse.github.io/admiral/articles/imputation.html#using-more-than-one-imputation-rule-for-a-variable) for an example)?

**Comment by oreillb1** [comment]
Thanks I will explore using slice_derivation() possibly including VISITNUM to identify first or last correctly

**Comment by bundfussr** [comment]
@oreillb1 , could you provide an example call of the enhanced function and the expected output? Also the specification of the variable you want to derive would be helpful.

It is still not clear to me which functionality you need.

**Comment by thomas-neitmann** [comment]
Closing as underlying issue is #1317.
