### ISSUE TITLE
Feature Request:  derive_locf_records

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1316]
### Feature Idea

Implement a Last observation carried forward derviation function called `derive_locf_records`.  This is based on discussion from #645 

### Reproducible Example/Pseudo Code

```
derive_locf_records(
  dataset,
  dataset_expected_obs,
  by_vars,
  order
)
```

Proposed workflow:

1. Split input dataset into observations with non-missing `AVAL` and missing `AVAL`.
1. For the non-missing part add for each by group the observations from `dataset_expected_obs` if they are not present. Set `DTYPE = "LOCF"` for the added observations.
1. Use `group_by(by_vars)`, `arrange(order)` and `fill("AVAL")` to populate `AVAL` (and `AVALC`?) for the added observations.
1. Put together the extended non-missing part and the missing part.

For `dataset_expected_obs` the function expects a data frame with all the combinations of `PARAMCD`, `PARAM`, `AVISIT`, `AVISITN`, ... which are expected. If the visits are the same for all parameters, `PARAMCD` and `PARAM` can be omitted and added to `by_vars`.

The value of `dataset_expected_obs` is the study specific part. I would expect that the workflow should meet the needs for LOCF in most studies.

**Comment by gg106046** [comment]
@bms63 Can I take this up?

**Comment by bms63** [comment]
That sounds great!  Did you finish the admh script?

**Comment by gg106046** [comment]
> That sounds great! Did you finish the admh script?

Yes admh script is done. I've pushed the latest code into GitHub
