### ISSUE TITLE
Feature Request: Enhance `derive_param_first_event()`

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#1317]
### Feature Idea

`derive_param_first_event()` should be enhanced such that the order can be specified and the last instead of the first event can be derived. I.e.,
- the `date_var` argument should be replaced by the `order` argument and
- the function should be renamed to `derive_param_extreme_event()` and the `mode` argument should be added.

**Comment by thomas-neitmann** [comment]
@sophie-gem volunteered to work on this.

**Comment by sophie-gem** [comment]
Firstly, apologies it has taken me so long to find time to contribute to admiral again!

I just wanted to confirm, as the entire function is changing (so following the function depreciation method) do I need to follow the parameter depreciation function for `date_var` which is changing to `order` or not? (I am thinking not, but just wanted to check)

**Comment by thomas-neitmann** [comment]
> I just wanted to confirm, as the entire function is changing (so following the function depreciation method) do I need to follow the parameter depreciation function for date_var which is changing to order or not? (I am thinking not, but just wanted to check)

That's an interesting case we didn't have before, i.e. both function name and one parameter name changing. My gut feeling is that we should properly deprecate both the old function and the old parameter.

**Comment by sophie-gem** [comment]
> My gut feeling is that we should properly deprecate both the old function and the old parameter.

Right ok, thanks @thomas-neitmann, I will give that a go.

**Comment by thomas-neitmann** [comment]
Awesome, thanks a lot @sophie-gem!

**Comment by sophie-gem** [comment]
Do we remove deprecated parameter descriptions? Or do we just add in the ```*Deprecated*, please use `order` instead.``` above the initial description?

**Comment by thomas-neitmann** [comment]
I think we remove the original description.

**Comment by sophie-gem** [comment]
The programming vignette states that we remove the `@family` roxygen tag from the documentation however in other deprecated function programs they've set the `@family` roxygen tag to `deprecated`. Which should I follow?

**Comment by sophie-gem** [comment]
Also, am I correct in thinking that the next release will be version `0.9.0`?

**Comment by thomas-neitmann** [comment]
> The programming vignette states that we remove the @family roxygen tag from the documentation however in other deprecated function programs they've set the @family roxygen tag to deprecated. Which should I follow?

The latter. And could you open an issue to fix this discrepancy?

> The programming vignette states that we remove the @family roxygen tag from the documentation however in other deprecated function programs they've set the @family roxygen tag to deprecated. Which should I follow?



> Also, am I correct in thinking that the next release will be version 0.9.0?

That's right!

**Comment by sophie-gem** [comment]
Thinking about it, don't we need the `date_var` argument as well as the `order` argument, as they need to indicate what `ADT` is set to for the new observations?

See block of code below:
```
  new_obs <- bind_rows(events, noevents) %>%
    mutate(
      ADT = !!date_var,
      AVALC = if_else(!is.na(ADT), "Y", "N"),
      AVAL = if_else(!is.na(ADT), 1, 0),
      !!!set_values_to
    )
```

**Comment by thomas-neitmann** [comment]
> Thinking about it, don't we need the date_var argument as well as the order argument, as they need to indicate what ADT is set to for the new observations?

@bundfussr @bms63 What do you think?

**Comment by bundfussr** [comment]
If we want to keep `ADT` hard-coded, we need the `date_var` argument.

However, I am not sure if that's the right way for a general admiral function. The function was implemented for oncology, where it is fine to use `ADT` (and not `ADTM`). Maybe we should remove `ADT = !!date_var` and use `set_values_to` to define variables like `ADT` or `ADTM`?

**Comment by sophie-gem** [comment]
I think your second suggestion is the best way around this - thanks @bundfussr! I'll insert some additional documentation to make it clear that programmers are required to provide what is needed as the date for the new rows.

**Comment by rossfarrugia** [comment]
@sophie-gem firstly, thanks for picking this up! we wanted to ask if you think this one will be ok to update in the next month or so? reason being with this update we found we could deprecate a function in {admiralonco} so would be good to have both updates in the next release in Dec. tagging @sgorm123 as FYI as he's on that respective onco issue.

**Comment by sophie-gem** [comment]
Hi @rossfarrugia @sgorm123 , yes of course - I plan on finishing off this issue in the next couple of weeks. Will that work for you?

**Comment by rossfarrugia** [comment]
Absolutely, thanks! 🌟

**Comment by rossfarrugia** [comment]
hi @sophie-gem, how's it going with this one?

**Comment by sophie-gem** [comment]
Hi, in terms of unit tests for the updated function: do I only update those tests that were written for the deprecated function? Or would it be wise to add in another test for `mode = 'last'` (as due to the nature of the deprecated function each of the two tests are based just on `mode = 'first'`)? Or is this ok, as the parameter `mode` is passed onto `filter_extreme` which should have its own set of unit tests?

**Comment by rossfarrugia** [comment]
i would add extra tests to check the new feature `mode = 'first'`, and also please follow https://pharmaverse.github.io/admiraldev/devel/articles/programming_strategy.html#deprecation guidance for deprecation. @bundfussr may be able to add deeper details.

**Comment by sophie-gem** [comment]
**Status update**: `derive_param_first_event` has been deprecated with warning (as has the associated `date_var` parameter within `derive_param_extreme_event`). Function `derive_param_extreme_event` has been created (adapting and generalising as requested in issue definition). Tests have been writing to check for warnings in deprecation and for the new function with `mode` equal to both 'first' and 'last'. Believe all that is left is for me to work through the PR checklist (update NEWS etc.). So, if I don't get it complete by later this evening - hopefully tomorrow morning at the latest the PR will be available.

**Comment by bundfussr** [comment]
Deprecating `date_var` in `derive_param_extreme_event()` looks strange to me because the function was not available before. So user should not have old code calling `derive_param_extreme_event()` with the `date_var` argument. I would deprecate `derive_param_first_event()` only and mention in the deprecation message that `derive_param_extreme_event()` should be used now with the `order` argument instead of the `date_var` argument.

@thomas-neitmann , what do you think?

**Comment by sophie-gem** [comment]
Thanks both - I will make that alteration then!

**Comment by sophie-gem** [comment]
Just one final question - should I change the file name from `derive_param_first_event.R` to `derive_param_extreme_event.R` (and then the same for the test file) or is it recommended to leave these as is?

**Comment by rossfarrugia** [comment]
Use extreme @sophie-gem - then it will match the other "extreme" functions.

**Comment by sophie-gem** [comment]
Hi (me again, sorry), I was going to put the explanation in the 'New Features' section of the `NEWs.md` file, but then I was wondering if it would be more appropriate to go in 'Updates of Existing Functions' section. Any preferences?

**Comment by rossfarrugia** [comment]
'Updates of Existing Functions' & 'Breaking Changes' i think - but shout anyone if you disagree!

**Comment by bundfussr** [comment]
@sophie-gem , unfortunately, I found a bug in `derive_param_first_event()`.
There the following call is used.
```
  derive_param_extreme_event(
    dataset = dataset,
    dataset_adsl = dataset_adsl,
    dataset_source = dataset_source,
    filter_source = !!filter_source,
    order = vars(!!date_var),
    subject_keys = subject_keys,
    set_values_to = set_values_to,
    check_type = check_type,
    mode = "first"
  ) %>%
    mutate(
      AVAL = if_else(AVALC == "Y", 1, 0)
    )
```
The `mutate()` call derives `AVAL` for all records but it should derive it for the new records only.

Do you have time to fix it?

**Comment by sophie-gem** [comment]
@bundfussr  Ah, I'm sorry - should've seen this! When do you need it by - if I fixed it tomorrow morning would that work? Also, is the feature branch still available or should I create a new one?

**Comment by bundfussr** [comment]
@sophie-gem , thanks for the quick reply. Yes, tomorrow morning is fine.

The feature branch was removed when the PR was merged but you can restore it. There is a "Restore branch" button at the end of the pull request.

**Comment by sophie-gem** [comment]
@bundfussr I will need to open a new PR, is that correct?
