### ISSUE TITLE
General Issue: ADVS vignette code text header for BMI section incorrect

### ISSUE THREAD

**Issue by oreillb1** [pharmaverse/admiral#1318]
### Background Information

ADVS vignette code repeated above incorrect code section 
# Derive Body Surface Area header is used above section derive_param_bmi
Should read 
# Derive Body Mass Index 
above section derive_param_bmi

**Comment by oreillb1** [comment]
Yes I would be happy to make this straightforward change.

**Comment by thomas-neitmann** [comment]
Excellent, thanks a lot @oreillb1! Please refer to [this document](https://pharmaverse.github.io/admiral/articles/git_usage.html) for information regarding `git` usage.
