### ISSUE TITLE
Documentation: Website should be published on release, not push to main

### ISSUE THREAD

**Issue by thomas-neitmann** [pharmaverse/admiral#1320]
### Please select a category the issue is focused on?

Other

### Let us know where something needs a refresh or put your idea here!

Currently the website is updated when something is pushed to `main`. This lead to v0.7.1 being visile on the website since last Friday although we haven't formally released it, yet. Thus, I propose that we only publish the website when a new release is made.

Fyi @bms63 @dinakar29

**Comment by thomas-neitmann** [comment]
We only make the GitHub release after the package has been accepted to CRAN. Thus, there'a a lack between the push to `main` and the release.

**Comment by thomas-neitmann** [comment]
We could circumvent that by having a `pre-release` branch off which we submit to CRAN and once we get accepted we merge that branch into `main`.

**Comment by bundfussr** [comment]
I like the `pre-release` branch idea. Seems a clean solution.

Pushing to `main` without any announcement and without publishing the website could cause confusion because the workflows for extension packages install admiral from `main`.

**Comment by bundfussr** [comment]
By the way, why is the CRAN date not displayed on the Changelog page? Is this intentional?

**Comment by thomas-neitmann** [comment]
Certainly **not** intentional. Please open a separate issue.

**Comment by bundfussr** [comment]
Done: https://github.com/pharmaverse/admiral/issues/1321

**Comment by bms63** [comment]
This topic is capture in the release vignette update.  Shall we close or link?

**Comment by bundfussr** [comment]
I think we can close it because using the `pre-release` branch does no longer require an update of the workflow.
