### ISSUE TITLE
Documentation: Display CRAN Date on Changelog Page

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#1321]
### Please select a category the issue is focused on?

Other

### Let us know where something needs a refresh or put your idea here!

The CRAN release date should be displayed on the Changelog page. (Update `_pkgdown.yml`:
```
news:
  cran_dates: true
```
)

**Comment by bms63** [comment]
I guess one of the updates snuck into `devel`  from 0.7.1
![image](https://user-images.githubusercontent.com/10111024/179542300-756a87d7-6bea-4095-8560-ce7528edad98.png)
