### ISSUE TITLE
General Issue: Action to synch main/pre-release branch to patch branch

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1332]
### Background Information

To keep the `patch` branch up to date with the `main/pre-release` branch we should use a GH action to automate this step.

The `patch` branch will hopefully be used infrequently, but we want it to be ready  if needed in a pinch.  Having to trouble shoot and update the `patch` branch might get tedious as it could be severely outdated.  To remedy this an action should be created that will automatically create a PR for merging `main` into `patch` with reviewers assigned when main is updated.  

A possible candidate is here https://github.com/marketplace/actions/sync-branches

### Definition of Done

Action created that automatically merges `main` into `patch` whenever `main` is updated.

**Comment by galachad** [comment]
Hi @bms63, could you verify the logic behind https://github.com/pharmaverse/admiral/pull/1801 if we still need this action?

> Action created that automatically merges main into patch whenever main is updated.

**Comment by bms63** [comment]
I think we only need one PR to be created for `main > patch` when we make do a proper release. 

This way we can be ready for a hotfix and not interrupt development work in `devel` if the hotfix/pathch is needed.  

We are removing `pre-release` branch as it is overly complicated, but we need to update CI workflow for building website to only to that when we do a release.

**Comment by bms63** [comment]
oh but i guess if we do a hotfix and merge to main then we also need a auto-PR for `main with hotfix/patch` to `devel` branch

**Comment by bms63** [comment]
I think this can get closed out as we are going to move to the more modern approach.

@cicdguy Still good for July 25th demo at IDR meeting to brings us from 2008 to 2023?  

@pharmaverse/admiral just for everyone's awareness - we are most likely removing the `devel` and `patch` branches from our admiral lives. :( they served us well!  This brings us more in-line with how everyone else does thing in their development processes.
