### ISSUE TITLE
Deprecation:  `derive_var_agegr_fda` and `derive_var_agegr_ema`

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1333]
These two functions need to be deprecated following our deprecation strategy.  https://pharmaverse.github.io/admiral/articles/programming_strategy.html#deprecation

**Comment by bundfussr** [comment]
We decided that the `derive_var_agegr_*()` functions should be deprecated (see https://github.com/pharmaverse/admiral/issues/856). Apparently we missed to do it. We could use this issue for the deprecation or create a new one.
