### ISSUE TITLE
Feature Request:  Global option program to save maintaining things in many programs

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiral#1338]
### Feature Idea

Summarizing the below thread of discussions with an agreement from myself, Ben and Thomas over a call:

We intend here to allow for the subject key variables (only) to be controlled by an option that a user could pass once for their study/reporting event etc and it would impact all function calls. Default option would still be `vars(STUDYID, USUBJID)` so we have no breaking change and many users would never need to use this. An example of usage would be say if for a study you needed to use `USUBJID2` instead of `USUBJID`.

The way we plan to achieve this would be to make a new admiral function to set the subject key option using `getOption("admiral_subject_keys", vars(STUDYID, USUBJID))`. By creating a new function for this it would allow us to include a functional reference page with explanatory documentation and examples. 

All of the functions that include the `subject_keys` argument would then use the global option `"admiral_subject_keys"` as default and in the explanation of this argument we could link to the new admiral function documentation replacing the below 2nd sentence:
![image](https://user-images.githubusercontent.com/82581364/196451106-3dfe1706-9e03-4e42-ba3d-101ef5a9d2eb.png)

Note: below there were ideas for other areas this could be potentially used, but we wanted to limit it to only places where it saves a substantial amount of user copy and paste across most functions, as by including this we recognise it's another layer of complexity and means developers and QC'ers have to be aware of one additional program.

**Comment by bundfussr** [comment]
Another example is the `preserve` argument of the imputation functions. If a company or study does not want to use the default, the argument needs to be specified in each imputation function call. Obviously this is tedious and error-prone.

**Comment by millerg23** [comment]
Do we have subject identifiers hard-coded into the functions? Aren't most of the variables passed in as input parameters? Perhaps there are a few default values with subject IDs, but don't we have things like PARAMCD and AVAL also hard-coded.

**Comment by bundfussr** [comment]
I hope we do not have subject identifiers hard-coded in the function. Functions which derive by subject should have a `subject_keys` parameter which is defaulted to `vars(STUDYID, USUBJID)`.

**Comment by bms63** [comment]
In logrx package we have ability to write a list of approved and unapproved packages and functions.  https://atorus-research.github.io/logrx/articles/approved.html.  When logrx is executed and this is declared in options as something the user wants, then a new section of the log is written with approved and unapproved functions.

Maybe there is a way to adopt this for a list of approved variables across the functions for certain datasets.  Then someone can go in and update the list if they are moving programs to another study and need to change for example the treatment codes across all the functions used within that  programs?  

| Global Variable                                                               |   Approved Variable|
|-----------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------|
| `trtcd`                                                                   | tr01an                                                                   | 	
| `trt`                                                                |tr01a                                                                                    |

`options(admiral.approved__adsl_vars = file.path(dir, "approved_vars_adsl.rds"))`

**Comment by rossfarrugia** [comment]
i think that's a similar thinking from what I understand of your reply @bms63. it's just a case of storing global defaults in one central program, so that if for whatever reason a user needed to use STUDYID USUBJID**2** then they'd only update this default in one place for their study and it would work for all their function calls. i'm open to the best way technically to achieve this, but hope it can be a simple and transparent solution, and it should be documented in our site.

**Comment by thomas-neitmann** [comment]
This is fairly straightforward to achieve. Let's take the `subject_vars` parameter as an example. Currently, by default it is set to `vars(STUDYID, USUBJID)` in several functions. Instead, we could set it to `getOption("admiral_subject_keys", vars(STUDYID, USUBJID))`. This basically means, use the global option `"admiral_subject_keys"` if it has been set by the user using `options(admiral_subject_keys = ...)` or use the default `vars(STUDYID, USUBJID)` if not. One could also automatically set the global option when loading the package and make the default value just `getOption("admiral_subject_keys")`. However, I think the former is much more transparent and thus preferrable.

ALl that being said, I still think we should make use of global options **very** sparingly as they make things depends upon things not specified as function arguments.

**Comment by bms63** [comment]
When would a user/users want to do this?   Does this make sense to have these types of examples in admiral?

I'm starting to feel like this would be a great bookend for the e2e examples?   Like an advance use-case of how to use the options to make your code re-usable across the life of a study

**Comment by thomas-neitmann** [comment]
> When would a user/users want to do this? Does this make sense to have these types of examples in admiral?

I'd imagine this to be set either at the top of an individual script or if there is some sort of pipeline tool involved to run all scripts in a batch then inside a little "config" file that is run first.

> I'm starting to feel like this would be a great bookend for the e2e examples? Like an advance use-case of how to use the options to make your code re-usable across the life of a study

That would certainly a good place to highlight this functionality.

> I would prefer setting the global option when loading the package. Otherwise, we would need to repeat the default in each place where we are using the global option. I think this would be error-prone.

Very valid point!

**Comment by bms63** [comment]
Transferred as an issue to e2e examples. https://github.com/pharmaverse/end_to_end_examples/issues/10

**Comment by rossfarrugia** [comment]
@bms63 we absolutely could include an example of this in e2e site which shows an example say where you needed to use a different set of subject identifier variables across all functions in one easy way.... but why would this issue be closed for admiral? As for me it first needs to be implemented in admiral, e.g. creating the file that stores these global options and then updating every function to include for example: `getOption("admiral_subject_keys", vars(STUDYID, USUBJID))`

Am i missing something though?

**Comment by bms63** [comment]
We were discussing this as a more process-based topic of moving code from one study to a new study/making code re-usable and out of scope for `admiral` for building ADaM datasets.   It seems to open a can of worms of how deep to go with the `Options` and we discussed how it might be confusing for users to see this as an option.  

It was thought that this could be developed within the e2e examples and suggestions could be made to allow for the admiral functions to be adapted to be more re-usable across studies.  I'm happy to keep open if you think it should be.

I definitely sympathize with this idea and that is why we transferred rather than fully closed.!!

**Comment by rossfarrugia** [comment]
OK, so the decision is we won't implement this for subject identifier keys in the admiral package (as that would involve updating many admiral functions), and instead we could put an example of this in the e2e examples, e.g. maybe easiest to do this for the ADSL keep list there.

If a user then ever needed to change say `USUBJID` to `USUBJID2`, they would have to set up an option for this at their study level and then set `subject_keys` to this option across all their function calls, rather than being able to update this only in one single place. Or probably in this case it would be just as easy for them to set `subject_keys` as `vars(STUDYID, USUBJID2)` everywhere anyway. i.e. my point is without enabling such a global option via admiral there's little value here to the users in this case, as they're going to be updating the same thing in many places regardless. 

I'm OK with the team decision on this as I accept most users won't ever need this and I see how it could open up a pandora's box of other places this approach could be considered, but just want to be sure it's clear that doing this only on the e2e examples side doesn't help for the subject identifier case.

**Comment by bundfussr** [comment]
I completely agree with @rossfarrugia . If it is not implement in admiral, it doesn't help. Furthermore, I already know of some use cases at Roche:
- A group at Roche needs to change the subject identifier variables frequently due to anonymization.
- For date imputation Roche uses `preserve = TRUE`. I.e., in all Roche programs the `preserve` argument needs to be specified.
- The admiralonco functions provide the `aval_fun` argument to specify the mapping of AVALC values to AVAL values. At the moment it is defaulted to the Roche standard. Companies which use a different mapping need to specify the argument in each function call.

Thus I think it would be useful to implement the feature in admiral.

**Comment by bms63** [comment]
Okay....I'm worried this is going to make things more confusing for users, but sounds like we got a lot of interesting use cases to investigate.

**Comment by rossfarrugia** [comment]
thanks @bms63 - i moved this back to priority issues now and fine if this one is picked up as part of release 9 by end of the year, if we don't get around to adding it for upcoming release next month.

**Comment by rossfarrugia** [comment]
@bms63 @thomas-neitmann see the edited issue now and please update further if needed. We can discuss with the core dev team tomorrow

**Comment by bms63** [comment]
Looks good to me.

**Comment by bundfussr** [comment]
@rossfarrugia , I do not understand "The way we plan to achieve this would be to make a new admiral function to set the subject key option using `getOption("admiral_subject_keys", vars(STUDYID, USUBJID))`.".
Why is `getOption()` used if the function should *set* the option?
How is the default for `admiral_subject_keys` set if the user does not call the new function?

**Comment by rossfarrugia** [comment]
@bundfussr probably my bad wording... we need a new admiral function here to ensure it gets its own Roxygen2 section and documentation page, but we should be able to make use of getOption R function as part of it.

Good question on how to set the default - ideally we'd want this option set to `vars(STUDYID, USUBJID)` always as default unless they specifically set it otherwise. @thomas-neitmann @bms63 any ideas??

**Comment by thomas-neitmann** [comment]
Basically we'd have a `set_subjects_key()` and `get_subject_keys()` function which would both live on the same help page. Upon loading admiral `set_subject_keys()` would be called to set our default, `set_subject_keys(vars(STUDYID, USUBJID))` and all our functions would have `get_subject_keys()` as default.

One could implement these function using R's `options()` and `getOption()` functionality but we can also just save the values in our package namespace.

**Comment by rossfarrugia** [comment]
thanks @thomas-neitmann - can you edit the issue above please to explain this better than i did? :)

**Comment by bundfussr** [comment]
Thanks, I understand now what you want to do.

However, the approach does not look convincing to me.

- Why do we add new functions just for writing documentation? Why do we not use `options()` and `getOptions()` and write a vignette describing the admiral options or document them like the datasets in `data.R`?
- How would this work for the other use cases? Would we add another two functions for each option?

**Comment by rossfarrugia** [comment]
Good discussion topics for the call today! We were trying to avoid an extra vignette just for this (as we couldn't see anywhere it fit in the current site pages) and we don't see this being extended to any other areas of usage, but agree not sure it's the most elegant solution so open to other ideas.

**Comment by rossfarrugia** [comment]
FYI @zdz2101 and @sadchla-codes as discussed and please one of you take this on and unassign the other, whenever you're ready.

**Comment by rossfarrugia** [comment]
Also whoever takes on please assign yourself for: https://github.com/pharmaverse/admiralonco/issues/175 - i just sent you an invite for write access to this repo too.

**Comment by zdz2101** [comment]
Is this only for `subject_keys` input? Or a matter of wherever `vars(STUDYID, USUBJID)` is being used which would include many of the `by_vars` instances as well? Screenshot of the find in files below:

![image](https://user-images.githubusercontent.com/43018762/196802081-5c538b87-41ff-4d88-8074-80ee1db89260.png)

**Comment by thomas-neitmann** [comment]
Only for `subject_keys`.

**Comment by rossfarrugia** [comment]
@bms63 shouldn't the `derive_var_last_dose*` functions that Zelos found above have a blank default for `by_vars` like all the other functions? I saw you were the author. That would solve this potential confusion for users, as they may ask why we don't set these as default to `"admiral_subject_keys"` also. It could be something we clean up all in one go as part of this issue if you agree?

**Comment by zdz2101** [comment]
As for the solution implementation, it seems what's been discussed so far would be either: 

1. The use of R's options functions: `options(admiral_subject_keys = ...)` and `getOption("admiral_subject_keys")` 
2. Creating the separate `set_subjects_keys()` and `get_subject_keys()` functions. 

Although we should advise to use sparingly is there a scenario one day where other inputs or a future input might need this flexibility as well? Is there any merit to having a global `admiral_options` which would contain a list of defaults when loading into the package?

For example something along the lines of this,

options(
admiral_options = list(
subject_keys = vars(STUDYID, USUBJID),
future_input = vars(STUDYID, SITEID))
)

Then create `get_admiral_options()` and `set_admiral_options()` such that it would pull the necessary defaults/user-defined inputs

`set_admiral_options(subject_keys = vars(STUDYID, USUBJID2)) `
and functions would have 
`get_admiral_options(subject_keys)` as default

Then if in the future, if another instance of this scenario arises for another input,
`set_admiral_options(future_input = vars(STUDYID, COUNTRY))`
`get_admiral_options(future_input)`

This way the documentation only needs to written once, and we can control how many options-able inputs we have?

**Comment by thomas-neitmann** [comment]
@zdz2101 I like your suggestion! I would store the `admiral_options` list in our package environment, i.e. not using `options()`, and set default values there. Both the `set` and `get` function can check whether the specified option actually is part of `admiral_options` and if not throw an error.
