### ISSUE TITLE
General Issue: derive_param_tte appears to be missing a set up for AVALU

### ISSUE THREAD

**Issue by oreillb1** [pharmaverse/admiral#1339]
### Background Information

derive_param_tte appears to be missing a setup for AVALU, which can be different depending on the domain data.

**Comment by thomas-neitmann** [comment]
Could you elaborate a bit more @oreillb1? `derive_param_tte()` returns the time to event in **days**. Are you looking for functionality to output the result in other units, e.g. "weeks"? Or is this just about setting the `AVALU` variable? In that case you can use the `set_values_to` parameter, e.g. `set_values_to = vars(AVALU = "DAYS")`.

**Comment by bundfussr** [comment]
`derive_param_tte()` derives `ADT` or `ADTM` only. `AVAL` (and `AVALU`) is derived in a separate step for all parameters together:
```
adtte <- derive_vars_duration(
  adtte,
  new_var = AVAL,
  new_var_unit = AVALU,
  start_date = STARTDT,
  end_date = ADT
)
```
You can specify the `new_var_unit` argument to add a variable for the unit.

**Comment by oreillb1** [comment]
AVALU is in our ADaM specifications for ADTTE so it will always be missing from the dataset unless deliberately included in derive_vars_duration. Could AVALU be created null by default in ADTTE and then it would be up to the programmer to define?

**Comment by bundfussr** [comment]
`AVALU` is a Roche specific variable. Thus I would not add it to the general admiral vignette. If we provide a template script for ADTTE in admiralroche, it will create `AVALU`.

**Comment by oreillb1** [comment]
Many thanks for the clarification
