### ISSUE TITLE
Documentation: Update branch naming convention

### ISSUE THREAD

**Issue by thomas-neitmann** [pharmaverse/admiral#1340]
### Please select a category the issue is focused on?

Developer Guides

### Let us know where something needs a refresh or put your idea here!

We'll be using [{staged.dependencies}](https://github.com/openpharma/staged.dependencies) going forward which requires us to change our branch naming convention from `<issue_number>_<description>` to `<issue_number>_<description>@<target_branch>`, e.g. `33_derive_aage@devel`. We have to update our documentation accordingly.

**Comment by rossfarrugia** [comment]
thanks Thomas! please also include in the text the benefit of staged.dependencies around how this enables our admiral family of packages to keep in sync with latest development versions of each admiral dependency package, and maybe link to https://github.com/openpharma/staged.dependencies#branch-naming-convention for those curious to read more.

**Comment by bms63** [comment]
Fun!
