### ISSUE TITLE
General Issue: Follow deprecation strategy for removing deprecated functions and identify functions to be deprecated in 0.90 

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1344]
### Background Information

Functions that are deprecated or soon to be deprecated need to follow the deprecation strategy.  @bundfussr has removed a few in his PR, but there might be others.  

https://pharmaverse.github.io/admiral/articles/programming_strategy.html#deprecation

### Definition of Done

Functions removed that were deprecated in previous release.  

Functions that need to be deprecated for this release, with warning of pending deprecation, should be identified and follow the deprecation strategy.

**Comment by thomas-neitmann** [comment]
Note that rather than removing the functions we should chage `deprecate_warn()` to `deprecate_stop()` inside the deprecated functions' bodies. That way an error is issued but we still let users know what alternative function to use. The finl step thereafter would be to actually remove the function.

The "Deprecation" section in our Programming Strategy lacks a bit of detail which we should add.

**Comment by bms63** [comment]
Hey Thomas.  We should keep a list of functions being deprecated and when the start of their cycle began.  Hoping we aren't deprecating too much stuff anymore...but maybe nice to have a list that we update at each release.  Possibly just a excel tracker on box??

**Comment by bms63** [comment]
https://github.com/pharmaverse/admiraldev/issues/36

**Comment by bms63** [comment]
@millerg23 Here is list of deprecated functions from the pkgdown version 0.8.0 site.  I think verifying these will be a good start.  

![image](https://user-images.githubusercontent.com/10111024/187784957-bcd252a7-5f65-4021-985f-52830bbc5321.png)

The one with the x was deprecated in version 0.7.0 I think?  Anyways good place to good started.

**Comment by millerg23** [comment]
**Updates for Release 0.8:**
Currently WARNING:
`derive_var_ady()` (derive_var_ady.R)
`derive_var_aendy()` (derive_var_aendy.R)
`derive_var_astdy()` (derive_var_astdy.R)
`derive_var_atirel()` (derive_var_atirel.R)
`derive_var_extreme_flag()` (derive_var_extreme_flag.R)
`derive_var_worst_flag()` (derive_var_extreme_flag.R)
Currently STOP:
`derive_vars_suppqual()` (derive_vars_suppqual.R)

**Updates for Release 0.9:**
Currently WARNING:
`derive_vars_merged_dt()` (derive_merged.R)
`derive_vars_merged_dtm()` (derive_merged.R)
`derive_derived_param()` (derive_computed_param.R)
`derive_var_agegr_fda()` (derive_vars_aage.R)
`derive_var_agegr_ema()` (derive_vars_aage.R)
Currently STOP:
`date_source()` (derive_var_extreme_date.R)

**Comment by bms63** [comment]
Should this be 0.7 and 0.8?

**Comment by millerg23** [comment]
Sorry if its confusing, I was putting it under the Release where it would be updated. SO for this Release 0.8, we need to make the updates to:
derive_var_ady() (derive_var_ady.R)
derive_var_aendy() (derive_var_aendy.R)
derive_var_astdy() (derive_var_astdy.R)
derive_var_atirel() (derive_var_atirel.R)
derive_var_extreme_flag() (derive_var_extreme_flag.R)
derive_var_worst_flag() (derive_var_extreme_flag.R)
derive_vars_suppqual() (derive_vars_suppqual.R)

**Comment by bms63** [comment]
derive_var_ady() (derive_var_ady.R)
derive_var_aendy() (derive_var_aendy.R)
derive_var_astdy() (derive_var_astdy.R)
derive_var_atirel() (derive_var_atirel.R)
derive_var_extreme_flag() (derive_var_extreme_flag.R)
derive_var_worst_flag() (derive_var_extreme_flag.R)
derive_vars_suppqual() (derive_vars_suppqual.R)

So these all get removed from `admiral` or do we do add a `deprecate_stop`?

**Comment by millerg23** [comment]
Change from `deprecate_warn` to `deprecate_stop` for all those except `derive_vars_suppqual()` that is already at `deprecate_stop`, I think this needs completely removed. We can discuss on related pull request.

**Comment by millerg23** [comment]
New list for 0.9 deprecation updates

Currently at WARNING (at 0.8) -> should be moved from WARNING to STOP in 0.9 release
derive_vars_merged_dt() (derive_merged.R)
derive_vars_merged_dtm() (derive_merged.R)
derive_derived_param() (derive_computed_param.R)
derive_var_agegr_fda() (derive_vars_aage.R)
derive_var_agegr_ema() (derive_vars_aage.R)

Currently at STOP (at 0.8) -> should be removed in 0.9 release:
date_source() (derive_var_extreme_date.R)
derive_vars_suppqual() (derive_vars_suppqual.R)
derive_var_ady() (derive_var_ady.R)
derive_var_aendy() (derive_var_aendy.R)
derive_var_astdy() (derive_var_astdy.R)
derive_var_atirel() (derive_var_atirel.R)
derive_var_extreme_flag() (derive_var_extreme_flag.R)
derive_var_worst_flag() (derive_var_extreme_flag.R)
