### ISSUE TITLE
Feature Request:  ADEG vignette, include character-only results processing

### ISSUE THREAD

**Issue by oreillb1** [pharmaverse/admiral#1350]
### Feature Idea

ADEG vignette code should include character-only parameters e.g. TWAVE, UWAVE processing including shift from baseline

**Comment by w316liu** [comment]
@oreillb1 can I work on this?

**Comment by oreillb1** [comment]
Happy for anyone who has time to set up character results processing, especially looking for shift values

**Comment by w316liu** [comment]
Just wanna clarify, the "ADEG vignette code" is the template script under _inst/templates/ad_adeg.R_?

**Comment by w316liu** [comment]
@oreillb1 the test data EG does not have TWAVE and UWAVE tests. The shift from baseline is not a generic variable in ADEG either. I'd kind of question the necessity of adding these two parameters to the template code. @rossfarrugia @millerg23 any thought?

**Comment by millerg23** [comment]
Hi,
The BDS Finding vignette shows character variables and creates `BASEC` and `AVALC`, it also shows `SHIFT1` being created from `ANRIND` and `BNRIND`, so replacing with `AVALC` and 'BASEC` is simple enough for users.
As already stated we don't have TWAVE and UWAVE in the test data, so wouldn't include in the template. The template is just a guide on how a study could use {admiral}, it won't cover every scenario.
Regards,
Gordon

**Comment by oreillb1** [comment]
I'm going to re-visit the test data again and compare the shift variables we would normally produce for character ECG results

**Comment by w316liu** [comment]
Thank you @millerg23 for the clarification.
@oreillb1 I will unassign myself.

**Comment by rossfarrugia** [comment]
I'm going to close this issue for now, as we'll also have the admiralroche template coming here, and @oreillb1 please feel free to re-open later if you still feel we should add to admiral core package.

**Comment by oreillb1** [comment]
In admiral_eg we have [EG.EGTESTCD] = "ECGINT" that has only character results that are excluded in the ADEG processing.

**Comment by rossfarrugia** [comment]
@millerg23 please can you check Barbara's comment?

**Comment by rossfarrugia** [comment]
@millerg23 can you check if this one is still an issue please? and either action or close accordingly

**Comment by millerg23** [comment]
I will close this, I think we need a minor update in ADEG metadata in admiralroche which may have led to some confusion.
