### ISSUE TITLE
Documentation:  Clarification on documentation of compute_duration()

### ISSUE THREAD

**Issue by SyedMubasheer** [pharmaverse/admiral#1353]
### Please select a category the issue is focused on?

Function Documentation

### Let us know where something needs a refresh or put your idea here!

Kindly wanted to check regarding the note which has to be added for compute_duration(), Should I replace derive_vars_dt() with convert_dtc_to_dt() as I think it makes more sense with the later one as we are just deriving duration so I believe no need of new xxDT and xxDTF variables which we will get from derive_vars_dt(). Could you please let me know your suggestions.
Referencing Issue #889.
![image](https://user-images.githubusercontent.com/106958950/183067968-0eaed004-b210-4f20-a517-d8573ca1cd59.png)

**Comment by bundfussr** [comment]
Maybe we should mention both functions as it depends on the context which one is more suitable. If I have several `compute_duration()` calls, I would call `derive_vars_dt()` in a pre-processing step. While I would use `convert_dtc_to_dt()` if it is just a single `compute_duration()` call.

@bms63 , @thomas-neitmann , what do you think?
