### ISSUE TITLE
Feature Request:  Machine-readable way to identify the type of a function output

### ISSUE THREAD

**Issue by paltusplintus** [pharmaverse/admiral#1359]
### Feature Idea

It would be very helpful to have a machine-readable way to identify the type of each function's output, including types of newly derived columns in a dataframe if the function returns a dataframe. (e.g. by parsing vignettes or some other way)

We are running some experiments to automate creation of derived datasets by chaining procedures together in a metadata-driven way. We use admiral along with other packages (could be R or Python) and we are unfortunately lacking the mentioned information. Please let me know if there is already a way of getting this information or if it could be added to your roadmap.
Thank you.

### Relevant Input

derive_vars_dtm

### Relevant Output

list("{new_vars_prefix}DTM" = "**lubridate:datetime**")

**Comment by paltusplintus** [comment]
FYI my GSK email address is alexey.k.kuznetsov@gsk.com

**Comment by thomas-neitmann** [comment]
@paltusplintus I'd be eager to learn a bit more what you are up to. If OK with you I'd like to schedule a meeting with you and interested devs from the {admiral} team. @pharmaverse/admiral Please let me know if you'd like to participate.

**Comment by bms63** [comment]
I'm intrigued, but OOO for the next week so don't let me hold anything up.

**Comment by bundfussr** [comment]
I'm interested as well but on vacation the next two weeks. So don't wait for me.

**Comment by paltusplintus** [comment]
Happy to meet @thomas-neitmann and anyone else interested. Could do next week Tue, Thu or Fri at 16:00 CET - feel free to setup, or let me know your email address and preferred time.
Ojesh Upadhyay <ojesh.r.upadhyay@gsk.com> would like to join the call as well, please include him.

**Comment by zdz2101** [comment]
@thomas-neitmann Did a meeting take place/was there a decision or outcome? Or do we need to schedule another meeting?

**Comment by bms63** [comment]
There was a meeting, but we never really moved this along with the person from GSK. @paltusplintus we can keep this on our backlog, but it hasn't been a focus for us.  apologies.

**Comment by bms63** [comment]
Going to close and maybe re-visit once admiral is out of the experimental phase/stable
