### ISSUE TITLE
Feature Request:  Check input date format in derive_var_last_dose_date()

### ISSUE THREAD

**Issue by w316liu** [pharmaverse/admiral#1365]
### Feature Idea

Need to add a check to check the format of the input date in derive_var_last_dose_date() - dose_date , analysis_date.
Some context:
derive_var_last_dose_date() currently allows input date in both ISO8601 and datetime format. However, if input date is in ISO8601 format, the time part cannot be processed and the function would not issue a warning.

**Comment by w316liu** [comment]
#1364 1364

**Comment by w316liu** [comment]
Noticed this feature request been resolved via Merge request #1343

**Comment by thomas-neitmann** [comment]
Thanks @w316liu, I didn't realize that.
