### ISSUE TITLE
Documentation:  Update ADLB script for ADLB grading (ATOXGRL, ATOXGRH, ATOXGR)

### ISSUE THREAD

**Issue by millerg23** [pharmaverse/admiral#1370]
### Please select a category the issue is focused on?

User Guides

### Let us know where something needs a refresh or put your idea here!

Update ADLB script to add in functoins that create ADLB grading - new functions `derive_var_atoxgr_dir` and `derive_var_atoxgr`.

**Comment by bms63** [comment]
Close as part of version 8 release
