### ISSUE TITLE
Bug: create_single_dose_dataset processing error, function code  update required

### ISSUE THREAD

**Issue by oreillb1** [pharmaverse/admiral#1375]
### What happened?
Error in `create_single_dose_dataset()`:
! The following values of EXDOSFRQ in ex_single_palb do not appear in dose_freq_lookup:
ONCE" This error was seen only once

**Comment by oreillb1** [comment]
Although it now seems 'ONCE' is the default and therefore an expected single_dose_condition used in derive_var_last_dose_date, it seems impossible to find a single_dose_condition that does not report errors like this. My EX data have CRF single day records and diary card records that cover a range of dates. Preprocessed EX input data have the correct number of original and derived records.
Error in `signal_duplicate_records()`:
! Multiple doses exist for the same `dose_date`. Update `dose_id` to identify unique doses

**Comment by rossfarrugia** [comment]
@bundfussr @bms63 @thomas-neitmann - was this issue missed? if its a bug we usually try to fix asap. would be good to check and add a reply with our plan of action

**Comment by bundfussr** [comment]
@rossfarrugia , good catch! Yes, we missed this one.

I'll fix it.
