### ISSUE TITLE
Documentation:  Update Roxygen Examples with library(pkg_name) rather than pkgname::function()

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1380]
### Please select a category the issue is focused on?

Function Documentation

### Let us know where something needs a refresh or put your idea here!

Update all functions with roxygen examples using the pkgname::function() way.

See #1235 for additional guidance and discussion,

**Comment by esimms999-gsk** [comment]
02Nov2022: confirmed in our standup meeting that we want Roxygen examples to use library(pkgname) and function() instead of pkgname::function() in Roxygen examples. Note that this is the opposite of what is needed in unit tests (testthat folder).

**Comment by bms63** [comment]
@esimms999-gsk Triple colons allow you to access objects in a package that are not exported to the Namespace.  https://stat.ethz.ch/R-manual/R-devel/library/base/html/ns-dblcolon.html

**Comment by bms63** [comment]
We close these issues after a release.  Just so people know it was worked on and updated.
