### ISSUE TITLE
General Issue: Add in authors to Description

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1383]
### Background Information

No matter how small the contribution we want folks to be recognized for their contribution to admiral.

### Definition of Done

Add in Shan Lee @fshanlee , Bill Denney, Jack McGavin @JMcGavigan32 

@pharmaverse/admiral Is there anyone else that we need to add in to the author list for this release?

**Comment by bms63** [comment]
Add in Syed @SyedMubasheer

**Comment by bms63** [comment]
Add in Wendy @w316liu

**Comment by rossfarrugia** [comment]
Dinakar Kulkarni, Tamara Senior, Jordanna Morrish, Anthony Howard, Barbara O'Reilly, John Kirkpatrick, James Black, Leena Khatri

any more from our side @koegerr @thomas-neitmann??

**Comment by w316liu** [comment]
> Jack McGavigan was already listed as Author. I added the following as Contributors: Shan Lee, Bill Denney, Syed Mubasheer, Wendy Liu, Dinakar Kulkarni, Tamara Senior, Jordanna Morrish, Anthony Howard, Barbara O'Reilly, John Kirkpatrick, James Black, Leena Khatri.

Just a minor note, my name is "Wenyi Liu", Not Wendy lol

**Comment by esimms999-gsk** [comment]
Thanks Wenyi!
