### ISSUE TITLE
Documentation: Align "join" documentation to be consistent across functions

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1396]
If we go ahead with this approach, we should at least be consistent and update `derive_var_extreme_dt()`, `derive_var_extreme_dtm()`, `derive_param_tte()`, and `create_query_data()` as well.

_Originally posted by @bundfussr in https://github.com/pharmaverse/admiral/issues/1367#issuecomment-1231392264_

**Comment by bms63** [comment]
@bundfussr  I made a new issue for your suggestion.  I don't think we have time to update this and I honestly don't really like how it is presented.  However, I haven't seen a better alternative! :(  But I think you are right that we should be consistent.

**Comment by bundfussr** [comment]
Maybe we can extend roxygen such that helper objects like `dthcaus_source` are displayed in a separate section. It seems possible to extend roxygen (see https://roxygen2.r-lib.org/articles/extending.html) but it requires some investigation to find out what is possible. If we find a solution, we could also ask for including it as core roxygen functionality. I think it would be useful for other non admiral packages as well. Usually R man pages documenting more than one functions are hard to read.

Furthermore, we could also try to add a `@permitted` tag for the permitted values of an argument.

@bms63 , @thomas-neitmann , what do you think?

**Comment by bms63** [comment]
Shall we transfer this to admiraldev?  This will impact several others functions and we should document when we should be doing this.

**Comment by bundfussr** [comment]
We could move the roxygen2 extension part to admiraldev. But we still need this ticket for updating the admiral functions.

**Comment by bms63** [comment]
It doesn't look like we can modify the roxygen header to make it more aesthetically pleasing for the user when two functions are on the same page.

https://community.rstudio.com/t/separate-function-documentation-arguments-for-helper-functions/149882

![image](https://user-images.githubusercontent.com/10111024/195915893-c3eda58a-eb82-4ce1-a523-5227db024363.png)

**Comment by thomas-neitmann** [comment]
Decisision:

- Document main function and `source()` function **separately**
- Add examples to all `source()` functions
