### ISSUE TITLE
Documentation: Explore better way to show default arguments where some internal derivation needed

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiral#1402]
Related to https://github.com/pharmaverse/admiraldev/issues/72 & https://github.com/pharmaverse/admiraldev/issues/64, for default argument values where we have `NULL` shown in Usage section but then some derived field is shown below, explore whether there's a better way to show this.

For example showing the derived part in Usage section, or use of "auto" instead of NULL.

Example: 
![image](https://user-images.githubusercontent.com/82581364/187704216-86d15d76-e7a9-4178-aa10-1ac8cec55ea4.png)

![image](https://user-images.githubusercontent.com/82581364/187704308-1f5ed4a4-bfd9-4164-8595-971a3b9c7279.png)

@bundfussr I'll assign you given you understand this best from our discussions at the core dev team.

**Comment by bundfussr** [comment]
We should keep this issue because `derive_vars_merged()` is in admiral. If we have function in admiraldev with such default values, we should create an additional ticket there.
