### ISSUE TITLE
Documentation:  Update derive_extreme_records() and derive_summary_records() to use correct keyword/family

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1414]
### Please select a category the issue is focused on?

Function Documentation

### Let us know where something needs a refresh or put your idea here!

Update derive_extreme_records() and derive_summary_records() to use correct keyword/family

**Comment by bundfussr** [comment]
`derive_param_rr()` is classified wrong as well.

**Comment by bms63** [comment]
Should this be Derivations for Adding Parameters/Records ? 

![image](https://user-images.githubusercontent.com/10111024/188176011-e9a5aa9b-0b43-4c9f-9220-ac3c14ed696f.png)

**Comment by bundfussr** [comment]
Yes, sounds good.
