### ISSUE TITLE
Feature Request:  Automate assigning variable labels

### ISSUE THREAD

**Issue by w316liu** [pharmaverse/admiral#1423]
### Feature Idea

In current template code, the newly created variables do not have labels assigned to them. Bearing in mind the esub-readiness principle, this should be added to the template code. Moreover, instead of manually assigning labels, there should be a way to automate this process by directly reading spec.

**Comment by bms63** [comment]
Labels are brought up quite a bit and are covered in the e2e examples.  However, a user might not be aware of the e2e examples and so maybe we should start applying them in our templates and vignettes.

We could leverage metacore/metatools or the xportr package to take in spec and apply the labels.  I don't think a spec file would take up too much space in our package.  Or maybe we could store them somewhere other than the package and read them in with the script and then apply them.

@pharmaverse/admiral any thoughts?

**Comment by bundfussr** [comment]
We could add a section to the "Get Started" page, which refers to the e2e example page.

Creating specs and adding the metacore, metatool, xportr calls to all the vignettes and templates looks like a lot of initial and maintenance work to me.

**Comment by thomas-neitmann** [comment]
So far we refrained from adding this to our vignettes because that would make {admiral} depend on the other packages mentioned. Thus, I'd much rather point users to the e2e example (ideally also directly towards the end of the templates in a comment.

**Comment by bms63** [comment]
I think pointing to e2e examples is the best way forward to minimize work and dependencies like you all suggested.   @w316liu do you mind making this change to our vignettes?
