### ISSUE TITLE
Documentation:  Youtube Video Walkthrough of Vignette

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1424]
### Please select a category the issue is focused on?

Other

### Let us know where something needs a refresh or put your idea here!

We should release a new video with each new release onto the youtube channel.  Eric did the adae and we should pick another dataset.

**Comment by rossfarrugia** [comment]
Happy to take this one on - was thinking of doing one for ADSL as it has some complexities around source objects and partial date imputations that are worth calling out. 

One maybe out of the box idea though... what if i show the admiralroche template here instead and talk through as an example of how a company has done the final bit of effort to extend admiral to their company-specific needs? i was thinking of doing something like this at next quarterly community meeting anyway. what do you think? @bms63 @thomas-neitmann @koegerr @millerg23 @bundfussr @esimms999-gsk

**Comment by esimms999-gsk** [comment]
@rossfarrugia I think it makes sense to show this for one or two _simple_ company-specific items.

**Comment by bms63** [comment]
Sounds awesome!

**Comment by rossfarrugia** [comment]
thanks both - will see what the others think and if they agree will pick this up in the next couple of weeks. working on something similar for Roche training anyway

**Comment by millerg23** [comment]
Sounds good @rossfarrugia , as already been said would keep the company-specific ones fairly simple, ie. updating a source object.

**Comment by bundfussr** [comment]
@rossfarrugia makes sense.

I think the issue with the source objects is that their benefit is not obvious from the template scripts. If you just look at one script, it looks overcomplicated. You have to look at several scripts (of the same dataset) to see why it makes sense.

**Comment by rossfarrugia** [comment]
agree @bundfussr i was thinking of showing an example of the flexibility this gives, but won't go too deep here. it's probably an area users won't like at first but will grow to appreciate over time.

**Comment by rossfarrugia** [comment]
Now done and shared on youtube: https://www.youtube.com/watch?v=eKLV2tdwXU8
