### ISSUE TITLE
Documentation:  Update admiral hex to be transparent

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1438]
### Please select a category the issue is focused on?

Other

### Let us know where something needs a refresh or put your idea here!

The current logo for admiral-core is not transparent.  This is reflected in the tab icon and is noticeably different when comparing different admiral website together.

![image](https://user-images.githubusercontent.com/10111024/190210033-2164657c-866b-41f7-9a4f-451ec4180a12.png)

*  You will need to track down the newest version of the admiral logo.
*  Using pkgdown functions update the website to the most current version of the logo

I believe this is the fucntion https://pkgdown.r-lib.org/reference/build_favicons.html

**Comment by rossfarrugia** [comment]
I think someone just needs to run build_favicons and commit all the updated files it delivers here, as the original logo was fixed via https://github.com/pharmaverse/admiral/pull/1143

**Comment by bms63** [comment]
@thomas-neitmann do you mind uploading to box into the hex-stickers folder?

**Comment by thomas-neitmann** [comment]
Done 👍
