### ISSUE TITLE
CRAN submission failed due to broken links

### ISSUE THREAD

**Issue by thomas-neitmann** [pharmaverse/admiral#1443]
>   Found the following (possibly) invalid URLs:
    URL: https://pharmaverse.github.io/admiral/articles/faq.html
      From: README.md
            NEWS.md
      Status: 404
      Message: Not Found
    URL: https://pharmaverse.github.io/admiral/articles/faq.html#why-do-we-use-a-certain-r-version-and-package-versions-for-development
      From: README.md
      Status: 404
      Message: Not Found

@bms63 The FAQ has been re-added in your recent PR but as it's not on the `main` branch, yet, it's not part of the deployed website.

**Comment by bundfussr** [comment]
The links caused similar issues for the admiralonco release. I think we need to find a better way of creating links. Ideally we should use relative links for targets within the project. But this may not work with the R help pages.

@bms63 , @thomas-neitmann , what do you think? Should we create an issue for finding a better solution?

**Comment by thomas-neitmann** [comment]
I'm always in favor of finding better solutions 👍

**Comment by thomas-neitmann** [comment]
For the moment I'd suggest we remove these links and re-submit the package.

**Comment by bms63** [comment]
Can we just merge in the faqs into the main branch so the site is redeployed with them?
