### ISSUE TITLE
General Issue: Find better solution for internal links in documentation

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#1444]
### Background Information

Absolute links in the documentation causes issues when submitting admiral packages to CRAN (see https://github.com/pharmaverse/admiral/issues/1443)
We want to find a better way of creating internal links. Ideally we should use relative links for targets within the project. But this may not work with the R help pages.

### Definition of Done

- [ ] Create proposal of how to create internal links in documentation
- [ ] Discuss proposal in admiral meeting and agree on a solution
- [ ] Implement solution

**Comment by esimms999-gsk** [comment]
@bundfussr @bms63 

Looking at an example, occds.Rmd has a couple of links to our admiral files (ad_adae.R and ad_adcm.R):

![image](https://user-images.githubusercontent.com/85294667/202565034-2e2a32fb-c276-422c-9877-7510b72b2e34.png)

My understanding: If we want to add a new link, e.g. to a template for ad_adzz.R, we need to point to the same github location as the other two links, but for ad_adzz.R. But that does not yet exist, because the github location/file is based off of main. This will cause CRAN tests to fail due to an invalid URL.

But where else should we point if we eventually need this to point to GitHub? Point to an internal package file with a relative link? While that might pass the CRAN tests, it would then need to be changed back to pointing at the GitHub location for the release version.

I do not see any way around this. Perhaps I am missing something. I would post to slashdot, RStudio Community, etc. but I expect people will be asking why we are submitting our devel version to CRAN for checks.

Anyone have any ideas?

**Comment by bundfussr** [comment]
We submit to CRAN from `pre-release` instead of `main` because we want to minimize the time where the `main` branch and website is not in sync with CRAN. If a release is accepted by CRAN, we can update the `main` branch and website in a few minutes.  If we update `main` and website first and submit to CRAN from `main`, it takes a few days until the new version is available on CRAN. During these days the website says that the new version is on CRAN but if you install from CRAN, you still get the old version.

**Comment by bundfussr** [comment]
I did some investigations but I do not see a clean solution. Here is a summary of the issues and some options and questions:

The links should work in the following situations:
- local build of the documentation during development
- build of devel version on github pages
- build of main version on github pages
- build of older version (0.8.4, 0.7.1, 0.6.3, …) on github pages
- when a new version is submitted to CRAN from pre-release but not yet available on main
- help pages in RStudio

Problematic links:
- Links from function documentation to vignettes: relative links like `../articles/occds.html` work for all situations where a website is created but not for help pages because the man pages are stored in a different place than the function html pages. It is possible to include R code in the man files which is executed to generate mark-up but I found no way to distinguish between viewing a page as a help page and transforming the man file into an html file for a website.
- Links to templates: At the moment these work for the build of the main version on github pages only as they are absolute links to main. Options:
    - Use a function like `dyn.link()` in `admiraldev/README.Rmd` which creates absolute links depending on an environment variable. We would need to build a pre-release website to make this work for the CRAN submission.
    - Use a function which copies the template file to a source folder in the docs folder and creates a relative link to the copied file.
- Links to vignettes in README and NEWS: At the moment absolute links to main are used in README and no links in NEWS. Options:
    - Use a function like `dyn.link()` in `admiraldev/README.Rmd` and create `README.md` and `NEWS.md` from `README.Rmd` and `NEWS.Rmd` respectively. `dyn.link()` creates absolute links depending on an environment variable. `README.md` and `NEWS.md` would need to be rebuilt before the website is built. We would need to build a pre-release website to make this work for the CRAN submission.

- Links to source files (at the top right beneath the heading in function documentation and vignettes): These are absolute links created based on `repo:url:source:` in _pkgdown.yml. Options:
    - Modify `_pkgdown.yml` before building the documentation
- Links to vignettes of other packages: At the moment absolute links are used, i.e., they link to the main version of the other packages. If older versions are build, should the links refer to the corresponding version of the other package, e.g., should admiralonco 0.1.0 link to admiral 0.8.4?
- Links to functions of other packages: Same question as for “Links to vignettes of other packages”. Additional problem: these links are created automatically. Most likely they are based on the most recent version of the other package (taken from the web). I.e., the linking might not work if the function no longer exists in the most recent version of the other package.

Another option is to post-process the html files and update the links. This would require rules for selecting and updating links.

**Comment by bms63** [comment]
I think figuring this out should be a priority issue for `0.10.0` release.

I'm very eager for the different admiral version package down sites to be available and think this will dovetail nicely.

@cicdguy We need your power - please help us in our time of need.  

![image](https://user-images.githubusercontent.com/10111024/204174878-e8b594bc-c614-4b12-8104-38e5296b6128.png)

**Comment by galachad** [comment]
We have two different link issues that cover the same topic [#1510](https://github.com/pharmaverse/admiral/issues/1510#issuecomment-1365705628). 

For generating the `README` file  it's worth to consider tweaking the html links during pkgdown build https://github.com/pharmaverse/admiralci/issues/13 (same as proposal here).
