### ISSUE TITLE
Feature Request: Implement `derive_vars_joined()`

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#1448]
### Feature Idea

Implement a function to add a variable like the lowest value of AVAL before the current observation (NADIR in oncology) or the lowest grade before treatment start from FAAE to each AE.

```
derive_vars_joined <- function(dataset,
                               dataset_add,
                               by_vars,
                               order,
                               new_vars,
                               join_vars,
                               filter_add,
                               filter_join,
                               mode)
```

### Flow

1. `dataset_add` is restricted by `filter_add`.
2. `dataset` and the restricted `dataset_add` are joined by `by_vars` (from `dataset_add` only `by_vars`, `new_vars`, and `join_vars` are kept, for `join_vars` the suffix ".join" is added)
3. The joined dataset is restricted by `filter_join` (which allows to use variables from `dataset` and `dataset_add`).
4. The joined dataset is sorted by `order` and the first or last observation (depending on `mode`) is selected.

### Reproducible Example/Pseudo Code

Set `NADIR` to the lowest value at or after baseline and before the current observation:
```
derive_vars_joined(
  adtr,
  dataset_add = adtr,
  by_vars = vars(USUBJID),
  order = vars(AVAL),
  new_vars = vars(NADIR = AVAL),
  join_vars = vars(ADT),
  mode = "first",
  filter_add = ABLFL == "Y" | ADT >= TRTSDT,
  filter_join = ADT.join < ADT
)
```
Set `AETOXGR_pre` to the lowest grade recorded in FAAE before treatment start for each AE:
```
derive_vars_joined(
  adae,
  dataset_add = faae,
  by_vars = vars(USUBJID, AEGRPID = FAGRPID),
  order = vars(FAORRES),
  new_vars = vars(AETOXGR_pre = FAORRES),
  join_vars = vars(FADTM)
  mode = "last",
  filter_add = FATESTCD == "TOXICITY",
  filter_join = FADTM.join < TRTSDTM
)
```

**Comment by rossfarrugia** [comment]
@HinalPat FYI for ADTR for onco - this one will come in useful!

**Comment by thomas-neitmann** [comment]
The name of the function is quite confusing. The difference between `derive_vars_merged()` and `derive_vars_joined()` is not clear at all. Sounds like the exact same thing...

**Comment by rossfarrugia** [comment]
yeh agree - why not call it `derive_vars_nadir()`? that's not solely a term used in onco.

**Comment by bundfussr** [comment]
I agree that the name is not very descriptive. If you have a better one, please let me know.

The difference between `derive_vars_merged()` and `derive_vars_joined()` is that the former one selects the relevant observations from `dataset_add` first and then adds them to the input dataset while the later one joins `dataset_add` and the input dataset first and then selects the relevant observations. In `derive_vars_joined()` the selection can depend on variables from both datasets while in `derive_vars_merged()` only variables from `dataset_add` can be used. In principle you do not need `derive_vars_merged()` because you could achieve the same with `derive_vars_joined()`. However, `derive_vars_joined()` requires much more resources (time and memory). Thus I would not remove `derive_vars_merged()`.

Calling it `derive_vars_nadir()` seems to specific to me. Deriving the nadir is just one example. For the `TRTEMFL` derivation in admiralroche I need to derive the last grade before treatment start and the highest grade after treatment start. So "nadir" does not really fit.

Maybe we need to introduce a terminology like "merged" and "joined". The term itself is not self-explanatory but once you know its meaning it helps to classify functions. We have already some "merged" functions and I would expect that we get also more than one "joined" function (`filter_confirmation()` is of the "joined" type).

**Comment by bundfussr** [comment]
I just got another use case from an early explorer team:
```
proc sql ;
   create table _visit as
      select a.*, b.avisit as _avisit1, b.avisitn as _avisitn1, b.awtarget as _awtarget1, b.awlo as _awlo1, b.awhi as _awhi1
      from _advs a left join visit_windows b
      on b.awlo <= a.ady <= b.awhi ;
quit ;
```

**Comment by bms63** [comment]
What about `derive_vars_lash` .  :) That way we have a nautical themed function in `admiral`.  

![image](https://user-images.githubusercontent.com/10111024/191499901-5e895658-af03-45a0-874b-0979d88752a3.png)

**Comment by bms63** [comment]
Ohhh...how about `derive_vars_conjoin()`.   

https://ell.stackexchange.com/questions/46282/conjoin-vs-join

@pharmaverse/admiral  Anyone want to help name a function!?!

**Comment by rossfarrugia** [comment]
I'm not sure any naming would truly easily explain Stefan's explanation to a new user without them having to delve deeper - i even had to read it a couple of times to understand, so my main 2 cents on this are that whatever we name it i definitely think it has to be well explained as part of the new merge functions vignette: https://github.com/pharmaverse/admiral/issues/734. I would include Stefan's full explanation above with lots of examples, including why we didn't just make these 1 function, as technically here if you leave `filter_join` null then you get same as `derive_vars_merged`.

The closest i could come to trying to really explain what it does in the name would be something like `derive_vars_postmerged` but not sure i like that either.

**Comment by jeffreyad** [comment]
This will be useful for ADNCA/ADPC for finding the next upcoming dose for PRE-DOSE records.  This could be used both for actual relative times (ARRLT) and nominal relative times (NRRLT).  

Find next dose:

```
adpc <- adpc %>% 
  derive_vars_joined(
    dataset_add = ex,
    by_vars = vars(USUBJID),
    order = vars(ADTM),
    new_vars = vars(ADTM_next = ADTM, EXDOSE_next = EXDOSE, VISIT_next = VISIT, AENDTM_next = AENDTM),
    join_vars = vars(ADTM),
    filter_add = NULL,
    filter_join = ADTM < ADTM.join,
    mode = "first",
    check_type = "none"
  )
```

Find previous nominal dose time:

```
adpc <- adpc %>% 
  derive_vars_joined(
    dataset_add = ex,
    by_vars = vars(USUBJID),
    order = vars(NFRLT),
    new_vars = vars(NFRLT_prev = NFRLT),
    join_vars = vars(NFRLT),
    filter_add = NULL,
    filter_join = NFRLT > NFRLT.join,
    mode = "last",
    check_type = "none"
  )
```

Find next nominal dose time:

```
adpc <- adpc %>% 
  derive_vars_joined(
    dataset_add = ex,
    by_vars = vars(USUBJID),
    order = vars(NFRLT),
    new_vars = vars(NFRLT_next = NFRLT),
    join_vars = vars(NFRLT),
    filter_add = NULL,
    filter_join = NFRLT <= NFRLT.join,
    mode = "first",
    check_type = "none"
  )
```

This would replace the need for #1516

**Comment by rossfarrugia** [comment]
Thanks @jeffreyad - feel free to try out the function and add any review comments to the PR: https://github.com/pharmaverse/admiral/pull/1468. We're hoping to merge this one to `devel` soon.
