### ISSUE TITLE
General Issue: Remove `assertions.R` from {admiral}

### ISSUE THREAD

**Issue by PoojaKumari05** [pharmaverse/admiral#1450]
### Background Information

Once [(https://github.com/pharmaverse/admiraldev/issues/62)](url) is merged,  `assertions.R` from {admiral} should be removed.

### Definition of Done

`assertions.R` from {admiral} is removed.

**Comment by zdz2101** [comment]
Was done alongside with https://github.com/pharmaverse/admiral/pull/1592
