### ISSUE TITLE
Feature Request: Implement `derive_var_relative_flag`

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#1453]
### Feature Idea

The `derive_var_relative_flag()` function should have the same arguments as `filter_relative()` and additionally a `new_var` argument. The function should flag the observations which would we returned by `filter_relative()`.

### Reproducible Example/Pseudo Code

Flag observations up to first PD for each patient:
```
response %>%
  derive_var_relative_flag(
    by_vars = vars(USUBJID),
    order = vars(AVISITN),
    new_var = ANL02FL,
    condition = AVALC == "PD",
    mode = "first",
    selection = "before",
    inclusive = TRUE
  )
```

**Comment by rossfarrugia** [comment]
@bundfussr how would we use this to achieve ANL02FL as both up to/incl PD **& on/after randomization date**? As there's no `filter` argument I guess we could add the `ADT>=RANDDT` anywhere here?

**Comment by bundfussr** [comment]
@rossfarrugia , if you want to exclude observations before randomization from flagging, you can use `restrict_derivation()`.
