### ISSUE TITLE
Documentation: Installation instruction for development version outdated

### ISSUE THREAD

**Issue by thomas-neitmann** [pharmaverse/admiral#1454]
### Please select a category the issue is focused on?

Other

### Let us know where something needs a refresh or put your idea here!

The instructions are missing a call to install {admiraldev}.

**Comment by bms63** [comment]
@thomas-neitmann  lets include this in the hotfix

**Comment by thomas-neitmann** [comment]
Sounds good 👍

**Comment by bms63** [comment]
Didn't close with newest release.   Manually closing
