### ISSUE TITLE
Remove assert_that() and update with assertions.R functions in derive_date_var.R

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1456]
The function assert_that() is used throughout derive_date_var.R.  It was proposed to create additional assertion.R functions, e.g. assert_date_vector() and reduce reliance on assert_that() as it produces verbose error messages.  

Discussion is in the pharmaverse/admiral#746 Pull Request

**Comment by thomas-neitmann** [comment]
That's 2 separate issues for me. First create the new function in {admiraldev} and then make the update in {admiral}.

**Comment by bms63** [comment]
So I think this has been completed by @sadchla-codes ??

**Comment by bms63** [comment]
@sadchla-codes we finished this one correct?

**Comment by sadchla-codes** [comment]
@bms63 correct
