### ISSUE TITLE
General Issue: Increase Test Coverage for `user_helpers.R`

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1459]
### Background Information

We need to increase test coverage for our functions. The below screenshot has the function and gap in test coverage that we need to write additional unit tests `user_helpers.R`.

![image](https://user-images.githubusercontent.com/10111024/191993303-ee6bfc23-4a3c-42f9-85e5-7d980bfd2484.png)

### Definition of Done

New tests written that covers the red gap area for user_helpers.R.

Use devtools::test_coverage() to reproduce the report

**Comment by fshanlee** [comment]
Hi @bms63 , I'm not sure whether it's possible to create a testthat script for the red gap area: this code opens a text editor and does not appear to hand control back to R until the editor is closed, which requires someone to click _Save_ or _Cancel_.
I will be unable to attend Monday's stand-up meeting--if you will be attending, then please could you ask whether anyone has any suggestions?

**Comment by thomas-neitmann** [comment]
I agree with @fshanlee, the highlighted code does not lend itself to unit testing as it required user interaction.

**Comment by bms63** [comment]
Then we shall close this issue.
