### ISSUE TITLE
come up with an agile workflow how to prioritize/identify/specify/combine functionality in admiral (workshop)

### ISSUE THREAD

**Issue by koegerr** [pharmaverse/admiral#146]
Future way of working in the admiral core team with more focus on across ADaM functionality (e.g. BDS functions) and less focus on ADaM dataset specifics.

Goal: What do we need to do this?

**Comment by bms63** [comment]
Hey Robin,

I do think we need a review of agile (im new at it) but it seems like this hybrid approach to agile is working now.  Do you still think we need update workflow on how this is handle?  This exists https://app.box.com/file/812035970361?s=60x2ahhbyt7jn05kiqaptir58ddgzril which is nice.  Maybe an update is needed?
