### ISSUE TITLE
General Issue: Increase Test Coverage for `duplicates.R`

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1466]
### Background Information

We need to increase test coverage for our functions. The below screenshot has the function and gap in test coverage that we need to write additional unit tests for  `duplicates.R`

![image](https://user-images.githubusercontent.com/10111024/192027947-75e86341-f1c3-417b-a44f-a945c6b89e2c.png)

### Definition of Done

New tests written that covers the red gap area for duplicates.R.

Use devtools::test_coverage() to reproduce the report

**Comment by sadchla-codes** [comment]
@thomas-neitmann is `print.duplicate()` intended to be part of the `signal_duplicate_records()` or its own function?

**Comment by zdz2101** [comment]
@sadchla-codes do you think you can still get this done for the release?

**Comment by zdz2101** [comment]
@bms63 This print function actually isn't used anywhere/looks redundant to the warning message from `signal_duplicate_records()` in the codebase, should we actually just deprecate (thought in this case removal might be justified) the function instead? Looks like it won't be missed

**Comment by zdz2101** [comment]
Closing as we decided next step is to remove redundancy instead of hosting old unused code

**Comment by bundfussr** [comment]
> @bms63 This print function actually isn't used anywhere/looks redundant to the warning message from `signal_duplicate_records()` in the codebase, should we actually just deprecate (thought in this case removal might be justified) the function instead? Looks like it won't be missed

We should not remove the print function. It is not called in admiral but it is called by the users. If duplicates are found, an S3 object of class `duplicates` is stored in the package environment and the user can retrieve it by calling `get_duplicates()`. The print function ensures that the `duplicates` object is printed nicely.
