### ISSUE TITLE
URGENT: Need to update admiral to avoid getting removed from CRAN

### ISSUE THREAD

**Issue by thomas-neitmann** [pharmaverse/admiral#1469]
I received this mail today:

> Dear maintainer,
>
> Please see the problems shown on
> <https://cran.r-project.org/web/checks/check_results_admiral.html>.
> 
> Apparently your package fails its checks in a strict Latin-1* locale,
> e.g. under Linux using LANG=en_US.iso88591 (see the debian-clang
> results).
> 
> Please correct before 2022-10-11 to safely retain your package on CRAN.
> 
> Best,
> -k

Here's the part that throws an error:

```
checking tests ... [71s/85s] ERROR
  Running 'testthat.R' [71s/85s]
Running the tests in 'tests/testthat.R' failed.
Complete output:
  > library(testthat)
  > library(admiral)
  >
  > test_check("admiral")
  [1] "N" "Y" NA
  [ FAIL 1 | WARN 1 | SKIP 0 | PASS 497 ]
  
  == Failed tests ================================================================
  -- Failure (test-user_helpers.R:71:3): `adam_templates` objects are printed as intended: some templates --
  capture.output(print(templates)) not identical to `expected_print_output`.
  2/3 mismatches
  x[2]: "<U+2022> ADAE"
  y[2]: "<U+2022> ADAE"
  
  x[3]: "<U+2022> ADSL"
  y[3]: "<U+2022> ADSL"
  
  [ FAIL 1 | WARN 1 | SKIP 0 | PASS 497 ]
  Error: Test failures
  Execution halted
```

**Comment by bms63** [comment]
So they don't like these bullet points? 
![image](https://user-images.githubusercontent.com/10111024/192774284-f6aa392d-5126-4a4d-80b9-823dd3ea4096.png)

**Comment by bms63** [comment]
Simplest solution is we just remove the bullet points

![image](https://user-images.githubusercontent.com/10111024/192776109-eecedadc-376f-4a1f-930c-503b782e17e7.png)

**Comment by thomas-neitmann** [comment]
> So they don't like these bullet points?

At least with that specific encoding it leads to strange errors...

> Simplest solution is we just remove the bullet points

Let's at least add a `-` instead of the bullet point.

**Comment by bms63** [comment]
Umm....so the test has the actual bullet point in it rather than the code that makes it
![image](https://user-images.githubusercontent.com/10111024/192782823-7085d664-ae6f-4964-9cbc-1087f921de37.png)

**Comment by thomas-neitmann** [comment]
Then I'd try to use the code instead.

**Comment by bms63** [comment]
@cicdguy So we just got dinged from CRAN for this locale issue.  Is there a way for us to check if the package installs with `Linux using LANG=en_US.iso88591 (see the debian-clang results)`?   Thinking this might go along with our Windows and Mac release check once we get those set up.

**Comment by cicdguy** [comment]
> @cicdguy So we just got dinged from CRAN for this locale issue. Is there a way for us to check if the package installs with `Linux using LANG=en_US.iso88591 (see the debian-clang results)`? Thinking this might go along with our Windows and Mac release check once we get those set up.

To really get close to CRAN-like testing is to emulate tests on all their compute systems: https://cran.r-project.org/web/checks/check_flavors.html

The first one on the list, which is where the error occurs, is a Debian 11 instance with the locale set to `en_US.iso88591` (see the `LC_TYPE` config). 

So not only would you need a Debian 11 instance, but you'll also need to install the `en_US` language pack and need to set the locale to the `iso88591` flavor of the locale.

You're talking custom runners or a Docker image with these specs, which is a whole new world of pain.

**Comment by cicdguy** [comment]
Bottomline - let the CRAN maintainers do their thing with their machines. This feedback loop from CRAN is imminent as they have compute systems that aren't necessarily cheap, nor easy to acquire.

**Comment by esimms999-gsk** [comment]
@bms63 Wow! Gotta love that list!

So ... is there a way to do a "draft" trigger of all of those CRAN tests and get the feedback? Kind of like we can do a draft PR to trigger our own GitHub tests without submitting the PR?

**Comment by cicdguy** [comment]
> @bms63 Wow! Gotta love that list!
> 
> So ... is there a way to do a "draft" trigger of all of those CRAN tests and get the feedback? Kind of like we can do a draft PR to trigger our own GitHub tests without submitting the PR?

Good question. There should be a way to do this for release candidates, right @thomas-neitmann?

**Comment by cicdguy** [comment]
Ok, so this could mean that CRAN is changing something on their side, system-wise, and it could lead to some issues for packages on the new/updated system?

**Comment by esimms999-gsk** [comment]
I mentioned my concerns to @rossfarrugia about CRAN having the ability to de-platform admiral to enforce fixes which may not fit our support schedule and available resources. He thinks it may not be a problem due to companies storing admiral locally vs on CRAN. 

It still makes me nervous. What if CRAN sends out a similar email on Dec 5 with a cutoff date of Dec 19 for fixes to be made? And, due to end of year shutdown/vacations, it takes until Jan 30 to make those fixes? Does that mean any **new users** who would like to install admiral may not be able to get it from CRAN during the period of Dec 20 - Jan 30?

**Comment by cicdguy** [comment]
> Does that mean any new users who would like to install admiral may not be able to get it from CRAN during the period of Dec 20 - Jan 30?

They should be able to install directly from GitHub (since the `main` branch has the current stable version) if it gets thrown out of CRAN.

**Comment by bundfussr** [comment]
There is definitely a risk. Especially because there is only one maintainer. If he is on vacation when the CRAN sends the e-mail, nobody notice the issue until the the package is archived. Unfortunately, CRAN requires a single maintainer.

However, as Dinakar pointed out, users can install the package from other sources.

Maybe we should extend the installation instructions to "The package is available from CRAN and can be installed by running `install.packages("admiral")` or can be installed from github by calling `remotes::install_github("pharmaverse/admiral", ref = "main")`

**Comment by bms63** [comment]
> I mentioned my concerns to @rossfarrugia about CRAN having the ability to de-platform admiral to enforce fixes which may not fit our support schedule and available resources. He thinks it may not be a problem due to companies storing admiral locally vs on CRAN.
> 
> It still makes me nervous. What if CRAN sends out a similar email on Dec 5 with a cutoff date of Dec 19 for fixes to be made? And, due to end of year shutdown/vacations, it takes until Jan 30 to make those fixes? Does that mean any **new users** who would like to install admiral may not be able to get it from CRAN during the period of Dec 20 - Jan 30?

GSK would not have this issue of not being able to use `admiral` as we have RStudio Package Managers that has a snapshots of the packages taken almost everyday.  

I think `remotes::install_github("pharmaverse/admiral", ref = "main")` is a nice suggestion if folks can access CRAN for some reason.  However, I feel like if a person can't access CRAN then they probably can't access GitHub either.

**Comment by rossfarrugia** [comment]
I think most pharma companies will have similar setups over time Ben so at worst this might be a minor inconvenience for some individual users who have to install from github for a time instead of CRAN. Not much else we can do besides adding the github installation instructions to README as Stefan suggested, and then when we do get such hotfixes requested we prioritise them. Every package on CRAN has same risk, and vast majority are far less well resourced than admiral.

**Comment by thomas-neitmann** [comment]
I think we should **not** exagerate the impact of this problem. As mentioned already even in case the package would get kicked off CRAN (which is **very** unlikely given how many people are involved with this project) there's more than one alternative way to install the package. I agree that we should mention these alternative installation methods in the README.

The only real issue I see is that I as the maintainer was the only one that got the email from CRAN. If I'd be ooo for the allocated time to fix the issue and don't look into my emails we might miss the notification. However, the results of the checks CRAN runs are publicly available on [this URL](https://cran.r-project.org/web/checks/check_results_admiral.html) and updated whenever the checks are run. We could create a GitHub action with a cron job that runs every day, scraps the table on the website and if it finds the "ERROR" keyword opens an issue on our repo. That way everyone who has notifications turned on would be notified.

**Comment by bundfussr** [comment]
@thomas-neitmann , I like the idea of the github action. Could we add it to admiralci? Then it is available for all admiral packages.

**Comment by thomas-neitmann** [comment]
@bundfussr Yes, this should be part of admiralci!

The code to get this working is suprisingly simple.

```r
library(rvest)

pkg <- "admiral"
url <- sprintf("https://cran.r-project.org/web/checks/check_results_%s.html", pkg)

checks <- url %>%
  read_html() %>%
  html_element("table") %>%
  html_table()

if (any(checks$Status == "ERROR")) {
  stop("One or more CRAN checks resulted in an error")
}
```

@cicdguy We'd just need a way to dynamically populate the `pkg` variable inside the workflow and add some magic to open an issue if an error is thrown.

**Comment by bms63** [comment]
This is fixed with latest release - although we have more headaches to chase...
