### ISSUE TITLE
General Issue: Remove tests for `derive_var_agegr_fda` and `derive_var_agegrp_ema`

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1471]
### Background Information

These tests for the above functions were not removed and are causing small issues in the tests checking.  

![image](https://user-images.githubusercontent.com/10111024/192609416-305702c6-1e9e-4703-a4ad-af4bfefa4f95.png)

Functions being deprecated should have their tests removed.  

![image](https://user-images.githubusercontent.com/10111024/192779804-0f7e4837-8ce1-4bcd-80c5-acf600195d41.png)

### Definition of Done

Tests `derive_var_agegr_fda` and `derive_var_agegrp_ema` in the `test-derive_vars_aage.R` file are removed and everything works well and good.

**Comment by thomas-neitmann** [comment]
@huangr25 @nkr821 @AniaGolab Either of you interested in picking this up as a first issue?

**Comment by AniaGolab** [comment]
sure @thomas-neitmann  I can take it :)

**Comment by thomas-neitmann** [comment]
Wesone, thanks a lot @AniaGolab!

**Comment by AniaGolab** [comment]
Hi @thomas-neitmann - should I close this issue ? thank you!
