### ISSUE TITLE
Feature Request: Implement `create_period_dataset()`

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#1477]
### Feature Idea

Implement
```
create_period_dataset <- function(dataset,
                                  new_vars,
                                  subject_keys = vars(STUDYID, USUBJID))
```
- `dataset` expects an ADSL dataset
- `new_vars` expects a named list of variables, e.g., `new_vars = vars(APERSDT = APxxSDT, APEREDT = APxxEDT, TRTA = TRTxxA)` or `new_vars = vars(PHSDTM = PHwSDTM, PHEDTM = PHwEDTM, APHASE = APHASEw)`

The function creates a dataset with one observation per subject and phase/period/subperiod and the variables specified by `new_vars`. Additionally `APERIOD` is added if variables containing "xx" are specified, `ASPER` if variables containing "xx" and "w" are specified, and `APHASEN` if variables containing "w" but not "xx" are specified.

**Example code for transposing:**
```
period_ref <- pivot_longer(
  adsl,
  matches("AP\\d\\d[ES]DT"),
  names_to = c("APERIODC", ".value"),
  names_pattern = "AP(\\d\\d)([ES])DT"
) %>%
  rename(APERSDT = S, APEREDT = E) %>%
  mutate(
    APERIOD = as.integer(APERIODC),
    APERIODC = paste("Period", APERIODC)
  )
```

### Relevant Input

```
adsl <- tribble(
  ~USUBJID, ~AP01SDT,     ~AP01EDT,     ~AP02SDT,     ~AP02EDT,
  "1",      "2021-01-04", "2021-02-06", "2021-02-07", "2021-03-07",
  "2",      "2021-02-02", "2021-03-02", "2021-03-03", "2021-04-01"
) %>%
  mutate(
    across(matches("AP\\d\\d[ES]DT"), ymd)
  )
```

### Relevant Output

```
#> # A tibble: 4 x 5
#>   USUBJID APERIODC  APERSDT    APEREDT    APERIOD
#>   <chr>   <chr>     <date>     <date>       <int>
#> 1 1       Period 01 2021-01-04 2021-02-06       1
#> 2 1       Period 02 2021-02-07 2021-03-07       2
#> 3 2       Period 01 2021-02-02 2021-03-02       1
#> 4 2       Period 02 2021-03-03 2021-04-01       2
```

**Comment by bundfussr** [comment]
The last example for `derive_vars_joined()` should be updated such that it uses the new function.

**Comment by bms63** [comment]
I see we have `create` and `consolidate` as the start of the function names for these new features.  Shall we consider a new class of functions that start with these verbs and update the dev document.  

Or  use `derive`.  I sort of like not having `derive` in everything, but then what is the difference between `create` and `derive`?

Sorry just musing a bit.  @pharmaverse/admiral  Any thoughts?

https://pharmaverse.github.io/admiraldev/devel/articles/programming_strategy.html#function-names

**Comment by bundfussr** [comment]
The `derive_*()` functions add variables or observations to the input dataset. The `create_*()` or `consolidate_*()` functions create a dataset without keeping the source observations.

**Comment by bms63** [comment]
| Function name prefix                         | Description                                                                                         |
|----------------------------------------------|-----------------------------------------------------------------------------------------------------|
| `assert_` / `warn_` / `is_`                  | Functions that check other functions’ inputs                                                        |
| `derive_`                                    | Functions that take a dataset as input and return a new dataset with additional rows and/or columns |
| `derive_var_` (e.g. `derive_var_trtdurd`)    | Functions which add a single variable                                                               |
| `derive_vars_` (e.g. `derive_vars_dt`)       | Functions which add multiple variables                                                              |
| `derive_param_` (e.g. `derive_param_os`)     | Functions which add a single parameter                                                              |
| `compute_` /  `calculate_` / ...             | Functions that take vectors as input and return a vector                                            |
| `create_`  /  `consolidate_`   | Functions that create datasets without keeping the original observations  |
| `derive_merge_`   |  Functions that add variable(s) to the input dataset based on variables from another dataset  |
| `_derivation` (suffix)  |  High order functions that takes another function as input |


Will make into separate issue, but wanted to get the conversation going around new function names and trying to name appropriately so increases findability.

**Comment by bundfussr** [comment]
I would remove the `derive_merge_` prefix because we have `derive_vars_merged()` and `derive_var_merge_*()` and not all functions which match to the description have the suffix, e.g., `derive_var_base()`. Otherwise we would need much more explanation to avoid confusion.

**Comment by bms63** [comment]
Hey Stefan I made a new issue for this so not to derail your feature request
