### ISSUE TITLE
Feature Request: Implement `consolidate_lookup_tables()`

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#1479]
### Feature Idea

Implement
```
consolidate_lookup_tables <- function(datasets,
                                      source_var = SOURCE,
                                      key_vars)
```
- `datasets` expects a named list of dataset, e.g., `datasets = list(company = global_adlb_params, study = adlb_params)`
- `key_vars` expects a list of variables, e.g., `key_vars = vars(LBTESTCD, LBSPEC, LBMETHOD)`

The function returns a dataset with one observation per key occurirng in any of the specified dataset. If a key occurs in more than one dataset, the observation from the last dataset is taken. The variable `SOURCE` should be added to the output dataset and set to the name of the dataset the observations is taken from.

Warnings should be issued if
- The keys are not a unique key of any of the datasets.
- The datasets contain different variables.

**Comment by rossfarrugia** [comment]
@bundfussr i forget the background of this one, but do you think it should be tagged for next release? what's the purpose/impact?

**Comment by bundfussr** [comment]
@rossfarrugia , the background for this issue is that `derive_vars_merged_lookup()` expects a single lookup dataset. I.e., if you have  different sources, e.g., company parameter mappings and project parameter mappings, these need to be consolidated into a single dataset. This should be done by `consolidate_lookup_tables()`.
