### ISSUE TITLE
Documentation:  OCCDS vignette update TRTEMFL section

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiral#1494]
### Please select a category the issue is focused on?

User Guides

### Let us know where something needs a refresh or put your idea here!

We now have `derive_var_trtemfl()` function available in `devel` so we should use this in the OCCDS vignette that shows an ADAE example: https://pharmaverse.github.io/admiral/articles/occds.html#trtflag

FYI @bundfussr

**Comment by bundfussr** [comment]
@rossfarrugia , I think I updated the vignette and the template in https://github.com/pharmaverse/admiral/pull/1445. Or did I miss something?

**Comment by rossfarrugia** [comment]
yes you did sorry - i was looking in the wrong branch 👍
