### ISSUE TITLE
Website - option to switch to previous releases

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiral#1495]
In a future release, let's add the option in the site to be able to view the site pages from previous releases via multi-version docs, which as discussed at the core dev team we feel will be even more useful in practice than enabling to switch between devel/main. Will be relevant for package exts too.

FYI @thomas-neitmann @bms63 and @cicdguy - tracking here so discussion not missed.

**Comment by bundfussr** [comment]
@cicdguy , did you find a solution to control the order of the entries in the "Versions" menu? For example in admiralonco we have "pre-release", "devel", "main" but I would prefer "main", "pre-release", "devel".

**Comment by bundfussr** [comment]
@rossfarrugia , @thomas-neitmann , @bms63 , we should update the release_strategy vignette. It should be added when and how a new version is added. I would not add a version for each hotfix release but just the latest, i.e., 0.8.3, 0.7.1, 0.6.3, 0.5.0, ...

**Comment by rossfarrugia** [comment]
agree @bundfussr on the release strategy and yes @cicdguy and his team added an option for ordering! glad this is all on the horizon - just creating this issue to remind and to mention that we discussed most value here being for releases, as we don't anticipate users to often be looking at devel once admiral becomes more stable.

**Comment by bms63** [comment]
So I will close the similar [issue](https://github.com/pharmaverse/admiralci/issues/220 on admiralci.  I think the release strategy updates will live in `admiraldev` and we will have a separate issue to enable multi-versions for admiral?

**Comment by bms63** [comment]
Agree on only major releases should be showcased

**Comment by rossfarrugia** [comment]
thanks @bms63, agree - sorry i missed that this got added there, still getting used to the new project board and finding issues across the repos
