### ISSUE TITLE
Documentation:  Update baseline function examples

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiral#1496]
### Please select a category the issue is focused on?

Function Documentation

### Let us know where something needs a refresh or put your idea here!

See https://pharmaverse.github.io/admiral/reference/derive_var_base.html bottom example:

![image](https://user-images.githubusercontent.com/82581364/194525023-1dbfe800-1a25-46ae-b5d1-2e3e4df58c1c.png)

If we add `ANRIND` to the test data tibble then we'd be able to include this function call to create `BNRIND` (i.e. remove the `if (FALSE)` bit) and we could show the output data created same as for the above examples. I would remove STUDYID though to ensure there's space on the site page for all variables to be displayed, as it isn't used in the calls anyway.

**Comment by zdz2101** [comment]
![image](https://user-images.githubusercontent.com/43018762/195709347-1c4f7d50-36d1-4c54-a999-71f6c0a2f48d.png)
![image](https://user-images.githubusercontent.com/43018762/195709417-1304be27-dead-4982-8e09-24578619cca2.png)
@rossfarrugia   It all still fits including ANRIND and STUDYID, should it still be removed? Also, I tried to make the ANRIND values be intuitive with low-high cutoffs of 10 & 15. Not sure if it would be appropriate to show how the ANRIND values are derived using derive_var_anrind()

**Comment by rossfarrugia** [comment]
@zdz2101 did you run `pkgdown::build_site()` to check if it all renders ok on the site? if so then fine to display all columns. for ANRIND i wouldn't think necessary as that function has its own page where people could look for examples.

thanks for the first contribution!

**Comment by zdz2101** [comment]
@pharmaverse/admiral I was able to render these screenshots using pkgdown::build_reference() so I think it should render fine on the site in theory. But when I use pkgdown::build_site() it seems to break at the Building News portion. Any suggestions?

![Image](https://user-images.githubusercontent.com/43018762/195877396-7f7d9f5b-179b-49db-bc80-458fcdadf85a.png)

**Comment by bms63** [comment]
Are you on a company vpn?  These curl issues pop up when I have been on GSK's vpn

**Comment by zdz2101** [comment]
I am not, weirdly enough, not running into any issues building admiraldev though, so must be something inside that news.md file, I'll try and troubleshoot a little more

**Comment by bms63** [comment]
are you using the pkgdown version in the lock file?

**Comment by bms63** [comment]
@zdz2101 any resolution?  If not, you might want to talk to Eli Miller from Atorus.  He is familiar with pkgdown
