### ISSUE TITLE
Feature Request:  Add Function to Find Next Dose

### ISSUE THREAD

**Issue by jeffreyad** [pharmaverse/admiral#1516]
### Feature Idea

For ADNCA and ADPC the PRE-DOSE concentration records have time variables that refer to the upcoming dose rather than the prior dose.  Adding a new function `derive_vars_next_dose()` which is a modified version of `derive_vars_last_dose()` would accomplish this.  For example ARRLT will be the relative time to the upcoming dose e.g. ARRLT = -0.5 if PRE-DOSE sample is at 11:50 and the next dose is at 12:20.

### Relevant Input

Inputs are PC and EX records.  The call is the same as `derive_vars_last_dose()`

### Relevant Output

Output is ADPC dataset with attached EX records for upcoming dose.

### Reproducible Example/Pseudo Code

```

adpc <- adpc %>% 
  derive_vars_next_dose(
    dataset_ex = ex,
    filter_ex = NULL,
    by_vars = vars(STUDYID, USUBJID),
    dose_id = vars(EXTRT),
    dose_date = ASTDTM,
    analysis_date = ADTM,
    single_dose_condition = EXDOSFRQ == "ONCE",
    new_vars = dplyr::vars(NEXTDOSE = EXDOSE, NEXTDTM = ASTDTM, NENDTM = AENDTM),
    traceability_vars = dplyr::vars(NDOSEDOM = "EX", NDOSESEQ = EXSEQ, NDOSEVAR = "EXSTDTC")
  )
```

**Comment by bundfussr** [comment]
@jeffreyad , thanks for creating this issue. Could you have a look at https://github.com/pharmaverse/admiral/issues/1448? I think the functionality you need is covered by `derive_vars_joined()`.

**Comment by jeffreyad** [comment]
> @jeffreyad , thanks for creating this issue. Could you have a look at #1448? I think the functionality you need is covered by `derive_vars_joined()`.

Hi @bundfussr, Yes! `derive_vars_joined()` works for this, and better still it also handles the same situation I need to be able to compare nominal times with prior nominal dose time and next nominal dose time.  Thanks!

**Comment by rossfarrugia** [comment]
We can close this one then and glad to see another usage for the new joined function :)
