### ISSUE TITLE
Documentation: BDS TTE vignette outdated

### ISSUE THREAD

**Issue by thomas-neitmann** [pharmaverse/admiral#1520]
### Please select a category the issue is focused on?

User Guides

### Let us know where something needs a refresh or put your idea here!

> The events and censorings are defined by the [event_source()](https://pharmaverse.github.io/admiral/reference/event_source.html) and the [censor_source()](https://pharmaverse.github.io/admiral/reference/censor_source.html) class respectively. It defines
> 
>   - which observations (filter parameter) of a source dataset (dataset_name parameter) are potential events or censorings,
>   - the value of the CNSR variable (censor parameter), and
>   - which variable provides the date (date parameter).
>
> The date can be provided as date (--DT variable), datetime (--DTM variable), or character ISO-8601 date (--DTC variable).

This is **not** true, because `--DTC` variables won't be accepted anymore.

**Comment by rossfarrugia** [comment]
good spot - i'll quickly fix this one now.
