### ISSUE TITLE
Functions clean up - for consistency and to reduce duplication now we have Generic Functions

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiral#1522]
For release 0.10.0 (maybe 1.0.0) in March 2023, let's re-visit discussions from https://github.com/pharmaverse/admiral/pull/1484 and look at which functions may need to be re-named/deprecated in favour of having cleaner sets of consistent functions like "merged" and "joined". Ross and Stefan to collate a list and bring to the core dev team for discussion. Then the changes should be reflected in the Generic Functions vignette.

After this stage we should endeavour to avoid such breaking changes where possible!

**Comment by bundfussr** [comment]
Also consider MDIS parameter derivations in admiralroche ADRS template.

**Comment by bundfussr** [comment]
`vars()` is superseded.

**Comment by bundfussr** [comment]
`restrict_derivation()` does not work with `mutate()`.

**Comment by bundfussr** [comment]
Consider https://github.com/pharmaverse/admiral/issues/1561#issuecomment-1308974099

**Comment by bundfussr** [comment]
Consider if keeping everything by default for selection functions like `derive_param_extreme_event()` is a good idea. Maybe it should be specified explicitly in the call what to keep.

**Comment by bundfussr** [comment]
Consider making the `by_vars` argument consistent with dplyr `*_join()` functions, i.e., the following should work
```
adtr <- derive_vars_merged (
  tr,
  dataset_add = tu,
  new_vars = vars(TULOC),
  by_vars = vars (STUDYID, USUBID, TRLNKID = TULINKID)
)
```

**Comment by rossfarrugia** [comment]
@bundfussr FYI i'm hoping this week to start a Box doc with a list of all these proposed updates for core team to review. Will share with you first as sure you'll find some i miss.

**Comment by bundfussr** [comment]
@rossfarrugia , I am working on a document as well. I will share it with you soon.

**Comment by rossfarrugia** [comment]
great, thanks! i'll wait for yours then, and then add anything else i can spot. appreciated!

**Comment by bundfussr** [comment]
@thomas-neitmann , @bms63 , I have uploaded two documents to box:
- https://exbpbox.box.com/s/gxi1t1a1xq1yn9txuftaum7kw4iwxeud: Classification of functions and review of each function regarding overlaps and clean-up
- https://exbpbox.box.com/s/kq9dvjyuz56ouqc75k5xaugpyvfsl72q: General ideas for clean-up and improve stability and usability

Please have a look and add comments.
Ross will set up a meeting in the next year.

**Comment by bms63** [comment]
Thanks @bundfussr!!

**Comment by bms63** [comment]
@bundfussr I added comments - not sure I was super decisive.  @thomas-neitmann can you take a look please before our meeting on Monday.  

Many many thanks for putting these together Stefan!!!!!!!!!!!

![OIP](https://user-images.githubusercontent.com/10111024/213814106-7a956a53-28fe-4096-a1a6-c7f754d9d67b.jpg)

**Comment by rossfarrugia** [comment]
@bundfussr you could feel free to close this one anytime once we finish our weekly brainstorm meets and once all the other action issues are added.
