### ISSUE TITLE
Documentation:  "See also" section for `source` objects list wrong stuff

### ISSUE THREAD

**Issue by thomas-neitmann** [pharmaverse/admiral#1552]
### Please select a category the issue is focused on?

User Guides

### Let us know where something needs a refresh or put your idea here!

Much of what is displayed after "Source specifications" is not a `source` object. This is confusing and should be updated.

<img width="766" alt="image" src="https://user-images.githubusercontent.com/11788080/199524548-80ea6050-2525-4e3f-981f-dc50e44c909c.png">

**Comment by rossfarrugia** [comment]
Currently all these fall on the Reference page under **Advanced Functions: Other**, as they use:
```
@keywords source_specifications
@family source_specifications
```

My suggested updates would be to add a new extra category for **Advanced Functions: Source Objects** and include the following here:
`basket_select()`, `censor_source()`, `date_source()`, `dthcaus_source()`, `event_source()`, `sdg_select()`, `smq_select()`, `tte_source()` and all the Pre-Defined Time-to-Event Source Objects.
In `man/roxygen/meta.R` we'd show these with the label "Source Objects: "

Then leave the rest from this list under Advanced Functions: Other.
In `man/roxygen/meta.R` we'd show these with the label "Other Advanced Functions: "

@thomas-neitmann @bms63 @bundfussr can you sanity check this proposal please before i make the updates?

**Comment by bundfussr** [comment]
`sdg_select()` and `smq_select()` are deprecated. Thus I would remove them from "Source Objects:'".

I would add `query()` as it is related to `basket_select()`.

**Comment by rossfarrugia** [comment]
Ah yes of course, can move them to deprecated as part of this PR. makes sense for `query()` too.

**Comment by rossfarrugia** [comment]
Note: when i checked code Sadchla has already deprecated those 2 in `devel`

**Comment by bms63** [comment]
Look sane to me - could this new category get updated in the `admiraldev` documentation as well? https://pharmaverse.github.io/admiraldev/devel/articles/programming_strategy.html#categorization-of-functions
