### ISSUE TITLE
Documentation:  Remove_pkgname::function() synatax from Roxygen examples

### ISSUE THREAD

**Issue by esimms999-gsk** [pharmaverse/admiral#1558]
### Please select a category the issue is focused on?

Other

### Let us know where something needs a refresh or put your idea here!

The work done for Issue #1380 was limited to tibble:: and stringr:: and lubridate:: syntax. There are other pkgname::function() instances in the R directory but these require additional discussion. Are rlang::, admiraldev:: and utils:: to be treated the same way? What about dplyr::n()?

**Comment by bms63** [comment]
I think we should be consistent and remove the `::` calls from any roxygen examples.

**Comment by thomas-neitmann** [comment]
Agree, either all or nothing. SO let's drop the `pkg::function()` syntax for all instances in the docs.

**Comment by bundfussr** [comment]
I would propose to close this issue and do the change in #1380.

**Comment by esimms999-gsk** [comment]
All or nothing? OK, let's go for all. I was breaking it up into two issues in the hope that I could avoid taking too long and having 1000 conflicts. :(

Looking at the few that are left:

The remaining lines found with :: (two colons) in the Roxygen example blocks are:

create_query_data.R:#'   get_smq_fun = admiral.test:::get_smq_terms,
create_query_data.R:#'   get_sdg_fun = admiral.test:::get_sdg_terms,
create_query_data.R:#'   get_smq_fun = admiral.test:::get_smq_terms,

derive_summary_records.R:#'   filter = dplyr::n() > 2,

derive_var_basetype.R:#'   basetypes = rlang::exprs(
derive_var_basetype.R:#' dplyr::count(bds_with_basetype, BASETYPE, name = "Number of Records")
derive_var_basetype.R:#'   basetypes = rlang::exprs(
derive_var_basetype.R:#' dplyr::count(bds_with_basetype, BASETYPE, name = "Number of Records")

derive_vars_last_dose.R:#'     traceability_vars = dplyr::vars(LDOSEDOM = "EX", LDOSESEQ = EXSEQ, LDOSEVAR = "EXENDTC")

get_summary_records.R:#'   filter = dplyr::n() > 2,

- I do not know what the ::: (triple colon) represents and am guessing it should remain as is.
- can dplyr::count(), dplyr::vars, dplyr::n be replaced with library(dplyr) and count(), vars(), n() ? I am wondering if the dplyr:: is necessary to ensure the Base R functions are not used.
- I was thinking that rlang:: was some developer-type package and should be handled differently; maybe I was wrong.

I will leave the admiral::: code alone. I will make changes for the dplyr:: and rlang:: code.

**Comment by esimms999-gsk** [comment]
Changes made in #1380 branch and done with PR #1555.

**Comment by bundfussr** [comment]
@esimms999-gsk , makes sense. We used the triple colon for `get_smq_terms()` to point out that it is just a dummy function for the example and that the users have to replace it by their own function which reads the terms from the company database.
