### ISSUE TITLE
Store our package data as rds

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiral#1562]
@bms63 @thomas-neitmann  After updating https://github.com/pharmaverse/admiral/issues/1501, shouldn't our example datasets like ADSL in `data/` now be stored as `.rds` instead of `.rda` too? from ophtha team (@millerg23) we also heard this causes R errors and `.rds` then need to be stored in `inst/` instead of `data/`.

Hadley's guide talks of storing `.rda` in `data/` though so maybe the way we have it is fine?

Same impact would be in admiral.test if you agree (and if so please create new issue there accordingly, or if its fine to leave as rda then just close this issue).

**Comment by thomas-neitmann** [comment]
Any datasets that ship with the package in the `data` folder have to be stored as `.rda`.
