### ISSUE TITLE
General Issue: v9 release video

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1566]
### Background Information

We created a release video for v8 and would like to continue with this trend.  Is it possible for one of you two to work on this?  It does not have to be a work of art!!  I set the bar pretty low in v8 https://www.youtube.com/watch?v=vFJww0R87wI :)  

* It only has to be 5-10 (max) minutes
* Highlight all the features that have been developed
* Highlight new vignettes and documentation updates 
* Highlight downstream and upstream packages and our interactions with them - e.g. testing for admiraldev package has been increased which is a dependency of admiral.  
* AOB you think is relevant to a release video, e.g. pointing to changelog notes to see other changes??

I made the previous video in Power Point using the recoding feature.  And just had a cheesy background, which we should use the same one for v9. 

This will get shared on slack and on linkedin and on other platforms.  

### Definition of Done

Release video created and uploaded to pharamverse youtube channel.

**Comment by bms63** [comment]
This can be done after the release (December 5th), but good to start getting familiar with the changelog to see what to highlight.

**Comment by sadchla-codes** [comment]
@bms63 @zdz2101 I can work on that
