### ISSUE TITLE
define how to implement periods/phases in a workshop (3h)

### ISSUE THREAD

**Issue by koegerr** [pharmaverse/admiral#157]
goal: get feedback from DSG and ADaM Connect team define how to implement it conceptually

**Comment by bundfussr** [comment]
@koegerr , what was the outcome? Should it not be covered by admiral core but implemented in company specific admiral extension packages?

**Comment by koegerr** [comment]
@bundfussr : we still discussion the model within Orchid. Overall the thinking is that it is too protocol specific. But maybe when we have a timing model we can have a look if pieces of it can be used to create some utility functions. Probably more Roche specific

**Comment by bundfussr** [comment]
@koegerr , maybe we should split it into two parts. The first part is the the creation of the phase and period variables in ADSL. I agree that this is very study-specific. We could provide an interface like the [Input Data Sets to Pass Phase, Period or Subperiod Information to ADSL VAD Macro](https://pages.github.roche.com/MDIS/stream_doc/um/vad_concept_atx_dataset.html) in STREAM but the creation of the input datasets would be study-specific.
The second part is the creation of the phase and period variables in the BDS and OCCDS dataset. These can be derived from the ADSL variables and are usually not study-specific. I think providing an admiral function for this would be very useful.

What do you think?
