### ISSUE TITLE
Feature Request: Create only a single environment for admiral in a separate file

### ISSUE THREAD

**Issue by thomas-neitmann** [pharmaverse/admiral#1572]
### Feature Idea

Right now environments are created in multiple files and are not documented.

**Comment by bundfussr** [comment]
I would prefer a meaning full name, e.g., `admiral_environment.R` instead of `aaa.R`. We could use the `@include` tag if a file needs the environment when loading. There shouldn't many such files if at all.

**Comment by bms63** [comment]
I like `admiral_environment.R` - much more meaningful.

**Comment by zdz2101** [comment]
Looks like we create new environment objects in three places: 

1. `admiral_options.R` - used to house the default values for `subject_keys`
2. `derive_merged.R` - used for `get_not_mapped()`
3. `duplicates.R` - used for `get_dupllicates_dataset()` 

Should we also unify the three environment objects into one object calling it `admiral_environment` . Then within it, it can call 

1. `admiral_environment$subject_keys`
2. `admiral_environment$nmap`
3. `admiral_environment$duplicates`

as appropriate in the respective scripts?

**Comment by bundfussr** [comment]
Makes sense to me.

Should we use the same approach in admiraldev and add `admiraldev_environment.R` which creates the environment `admiraldev_environment` instead of `.datasets` in `datasets.R`?

**Comment by zdz2101** [comment]
Yes and while parsing that out in admiraldev, can also add a line or two in the programming strategy describing if the developer needs to use a separate environment to fulfill some sort of purpose for their function, the respective `xxx_environment.R` is the appropriate location for it

**Comment by bundfussr** [comment]
Yes, good idea.
We should also add to the programming strategy that all objects which are stored in the environment must be documented in `admiral_environment.R`. Then it is easier to see which objects are already used.

**Comment by bms63** [comment]
Ah I see you are already on @zdz2101 for the programming strategy!!

**Comment by zdz2101** [comment]
> Ah I see you are already on @zdz2101 for the programming strategy!!

Perhaps we should push the admiraldev one first to make sure everything is fine and dandy?

**Comment by bms63** [comment]
Haha yeah this new environment stuff scares me a little...
