### ISSUE TITLE
Documentation: adsl example dataset got added to function section

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1574]
### What happened?

![image](https://user-images.githubusercontent.com/10111024/200962231-775204e7-8a29-420c-a1ab-c2c8416f163f.png)

Looks like the `admiral_adsl` got moved somehow to the function section.  It should live in the Example dataset section.

**Comment by bms63** [comment]
ACtually...it looks like the all the functions are being placed into the BDS-specific section.  Unsure of the root cause
![image](https://user-images.githubusercontent.com/10111024/201498201-f105a3e4-5bbc-4cb6-83a5-4b35b017bb8b.png)

**Comment by rossfarrugia** [comment]
@thomas-neitmann @bundfussr @sadchla-codes @zdz2101 any ideas on this one?? i took a look but i couldn't find the issue and i recreated the site in devel on my side and got the same as Ben sees. we really need this one fixed before the upcoming release.

**Comment by bundfussr** [comment]
It seems to be a bug in pkgdown.
We have
```
- contents:
  - has_keyword("der_bds_gen")
  - has_keyword("der_bds_findings")
```
but we do not use the `der_bds_gen` keyword. Instead of adding nothing for `has_keyword("der_bds_gen")` pkgdown adds all.

**Comment by rossfarrugia** [comment]
thanks @bundfussr - can you double check admiralonco is not impacted by this too please

**Comment by bundfussr** [comment]
@rossfarrugia , admiralonco is fine. All `contents:` fields have only one item there.

**Comment by bms63** [comment]
@esimms999-gsk This has been completed FYI
