### ISSUE TITLE
Documentation:  filter_if exported both from admiral and admiraldev

### ISSUE THREAD

**Issue by PatrickRWright** [pharmaverse/admiral#1575]
### Please select a category the issue is focused on?

Function Documentation

### Let us know where something needs a refresh or put your idea here!

Presumably this is a straggler in `admiral`. Is that so?

https://github.com/pharmaverse/admiral/blob/main/NAMESPACE#L124  
https://github.com/pharmaverse/admiraldev/blob/main/NAMESPACE#L39

**Comment by bundfussr** [comment]
@PatrickRWright , yes, you are right. Thanks for raising this.

We have already an issue for this (https://github.com/pharmaverse/admiral/issues/1450). So I'll close this one.
