### ISSUE TITLE
General Issue: Implement a roxygen roclet to improve documentation

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#1590]
### Background Information

A roxygen roclet defines how the roxygen tags in the function header are processed and how the man pages are generated. By implementing our own roclet we could achieve the following:
- Define a `@default` tag. If the tag occurs after a `@param` tag, the value is displayed at the end of the parameter description. If it does not occur and the parameter has a default value, the default value is taken from the function definition.
- Define a `@permitted` tag. The value is displayed at the end of the parameter description. If the tag is not specified, the permitted value could be determined from the default value. We could also define keywords for common permitted values like "list of variables created by `vars()`", e.g., it could be requested by `@permitted [varlist]`.
- The processing of the ` @describeIn` tag could be changed such that each functions gets it own subsection on the page. This is useful for the `*_source()` functions and also for helper functions which are related to a single function, e.g., `assert_db_requirements()` used by `create_query_dataset()`.
- A `@title` (and a `@description` tag) could be added for examples such that each example gets a subsection with title and optionally a description. This helps navigating documentation of functions with many long examples like [derive_var_extreme_flag()](https://pharmaverse.github.io/admiral/reference/derive_var_extreme_flag.html#ref-examples).

See https://roxygen2.r-lib.org/articles/extending.html and https://roxygen2.r-lib.org/reference/roclet.html for some guidance on implementing roxygen roclets.

**Comment by galachad** [comment]
It looks like nice and easy to add new tag to roxygen and parse it into rd section but it's worth to consider if we would like to automate this process without adding extra tag into docs.

The rd section is executed sequenatialy so the `@default variables` or `@defaultValues` tag need to added after `@param` tag. 

The both proposal for adding new tags or  editing `roxygen2` behaviour do not solve the case with `@inheritsParams`.
Note: The `@inheritsParam` is processed later in [`topics_process_inherit`](https://github.com/r-lib/roxygen2/blob/39d2dbefddac508dba6bffdec3a625cac7af16bc/R/rd-inherit.R#L96) function.

The tags are not enough to cover all use cases.

We have few option for implementing this as we do not want to build the full roclet:
1) Modify the `roxygen2` namespace.  It's not perfect solution, hard to maintain, can messy with other R packages. Mosty not recommended but sometimes very powerful. Example: [[1]](https://gist.github.com/galachad/83e0f5a10180f0a7a0d4d95ced4eafd0).
The pros of this solution is that the workflow for build docs will not change.

2) Apply tags - tags it self do not cover all use cases as e.g. `@inheritsParams` is processing after tag application [[2]](https://gist.github.com/galachad/e594cd32d1f392cb3b4b0fea7a3e2346).

3) We can use custom `roclet`. It looks like nice solution but the workflow will change a little.
The developer need to call roxygenise with custom roclet param.
E.g. 
```r
devtools::document(roclets = c("collate", "namespace", "admiral_roclet"))
roxygen2::roxygenise(roclets = c("collate", "namespace", "admiral_roclet"))
admiraldev::document() # Possibility to have admiral wrapper
# modify roxygen2 to apply rules to admiral* packages
```

Example (setting function param value in param section):

```r
library(rlang)
add_default_values <- function(params, rd, param_names) {
  for (param_name in param_names) {
    param <- params[[param_name]]
    if (!is_missing(param) && !is.null(param)) {
      rd$sections$param$value[[param_name]] <- sub(
        "\n\n% default_value start\n(.*)% default_value end\n", "",
        rd$sections$param$value[[param_name]]
      )
      try({
        # Get default value from vector
        param <- match.arg(param)
      }, silent = TRUE)
      rd$sections$param$value[[param_name]] <- paste0(
        rd$sections$param$value[[param_name]],
        "\n\n% default_value start\n",
        "\\emph{Default:} \\strong{",
        as_label(quo(!!param)),
        "} % default_value end\n"
      )
    }
  }
}


admiral_roclet <- function() {
  roxygen2::roclet(c("admiral"))
}

roclet_process.roclet_admiral <- function(x, blocks, env, base_path) {
  x <- roxygen2:::rd_roclet()

  topics <- roxygen2::roclet_process(x, blocks, env, base_path)

  # Topics manipulation
  purrr::imap(topics, function(x, y) {
    name <- x$get_name()
    obj <- get0(name, envir = env)
    if (is.null(obj) || !is.function(obj)) return(x)
    params <- rlang::fn_fmls(obj)
    param_names <- names(x$get_value("param"))
    if (is.null(params) || is.null(param_names)) return(x)
    add_default_values(params, x, param_names)
  })

  topics
}

roclet_output.roclet_admiral <- function(x, results, base_path, ...) {
  x <- roxygen2:::rd_roclet()
  roxygen2::roclet_output(x, results, base_path, ...)
}
```

In my opinion the 3rd option will be the most clean. 

### Tags

Proposal:
- The `@default name description/explanation` tag is used 
- The `@default` tag explain defaults values e.g NULL 
- The `@default` tag should be post process after inherits. 
- The `@permitted` tag should be post process after inherits
- The `@permitted` tag can be use for define variable or evaluate function in package namespace to get this list
- I'm wondering why in some cases  the `arg_match` concept is not followed. (consistency for not character vector or documentation 
- The `@permitted` tag can impact the other section like usage (optimisation of usage section)
- For `@describeIn` I understand the concept but I would like to know more. Is it about splitting the usage between different section? I can be a little bit more complicated as to do that we need to inject code execution in the middle process.

```
\description[1]
\usage[1]
\description[2]
\usage[2]
```

- For `@title` and `@description` it should be handled in different way as tags in roxygen are parse on the top level.
We can separate examples using comments section in code.

@bundfussr let me know, what you think. If it looks good for you I can do this as extension for admiraldev.

### Ideas for more
- Add extra checks for documentation.
- Verify the names consistency in the package
- Custom tag for docs
- Evaluate code e.g. eval variables to be always uptodate
- Generating docs template base on the object

**Comment by bundfussr** [comment]
@galachad 

- What do you mean by "I'm wondering why in some cases the `arg_match` concept is not followed. (consistency for not character vector or documentation"?
- Why can the `@permitted` tag impact the usage section?
- The `@describeIn` tag should not just split the usage section but all sections. It should more or less concatenate the documentation of the functions. For example if `@descibeIn derive_var_dthcaus` is used in the header of `dthcaus_source()`, the documentation of `dthcaus_source()` would be appended to the `derive_var_dthcaus()` documentation.
- Separating examples using comments does not work well, especially for functions with many examples. What I had in mind was something like
    ```
    #' @examples
    #' @title Deriving `ABLFL` (last observation)
    #' @description Flagging the last observation before start of treatment.
    #' ```
    #" example code
    #' ```
    #' @title Deriving `ABLFL` (worst observation)
    #' @description Flagging the worst observation, i.e., the highest value before start of treatment.
    #' ```
    #" example code
    #' ```
    ```
    The `@title` tag should generate subsections such that we get a TOC like
    ```
    ...
    See also
    Author
    Examples
      Deriving `ABLFL` (last observation)
      Deriving `ABLFL` (worst observation)
    ```
    Do you think this is possible?

**Comment by galachad** [comment]
I will do initial implementation in admiraldev, so it will be easiest to follow up

- For arg_match It's done by assertion, sorry.
- Why can the @permitted tag impact the usage section? 
It can be more as extra features as by default usage section will be looks like:
```
param = NULL
```

- For describeIn it's inheriting the changes so it can be probably added latter. 

- Separating examples—it's definitely possible, but let's start from implementing the roclet first.

**Comment by zdz2101** [comment]
Closing to centralize as denoted in https://github.com/pharmaverse/admiraldev/issues/290
