### ISSUE TITLE
Bug: get_many_to_one() and get_one_to_many() examples aren't displaying correctly

### ISSUE THREAD

**Issue by zdz2101** [pharmaverse/admiral#1596]
### What happened?

This is what is currently live on the admiral website: 

![image](https://user-images.githubusercontent.com/43018762/202800804-645420d0-e1ca-4da7-93a8-522052643ebb.png)

**Comment by bms63** [comment]
Umm...I wonder if `admiraldev` should be in the example

**Comment by bms63** [comment]
Also...wonder how that doesn't fall over in the `check()`

**Comment by zdz2101** [comment]
I think the `try()` wrapper lets us get through with error, but this was an unexpected error.

I stumbled upon it when investigating the implications of https://github.com/pharmaverse/admiral/issues/1572 and https://github.com/pharmaverse/admiraldev/issues/179 . There's actually chain of functions:

derive_param_tte >> assert_one_to_one >> set_dataset
get_many_to_one >> get_dataset
get_one_to_many >> get_dataset

At the bottom of these chains, there's hard code that refers to the `.Datasets` environment, but both of these `.Datasets` environments are individually created in both admiral and admiraldev, still trying to dissect that means when we try to consolidate the environment lines
