### ISSUE TITLE
Documentation:  Description file needs update for admiral dev and admiral.test

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1605]
### Please select a category the issue is focused on?

Other

### Let us know where something needs a refresh or put your idea here!

Since admiral.test and admiraldev have breaking changes for previous admirals should the v9 admiral have admiral dev >= 0.2 and admiral.test >= 0.4??  so this prompts update of packages??

@thomas-neitmann @bundfussr

**Comment by thomas-neitmann** [comment]
Yes!

**Comment by thomas-neitmann** [comment]
Good catch! Should be part of our release check list.

**Comment by zdz2101** [comment]
Looks like closing #1611 would close this as well
