### ISSUE TITLE
Prepare "Introduction to R for SAS Programmers" workshop for {admiral} hackathon

### ISSUE THREAD

**Issue by thomas-neitmann** [pharmaverse/admiral#1612]

**Comment by rossfarrugia** [comment]
In case useful, at previous PHUSE workshops we just sent out the following from Atorus as a pre-read:
[Introduction to R for the Statistical Programmer](https://atorus-research.github.io/phuse_intro_to_r_2021_website/) (see Content & Resources sections)

Alternatively there is now also [SAS&R](https://bayer-group.github.io/sas2r/) open source materials from Bayer that could be re-used.

**Comment by bms63** [comment]
I'm assuming you all got this completed - can we close out?

**Comment by thomas-neitmann** [comment]
Yes.
