### ISSUE TITLE
Find or create SDTM datasets for admiral hackathon

### ISSUE THREAD

**Issue by thomas-neitmann** [pharmaverse/admiral#1614]
Might be worth looking at the PHUSE Open Data Repository.

**Comment by rossfarrugia** [comment]
why would you not just re-use {admiral.test}?

**Comment by thomas-neitmann** [comment]
That would be the same old data everyone has been using for the last decade 😅 

I had hoped to find something "more interesting" but in case we don't than the CDISC pilot data will be our fallback option.

**Comment by rossfarrugia** [comment]
ha true, but tbh its not the data people really care about when learning admiral, it's our functions and templates. familiarity with the test data (if somehow they already tried it) is actually a useful thing for training people on a new toolkit

**Comment by bms63** [comment]
Can we close this?

**Comment by thomas-neitmann** [comment]
Actually, not just yet...
