### ISSUE TITLE
Feature Request:  derive_vars_duration rounding

### ISSUE THREAD

**Issue by SHAESEN2** [pharmaverse/admiral#1616]
### Feature Idea

derive_vars_duration should include a rounding argument so we dont need an additional mutate step.

### Reproducible Example/Pseudo Code

adsl06 <- adsl05 %>%
  dplyr::left_join(visit1dt, by = c("STUDYID", "USUBJID")) %>%
  dplyr::left_join(visnumen, by = c("STUDYID", "USUBJID")) %>%
  dplyr::left_join(disonsdt, by = c("STUDYID", "USUBJID")) %>%
  admiral::derive_vars_duration(new_var=DURDIS,
                              start_date = DISONSDT,
                              end_date = VISIT1DT, 
                              out_unit = "months",
                              add_one = TRUE
                              )

**Comment by thomas-neitmann** [comment]
Why would you already round values in the dataset itself? Feels like something you'd do when creating your TLGs.

**Comment by SHAESEN2** [comment]
I agree, but it seems not everyone does eg CDISC pilot https://github.com/RConsortium/submissions-pilot3-adam/issues/1

**Comment by thomas-neitmann** [comment]
I think that's quite an edge case and not best practice so if someone really wants to round values in their dataset then they'll have to use a `mutate()` step. {admiral} does not strive to cover 100% of use cases.
