### ISSUE TITLE
Documentation:  derive_vars_duration additional example

### ISSUE THREAD

**Issue by oreillb1** [pharmaverse/admiral#1620]
derive_vars_duration start_date and end_date inputs can be counter-intuitive when start_date needs to be an end data variable and end_date needs to be a start date variable.   
"Last Dose Relative Time" LDRELTM requires start_date = LDOSEDTM, end_date = ASTDTM so that LDRELTM will be positive (unless there are data issues).  Suggestion is to include an example for "Derive adverse event start time since last dose in hours" showing missing data examples.
```
data <- tribble(
  ~USUBJID, ~ASTDTM, ~LDOSEDTM,
  "P01", ymd_hms("2019-08-09T04:30:56"), ymd_hms("2019-08-08T10:05:00"),
  "P02", ymd_hms("2019-11-11T23:59:59"), ymd_hms("2019-10-11T11:37:00"),
  "P03", ymd_hms("2019-11-11T00:00:00"), ymd_hms("2019-11-10T23:59:59"),
  "P04", ymd_hms("2019-11-11T12:34:56"),NA,
  "P05", NA, ymd_hms("2019-09-28T12:34:56")
)
derive_vars_duration(
  data,
  new_var = LDRELTM,
  new_var_unit = LDRELTMU,
  start_date = LDOSEDTM,
  end_date = ASTDTM,
  in_unit = "hours",
  out_unit = "hours",
  add_one = FALSE
)
```

**Comment by bundfussr** [comment]
@pharmaverse/admiral , should we add this example and where should we add it?

**Comment by bms63** [comment]
It might be okay in the Examples for this Function with some additional comments.   

We could also make an "Exotic" Use Case Vignette and discuss using our functions in use cases as above??

**Comment by thomas-neitmann** [comment]
> It might be okay in the Examples for this Function with some additional comments.

That makes most sense to me.

> We could also make an "Exotic" Use Case Vignette and discuss using our functions in use cases as above??

Feels mike a miscellaneous vignette which I'm not a fan of.

**Comment by rossfarrugia** [comment]
As its just an extra example i think a good one for an admiral community contributor to pick this up anytime after we make this upcoming release. @oreillb1 feel free to self-assign this yourself if you're interested in making the required update, but no pressure.

**Comment by bms63** [comment]
@oreillb1 can you finish this update for `v0.10` release?  Release is planned for March 5th - ideally one week before but there is some wiggle room.

If not we can re-assign to someone else.  Please just let me know.
