### ISSUE TITLE
Bug:  derive_vars_dtm - seconds

### ISSUE THREAD

**Issue by SHAESEN2** [pharmaverse/admiral#1621]
### What happened?

I have a date time variable with time reported up until minutes and want to populate ADTM (without seconds). It seems like the function does not accommodate this. It forces the user to impute seconds, even though this is often not relevant in trials.

### Reproducible Example

```r
adlb02 <- adlb01 %>%
  admiral::derive_vars_dtm(
    new_vars_prefix = "A",
    dtc = LBDTC,
    highest_imputation = "s", # admiral assumes seconds are present before populating ADTM (strong assumption)
    ignore_seconds_flag = F
  ) 

    LBDTC            ADTM               
   <chr>            <dttm>             
 1 2013-12-26T14:45 2013-12-26 14:45:00
 2 2014-01-16T13:17 2014-01-16 13:17:00
 3 2014-01-30T08:50 2014-01-30 08:50:00
 4 2014-02-12T12:56 2014-02-12 12:56:00
 5 2014-03-05T12:25 2014-03-05 12:25:00
 6 2014-03-26T15:15 2014-03-26 15:15:00
   ```

**Comment by bundfussr** [comment]
`ADTM` is a "numeric" variable. You can not have it without seconds.

If seconds are not collected, you can set `ignore_seconds_flag = TRUE` to avoid that `ATMF` is set to `"S"`.
