### ISSUE TITLE
General Issue: Replace `vars()`

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#1627]
### Background Information

The `vars()` function is used extensively in admiral and admiral function calls. Unfortunately, it is superseded (see https://dplyr.tidyverse.org/reference/index.html#superseded).

### Definition of Done

- [x] Team agrees on a replacement of `vars()`.
- [x] Develop deprecation strategy and implement
- [x] Replacement in functions
- [x] Investigate templates and replace where necessary
- [x] Investigate vignettes and replace where necessary
- [x] Investigate tests and replace where necessary

@bundfussr Can you think of anywhere else that we need to replace `vars()` or be worried about?

**Comment by thomas-neitmann** [comment]
Not sure this requires immediate action as "superseded" is different from "deprecated":

> Superseded functions have been replaced by new approaches that we believe to be superior, but we don’t want to force you to change until you’re ready, so the **existing functions will stay around for several years**.

**Comment by bundfussr** [comment]
I think if we change it in the next release, the impact for the users is small because it does not exist much user code. If we do it in two or three years, the impact is huge because the users have to update all the admiral function calls in their scripts and functions.

Thus I would change it as soon as possible.

**Comment by bundfussr** [comment]
I would propose to replace `vars()` with `exprs()`. The other replacement option is `quos()` but as the expression will never be evaluated in the environment, it is simpler and cleaner to use expressions instead of quosures.

**Comment by rossfarrugia** [comment]
@bms63 @thomas-neitmann do you agree with Stefan's suggestion?

**Comment by bms63** [comment]
Sadly, I think we should change it now like Stefan suggested as if we wait a few years then more people will have used `vars()`  in their code.

**Comment by rossfarrugia** [comment]
@HinalPat @hiren8484 watch this issue and associated PR for impact to onco and ophtha too

**Comment by bms63** [comment]
## Pros and Cons for keeping `vars()`

|                        |  Pro        |          Con      |
|--------------   |-----------|------------|
| Already implemented in all our code   |  :white_check_mark:  |          |
| No impact on downstream packages - code and templates|   :white_check_mark:   |  |
| Likely removal from `dplyr` in a few years |    | :x:|    
| `dplyr::across()` is likely replacement - confusing for users and its purpose|    | :x:|    
| Possible re-implementation of `vars()` in `admiral` to keep its use |    | :x:| 
| Re-implementation could cause unforeseen bugs and gremlins  |    | :x:|   
| `vars()` is easy to understand for simple use cases |  :white_check_mark:   |  | 
| Secondary use cases, e.g. expressions, not clear |    | :x: |

## Pros and Cons for replacing `vars()` with `exprs()`

|                 |  Pros | Cons |
|--------------   |-----------|------------|
| Large impact of Implementation of replacing `vars` with `exprs()` in `admiral` code base |    |  :x:        |
| Implementation will impact downstream packages - code and templates|    | :x: |
| Current user base will be impacted - however minimal adoption of `admiral` |    | :x: |
| Implementation now will reduce impact of code base for Studies later  | :white_check_mark:  :white_check_mark:   :white_check_mark:  | |
| Possible confusing argument, i.e. `exprs()` versus `vars()` for new users  |   |  :x: |
| Clearer argument for intermediate and advanced users  | :white_check_mark:  |   |

**Comment by bundfussr** [comment]
The result of `exprs()` is clearer than the result of `vars()`:
```
> exprs(USUBJID, AVISIT)
[[1]]
USUBJID

[[2]]
AVISIT

> vars(USUBJID, AVISIT)
<list_of<quosure>>

[[1]]
<quosure>
expr: ^USUBJID
env:  global

[[2]]
<quosure>
expr: ^AVISIT
env:  global
```
I think most of the users do not know quosures and there is no need to know them. Therefore the output of `vars()` may confuse them.

**Comment by thomas-neitmann** [comment]
This might seem a bit hacky but why don't be export our own `vars()` function which is defined simply as

```
vars <- exprs
```
?

That way there's no need to change anything in our codebase. And just visually speaking listing out variables inside a function whose name suggests expression looks off to my. Just my 2 cents, though...

**Comment by bundfussr** [comment]
```
vars <- exprs
```
could have confusing side effects because the behavior of `vars()` would depend on the order of the library calls. 
```
library(dplyr)
library(admiral)
vars(USUBJID, AVISIT)
```
would create a list of expressions while
```
library(admiral)
library(dplyr)
vars(USUBJID, AVISIT)
```
would create a list of quosures.

Reexporting functions of other packages with a different name looks strange to me. Why should we introduce a new name for an established function?

I think for R novices it does not make a difference if an example uses
```
  by_vars = vars(USUBJID, AVISIT),
```
or
```
  by_vars = exprs(USUBJID, AVISIT),
```
They would consider `vars()` or `exprs()` just as the R function for quoting.

**Comment by thomas-neitmann** [comment]
Decision: go with `exprs()`.

**Comment by bundfussr** [comment]
I've created https://github.com/pharmaverse/admiraldev/issues/208 for the updated in admiraldev.

**Comment by bundfussr** [comment]
@pharmaverse/admiral , I have implemented the replacement of `vars()` with `exprs()` in admiral and admiraldev (see linked PR). Please have a look.

- I have reexported `rlang::exprs()` like we did before with `dplyr::vars()`. Do you agree?
- I have reimplemented `vars()` such that it issues a deprecation warning and calls `exprs()`. This way old scripts could work. Unfortunately, it works only if admiral is loaded _after_ dplyr.
 Is this a good deprecations strategy? What do you think?

**Comment by galachad** [comment]
To solve the issue with the package attach order, it's possible to define the event/hook that will be executed during dplyr attach.

If the `admiral` will be attached after dplyr, it will mask the `vars` in the namespace.  (standard behavior)

In the second case when dplyr will be attached after admiral, the admiral will set up an event in `.onLoad` package.

The package event is defined by string generate with `packageEvent` function.
```
> packageEvent("dplyr", event = "attach")
[1] "UserHook::dplyr::attach"
```

The event hook should be added to execute when dplyr will be attached.
```
setHook(packageEvent("dplyr", event = "attach"), function(libname, pkgname) {print("Hello from dplyr attach")}, action = "append")
```

This extra function will be executed when the `dplyr` will be attached when call `library(dplyr)` or `attach`.

We can modify the search path, so the admiral still will be before dplyr.

```
setHook(packageEvent("dplyr", event = "attach"), function(libname, pkgname) {
  detach("package:admiral")
  suppressWarnings(library("admiral", pos=2L,
                           warn.conflicts = FALSE,
                           quietly = TRUE,
                           character.only = TRUE,
                           verbose = FALSE))
}, action = "append")
```

@bundfussr let me know if it solves the issue.

**Comment by bundfussr** [comment]
Thanks @galachad . Modifying the search paths works for the R-CMD checks and it is not explicitly forbidden by the "CRAN Repository Policy".
