### ISSUE TITLE
admiraldev does not export `negate_vars`

### ISSUE THREAD

**Issue by hadley** [pharmaverse/admiral#1629]
I'm trying to explore a potential problem with the dev version of stringr, but I can't get your package to build because you have

```R
#' @export
admiraldev::negate_vars
```

but `negate_vars` is not exported by admiraldev (https://github.com/pharmaverse/admiraldev/blob/main/NAMESPACE).

**Comment by bms63** [comment]
So... we actually moved that back to `admiral` and are planning on sending to CRAN on Monday.  

Aslo, the current version of `admiraldev` breaks older versions of `admiral` as we removed the `assertthat` dependency.  While we were doing this rework we moved ` negate_vars` back to admiral.  

![image](https://user-images.githubusercontent.com/10111024/205364548-5d1c3cd6-acb7-4503-ad0e-2a44c471aad9.png)

**Comment by hadley** [comment]
I'm still seeing the problem with the main branch of admiral.

Anyway, perhaps you can diagnose if dev stringr is causing problems with admiral, since I can't seem to load your package.

**Comment by bms63** [comment]
Sorry - our updates are in the `devel` and `pre-release` branches.  Going out on Monday to CRAN and once accepted to CRAN we will merge into `main`.

We can test out the changes for `dev-stringr` and let you know of anything untoward.

**Comment by bms63** [comment]
@hadley  I don't see a dev branch on stringr github page?

![image](https://user-images.githubusercontent.com/10111024/205455910-9886556b-c2ad-4413-adf9-6456fe918fd2.png)

**Comment by hadley** [comment]
The development version of stringr is in the main branch (this is standard practice).
