### ISSUE TITLE
Bug: `derive_var_age_years()` returns the output dataset invisible

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#1634]
### What happened?

`derive_var_age_years()` returns the output dataset invisible. Therefore the output dataset is not displayed for the examples in the documentation.

**Comment by imaheshdivakaran** [comment]
Thank you, @bundfussr, for reporting this issue. Please share with us some dummy data you are facing issues using the tribble function from the Tibble package. This will speed up someone picking up this issue to fix.

**Comment by imaheshdivakaran** [comment]
Also, please try to assign the output to some data frame or Tibble so you can see the output from the environment. An example is mentioned below. 

> `library(admiral)
> 
> data <- data.frame(
>   AGE = c(27, 24, 3, 4, 1),
>   AGEU = c("days", "months", "years", "weeks", "years")
> )
> 
> data = data %>%
>   derive_var_age_years(., AGE, new_var = AAGE)
> 
> data = data.frame(AGE = c(12, 24, 36, 48)) %>%
>   derive_var_age_years(., AGE, age_unit = "months", new_var = AAGE)`

**Comment by bms63** [comment]
Hi all.  Please don't close issues unless they are part of a release or hotfix.  This is to minimize people reporting the same thing over and over again.   

https://pharmaverse.github.io/admiraldev/devel/articles/git_usage.html#reviewingclosing-an-issue

**Comment by thomas-neitmann** [comment]
@imaheshdivakaran Are you still intending to work on this?

**Comment by imaheshdivakaran** [comment]
Yes @thomas-neitmann

**Comment by bms63** [comment]
Hi @pharmaverse/admiral .  Can someone pick this up please?
