### ISSUE TITLE
General Issue: deprecate functions and arguments

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#1635]
### Background Information

- Functions and arguments which were deprecated in admiral 0.7.0 (or before) should be removed.
- For functions and arguments which were deprecated in admiral 0.8.0 `deprecate_warn()` should be replaced with `deprecate_stop()` and the "deprecated" badge with the "defunct" badge.
- Unit test should be updated.

This issue could be combined with https://github.com/pharmaverse/admiraldev/issues/36.

**Comment by bms63** [comment]
I think we also need to look into setting up the `devel` to `pre-release` PR checklist to help remind us to check on stuff like this...since we missed deprecating and removing functions on this for `v9`

**Comment by sadchla-codes** [comment]
Already addressing this in issue #1723
