### ISSUE TITLE
Feature Request: add keep_vars parameter in `derive_locf_records()`

### ISSUE THREAD

**Issue by kaz462** [pharmaverse/admiral#1636]
### Feature Idea

Would it be possible to specify variables that needs to be kept from "Last Observation" for new records? 
currently "Only variables specified in `derive_locf_records(..., by_vars)` will be populated in the newly created records."

### Relevant Input

`derive_locf_records(..., keep_vars)`

### Reproducible Example/Pseudo Code

add `PARAMN, PARAM, ADT, ADY` in the advs from [documentation example](https://pharmaverse.github.io/admiral/reference/derive_locf_records.html), and populate these columns in the newly created records.

**Comment by bundfussr** [comment]
How would you populate variables like `ADT` or `ADY`? Would you carry forward their values from the last valid observation or should they be set to the planned date or day?
What would you do if there is an observation for a certain visit but `AVAL` is missing? Would you keep `ADT` and `ADY` from the this observation or use `ADT` and `ADY` from the last observation with non-missing `AVAL`?

**Comment by kaz462** [comment]
Thanks, @bundfussr for the quick response!
An example from [CDISC pilot data adqsadas](https://github.com/cdisc-org/sdtm-adam-pilot-project/tree/master/updated-pilot-submission-package/900172/m5/datasets/cdiscpilot01/analysis/adam/datasets) carried forward their values (ADT/ADY) from the last valid observation, but it does not necessarily apply to other studies. 
What do you think of adding the option to specify variables (other than `by_vars`) that need to be carried over from the last valid observation (with non-missing AVAL)?
 
The following ones could be better examples than ADT/ADY: VISITNUM, VISIT, PARAM, PARAMN, etc

**Comment by kaz462** [comment]
I created a pull request to illustrate the [documentation example](https://pharmaverse.github.io/admiral/reference/derive_locf_records.html) (I added one more column `PARAMN` in the example data) :
if `PARAMN` needs to be populated, we can specify it in `keep_vars`
```
derive_locf_records_(
  data = advs,
  dataset_expected_obs = advs_expected_obsv,
  by_vars = vars(STUDYID, USUBJID, PARAMCD),
  order = vars(AVISITN, AVISIT),
  keep_vars = vars(PARAMN)
)
```
In the original function, `PARAMN` cannot be specified in `by_vars`, as it will be treated as a grouping variable and return unexpected results (63 records, 23 records are expected) 
```
derive_locf_records(
  data = advs,
  dataset_expected_obs = advs_expected_obsv,
  by_vars = vars(STUDYID, USUBJID, PARAMCD, PARAMN),
  order = vars(AVISITN, AVISIT)
)
```

**Comment by bms63** [comment]
HI @gg106046 what do you think?

**Comment by gg106046** [comment]
> HI @gg106046 what do you think?
This makes sense. I can try adding this feature!

**Comment by bundfussr** [comment]
@kaz462 , yes, I think adding `keep_vars` makes sense.
