### ISSUE TITLE
Documentation: Vignette for Hy's Law Implementation Guide

### ISSUE THREAD

**Issue by zdz2101** [pharmaverse/admiral#1637]
### Feature Idea

@pharmaverse/admiral To assist in Hy's Law discussion #1041 and to broaden the scope just because flagging instances of " ># times ULN" for laboratory values can arise beyond Hy's Law implementations, for example: 

- checking if lab values reach a certain threshold for retreatment criteria after an AE that caused dose delay/reduction 
- checking for inclusion/exclusion criteria 

`derive_lab_fl()` should create columns containing flags as appropriately based on the desired parameters and their respective cutoffs

### Relevant Input

Function arguments should include: 

- `data`: some sort of SDTM.LB or ADLB dataset
- `param`: lab parameter like "AST" or "BILI"
- `crit_seq`: a sequence of numbers to create categorical ># times ULN 
- `flname`: character string to assist with the naming convention of the columns 

### Relevant Output

Final returned dataset should be input dataset + N columns where N is defined as length(crit_seq) + 1, for example:

`derive_lab_fl(data = adlb, param = "AST", crit_seq = c(3,5,10), flname = "CRITAST")` should generate 

adlb + 4 more columns these 4 columns named: CRITAST_0_3, CRITAST_3_5, CRITAST_5_10, CRITAST_10_Inf 
where if AVAL was 40 and the ULN was 10, then this aval belongs in the 3-5xULN category, so the column CRITAST_3_5 would be flagged "Y" and other 3 columns are blank.

### Reproducible Example/Pseudo Code

derive_lab_fl <- function(data, param, crit_seq,  flname){
  #assert data is labs dataframe
  #assert param is character vector
  #assert crit_seq is numeric vector
  #assert flname is character vector

  flag_dataset <- data %>% 
    filter(PARAMCD %in% param & is.na(DTYPE)) %>% 
    select(USUBJID, LBSEQ, PARAMCD, AVAL, ANRHI) %>% 
    mutate(flag = cut(ANRHI/AVAL, breaks = c(0,crit_seq,Inf)),
           flagval = ifelse(!is.na(flag), "Y", NA))%>% 
    pivot_wider(., names_from = flag, values_from = flagval) %>% 
    rename_with(., ~gsub(",", "", .), starts_with("(")) %>% 
    rename_with(., ~gsub("\\(", flname, .), starts_with("("))%>% 
    rename_with(., ~gsub("\\]", "", .), starts_with(flname))

 #left join back with original dataset
}

*no implementation of the direction portion yet*

**Comment by bms63** [comment]
@pharmaverse/admiral check this out!!  Looks exciting!!

**Comment by bundfussr** [comment]
I think we need to add a `by_vars` argument for the join.

Do we need more flexibility, e.g., relation to baseline instead of ULN?

The naming convention for the columns is problematic because in most cases it creates non ADaM compliant variable names (the name must be no longer than 8 characters in length and for flags the FL suffix should be used).

I wonder if we need a new function or if we could use existing ones. For example:
```
call_derivation(
  adlb,
  derivation = derive_var_merged_exist_fl,
  dataset_add = adlb,
  filter_add = PARAMCD == "AST" & is.na(DTYPE),
  by_vars = vars(USUBJID, ADT),
  variable_params = list(
    params(
      new_var = AST01FL,
      condition = AVAL/ANRLO < 3
    ),
    params(
      new_var = AST02FL,
      condition = 3 <= AVAL/ANRLO & AVAL/ANRLO < 5
    ),
    params(
      new_var = AST03FL,
      condition = 5 <= AVAL/ANRLO & AVAL/ANRLO < 10
    ),
    params(
      new_var = AST04FL,
      condition = 10 <= AVAL/ANRLO
    )
  )
)
```
The call is a bit longer but I think it is clearer (the condition on `DTYPE` and the handling of border cases (AVAL/ANRLO = 3) is visible) and the approach offers more flexibility.

**Comment by zdz2101** [comment]
I agree, I think I like this more actually to create the flags, just hadn't realized this was a way to do it. Perhaps instead of writing/designing new functions, this becomes more about a vignette on how to create these flags
