### ISSUE TITLE
General Issue: Drop names in if_else()

### ISSUE THREAD

**Issue by zdz2101** [pharmaverse/admiral#1641]
### Background Information

Per https://github.com/pharmaverse/admiral/pull/1638 , 

`if_else()` is being updated for the upcoming release of `dplyr` 1.1.0 scheduled for January 27th, 2023. 

To make `admiral` compatible, adopt the changes as mentioned in above PR. 

### Definition of Done

- Adopt changes per https://github.com/pharmaverse/admiral/pull/1638 
- Double check for impact in other functions
- Update `NEWS.md` for 0.9.1
- Update `DESCRIPTION` 
- Remember to follow [hot fix release strategy](https://pharmaverse.github.io/admiraldev/devel/articles/release_strategy.html#hot-fix-release)

**Comment by bms63** [comment]
We should also see if  `admiralroche`, `admiralonco` or `admiraloptha` will be impacted as well.  

@pharmaverse/admiral  hotfix incoming
