### ISSUE TITLE
Bug: derive_vars_dtm() produces unexpected results

### ISSUE THREAD

**Issue by mivanov5** [pharmaverse/admiral#1646]
### What happened?

derive_vars_dtm() didn't work properly for me in several cases.

- This code:
  derive_vars_dtm(
    dtc = AESTDTC,
    new_vars_prefix = "AST",
    highest_imputation = "Y",
    date_imputation = "first",    
    time_imputation = "last",
    flag_imputation = "both",
    min_dates = vars(TRTSDTM)
  )
doesn't set ASTDTF to Y when year is imputed.

- This code:
derive_vars_dtm(
    dtc = HOSTDTC,
    new_vars_prefix = "AST",
    highest_imputation = "Y",
    date_imputation = "first",    
    time_imputation = "first",
    flag_imputation = "both"
  )
when HOSTDTC is missing produces 0-01-01 as date.

- If possible, please check that all combinations date_imputation = "first"/"last" and time_imputation = "first"/"last" work correctly, unfortunately I don't have examples at hand, but as I remember not all of them worked properly. Probably fixing the issues above may solve this problem as well.

**Comment by bms63** [comment]
@mivanov5 Thank you for reporting this issue.   Could you make us some dummy data using tribble function from tibble package .  This will speed up someone picking up this issue to fix.  Let us know if you need help - most of our examples in our function documentation use tibble::tribble.

thank you again!

**Comment by mivanov5** [comment]
@bms63 Sure, I can produce dummy data. The examples above can be easily produced by the following code:

my_ae1 <- data.frame(
  AESTDTC = NA_character_,
  TRTSDTM = ymd_hms("2022-01-01 23:59:59")
) %>% mutate(AESTDTC = as.character(AESTDTC)) %>% 
  derive_vars_dtm(
    dtc = AESTDTC,
    new_vars_prefix = "AST",
    highest_imputation = "Y",
    date_imputation = "first",    
    time_imputation = "last",
    flag_imputation = "both",
    min_dates = vars(TRTSDTM)
  )   

my_ae2 <- data.frame(
  AESTDTC = NA_character_
) %>% mutate(AESTDTC = as.character(AESTDTC)) %>% 
  derive_vars_dtm(
    dtc = AESTDTC,
    new_vars_prefix = "AST",
    highest_imputation = "Y",
    date_imputation = "first",
    time_imputation = "first",
    flag_imputation = "both"
  ) 

my_ae1 corresponds to the first error and my_ae2 to the second.
Please tell if anything else is needed.

**Comment by bundfussr** [comment]
@bms63 , @thomas-neitmann , should we do a hotfix for this bug or should we fix it in the next regular release?

**Comment by rossfarrugia** [comment]
@bundfussr please can you raise this one at the dev team meet tomorrow so we can get a decision? seems warranting a hotfix from my perspective but i defer to Ben and Thomas to make the call

**Comment by thomas-neitmann** [comment]
In favor of a hotfix.

**Comment by bms63** [comment]
hotfix sounds good to me @zdz2101 or @sadchla-codes do you all have time to work on this?

**Comment by zdz2101** [comment]
> @bms63 Sure, I can produce dummy data. The examples above can be easily produced by the following code:
> 
> my_ae1 <- data.frame( AESTDTC = NA_character_, TRTSDTM = ymd_hms("2022-01-01 23:59:59") ) %>% mutate(AESTDTC = as.character(AESTDTC)) %>% derive_vars_dtm( dtc = AESTDTC, new_vars_prefix = "AST", highest_imputation = "Y", date_imputation = "first", time_imputation = "last", flag_imputation = "both", min_dates = vars(TRTSDTM) )
> 
> my_ae2 <- data.frame( AESTDTC = NA_character_ ) %>% mutate(AESTDTC = as.character(AESTDTC)) %>% derive_vars_dtm( dtc = AESTDTC, new_vars_prefix = "AST", highest_imputation = "Y", date_imputation = "first", time_imputation = "first", flag_imputation = "both" )
> 
> my_ae1 corresponds to the first error and my_ae2 to the second. Please tell if anything else is needed.

@mivanov5 Are you only experiencing these bugs when working with NAs?

**Comment by bms63** [comment]
> @zdz2101 regarding cases with bugs, I didn't have much data and hence didn't do extensive testing of this macro. These bugs are the only ones that I caught and wrote down, but probably there are more bugs which I just forgot to write down, it is hard to understand now what they were.

Umm...there were other bugs?

I was just proposing you write some simple test cases for our unit tests for the fix @zdz2101 is implementing  We like to get our community members involved and I find that writing unit tests to be a great way to contribute.  No problem if this is not of interest to you.
