### ISSUE TITLE
Feature Request:  Update `compute_duration` function to have "min" and "sec" for output units

### ISSUE THREAD

**Issue by millerg23** [pharmaverse/admiral#1647]
### Feature Idea

Roche uses controlled terminology for any derivation with unit of duration, this controlled terminology is the same as used by SDTM variables.
For "seconds" the controlled terminology is "sec" and for "minutes" its "min".

### Relevant Input

For `compute_duration` for units of minutes the function outputs "minutes" and for seconds the function outputs "seconds"

### Relevant Output

For `compute_duration` for units of minutes the function should output "min" and for seconds the function should output "sec"

**Comment by millerg23** [comment]
@esimms999-gsk @bms63 can you check if GSK uses controlled terminology for ADaM derivations related to units of duration. If not can you check what controlled terminology is used for SDTM variables relating to unit of duration?

**Comment by bms63** [comment]
I've only seen "Study Specific" in our derivations for units of duration.  Let's go with the standard practice and make this enhancement.  We can always fix it internally at GSK if I am in wrong here.

I think this would be a good first issue as well.

**Comment by thomas-neitmann** [comment]
@imaheshdivakaran We'd like to include this in our release next month. Can you get this done by then?

**Comment by bms63** [comment]
Hi @pharmaverse/admiral  Can anyone pick up this issue please?

**Comment by jeffreyad** [comment]
It looked a similar change was needed for `derive_vars_duration()` to be consistent, so I updated that as well.  Based on previous discussion pharmaverse/admiraldev#122 it looks like `valid_time_units()` would not be updated since only the `out_unit` is affected.
