### ISSUE TITLE
General Issue: Do you plan on incorporating ADPPK functionality?

### ISSUE THREAD

**Issue by andersone1** [pharmaverse/admiral#1657]
### Background Information

There is a new ADaM dataset specification coming out soon for Population Pharmacokinetic (popPK) Analysis:

https://wiki.cdisc.org/display/ADPPK/

Do you expect (at this time) to be adding any specific functionality around this domain (either now, or in the future)?

**Comment by bms63** [comment]
Thanks @andersone1 for bringing this up?  Are there any variables that our current functions won't be able to cover in the ADPPK dataset?  

I imagine we can make a new template - adppk to help showcase our functions in building this dataset.  Perhaps our resident PK specialist can also chime in?  @jeffreyad  @RealSlimMahdi

**Comment by jeffreyad** [comment]
Thanks for the suggestion!  We are definitely developing functionality that will be helpful for `ADPPK` development.  In the next release we plan to include additional features for `ADNCA` that will also be useful for `ADPPK`.  

This could include an additional template or vignette for `ADPPK` development.

**Comment by andersone1** [comment]
@bms63 and @jeffreyad thank you both for responding to this so quickly. That all sounds good. I will continue to check in on the progress.

**Comment by jeffreyad** [comment]
Thanks @andersone1, I created a new tag ADPPK to track issues related to creating POPPK analysis data.

**Comment by jeffreyad** [comment]
@andersone1 we are closing this issue since #1772 is in progress.  The PK working group will meet Thursdays at 10:30 Eastern.  There is more information on Pharmaverse Slack Channel
