### ISSUE TITLE
Feature Request: Add function to derive SITEGR1

### ISSUE THREAD

**Issue by DeclanHodges** [pharmaverse/admiral#1659]
### Feature Idea

As per the [ADSL vignette](https://pharmaverse.github.io/admiral/articles/adsl.html#groupings), users are required to created their own pooled site group function to derive the variable SITEGR1. However, based off my experience of creating ADSL on the Admiral Pilot 3 study, the derivation here is more complex than the other grouping variable examples in the vignette, so I think it could be useful to create a function to derive this variable.

My main reservations with creating this function, is whether the difference in site pooling algorithms is too broad across studies, so I would appreciate further input here. Below is an example of a site pooling algorithm, used to derive SITEGR1 in Admiral Pilot 3:
![image](https://user-images.githubusercontent.com/113363343/210552791-e4a46ad4-5a86-4e1a-9f5b-37f50c87e868.png)
This study pools smaller sites together by the fewest number of subjects, but from discussions with other study leads, some studies instead pool smaller sites by geographical location.

### Reproducible Example/Pseudo Code

_Below is example code that I wrote to demonstrate how SITEGR1 could be derived using the algorithm screenshotted above:_

library(dplyr)
library(stringr)
library(admiral)

adsl <- admiral_adsl

format_sitegr1 <- function(dataset) {
  
  sites_to_pool <- adsl %>% 
    filter(str_to_upper(ACTARMCD) != "SCRNFAIL") %>% 
    group_by(SITEID) %>% 
    summarise(pop = n()) %>% 
    ungroup() %>% 
    arrange(pop) %>% 
    mutate(cumpop = cumsum(pop)) %>% 
    filter(pop < 3 | lag(cumpop, 1) < 3) %>% 
    pull(SITEID)
  
  adsl <- adsl %>% 
    mutate(SITEGR1 = case_when(
      SITEID %in% sites_to_pool ~ "900",
      TRUE ~ SITEID
    ))
  
}

adsl_sitegr1 <- adsl %>% 
  format_sitegr1()`

**Comment by bundfussr** [comment]
SITEGRy is a standard CDISC variable. However, the variable can be used for any grouping of sites. The grouping stated above seems quite specific to me. Thus I think admiral core is not the right place for implementing it.

**Comment by rossfarrugia** [comment]
yes i agree. @bms63 are you OK with us closing this issue and moving it more to GSK specific admiral implementation?
