### ISSUE TITLE
General Issue: Follow Deprecate Strategy for function from 0.7, 0.8, 0.9

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1666]
### Background Information

We missed deprecating functions from our last release.  Just putting this as a placeholder so we don't forget!!

### Definition of Done

Functions from 0.7 and 0.8 that were deprecated are removed.

Functions deprecated with warning in 0.9 are set to error.

https://pharmaverse.github.io/admiraldev/devel/articles/programming_strategy.html#deprecation

**Comment by bms63** [comment]
Starting to think that this should be an auto-generated issue when a release is done so we keep line of sight.

**Comment by bundfussr** [comment]
@bms63 , it seems we miss this frequently. I would suggest implementing https://github.com/pharmaverse/admiraldev/issues/36.

Maybe @zdz2101 is interested in implementing https://github.com/pharmaverse/admiraldev/issues/36.

**Comment by zdz2101** [comment]
I'll have a look!

**Comment by sadchla-codes** [comment]
Already addressing this in issue #1723
