### ISSUE TITLE
General Issue: admiral turned 2 on January 25th 2023

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1670]
### Background Information

![image](https://user-images.githubusercontent.com/10111024/212226390-03be331f-4327-4cfc-b6a2-17e8661fa13f.png)

What should we do!?!

### Definition of Done

@pharmaverse/admiral

**Comment by bms63** [comment]
That is the first commit when I run `git log --reverse`

**Comment by thomas-neitmann** [comment]
Wer have to bake some 🍰 🥳

**Comment by bms63** [comment]
@pharmaverse/admiral Two years old!

**Comment by sadchla-codes** [comment]
I like the cake idea!!
