### ISSUE TITLE
Feature Request:  Enable Renaming in `by_vars` Parameter

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#1680]
### Feature Idea

For all functions (where it makes sense) the `by_vars` argument should allow renaming like the dplyr `*_join()` functions and `derive_vars_joined()`.

### Reproducible Example/Pseudo Code

```
adtr <- derive_vars_merged(
  tr,
  dataset_add = tu,
  new_vars = vars(TULOC),
  by_vars = vars (STUDYID, USUBID, TRLNKID = TULINKID)
)
```

**Comment by bms63** [comment]
@gg106046 can you finish this for `v0.10` release?  Release is planned for March 5th - ideally one week before but there is some wiggle room.

**Comment by gg106046** [comment]
@bms63 I should be able to do this by end of Feb.

**Comment by gg106046** [comment]
> @gg106046 can you finish this for `v0.10` release? Release is planned for March 5th - ideally one week before but there is some wiggle room.

@bms63 I should be able to do this by end of Feb.

**Comment by gg106046** [comment]
Identified the following functions that involve merging of 2 datasets with the argument `by_vars`:  `derive_var_last_dose_amt`, `derive_var_last_dose_date`, `derive_var_last_dose_grp`, `derive_var_merged_cat`, `derive_var_merged_character`, `derive_var_merged_exist_flag`, `derive_var_merged_summary`, `derive_vars_joined`, `derive_vars_joined`, `derive_vars_merged`, `derive_vars_merged_lookup`, `derive_vars_transposed`, `derive_locf_records` . Just putting it here for reference.
