### ISSUE TITLE
Bug: Dataframes displayed in vignettes are extending into the table of contents

### ISSUE THREAD

**Issue by esimms999-gsk** [pharmaverse/admiral#1693]
### What happened?

I did pkgdown::build_site(lazy = TRUE, override = list(destination = "~/docs")) and then looked at User Guides -> Creating an OCCDS ADaM. Seeing this:
![image](https://user-images.githubusercontent.com/85294667/215193549-6dc35bb8-be7a-4528-a3a7-8975a18ac43a.png)

@bms63 confirms he has seen this before.

**Comment by esimms999-gsk** [comment]
Note: I am also seeing this on our production site at https://pharmaverse.github.io/admiral/articles/occds.html

![image](https://user-images.githubusercontent.com/85294667/215205602-824de7ec-8c6f-4efc-8d2a-6eb53d78b75f.png)

**Comment by bundfussr** [comment]
Hi @esimms999-gsk , this should have been fixed by https://github.com/pharmaverse/admiraldev/issues/197. I.e., in production it is still wrong but if you build the site with the devel version of admiraldev, it should work.

**Comment by esimms999-gsk** [comment]
@bundfussr Yes! I made use of the devel version of admiraldev and it looks good. Thanks ... closing this issue.

**Comment by esimms999-gsk** [comment]
admiraldev devel has already fixed this.
