### ISSUE TITLE
Feature Request: Add `keep_source_vars` parameter

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#1697]
### Feature Idea

Functions which add observations to a dataset and the new observations are selected (and not summarized) from a dataset should provide the `keep_source_vars` argument. This argument allows to specify which variables from the selected observations should be kept, e.g., `ADT`, `AVISIT`, `RSDTC`, ... It should accept tidyselect expressions. Then `keep_source_vars= everything()` could be specified to keep all variables.

The default of the parameter should be `everything()`.

An example should be provided how to select everything except some specific variables.

*Affected functions*: `derive_extreme_records()`, `derive_param_exist_flag()`

### Reproducible Example/Pseudo Code

```
derive_param_extreme_event(
  adrs,
  dataset_adsl = adsl,
  dataset_source = adrs,
  filter_source = PARAMCD == "OVR" & AVALC == "PD",
  order = vars(ADT),
  new_var = AVALC,
  keep_source_vars = vars(RSDTC, VISIT, VISITNUM),
  true_value = "Y",
  false_value = "N",
  mode = "first",
  set_values_to = vars(
    PARAMCD = "PD",
    PARAM = "Disease Progression",
    ANL01FL = "Y",
    ADT = ADT
  )
)
```

**Comment by gg106046** [comment]
This update was made only to `derive_extreme_records()` since the output of `derive_param_exist_flag()` are the new records (which shows existence of a record) that are not merged with the original dataset. And 'derive_param_extreme_event()` is deprecated.

**Comment by bundfussr** [comment]
I have implemented `keep_vars_source` for `derive_extreme_event()` in https://github.com/pharmaverse/admiral/issues/1960.

**Comment by bms63** [comment]
@gg106046 can you complete this for this release?  we want to use `keep_source_vars`.

@bundfussr `keep_source_vars` is our convention now.

**Comment by gg106046** [comment]
> 

@bms63 Yes, on it!

**Comment by bms63** [comment]
Thanks for working on this @gg106046 !!

`derive_var_merged_exist_flag()` is located in the `R/derive_merged.R` file.

![image](https://github.com/pharmaverse/admiral/assets/10111024/0c3610b7-790f-4a85-bd4b-d12a4f177c17)

**Comment by gg106046** [comment]
> Thanks for working on this @gg106046 !!
> 
> `derive_var_merged_exist_flag()` is located in the `R/derive_merged.R` file.
> 
> ![image](https://user-images.githubusercontent.com/10111024/262371899-0c3610b7-790f-4a85-bd4b-d12a4f177c17.png)

Ah okay. Thanks for showing me, will work on this!
