### ISSUE TITLE
Documentation: Improve Documentation of `derivation` in `restrict_derivation()`

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#1698]
### Please select a category the issue is focused on?

Function Documentation

### Let us know where something needs a refresh or put your idea here!

The documentation of the `derivation` argument in `restrict_derivation()` should provide more details on what is expected by the argument (a function which provides the `dataset` argument and all arguments specified in the `param` objects specified for `args`). It should be mentioned that `derivation = mutate` is not allowed.

**Comment by bms63** [comment]
`slice_derivation` could also use some improvement as well.
