### ISSUE TITLE
Man page of `reexports.R` is causing an issue due to the way rlang points to exprs() documentation

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1706]
@galachad , @thomas-neitmann , @bms63 , @cicdguy , the man page of `reexports.R` is causing an issue. It contains the line
```
\item{rlang}{\code{\link[rlang:defusing-advanced]{exprs}}}
```
which causes the R-CMD 4.0 check to fail.
I can fix it by replacing the line with
```
\item{rlang}{\code{\link[rlang]{exprs}}}
```
but then the Man Pages check fails.

Any ideas?

_Originally posted by @bundfussr in https://github.com/pharmaverse/admiral/issues/1688#issuecomment-1405089335_

**Comment by zdz2101** [comment]
Per https://github.com/pharmaverse/admiral/pull/1688#issuecomment-1413710785 , should we also add a section in our reference page to readily access the re-exported functions? Scanning across a variety of tidyverse repos like dplyr, tidyr, purrr. They all handle it a bit differently.

**Comment by zdz2101** [comment]
![image](https://user-images.githubusercontent.com/43018762/216367106-9b13b815-6767-4f41-96be-17700e04e520.png)

Would doing something like this^ for: `exprs()` `desc()` and `%>%` while also modifying the _pkgdown.yml to add a reexports section do the trick?

**Comment by bundfussr** [comment]
I have implemented it in https://github.com/pharmaverse/admiral/pull/1688
