### ISSUE TITLE
General Issue: Dirty Data and admiral functions

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1708]
### Background Information

A lot of our unit tests are built around very clean and simple test data.  I think most of the data is created using the `tibble::tribble()` function as it is small and easy for us to test out arguments and common errors/warnings that we are trying to pre-empt with our users.  The data gets less clean when we look at partial date test data and have a lot of test code and functions built around dealing with those issues...but that is it.

I've noticed a steady uptick of users with **Dirty Data** or incomplete data finding issues with our functions (this is a sample size of 3 - but noticeable to me).  

I was wondering - should we somehow try to build in some sort of testing that could explore what happens when our functions encounter data with a lot of issues.  Dates with weird characters in it, bad encoding, different languages, sparse data...the list could go on.

Perhaps there is a way to dirty up the CIDSC Pilot Data and run it through our templates and/or functions to really stress test our code-base and see if anything of interest comes of this.  No clue if this is a good way to pursue this sort of thing.

If this is of interest, definitely have to plan this way better than a back of napkin idea that I have going on here.  

What do you think @pharmaverse/admiral ?   

### Definition of Done

Nothing to be done yet until we decide if this is something for us to pursue.

**Comment by millerg23** [comment]
Sounds like most of the issues could be handled by unit testing, do you agree?. Any time we get an issue with a particular function, we should update the unit tests for that function. I think most of our unit tests are based on "nice" data, so its expected that they won't cover everything, but we should continually update them, when we find a gap.

**Comment by bundfussr** [comment]
I agree with Gordon.

Adding dirty data scenarios without a specific use case seems endless to me.

**Comment by thomas-neitmann** [comment]
While I understand the frustration of our functions not working with "dirty" data I think that's a rabbit hole we should **not** go into. I much rather have people run their SDTM to a package like [pharmaverse/sdtm](https://github.com/pharmaverse/sdtmchecks) to spot issues before they attempt to transform it to ADaM using admiral.

**Comment by bms63** [comment]
Roger roger.  Thanks for reining me back in - end of the day madness.
