### ISSUE TITLE
Documentation:  Use study data examples in `convert_blanks_to_na()`

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1709]
### Please select a category the issue is focused on?

Function Documentation

### Let us know where something needs a refresh or put your idea here!

I think we should use a simple study data examples for this function to align to our other function examples in `admiral`.  

![image](https://user-images.githubusercontent.com/10111024/216215617-1119a3f8-0d71-4be1-9bd1-840edf7e14c7.png)

**Comment by danleibovitz** [comment]
I think this issue can be tackled simultaneously with issue #1713. @bms63 or @thomas-neitmann, could you assign this to me?

**Comment by bms63** [comment]
Thanks!

**Comment by bms63** [comment]
Hi @danleibovitz are you able to finish this?
