### ISSUE TITLE
Implement read_gsk_query_data()

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#171]
The function should read the query definition from the GSK database and return the input dataset for the `derive_query_vars()` function.

**Comment by bundfussr** [comment]
https://github.com/Roche-GSK/admiral/issues/606 should help implementing this issue.

**Comment by koegerr** [comment]
@esimms999 can we close this?

**Comment by esimms999-gsk** [comment]
@koegerr Yes, I will close this (#171 - read_gsk_query_data). This GSK-specific functionality will be developed in the internal GSK 
repo.
