### ISSUE TITLE
General Issue: Review vignettes and templates for deprecated functions

### ISSUE THREAD

**Issue by sadchla-codes** [pharmaverse/admiral#1712]
### Background Information

Go through the templates and vignettes to ensure that all of the functions and/or parameters that were deprecated are following the deprecation process outlined in the programming strategy (screenshot below)
![image](https://user-images.githubusercontent.com/112789549/216503108-250d14e1-991c-4f53-a699-ace16a1591e0.png)

### Definition of Done

- [x] Functions and/or parameters with **deprecated_stop()** from previous release are no longer in any vignettes or templates
- [x] Vignette sections with the deprecated function and/or parameters are updated with their respective replacements

Actions required for specific functions
- [x] Following functions need to **throw an error** for **release Q1-2023** admiral version 0.10.0 because they were deprecated in version 0.8.0 with phase 1, but haven't gone through Phase 2 which is to throw an error **OR** the deprecation process started in admiral version 0.9.0
`derive_vars_merged_dt()`
`derive_vars_merged_dtm()`
`derive_var_agegr_ema()`
`derive_var_agegr_fda()`
`derive_param_first_event()`
`derive_derived_param()`

- [x] Remove the following parameters
[smq_select()](https://pharmaverse.github.io/admiral/reference/smq_select.html) and [sdg_select()](https://pharmaverse.github.io/admiral/reference/sdg_select.html) function
`meddra_version`, `whodd_version`, `get_smq_fun` and `get_sdg_fun` from the [create_query_data()](https://pharmaverse.github.io/admiral/reference/create_query_data.html) function
`date_imputation`, `time_imputation` and `preserve` from `data_source()`

- [x] Following programs and their associated test in /test-deprecations.R need to be **removed** since they were deprecated with **Phase 2** in admiral version 0.8.0 or early
[`R/derive_var_ady.R` ](https://github.com/pharmaverse/admiral/blob/main/R/derive_var_ady.R)
[`R/derive_var_aendy.R`](https://github.com/pharmaverse/admiral/blob/main/R/derive_var_aendy.R)
[`R/derive_var_astdy.R`](https://github.com/pharmaverse/admiral/blob/main/R/derive_var_astdy.R)
[`R/derive_var_atirel.R`](https://github.com/pharmaverse/admiral/blob/main/R/derive_var_atirel.R)

**Comment by bms63** [comment]
Many thanks @sadchla-codes for putting this together.  @pharmaverse/admiral are there any others missing from this list?

**Comment by sadchla-codes** [comment]
@bms63 I went through the changelog and search the vignettes/templates to generate the list above. I'm already deprecating some functions, I'll update the issue if i found other function/parameters that I missed.
