### ISSUE TITLE
Documentation: Call `convert_blanks_to_na()` in all vignettes

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#1713]
### Please select a category the issue is focused on?

User Guides

### Let us know where something needs a refresh or put your idea here!

Call `convert_blanks_to_na()` in all vignettes

**Comment by danleibovitz** [comment]
If I understand correctly, the idea here is to call `convert_blanks_to_na()` in all vignettes in the attaching/cleaning data sequence (some vignettes have this already, other don't). @bundfussr or @thomas-neitmann, could you assign this to me?

**Comment by thomas-neitmann** [comment]
Thanks for taking this in @danleibovitz. Just assigned you.
