### ISSUE TITLE
Documentation: Add reference to wrapped function

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#1726]
### Please select a category the issue is focused on?

Function Documentation

### Let us know where something needs a refresh or put your idea here!

For all wrapper functions, i.e., functions which are just calling a single (more general) admiral function like `derive_param_bmi()`, a reference to the wrapped function should be added to the short description. E.g. for `derive_param_bmi()` a reference to `derive_param_computed()` should be added.

**Comment by bms63** [comment]
This is a good one to knock out!  can anyone take this on? @pharmaverse/admiral

**Comment by bms63** [comment]
I would prefer it go in the highlighted section so the user is immediately alerted to this being a wrapper function.  I believe the `@seealso` tag will push it down to section above Examples.

![image](https://github.com/pharmaverse/admiral/assets/10111024/b5e511ed-76e0-4a5f-b31a-6f423db5c4a7)

**Comment by sophie-gem** [comment]
Does anyone have an opinion here?

Would the function `convert_date_to_dtm` be called a wrapper function for `convert_dtc_to_dtm` (screenshot below) or not as there is an alternative step included? (I can make a case for both, so wanted to check).

<img width="287" alt="image" src="https://github.com/pharmaverse/admiral/assets/90790226/b7c045a1-edce-40cf-95f7-445b22850e35">

Many thanks!

**Comment by StefanThoma** [comment]
I would consider this a wrapper function.
