### ISSUE TITLE
Feature Request: Implement `derive_var_merged_exist_flag()` for multiple sources

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#1728]
### Feature Idea

Implement a new function similar to [`derive_var_merged_exist_flag()`](https://pharmaverse.github.io/admiral/cran-release/reference/derive_var_merged_exist_flag.html) but considering multiple source datasets (for example for the ADJ, ADJAE, and ADJME parameter in ADEX) should be implemented.
The function should use source objects and the `source_datasets` argument like in `derive_var_dthcaus()`.

**Comment by bms63** [comment]
Hey @bundfussr I was going to start asking around for someone to work on this issue?  

I see you are not at backlog meeting next week.  Maybe we could spend some time on Wednesday meeting giving more context to this issue?

I think the first question I have:  is this intended to be a new function or an enhancement to `derive_var_merged_exist_flag()` the language is confusing to me in the issue.

I'm leaning towards a new function as current function has 9 arguments and is easy to understand from my perspective - adding in more args and documentation might be very confusing for users

**Comment by bundfussr** [comment]
> is this intended to be a new function or an enhancement to `derive_var_merged_exist_flag()`

Definitely a new function.

**Comment by bms63** [comment]
Proposal for new function name: `derive_var_merged_ms_exist_flag` where `ms` is multiple sources?

**Comment by bundfussr** [comment]
> Proposal for new function name: `derive_var_merged_ms_exist_flag` where `ms` is multiple sources?

I am not sure. I think we need to discuss the naming of the functions in general. I have made a proposal in the [admiral Functions review](https://phuseaccount.sharepoint.com/:w:/r/sites/Pharmaverse-admiral/Shared%20Documents/Development%20Team%20Working%20Docs/admiral%20Functions%20Overview.docx?d=w64c31636c93c47dda066585be7a8c42b&csf=1&web=1&e=uyQ7Bv). There I used "multi" for multiple sources. Another option is "msrc".
