### ISSUE TITLE
Documentation:  Update link to {admiraldev} version in home page of {admiral} & {admiraldev} website

### ISSUE THREAD

**Issue by PoojaKumari05** [pharmaverse/admiral#1740]
### Please select a category the issue is focused on?

Other

### Let us know where something needs a refresh or put your idea here!

![image](https://user-images.githubusercontent.com/90273880/218101878-619e5f7c-daae-4ce3-a4a2-811085c19ca6.png)
The links to {admiraldev} in the home page of {admiral} website points to version 0.2.0
![image](https://user-images.githubusercontent.com/90273880/218102347-7e79c3b2-187f-4f5a-ace7-a7d85d4fb7ac.png)

ACTION Needed: Update the link to reference latest version from the repository i.e. version 0.3.0
![image](https://user-images.githubusercontent.com/90273880/218102702-86601634-7a1f-4429-b2c0-3ea67d6c031b.png)

**Comment by bms63** [comment]
This has been fixed with the latest release.
