### ISSUE TITLE
Bug: Can't run example from help page of `derive_vars_merged()`

### ISSUE THREAD

**Issue by ramiromagno** [pharmaverse/admiral#1751]
### What happened?

I installed `{admiral}` version 0.9.1 from CRAN with:

```R
install.packages("admiral")
```

Then I was trying to run the first code example included in the help page of `derive_vars_merged()` but it failed because of the missing dependency `{admiral.test}`.

### Session Information

```
R version 4.2.2 (2022-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Arch Linux

Matrix products: default
BLAS:   /usr/lib/libopenblasp-r0.3.21.so
LAPACK: /usr/lib/liblapack.so.3.11.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.2.2 tools_4.2.2    renv_0.16.0   
```

### Reproducible Example

So the code I ran was:
(I've added `library(admiral)` to the reprex)

``` r
library(admiral)
library(admiral.test)
#> Error in library(admiral.test): there is no package called 'admiral.test'
library(dplyr, warn.conflicts = FALSE)
data("admiral_vs")
#> Warning in data("admiral_vs"): data set 'admiral_vs' not found
data("admiral_dm")
#> Warning in data("admiral_dm"): data set 'admiral_dm' not found

# Merging all dm variables to vs
derive_vars_merged(
  admiral_vs,
  dataset_add = select(admiral_dm, -DOMAIN),
  by_vars = vars(STUDYID, USUBJID)
) %>%
  select(STUDYID, USUBJID, VSTESTCD, VISIT, VSTPT, VSSTRESN, AGE, AGEU)
#> Error in is.data.frame(arg): object 'admiral_vs' not found
```

If `{admiral.test}` is a hard-dependency, then it ought to be listed in Imports. But it seems to be in Suggests only. So I don't understand how these examples even passed the CRAN checks...

I understand that you mention in the README that if one goes with installing the dev version of `{admiral}`, then `{admiral.test}` and `{admiraldev}` are required dependencies and should be installed too. But again, only `{admiraldev}` is listed in Imports.

**Comment by bms63** [comment]
Having `admital.test` in the Suggest is permitted by CRAN checks - https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Package-Dependencies.  

![image](https://user-images.githubusercontent.com/10111024/219243259-39e8c653-d7c8-4b09-a82d-5385b96ff4a5.png)

Perhaps we can be more transparent to new users about needing to install `admiral.test`, but I would expect intermediate and veterans to know to just install it.

I think we recommend installing admiral.test in the dev installs is because we are assuming most people doing that are developers and want our test data to work on examples, vignettes, ettc.

We have discussed this a bit in meetings about having `admiral.test` as an Import, but it is already growing in size with new ophtha specific datasets and soon vaccine datasets.  There is hesitancy to have another large dependency within admiral - actually a quite large package already.

**Comment by ramiromagno** [comment]
Okay, I understand. But then it would be best to wrap those examples that do depend on `{admiral.test}` in:

```
if(requireNamespace("admiral.test", quietly = TRUE)) {
 # run code dependent on `{admiral.test}`
} else {
## do nothing, or something else
}
```

Because as a user, usually, one expects all examples to run after installing a package from CRAN.

**Comment by bms63** [comment]
What do you think @pharmaverse/admiral?

**Comment by thomas-neitmann** [comment]
Adding the check wheter or not {admiral.test} is installed in every example is a lot of bloat. Either we leave as it (which I think is not too bad to be honest because the error is clear: install the missing package) or we add a message inside `.onAttach()` to check whether or not {admiral.test} is available and suggest to install it otherwise if you want to run the examples. This should only happy after the first time `library(admiral)` is called after installing it. So something like.

```r
library(admiral)
#> It looks like you are using {admiral} for the very first time.
#> Please note that in order to run examples you have to install the {admiral.test}
#> package by running `install.packages("admiral.test")`.
```

**Comment by sophie-gem** [comment]
I like the idea of adding a message to `.onAttach()` - as that would make it clearer for those who are just starting out with both R and {admiral}. 

(Didn't even realise that was a thing...you learn an awful lot by contributing to open-source! 🤩)

**Comment by bundfussr** [comment]
I think we should not use admiral.test datasets in the examples of the function documentation. Instead we should create small example datasets by calling `tribble()`.
- Then the input data is visible in the documentation.
- The data can be tailored to the functionality which should be demonstrated by the example.
- The example run faster. (The `derive_vars_merged()` example uses about 30000 observations! Shame on me, I have written it.)
- The admiral.test package is not required.

There are not so many files to update. I identified 15 and some are deprecated or may be deprecated.

**Comment by thomas-neitmann** [comment]
In favor of @bundfussr suggestion. Didn't relaize it's only so few functions using these datasets for their examples.

**Comment by thomas-neitmann** [comment]
The vignettes are already rendered when the package is build so no need to update anything there. Even if a user doesn't have admiral.test installed this would ot cause any issues when reading the vignettes.

**Comment by bms63** [comment]
> The vignettes are already rendered when the package is build so no need to update anything there. Even if a user doesn't have admiral.test installed this would ot cause any issues when reading the vignettes.

SO I meant the templates

**Comment by bundfussr** [comment]
> > The vignettes are already rendered when the package is build so no need to update anything there. Even if a user doesn't have admiral.test installed this would ot cause any issues when reading the vignettes.
> 
> Sorry I meant the templates

I think usually the users replace the admiral.test part of the template by code for reading in their data. Thus they do not need admiral.test.

**Comment by sadchla-codes** [comment]
Should I take from this discussion and create a new issue to do identify all of the programs with examples using admiral.test data and replace them by creating the needed data using `tribble()` ?

**Comment by zdz2101** [comment]
Sounds like it might be two separate tasks:

- swap `admiral.test` examples with `tribble()`
- For the `use_ad_template()` templates, it would sure be helpful to add @thomas-neitmann 's `.onAttach()` suggestion, especially if it's for the first time users

**Comment by bundfussr** [comment]
The affected files are:
```
admiral_options.R:#' library(admiral.test)
call_derivation.R:#' library(admiral.test)
call_derivation.R:#' library(admiral.test)
create_query_data.R:#' library(admiral.test)
derive_merged.R:#' library(admiral.test)
derive_merged.R:#' library(admiral.test)
derive_merged.R:#' library(admiral.test)
derive_merged.R:#' library(admiral.test)
derive_merged.R:#' library(admiral.test)
derive_var_anrind.R:#' library(admiral.test)
derive_var_disposition_status.R:#' library(admiral.test)
derive_var_disposition_status.R:#' library(admiral.test)
derive_var_extreme_date.R:#' library(admiral.test)
derive_var_extreme_date.R:#' library(admiral.test)
derive_var_extreme_flag.R:#' library(admiral.test)
derive_var_last_dose_amt.R:#' library(admiral.test)
derive_var_last_dose_date.R:#' library(admiral.test)
derive_var_last_dose_grp.R:#' library(admiral.test)
derive_var_obs_number.R:#' library(admiral.test)
derive_vars_disposition_reason.R:#' library(admiral.test)
derive_vars_disposition_reason.R:#' library(admiral.test)
derive_vars_last_dose.R:#' library(admiral.test)
filter_extreme.R:#' library(admiral.test)
```

**Comment by bundfussr** [comment]
> * For the `use_ad_template()` templates, it would sure be helpful to add @thomas-neitmann 's `.onAttach()` suggestion, especially if it's for the first time users

What should be the message from `.onAttach()`? As admiral.test will not be required anymore to run examples, we should change it. I am not sure how we could phrase it such that it helps users who are using an admiral template but does not confuse users who just load admiral.

**Comment by sadchla-codes** [comment]
Thanks @bundfussr, for now I can create an issue for the swapping of `admiral.test` portion and include a screenshot of the files that you shared. I am deprecating some functions that used to have examples using `admiral.test` so the list will already be reduced.

**Comment by bms63** [comment]
Shall we just have a short message/comment in the templates to make sure you have `admiral.test` installed first?  Perhaps the `.onAttach` is overkill.

**Comment by zdz2101** [comment]
> Shall we just have a short message/comment in the templates to make sure you have `admiral.test` installed first? Perhaps the `.onAttach` is overkill.

This seems to be a much simpler solution

**Comment by sadchla-codes** [comment]
@bundfussr @bms63 Should we also replace `admiral.test` calls in tests programs for the custom data generated with `tribble()`?

**Comment by bms63** [comment]
> @bundfussr @bms63 Should we also replace `admiral.test` calls in tests programs with the custom data generated with `tribble()`?

I don't think we need to do that as users would never run our tests.

**Comment by bms63** [comment]
Closing as this will be addressed with another issue, https://github.com/pharmaverse/admiral/issues/1752,  where we remove all `admiral.test` calls in function documentation in favor of small tribble examples.  

Thanks @ramiromagno for bringing this to our attention!
