### ISSUE TITLE
General Issue: Replacing admiral.test calls in the function examples

### ISSUE THREAD

**Issue by sadchla-codes** [pharmaverse/admiral#1752]
### Background Information

There are several functions that using `admiral.test` data in the function examples, these data calls need to be replace with data created calling `tribble()`. A list of the files with the `library(admiral.test)` call is below. Please note the list below is a living list since some functions are being deprecated and `library(admiral.test)` might have already being removed (see issues #1681, #1682 #1683  #1723 for the functions/files where the example section will be removed for the relevant files from the list below and issue #1751 for discussion surrounding this current issue )

![image](https://user-images.githubusercontent.com/112789549/219437156-ca85f7d1-73f5-4443-b94a-e63948568241.png)

### Definition of Done

- [ ] Prioritize fixing this - https://github.com/pharmaverse/admiral/issues/1780
- [ ] All `library(admiral.test)`  have been removed from the example sections for the aforementioned files
- [ ] Example data in the example sections are created by calling  `tribble()`
- [ ] NEWS.md  is updated

**Comment by bms63** [comment]
Just FYI @sadchla-codes  `create_single_dose_dataset()`  example needs data from admiral.test.  The original vignette #1610 was converted to just an example.  So this one is going to violate that rule

**Comment by sadchla-codes** [comment]
> Just FYI @sadchla-codes `create_single_dose_dataset()` example needs data from admiral.test. The original vignette #1610 was converted to just an example. So this one is going to violate that rule

Thanks @bms63 , I added that exception in the **Definition of done** section part of the issue.

**Comment by rossfarrugia** [comment]
Hey all, I added good first issue label, but shout if you disagree.

**Comment by StefanThoma** [comment]
In `create_query_data.R` `admiral.test` is used to access the `get_terms()` function as a stand-in for company specific functions. 

I believe that usage of `admiral.test`  in this example is justified. 
However, as the `get_terms()` function is accessed via `:::` the library call is somewhat redundant. 
Should we leave it in? 
Or am I missing something entirely? 

@sadchla-codes please advise.

**Comment by sadchla-codes** [comment]
@StefanThoma the goal of removing `admiral.test` library calls from the example section is to prevent a function from failing if a user doesn't have `{admiral.test}` installed. In this case, my opinion is that we might have to create a different type of example for the `create_query_data()` function. 

@bms63, and @bundfussr please correct me if I'm misinterpreting this.

**Comment by bundfussr** [comment]
I agree that we can remove the `library()` call.

I think the primary reason for replacing admiral.test calls was that they sometimes cause the R-CMD checks to fail because they take too long to run. We should not have this issue when calling `admiral.test:::get_terms()`.

I am not sure if we should update the examples such that `admiral.test:::get_terms()` is not used. We would need to create a similar function within the example then. This could be confusing.
