### ISSUE TITLE
Feature Request:  Implement `derive_extreme_event()`

### ISSUE THREAD

**Issue by kaz462** [pharmaverse/admiral#1755]
### Feature Idea

```r
derive_extreme_event(
  dataset,
  by_vars = NULL,
  events,
  order,
  mode,
  set_values_to
)
```
New admiral function to derive best/worst answer from `ADQS` workflow discussion https://github.com/pharmaverse/admiral/issues/1279

what do you think of the function name? @bundfussr @bms63 @DeclanHodges @nbrucken17 
it's similar to `derive_extreme_records()`, so I used `derive_extreme_answer()` instead of `derive_param_??`. also borrowed `mode` from `derive_extreme_records()`.

**Comment by bundfussr** [comment]
The function could also be used for oncology parameters like best overall response and maybe also for Hy's law events. So I wonder if we should use a more general name like `derive_extreme_event()`.
