### ISSUE TITLE
General Issue: Review example for `create_single_dose_dataset()`

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1760]
### Background Information

A vignette was created for Derive a single dose dataset with imputations using `create_single_dose_dataset()`  However, the vignette was pretty short and it was decided to collapse the vignette into the `create_single_dose_dataset()` example. #1610 

Unfortunately, this makes the example pretty epic!!!  It also violates our rule against using `admiral.test` in the example data #1752 - to keep things short and sweet. 

We need to revisit this example once the roclet enhancements are available for us.  

### Definition of Done

Example is cleaned up and better "delineated" for users.

**Comment by jeffreyad** [comment]
I can take a look.  I can also include example that expands nominal time for PK analysis.
