### ISSUE TITLE
Feature Request:  Create template for ADPPK 

### ISSUE THREAD

**Issue by jeffreyad** [pharmaverse/admiral#1772]
### Feature Idea

This would be a template for `ADPPK` (Population Pharmacokinetics).  

This will follow the draft implementation guide:

[https://www.cdisc.org/adam-poppk-implementation-guide-v1-0](url)

The requirements are similar to `ADPC/ADNCA` but there are a number of differences as well, including the requirement of additional numeric variables for modelers.

**Comment by andersone1** [comment]
My name is Eric Anderson and I work at Metrum Research Group. It is great to see progress on the ADPPK domain as we have a lot of interest in this new domain as well.

I will keep an eye on this issue as it moves forward. If there is anything I can do to help, please let me know.

**Comment by jeffreyad** [comment]
> My name is Eric Anderson and I work at Metrum Research Group. It is great to see progress on the ADPPK domain as we have a lot of interest in this new domain as well.
> 
> I will keep an eye on this issue as it moves forward. If there is anything I can do to help, please let me know.

Hi Eric @andersone1, great!  Will do

**Comment by bms63** [comment]
Hey @jeffreyad 

We have admiral sub-groups for Questionnaires and for Labs.  We usually meet once a week or every two weeks for half an hour.  Nice to have input from other companies and discuss admiral's gaps for these Domain Areas.

I am wondering if we should set one up for PK?  I'm  happy to put something together and put a call out on slack.    Probably start up at the end of March if you are interested.

**Comment by jeffreyad** [comment]
@bms63 Sure, sounds good.

**Comment by andersone1** [comment]
@bms63 I would definitely be interested in attending a PK one.

**Comment by jeffreyad** [comment]
I am updating the vignette currently called "Creating a PK NCA ADaM (ADPC/ADNCA)" to include the `ADPPK` template and rename it to "Creating a PK NCA or Population PK ADaM".  @bms63 let me know if this should be a separate issue or ok to include with this one.
