### ISSUE TITLE
Bug: Failing CI check - rework `derive_var_extreme_flag` example

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1780]
### What happened?

CI is occasionally failing for this example.  You can rerun the check manually to get it to pass, but this is not ideal

![image](https://user-images.githubusercontent.com/10111024/221865897-462ad089-93ff-400c-a0e0-881f64a5d38f.png)

**Comment by bundfussr** [comment]
It is one of the examples where we use admiral.test data (about 30000 observations from `VS` and 2000 observations from `AE`). I would expect that https://github.com/pharmaverse/admiral/issues/1752 solves the issue.

**Comment by bms63** [comment]
I think we should prioritize fixing this one first after the release
