### ISSUE TITLE
Feature Request: Rename `dataset_adsl` and `subject_keys` in `derive_param_exist_flag()`

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#1793]
### Feature Idea

The `dataset_adsl` and `subject_keys` argument in `derive_param_exist_flag()` should be renamed to `dataset_ref` and `by_vars` respectively. (See Hy's law vignette for use case.)

**Comment by zdz2101** [comment]
@StefanThoma this one might be a good one

**Comment by StefanThoma** [comment]
@bundfussr 
Does the deprecation of arguments require an entry to NEWS.md?

**Comment by bundfussr** [comment]
> @bundfussr Does the deprecation of arguments require an entry to NEWS.md?

Yes, it should be added to the "Breaking Changes" section.
