### ISSUE TITLE
Feature Request: Add argument for `A1HI`/`A1LO` usage to `derive_var_anrind()`

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#1795]
### Feature Idea

An argument should be added to `derive_var_anrind()` to turn on/off the usage of the `A1HI` and `A1LO` variable.

**Comment by bms63** [comment]
@pharmaverse/admiral can anyone take this on?

**Comment by manciniedoardo** [comment]
@bundfussr would the logic in the turned off case be like so?
```
result <- dataset %>%
    mutate(
      ANRIND = case_when(
        AVAL >= ANRLO & is.na(ANRHI) ~ "NORMAL",
        AVAL <= ANRHI & is.na(ANRLO) ~ "NORMAL",
        AVAL >= ANRLO & AVAL <= ANRHI ~ "NORMAL",
        AVAL < ANRLO ~ "LOW",
        AVAL > ANRHI ~ "HIGH",
        TRUE ~ NA_character_
      )
    )
```

**Comment by bundfussr** [comment]
> @bundfussr would the logic in the turned off case be like so?
> 
> ```
> result <- dataset %>%
>     mutate(
>       ANRIND = case_when(
>         AVAL >= ANRLO & is.na(ANRHI) ~ "NORMAL",
>         AVAL <= ANRHI & is.na(ANRLO) ~ "NORMAL",
>         AVAL >= ANRLO & AVAL <= ANRHI ~ "NORMAL",
>         AVAL < ANRLO ~ "LOW",
>         AVAL > ANRHI ~ "HIGH",
>         TRUE ~ NA_character_
>       )
>     )
> ```

Yes
