### ISSUE TITLE
General Issue: use newer version of styler

### ISSUE THREAD

**Issue by esimms999-gsk** [pharmaverse/admiral#1798]
### Background Information

The renv.lock specifies styler 1.8.0. I accidently ran styler::style_pkg() with styler 1.9.1 (latest version as of 06Mar2023) and had some files identified as needing changing; these were all due to styler wanting to remove blank lines. The files identified are:

![image](https://user-images.githubusercontent.com/85294667/223174106-fe418d9e-f059-40a1-9d98-c805f716d88f.png)

Note: until this change to the styler version is implemented, more files may be added to this list.

### Definition of Done

Latest version of styler is specified in renv.lock and styler::style_pkg() shows all files as unchanged.

**Comment by bms63** [comment]
Going to close as we are using new version of styler
