### ISSUE TITLE
General Issue: use newer version of lintr

### ISSUE THREAD

**Issue by esimms999-gsk** [pharmaverse/admiral#1799]
### Background Information

The renv.lock specifies lintr 2.0.1. I accidently ran lintr::lint_package() with lintr 3.0.2 (latest version as of 06Mar2023) and had some files identified as needing changing; these were all due to:

- using T instead of TRUE
- using "&" or "|" in logical statements instead of "&&" or "||"
- lines longer than 100 characters

### Definition of Done

Latest version of lintr is specified in renv.lock and lintr::lint_package() does not throw messages/warnings.

**Comment by bms63** [comment]
@galachad Is the new renv.lock updated to this version of lintr?

**Comment by esimms999-gsk** [comment]
No. The version of lintr in the renv.lock file is 2.0.1. I wo.uld like to see us modify that to use lintr 3.0.2.

**Comment by galachad** [comment]
It's already solved in #1704
