### ISSUE TITLE
Bug: Warning in imputation functions is too restrictive

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#1810]
### What happened?

The following call issues a warning.
```
  derive_vars_dtm(
    dtc = AESTDTC,
    new_vars_prefix = "AST",
    highest_imputation = "Y",
    time_imputation = "last",
    min_dates = exprs(TEMP_TRTSDTM),
    max_dates = exprs(AENDTM),
    preserve = TRUE
  ) 
```
It is caused by the following check.
```
  if (highest_imputation == "Y" & !is.null(min_dates) & date_imputation != "first") {
    warning("If `highest_impuation` = \"Y\" and `min_dates` is specified, `date_imputation` should be set to \"first\".") # nolint
  }
```
It should be updated to
```
  if (highest_imputation == "Y" & is.null(min_dates) & date_imputation == "first") {
    warning("If `highest_impuation` = \"Y\" and `date_imputation = \"first\"` is specified, `min_dates` should be specified.") # nolint
  }
```

**Comment by zdz2101** [comment]
![image](https://user-images.githubusercontent.com/43018762/223787602-9a2b431b-d2a8-4d68-8293-51a50b79a8e1.png)

I think when I was trying to implement the fix during the release, I tried following the "guidance" here, is there a particular "hierachy" of the function arguments? So for `highest_impuation` == "Y" , if I'm interpreting correctly, there should be a check of 1:1 correspondence between:

- supplying `min_dates` and `date_imputation` == "first" 
- supplying `max_dates` and `date_imputation` == "last" 

![image](https://user-images.githubusercontent.com/43018762/223791630-55871fdb-ce42-478e-a12e-f6a20cba3216.png)

Wondering if we need to consider them in separate case-conditions?

**Comment by bundfussr** [comment]
If `highest_imputation == "Y"`, three conditions should be checked:
- `date_imputation %in% c("first", "last")`
- if `date_imputation == "first"` then `min_dates` should be specified.
- if `date_imputation == "last"` then `max_dates` should be specified.

In particular, it is permitted to specify both `min_dates` and `max_dates`.
