### ISSUE TITLE
Define the scope of release 0.11.0

### ISSUE THREAD

**Issue by sadchla-codes** [pharmaverse/admiral#1818]
### Background Information

A list of features that would be part of the next release in June 2023

Priority issues thus far with none assigned to them
Documentation: Use study data examples in convert_blanks_to_na() https://github.com/pharmaverse/admiral/issues/1709  
Feature Request: Deprecate derive_var*_last_dose*() https://github.com/pharmaverse/admiral/issues/1797
restrict_derivation() expects the derivation in the global https://github.com/pharmaverse/admiral/issues/1765
Failing CI check - rework derive_var_extreme_flag example https://github.com/pharmaverse/admiral/issues/1780
Review Programs, vignettes and templates for deprecation https://github.com/pharmaverse/admiral/issues/1747

Others to target for release:
Implement filter_exist() and filter_not_exist() https://github.com/pharmaverse/admiral/issues/1699
Replacing admiral.test calls in the function examples  https://github.com/pharmaverse/admiral/issues/1752
Adding an RStudio style cheatsheet https://github.com/pharmaverse/admiral/issues/1529

### Definition of Done

List of desired features/ updates are under priority should be addressed

Timeline: A new release will occur in early June 2022 (release Q2-2023).
Theme: think overall theme should be around striving for more stability and consistency across our functions and documentation.

**Comment by bms63** [comment]
Thanks for setting this up @sadchla-codes !  @pharmaverse/admiral lets start the planning for `release Q2-2023`!  Please put in your thoughts, concerns.

I think overall theme should be around striving for more stability and consistency across our functions and documentation.

**Comment by esimms999-gsk** [comment]
I would like to upgrade the development tools we use. For example, we have lintr 2.0.1 in the renv.lock for admiral, admiraldev, admiral.test and the latest version of lintr is 3.0.2, which catches some additional things. Same with styler with all three renv.lock specifying v 1.8.0 and latest version is 1.9.1, which catches additional things. These two have been raised in Issues #1799 and #1798.

Perhaps there are other development tools we could upgrade?

**Comment by bms63** [comment]
> I would like to upgrade the development tools we use. For example, we have lintr 2.0.1 in the renv.lock for admiral, admiraldev, admiral.test and the latest version of lintr is 3.0.2, which catches some additional things. Same with styler with all three renv.lock specifying v 1.8.0 and latest version is 1.9.1, which catches additional things. These two have been raised in Issues #1799 and #1798.
> 
> Perhaps there are other development tools we could upgrade?

I believe that @galachad is a few steps ahead of you, Eric,  with his propagation https://github.com/pharmaverse/admiral/pull/1704

**Comment by rossfarrugia** [comment]
@bundfussr can you add the next release tag for all those clean up issues you had added as a result of our Q1 talks with Ben and Thomas on making the package more consistent?

**Comment by bundfussr** [comment]
> @bundfussr can you add the next release tag for all those clean up issues you had added as a result of our Q1 talks with Ben and Thomas on making the package more consistent?

@rossfarrugia , done

**Comment by bundfussr** [comment]
I think we should implement https://github.com/pharmaverse/admiraldev/issues/36 to reduce the time we spend on deprecation.

**Comment by bms63** [comment]
Scope is pretty well-defined for this release - going to close out.
