### ISSUE TITLE
Bug: derive_vars_merged_lookup / check_type

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1820]
### What happened?

@millerg23 

So I recently had an issue where my updated SDTM data had duplicate tests in it, but with different units.  So msec or ms for the same tests.  While I was using `derive_vars_merged_lookup` I thought I could suppress the check until I got new data, but the check seems to fire off no matter what I do and prevent a merge.  Is this intentional or should I be able to suppress the check and have duplicates in my dataset?

If this is not intentiional, then I can make up a reproducible example  for us to look at.

**Comment by millerg23** [comment]
Hi Ben,
Could you post the function call, to see exactly what you are trying to merge. I think the functionality comes from the main `derive_vars_merged()` function. You can use `order` and `mode` I think to handle duplicates. The `derive_vars_merged_lookup` has the added functionality of printing out records where you didn't get a match.

**Comment by bms63** [comment]
I think this was a user error as I believe I fixed it in my script.  going to close out
