### ISSUE TITLE
ADaM Date Format Issue 

### ISSUE THREAD

**Issue by kanagd03** [pharmaverse/admiral#1827]
### Feature Idea

Seems like all the date variables in ADaM(like ADT) are in ISO format similar to SDTM but generally it should be DATE9. format as per ADaM IG. 
eg: ISO format 2023-07-25
Date9 format 25JUL2023

Is there any specific reason for not displaying dates in DATE9. format in ADaM datasets in admiral?  **_Yes - See below discussion on why this is kept in ISO format rather than DATE9. format_**

### Proposed Update/Definition of Done

- [ ] Identify vignettes and function documentation discussing/showing ISO format
- [ ] Identify code solution to convert ISO to DATE9 like format
- [ ] In a new branch, include a footnote or snippet of code that shows how to convert to DATE9. format for each identified vignette or function documentation where this change makes sense.

**Comment by bundfussr** [comment]
@kanagd03 , thanks for creating this issue.

admiral does not use any specific formatting for date and datetime variables. The lubridate package is used to create these variables.

I could not find any guidance in the ADaM IG regarding formatting of dates except
> Numeric date, time, and datetime variables should be formatted, so as to be human-readable with no loss of precision.

> The ISO formats used in the ADaM Date Value column are for the purposes of illustration, and are not intended to imply any type of display standard or requirement. The DT variable is numeric and the producer will determine the appropriate display format.

Did I miss it?

**Comment by bms63** [comment]
Hi @kanagd03 I think @bundfussr  has answered this question sufficiently.  Perhaps we can make a recommendation in our guidance documentation on how to format like a DATE9?

@pharmaverse/admiral any thoughts?

**Comment by jeffreyad** [comment]
Yes, I was thinking it would be good to mention how to apply formats like date9 in xportr

**Comment by bundfussr** [comment]
The tricky question is where we should add this information.

At the end of our vignettes ("Add Labels and Attributes") section we are referring to xportr but we do not mention formats explicitly. Maybe we should replace "associate all metadata information" with something like "associate label, length, and format metadata information".

We could also add a paragraph to the functions which create date and datetime variables (`derive_vars_dt()` and `derive_vars_dtm()`).

**Comment by kanagd03** [comment]
Hi Team,

Good day!
Thanks for your response for my issue.
Talking about derive_vars_dtm function I just found an issue.
Please correct me if I am wrong.

By default, while calling derive_vars_dtm function, even if we do not have Time still we are getting ATMF variable created with value “H”.
This is because highest_imputation argument has default value as “h”. Can you also check this issue?
***@***.***


Thanks,
Dhivya.K

From: Stefan Bundfuss ***@***.***>
Sent: 31 March 2023 14:01
To: pharmaverse/admiral ***@***.***>
Cc: Kanagaraj, Dhivya ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [pharmaverse/admiral] ADaM Date Format Issue (Issue #1827)


The tricky question is where we should add this information.

At the end of our vignettes ("Add Labels and Attributes") section we are referring to xportr but we do not mention formats explicitly. Maybe we should replace "associate all metadata information" with something like "associate label, length, and format metadata information".

We could also add a paragraph to the functions which create date and datetime variables (derive_vars_dt() and derive_vars_dtm()).

**Comment by bms63** [comment]
@kanagd03 thank you for bringing this up - could you open a second issue for ATMF?  That way we can keep this issue focused on the formatting issue you brought to our attention

**Comment by kanagd03** [comment]
Sure Ben! Iwill issue a new issue for it.

Thanks,
Dhivya.K

From: Ben Straub ***@***.***>
Sent: 31 March 2023 19:56
To: pharmaverse/admiral ***@***.***>
Cc: Kanagaraj, Dhivya ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [pharmaverse/admiral] ADaM Date Format Issue (Issue #1827)


@kanagd03<https://urldefense.com/v3/__https:/github.com/kanagd03__;!!H9nueQsQ!4U-xuXfGMWuc8mjBuqPnhZawrz4M91qY7bHexdXZa6VcnxJxbiCYuNACXa53vFO0ybl5Eeo1-YazdlfuFG1BSos47PYnIg8$> thank you for bringing this up - could you open a second issue for ATMF? That way we can keep this issue focused on the formatting issue you brought to our attention

**Comment by bms63** [comment]
Can this just be made into a footnote in the documentation/vignette for these functions showing how to use `lubridate::function` to make this into `date9.`?

**Comment by kanagd03** [comment]
Yes, that’s a good idea!

Thanks,
Dhivya.K

From: Ben Straub ***@***.***>
Sent: 10 April 2023 19:49
To: pharmaverse/admiral ***@***.***>
Cc: Kanagaraj, Dhivya ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [pharmaverse/admiral] ADaM Date Format Issue (Issue #1827)


Can this just be made into a footnote in the documentation/vignette for these functions showing how to use lubridate::function to make this into date9.?

**Comment by bms63** [comment]
Hi all.  I updated the original question to include a proposal on how to address this issue identified.  Please give feedback if it is unclear.

**Comment by bundfussr** [comment]
@bms63 , what do you mean by "Identify code solution to convert ISO to DATE9 like format"? Do you want to change the way how date and datetime variables are displayed in the console or in the dataset viewer or do you want to add how to call `xportr_format()`?

**Comment by bms63** [comment]
> @bms63 , what do you mean by "Identify code solution to convert ISO to DATE9 like format"? Do you want to change the way how date and datetime variables are displayed in the console or in the dataset viewer or do you want to add how to call `xportr_format()`?

I was thinking just in the console/dataset viewer.

**Comment by bms63** [comment]
Oh 

> > > @bms63 , what do you mean by "Identify code solution to convert ISO to DATE9 like format"? Do you want to change the way how date and datetime variables are displayed in the console or in the dataset viewer or do you want to add how to call `xportr_format()`?
> > 
> > 
> > I was thinking just in the console/dataset viewer.
> 
> @bms63 , I am not sure if this is a good idea. We tried something similar in the beginning. For datetime variables time is not displayed if it is "00:00:00". We added some code to force displaying "00:00:00". But it caused a lot of issues. At the end we removed it.

Sorry this is for 2023-07-25 to 25JUL2023

**Comment by kaz462** [comment]
Just curious why do we need to display a specific date format in the R console/dataset viewer? Is it sufficient to only display the proper date format in the XPT file based on `format.sas` attribute?
```r
> attributes(adsl$TRTSDT)
$label
[1] "Date of First Exposure to Treatment"

$class
[1] "Date"

$format.sas
[1] "DATE9"
```

**Comment by bms63** [comment]
After some more discussion with core team, we have decided that this issue will not be pursued/addressed.   We feel that this issue would require some significant updates to admiral codebase which would fall outside of our scope with using formats in R versus SAS.  The compromise solution around providing example code for converting to `DATE9.` would also requite a lot of updates to all our documentation, templates and vignettes that we don't think is worthwhile.

Perhaps enhancements to Bayer's https://bayer-group.github.io/sas2r/index.html could be helpful to address this issue - as other SAS programmers have brought this up.  @kaz462 what do you think?
