### ISSUE TITLE
Add "Report a bug" link to our site

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiral#1836]
Example from https://pharmar.github.io/riskmetric/index.html:

![image](https://user-images.githubusercontent.com/82581364/227550889-13896317-f6bc-4cfb-9d29-4ad446c973c8.png)

As part of riskmetric, they even check for this: https://pharmar.github.io/riskmetric/reference/assess_has_bug_reports_url.html and it affects your score.

If we add this for admiral core, could also consider doing same for admiraldev, admiralonco, admiralophtha.

**Comment by bms63** [comment]
This is a nice one!
