### ISSUE TITLE
General Issue: Dependencies conflict with tidyverse recomendations

### ISSUE THREAD

**Issue by epijim** [pharmaverse/admiral#1838]
### Background Information

Currently dependencies on external functions are handled via importing the functions into the namespace in the `admiral-package.R` script.

Hadley's book on packages recommends not to do this, and instead to write `package::function(`. Some example reasons why `::` is preferred are;

- It makes it clear which functions are from this package, and which are external. This makes it easier to onboard to the codebase, debug the codebase, and generally understand what a function is doing
- There is no risk of namespace conflicts
- You don't end up with mismatches as the package evolves and dependencies are dropped, as dependencies are called where they are used, rather than in a separate file

He does though note 3 exceptions where it can be useful to import,

1. you use the function a lot (and it's clear it comes from somewhere else - e.g. for admiral `mutate` or `left_join` will obviously be `dplyr` to devs and users).
2. it's a loop, as it's slower - but only noticeably if running millions of times
3. it's an operator, e.g. `%--%` from lubridate

As a side note, it's more redundant rather than a bug - but there is least one case where we accidentally have done both. e.g. [in this line of code](https://github.com/pharmaverse/admiral/blame/6dead5ad9b9fe529d8b459ae718f8f35cb52296f/R/derive_date_vars.R#L369) the user wrote `stringr::str_match` despite the fact it's imported into the namespace

ref: https://r-pkgs.org/dependencies-in-practice.html#in-code-below-r

### Definition of Done

Consider a switch to following Hadley's best practices and move to `::`

**Comment by bms63** [comment]
ugh... i really dislike this part of R with `::` every where in your code - so distracting.  

I guess if Hadley is saying this is best practice we have to obey... just aesthetically it is so wacky to look at a function with `stringr::` and `dplyr::` peppered everywhere making it hard to look at and understand

@pharmaverse/admiral what do you think?

**Comment by thomas-neitmann** [comment]
We discussed this as a team already and I would be reluctant to change anything at this point.

**Comment by rossfarrugia** [comment]
@bms63 @thomas-neitmann can you raise at the team call tomorrow please and if team decision is to stick with current approach then the rationale should be explained in our programming strategy. I remember @sgorm123 raising this same concern previously but I don't see it documented anywhere why we chose not to follow this.

**Comment by epijim** [comment]
I guess if going against normal trends it would be good to document. Hadley's textbook is the defacto standard now for good in r packages. We also use both currently in `admiral`, it's just sometimes the `::` isn't doing anything due to the import.

1. In the link above `::` is used even though it doesn't do anything due to the import from. 
2. there is a [`purrr::pmap`](https://github.com/pharmaverse/admiral/blob/99c23e0d726fb1cf51e0e3d96fe6e6abfd3521c5/R/derive_extreme_event.R#L137), but that actually is doing something as bunch of `purrr` functions are imported, but not pmap. 
3. `derive_summary_records` also uses `dplyr::`

At the more general level Hadley's point was that it decreases confusion, as you are being that being explicit about internal vs external which makes the code easier to follow.   @rossfarrugia pointed out  (when we discussed this change for admiralroche) though admiral has very specific naming, so you run into less issues around reading the code and not knowing what functions are part of the package vs imported than a normal R package.

With `admiralroche` we switched to `::` where it is a `Suggests`, as you shouldn't import from at the package namespace level if it's not a `Depends`.

**Comment by epijim** [comment]
This is seperate to `admiral`, as it doesn't have to follow the majority - but I was kinda interested now to know what is the most common, once you remove the tidyverse. This is a bit hard though, as many of the famous names in R are either from pre-tidyverse (e.g. survival and data.table), which is an era where people hated dependencies 😆 - or they are posit employees or tidyverse contributors. 

But it looks like Jeeron Ooms (Ropensci) uses `::` based on `magick`, but Will Landau does it the `admiral` way based on `drake`. And then Karl Broman seems to do a mixture, but mostly aligns with `admiral` and in his package guide mentions both ways and then says he uses import.

**Comment by bms63** [comment]
Placed onto tomorrow's agenda - I think @zdz2101 did this one

**Comment by rossfarrugia** [comment]
@bms63 i can't make the team call so sharing my 2 cents here... happy to go with the majority and i don't have major concerns not following the tidyverse approach here, but if we stick with current rule then I'd ask:

1. lets make it consistent (e.g. the examples of `::` that James identified above and let's check any others in the codebase) 
2. when we add rationale to the programming strategy include why we don't see this as a major risk of namespace conflicts (i.e. admirals strict function naming conventions)

**Comment by bms63** [comment]
Hi all,

The decision is to keep our `admiral-package.R` convention.

We will update our code base to not use `::` #1842.  

We will update our programming documentation to explain our reasoning and best practice - there might be a slight exception to the rule from time to time. 
 https://github.com/pharmaverse/admiraldev/issues/253
 
 @pharmaverse/admiral any other thoughts?
