### ISSUE TITLE
Documentation:  Update certain `.R` files for consistency related to  `::` topic 

### ISSUE THREAD

**Issue by zdz2101** [pharmaverse/admiral#1842]
### Please select a category the issue is focused on?

Other

### Let us know where something needs a refresh or put your idea here!

Related to the topic of https://github.com/pharmaverse/admiraldev/issues/253

The following files have `::` inside the code

File | Line | Function
-- | -- | --
call_derivation.R | 93 | base::union
call_user_fun.R | 31 | rlang::as_label
create_single_dose_dataset.R | 43 | tibble::tribble
create_single_dose_dataset.R | 475 | stringr::str_locate_all
create_single_dose_dataset.R | 487 | stringr::str_locate_all
derive_date_vars.R | 369 | stringr::str_match
derive_date_vars.R | 558 | stringr::str_stars
derive_date_vars.R | 584 | stringr::str_stars
derive_date_vars.R | 784 | stringr::str_match
derive_date_vars.R | 950 | stringr::str_stars
derive_date_vars.R | 972 | stringr::str_stars
derive_date_vars.R | 1101 | lubridate::is.POSIXct
derive_date_vars.R | 1419 | rlang::as_data_mask
derive_date_vars.R | 1420 | rlang::as_data_mask
derive_date_vars.R | 1610 | rlang::as_data_mask
derive_extreme_event.R | 137 | purrr:pmap
derive_var_analysis_ratio.R | 74 | rlang::as_name
derive_var_extreme_date.R | 180 | rlang::list2
derive_var_extreme_flag.R | 348 | dplyr::filter
derive_var_extreme_flag.R | 356 | dplyr::filter
derive_var_extreme_flag.R | 363 | dplyr::filter
derive_vars_dtm_to_dt.R | 63 | lubridate::date
derive_vars_dy.R | 107 | stringr::str_replace_all
derive_vars_query.R | 104 | stringr::str_extract
derive_vars_query.R | 105 | stringr::str_extract
derive_vars_query.R | 181 | dplyr::group_by_at
derive_vars_query.R | 182 | dplyr::summarise
derive_vars_query.R | 309 | dplyr::summarise
duplicates.R | 68 | dplyr::everything
slice_derivation.R | 95 | rlang::list2
user_helpers.R | 67 | utils::file.edit

Issue is resolved when all `tidyverse` cases of `::` are removed, and functions are appropriately called in as `@importFrom` the `R/admiral-package.R` file. @pharmaverse/admiral most of these are `tidyverse` except for `base` , `rlang`, `utils` . Are these the "exceptions" we want? 

As part of the [admiraldev issue](https://github.com/pharmaverse/admiraldev/issues/253) , add text in the second paragraph of [R Package Dependencies](https://pharmaverse.github.io/admiraldev/devel/articles/programming_strategy.html#r-package-dependencies) section stating our rules

**Comment by StefanThoma** [comment]
@zdz2101 For now, I have decided to change all mentioned cases of `::`. 
Happy to take any other route.
