### ISSUE TITLE
Bug: create_period_dataset when both DT and DTM vars exist and DT requested

### ISSUE THREAD

**Issue by millerg23** [pharmaverse/admiral#1845]
### What happened?

When trying to create PERIOD_REF dataset from ADSL period variables using `create_period()` function, an ERROR is produced when using `new_vars = exprs(APERSDT = APxxSDT, APEREDT = APxxEDT)` and where APxxSDT and APxxSDTM exist in the input ADSL dataset. The code searches for the ADSL variables contained in `new_vars` ie. `APxxSDT` and `APxxEDT`. The use of function `matches` picks up both `APxxSDT` and `APxxSDTM` as well as `APxxEDT` and `APxxEDTM`, which triggers an ERROR later about not having unique observations.

### Reproducible Example

 ```
create_period_dataset(
   adsl,
   new_vars = exprs(APERSDT = APxxSDT, APEREDT = APxxEDT, TRTA = TRTxxA)
)
```

Code above is from header of function, the issue is when for example `AP01SDT` and `AP01SDTM` exist, it will find both of them, instead of just `AP01SDT`

**Comment by zdz2101** [comment]
I want to say by using the `"\\b"` metacharacter to match create a boundary/induce an exact string match should solve this, so any instance of:
 `matches(cols[[i]])` 
with
 `matches(paste0(cols[[i]], "\\b", sep = ""))`
