### ISSUE TITLE
Issue in derive_vars_dtm function

### ISSUE THREAD

**Issue by kanagd03** [pharmaverse/admiral#1855]
### What happened?

By default, while calling derive_vars_dtm function, even if we do not have Time still we are getting ATMF variable created with value “H”.
This is because highest_imputation argument has default value as “h”. Can you also check this issue?

![image](https://user-images.githubusercontent.com/114596982/230910606-8464b785-622a-4c15-9d85-5e89e6be8edc.png)

**Comment by bundfussr** [comment]
@kanagd03 , I think the derivation is correct. If your DTC variable does not provide time, it is imputed as "00:00:00" by default. In this case ATMF must be created and set to `"H"` according to the ADaMIG.
It seems that your viewer is not displaying the time if it is "00:00:00".

**Comment by rossfarrugia** [comment]
Will close this issue as agree with Stefan's response.
