### ISSUE TITLE
General Issue: `.lycheeignore` has higher order vignette in it (should be removed)

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1856]
### Background Information

We put this in the ignore so it would pass the checks.  It should be removed so our link checker can review it going forward. 

![image](https://user-images.githubusercontent.com/10111024/231000314-ff372647-946e-4172-8187-6839e183c363.png)

### Definition of Done

Remove higher order file from list of files to ignore.  

Link check passes.

**Comment by bms63** [comment]
@ashachakma will you be able to finish this issue or shall we re-assign it to someone else.  It should be a really quick fix.

**Comment by ashachakma** [comment]
Hi @bms63. I will be able to finish this issue soon. The only issue I am facing is that I don't have this file in the branch that I created for this, 1856_remove_higher_order_file@devel. Just to confirm, I have to follow the same development process or some other way to do this task?

**Comment by bms63** [comment]
You might need to check __Show Hidden Files__ for it to be appear.  Let me know if you can't see it.

![image](https://github.com/pharmaverse/admiral/assets/10111024/33ee2f24-a86b-4b5e-9dfc-e43cf2306e0c)

**Comment by bms63** [comment]
Can you also see if `admiraldev` .lycheeignore` needs to be updated.

**Comment by ashachakma** [comment]
> Can you also see if `admiraldev` .lycheeignore` needs to be updated.

Checked it, this file is not present in the  `admiraldev` .lycheeignore. So, doesn't need an update.
