### ISSUE TITLE
General Issue: Links keep failing CI/CD checks 

### ISSUE THREAD

**Issue by sadchla-codes** [pharmaverse/admiral#1865]
### Background Information

the following links are failing CI/CD checks and redirecting to a 404 Not found page

![image](https://user-images.githubusercontent.com/112789549/231520996-d13c6df4-82be-4aa1-b768-4ebbc2b39084.png)

**Comment by zdz2101** [comment]
May also be this all the mentions of this in the vignettes: [transport v5
file(xpt)](https://documentation.sas.com/doc/en/pgmsascdc/9.4_3.5/movefile/n1xbwdre0giahfn11c99yjkpi2yb.htm)

**Comment by bms63** [comment]
> May also be this all the mentions of this in the vignettes: [transport v5 file(xpt)](https://documentation.sas.com/doc/en/pgmsascdc/9.4_3.5/movefile/n1xbwdre0giahfn11c99yjkpi2yb.htm), looks like wherever this was pointing to on the SAS documentation website its no longer there

Looks like the entire section of SAS docs has bit the dust.

**Comment by bms63** [comment]
Some of these are missing cran-release and others need to be looked at closely in the NEws.md and which version they pertain to.
