### ISSUE TITLE
Feature Request:  a function to align the SAS rounding in R?

### ISSUE THREAD

**Issue by kaz462** [pharmaverse/admiral#1872]
### Feature Idea

The following function is from a [PHUSE paper](https://www.lexjansen.com/phuse-us/2020/ct/CT05.pdf)
```R
ut_round <- function(x, n=0)
{
  # x is the value to be rounded
  # n is the precision of the rounding
  scale <- 10^n
  y <- trunc(x * scale + sign(x) * 0.5) / scale
  # Return the rounded number
  return(y)
}
```

Similar work has been done as shown in the link below, but I couldn't find the source code:
https://rdrr.io/github/mbrothe/brdgr/man/round_sas.html

**Comment by bundfussr** [comment]
Having an option to use SAS rounding is a good idea.

I wonder why `round()` implements only one option for rounding. In the documentation of `round()` it is mentioned that the [IEEE 754](https://en.wikipedia.org/wiki/IEEE_754) standard is used. It has two options for rounding: the R way and the SAS way. I am not sure why only one option was implemented in R. (SAS provides functions for both.)

I don't think we need to implement a new function as implementations are already available like mentioned above or [`janitor::round_half_up()`](https://sfirke.github.io/janitor/reference/round_half_up.html).

At the moment we do not use `round()` in admiral. Once we do, we need to think about
- which option we should use (by default) and 
- if and how the user should control which option is used.

**Comment by bms63** [comment]
As this is an R package meant to build datasets in R for production, I think we should always have the default rounding in R, i.e. round to even.

I do like the option of having the round like SAS available if folks want to use admiral for double programming of SAS datasets, but will we need to have this implemented in admiral or just show users how they can switch his on in a mutate statement or in one of functions that allows for expressions?

**Comment by rossfarrugia** [comment]
My 2 cents on this... isn't this more something for downstream TLG packages rather than in ADaM? Generally in ADaM we just show the full number and let that be a decision for table formatting. as Stefan says we don't use `round()` anywhere in admiral. my personal perspective is that part of the move to R is appreciating differences like this, and if HAs are informed we're using R for submission via briefing package then they'd expect such differences. it could come up during QC comparisons if using SAS to double program, but even then that could be explained. really, there's no right or wrong approach, they're just different so i wouldn't go overboard here.

**Comment by kaz462** [comment]
Thank you all for the detailed replies! I agree no need to implement a new function as it's already available, and the rounding is not ADaM-specific.
The validation rounding discrepancies are not caused by SAS/R, but by different rounding approaches, which should be based on the study SAP instead of the software. (Sorry, the title of this issue may be misleading)

There are situations where rounding is done in ADaM (e.g., [CDISC pilot data](https://github.com/phuse-org/TestDataFactory/tree/main/Updated/TDF_ADaM) ADSL.BMIBL). I wonder if we could add examples/documentation on different rounding approaches in R, maybe at admiral or [pharmaverse/end_to_end_examples](https://github.com/pharmaverse/end_to_end_examples)?

**Comment by bms63** [comment]
Perhaps a certain blogging site could make a short article??

**Comment by rossfarrugia** [comment]
@mstackhouse / @MichaelRimler what's the latest on this PHUSE WG: https://advance.phuse.global/pages/viewpage.action?pageId=327874 ? That's where I usually point people towards and know there was a white paper planned for this.

@kaz462 another option could be a page at https://bayer-group.github.io/sas2r/ given it's not admiral or pharmaverse specific? i.e. it's part of general R training.

**Comment by MichaelRimler** [comment]
> 

Still reading the thread, but AVALC will round in its generation, won't it? @rossfarrugia

**Comment by kaz462** [comment]
Thanks all for your information! @bms63 @rossfarrugia a short article at [SAS2R catalog](https://bayer-group.github.io/sas2r/ ) sounds great, [issue](https://github.com/Bayer-Group/sas2r/issues/23) created, will include the two rounding approaches as mentioned by @bundfussr  @MichaelRimler 
> you could get round-to-even or round_away_from_zero with either. in SAS - round() or rounde(). In R, round() or janitor::round_half_up() {as mentioned above}.

and mention `options(tplyr.IBMRounding)` for Tplyr

**Comment by rossfarrugia** [comment]
thanks all for the input! think we can close this one out then. sounds a good outcome - thanks Kangjie!
