### ISSUE TITLE
Feature Request: Enhance `derive_param_computed()`

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#1873]
### Feature Idea

`derive_param_computed()` should be enhanced such that the following parameter can be derived.

- `PARAMCD = "CHSF13"`
- `AVAL`: If QS.QSORRES in("Not applicable") then AVAL=0. If QS.QSORRES="Yes" then AVAL=38. If QS.QSORRES="No" and QS.QSSTRESN when PARAMCD="CHSF12" is greater than QS.QSSTRESN when PARAMCD="CHSF14" then AVAL=25. If QS.QSORRES="No" and QS.QSSTRESN when PARAMCD="CHSF12" equals QS.QSSTRESN when PARAMCD="CHSF14" then AVAL=0. 

For example:
```
adchsf <- derive_param_computed(
  adchsf,
  dataset_add = qs,
  parameters = exprs(CHSF12, CHSF13 = QSTESTCD %in% c("CHSF113", "CHSF213"), CHSF14),
  analysis_value = case_when(
    QSORRES.CHSF13 == "Not applicable" ~ 0,
    QSORRES.CHSF13 == "Yes" ~ 38,
    QSORRES.CHSF13 == "No" ~ if_else(
      QSSTRESN.CHSF12 > QSSTRESN.CHSF14,
      25,
      0
    )
  ),
  set_values_to = exprs(PARAMCD = "CHSF13")
)
```
- The `dataset_add` argument is added to use observations from a different dataset than the input dataset.
- The `parameters` argument is enhanced such that "new" parameters can be defined via conditions.
- The `analysis_value` argument is enhanced such that other source variables than `AVAL` can be used, e.g., `QSORRES` or `QSSTRESN`.

**Comment by bms63** [comment]
What do you think of this update @pharmaverse/admiral ?

**Comment by bundfussr** [comment]
> I like this enhancement, but I can imagine it starts to become difficult to "visualize" what's happening here (also true for many of our advanced general functions) wondering if in the documentation for the function, we can include some sort of simple diagram the origin of the expressions/columns involved, what is retained/created/removed along the way to the end return object

Good idea! I never tried it but it seems that you can create diagrams directly in R markdown: https://bookdown.org/yihui/rmarkdown-cookbook/diagrams.html

**Comment by millerg23** [comment]
Yeah it seems very complicated to me, what would be the alternative solution with the current functions we have? 2 steps I guess?
I would be concerned about the need for diagrams to explain a function.

**Comment by bms63** [comment]
@PavloChaika if you are still interested, we have been given the go-ahead to implement this change.  We need to have it completed before no later than May 31st as we are doing a release on June 5th.  Let us know your thoughts!!  We will support you! :)

**Comment by PavloChaika** [comment]
> @PavloChaika if you are still interested, we have been given the go-ahead to implement this change. We need to have it completed before no later than May 31st as we are doing a release on June 5th. Let us know your thoughts!! We will support you! :)

Thank you for letting me know about the go-ahead to implement the change. I apologize for not responding earlier. I think it is better if Stefan finishes it since he has already started working on it. However, since I still want to gain some practice, I'll work on it locally. I will let you know if I have any questions.
