### ISSUE TITLE
Feature Request:  Enhance `compute_duration()` to handle Interval and Duration

### ISSUE THREAD

**Issue by kaz462** [pharmaverse/admiral#1875]
### Feature Idea

`lubridate::time_length(x, unit = "second")` handles [Interval](https://lubridate.tidyverse.org/reference/Interval-class.html) and [Duration](https://lubridate.tidyverse.org/reference/Duration-class.html) differently when unit is months/years

> When x is an [Interval](https://lubridate.tidyverse.org/reference/Interval-class.html) object and unit are years or months, time_length() takes into account the fact that all months and years don't have the same number of days.
> When x is a [Duration](https://lubridate.tidyverse.org/reference/Duration-class.html), [Period](https://lubridate.tidyverse.org/reference/Period-class.html) or [difftime()](https://rdrr.io/r/base/difftime.html) object, length in months or years is based on their most common lengths in seconds (see [timespan()](https://lubridate.tidyverse.org/reference/timespan.html)).

Example of difference between intervals and durations:
```r
> int <- interval(ymd("2000-02-01"), ymd("2000-03-01"))
> time_length(int, "months")
[1] 1
> time_length(as.duration(int), "months")
[1] 0.9527721
```

Currently, `compute_duration()` only uses interval to calculate "duration", would it be okay to add a feature to choose between interval and duration?

https://github.com/pharmaverse/admiral/blob/6dead5ad9b9fe529d8b459ae718f8f35cb52296f/R/compute_duration.R#L158

**Comment by bms63** [comment]
@pharmaverse/admiral what do people think about this one?

**Comment by zdz2101** [comment]
I like the idea of adding this, wondering if interval should still be retained as the default?

**Comment by bundfussr** [comment]
I think adding an argument to select duration vs. interval is a good idea.

I am not sure if we need an option to specify the number of days of a year or a month. The lubridate values (365,25 and 30,4375) are the standard values used at Roche.

**Comment by bms63** [comment]
@pharmaverse/admiral oohhh this issue is stale - tyty mr bot.  

Any takers @pharmaverse/admiral??  I think this would be a nice feature to add for the upcoming release.

**Comment by ddsjoberg** [comment]
@bms63 i can take this one on

**Comment by ddsjoberg** [comment]
I am working on this update now. @zdz2101 you mentioned keeping interval as the default (the current implementation in the released version). My impression is that the duration rather than the interval is the most common method for time period calculations, however. Certainly, this is the case in the academic research I've done. Is it different in the pharma world?

Thoughts @pharmaverse/admiral 

<img width="808" alt="image" src="https://github.com/pharmaverse/admiral/assets/26774684/84711193-d514-4938-924d-4fa87c348ae3">

**Comment by bms63** [comment]
My instinct is to lean towards keeping the default as interval just to minimize impact to users - thinking Roche here.  However, if @bundfussr, @millerg23, @manciniedoardo  says there is no big impact to `admiralroche` or Roche's templates - maybe we could just switch to duration.  I'd be keen on duration as well.

**Comment by manciniedoardo** [comment]
Agree to keep as is to minimise impact on any users.
