### ISSUE TITLE
vars vs. exprs

### ISSUE THREAD

**Issue by ningxuca** [pharmaverse/admiral#1886]
Hi, I am a new user and sorry for my naïve question. There was an error message with exprs(). It worked when I changed to vars, for example in the following example:
adex <- derive_param_exposure(
  adex,
  by_vars = vars(STUDYID, USUBJID),
  input_code = "DOSE",
  analysis_var = AVAL,
  set_values_to = vars(PARAMCD = "TDOSE", PARCAT1 = "OVERALL"), 
# error message with exprs(PARAMCD = "TDOSE", PARCAT1 = "OVERALL")
  summary_fun = function(x) sum(x, na.rm = TRUE)
)

**Comment by bms63** [comment]
CAn you do a `sessionInfo()` so we can see your installation and packages please.

It might be best to just remove `admiral` and `admiraldev` (a dependency package) and then re-install.

**Comment by ningxuca** [comment]
Thank you for your prompt response, Ben! I removed and reinstalled.
exprs works now.
Also, the vars() did not cause an error message, but the result was
incorrect.
