### ISSUE TITLE
General Issue: Questions about validation

### ISSUE THREAD

**Issue by seth127** [pharmaverse/admiral#1887]
### Background Information

_This may work better in the "Discussions" section, but I wasn't sure how to start one of those..._

Hello Admiral team,
First off, fantastic work here! I really appreciate how well done this package is, and the same for the entire `pharmaverse`. And, to the extent any of you are involved with the R Validation Hub, I really appreciate that work as well. Which brings me to my question...

I lead the Data Science team at [Metrum Research Group](https://metrumrg.com/). One of our main projects is working on a suite of open source R packages, primarily used for Pharmacometrics. Here is a [link to some of our work](https://merge.metrumrg.com/expo/expo1-nonmem-foce/), if you're interested.

We are continuing to work on how to most comprehensively and most efficiently Validate these packages, for our own use and for the use of others. I know your team has also put a lot of thought and work into this and I'm interested to hear about how you are currently approaching it. 

We have found much of the R Validation Hub work very valuable, and we are already using many of their [principles](https://higherlogicdownload.s3.amazonaws.com/AMSTAT/fa4dd52c-8429-41d0-abdf-0011047bfa19/UploadedImages/BIOP%20Report/BioPharm_fall2022FINAL.pdf) and several of their [packages](https://pharmaverse.org/e2eclinical/validation/). That said, the majority of their work seems focused on validating **packages developed externally** for their own _use_ in their respective companies. While this work has been very helpful to us (obviously, we use many packages developed by the open source community), I am particularly looking for guidance on what validation you do **for the packages you are developing internally.** In particular, how is it different than the validation you do for something like the `tidyverse` packages?

I see several mentions of validation in your documentation, in particular [this FAQ](https://pharmaverse.github.io/admiral/v0.10.2/articles/faq.html#is-the-admiral-package-validated). But again, this is focused on what another company might do if they are interested in using `admiral`. Is this essentially the same thing you are doing internally? Statements like [this one](https://pharmaverse.github.io/admiral/v0.10.2/articles/admiral.html?q=validat#validation) make me think that your internal processes are focused more on traditional software development and testing best practices, and that _Validation_ portion is left to the "user". I recognize that in many cases, the "user" is also yourselves, just in a different role. This pattern makes sense and seems appealing to me, but I want to make sure that I'm not misunderstanding or assuming too much.

Thanks in advance for any help or guidance. And of course, I realize that you may not be able or willing to discuss these kinds of internal processes, especially in a public forum like this. Please let me know if there is a more appropriate place for this conversation, or if any of you are willing to connect directly. And thanks again for all of your hard work to promote open source software.

Best,
Seth Green

### Definition of Done

A lively discussion on validating open source software development.

**Comment by rossfarrugia** [comment]
Agree Ben! There's even a validation channel there as it's always such a hot topic in the open source space. Will close this issue in anticipation of the discussion moving to Slack.

As FYI @seth127 here's some R/Pharma past sharing to help answer your question from Roche/Genentech perspective:
https://www.youtube.com/watch?v=xksxuvXVimM
https://www.youtube.com/watch?v=ZfZpypQ1jSM
