### ISSUE TITLE
Feature Request:  FMQ (FDA Medical Query)

### ISSUE THREAD

**Issue by esimms999-gsk** [pharmaverse/admiral#1897]
### Feature Idea

Do we need new functionality/documentation in admiral for FMQ's ("FDA Medical Query")?

### Relevant Input

We have functionality in admiral for SMQ's ("Standardized MedDRA Query") and CQ's ("Customized Queries").

As part of the SMQ/CQ-related development in admiral, a standard file format was defined for import of SMQ/CQ information. Individual Pharma companies would need to get their SMQ/CQ data into this expected format for use in admiral.

[An article about FMQ's.](https://onbiostatistics.blogspot.com/2022/09/fmq-fda-medical-query-and-smq.html)

**Comment by bundfussr** [comment]
Interesting!

Do you know if there is an official source of the definition of the FMQs? I have only found an excel document which was used for a workshop.

Unless CDISC adds new query variables I would use the `CQ*` variables for FMQs.

**Comment by bundfussr** [comment]
@esimms999-gsk , thanks for the feedback and the links.

I would suggest that we keep this issue in the backlog until FDA releases FMQs officially.
