### ISSUE TITLE
Remove {styler} dependency

### ISSUE THREAD

**Issue by lorenzwalthert** [pharmaverse/admiral#1919]
Hi, author of the formatting package {styler} here. As I judge from a search in your source code, there is no functionality that uses {styler}, in other words {styler} is not a runtime dependency. You recommend people to format their code when they contribute, so {styler} is a development dependency. Adding {styler} as a dependency to your package has the following drawbacks:

* Your user's may install a package they don't need (assuming most people who install your package are useres, not developers). This costs additional bandwith, installation time, disk space etc... If they need it, they can just manually install it.
* I as a maintainer of {styler} have to run reverse dependency checks (R CMD Check your package with my new version of {styler}) upon submitting to CRAN e.g. with {revdepcheck}. {styler} has more than 40 reverse dependencies, which makes this a long process.

For that reason, I suggest you to drop that dependency from your package. If you want to ensure your code remains styled, I recommend {precommit} to apply {styler} on each commit or other tools described in the  [third-party integrations](https://styler.r-lib.org/articles/third-party-integrations.html) website of {styler}.

For the removal to take effect, a CRAN submission of your package is required. For tracking, this issue is referenced in https://github.com/r-lib/styler/issues/1121.

**Comment by bms63** [comment]
HI @lorenzwalthert so we have an automated `renv.lock` generation that is housed here: https://github.com/pharmaverse/admiralci/blob/main/.github/workflows/r-renv-lock.yml

Unfortunately, it pulls the styler package out of the Description File to help generate the `renv.lock` file.  This way developers can easily install all necessary packages to do development work.  

I don't think we can remove the package right now, but we will continue to discuss if there is a better solution so we don't have so many dependencies like `styler` and cause you headaches when doing a release! 

@galachad @cicdguy what do you think?

**Comment by lorenzwalthert** [comment]
ok, thanks for the explanation. I agree that in conjunction with {renv}, it's a special case. FWIW with `renv::record()`, you can manually record a dependency into `renv.lock` that is not in `DESCRIPTION`, but then if people use {renv} APIs to update `renv.lock` e.g. with `renv::snapshot()` (if they ever), they might be confused about the diff they see, as styler would then be removed from `renv.lock`.

**Comment by galachad** [comment]
Hi @lorenzwalthert thank you for the suggestion.  I think we can remove it from the `DESCRIPTION` and keep the `{styler}` only in `renv.lock` for developers. 

The `{styler}` is only in `Suggests` section of `DESCRIPTION`. Is it still impacting your reverse dependency `{revdepcheck}` process?

**Comment by lorenzwalthert** [comment]
Ok, cool. Yes, `Suggests:` are also checked. Thanks.

**Comment by lorenzwalthert** [comment]
Thanks for acting so timely.
