### ISSUE TITLE
Documentation:  `derive_param_tte()` incorrect reference

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiral#1927]
### Please select a category the issue is focused on?

Function Documentation

### Let us know where something needs a refresh or put your idea here!

@bundfussr from https://github.com/pharmaverse/admiral/issues/1576 i don't think the following bit got fixed:

_Additionally the documentation should be updated where it mentions the start_imputation_flag argument. This argument does not exist._

See from https://pharmaverse.github.io/admiral/cran-release/reference/derive_param_tte.html the below:

![image](https://github.com/pharmaverse/admiral/assets/82581364/f38f8acc-d597-44c3-b21f-a0419c3aed79)

Do you agree? Will create this as good first issue for anyone to pick up.

**Comment by bundfussr** [comment]
@rossfarrugia , yes, you are right. I missed that bit.

**Comment by rossfarrugia** [comment]
No worries! An easy fix for one of our contributors to help with anytime. I didn't add the release tag as know the team have a lot on their plate for the upcoming release, so fine if this one gets resolved later.

**Comment by bms63** [comment]
@SyedMubasheer are you going to make this update or can we take you off this issue and let someone else work on it?

**Comment by SyedMubasheer** [comment]
> @SyedMubasheer are you going to make this update or can we take you off this issue and let someone else work on it?

I Should be able to do it @bms63 !
