### ISSUE TITLE
Re-evaluate package dependencies to identify/remove those that aren't runtime dependencies

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiral#1940]
### Background Information

See #1919 where the author of {styler} suggested this course of action for their package. Idea is to test out doing this for {styler} in Q2-2023 release, and then try identify other candidate packages in for Q3 2023 release.

Reasoning (quoting #1919 ):

- Your users may install a package they don't need (assuming most people who install your package are useres, not developers). This costs additional bandwith, installation time, disk space etc... If they need it, they can just manually install it.
- I as a maintainer of {styler} have to run reverse dependency checks (R CMD Check your package with my new version of {styler}) upon submitting to CRAN e.g. with {revdepcheck}. {styler} has more than 40 reverse dependencies, which makes this a long process.

### Definition of Done

Remove package dependencies that we don't need, in order to lessen the load on maintainers of said packages.

**Comment by zdz2101** [comment]
@pharmaverse/admiral 

Looks like we have a file `inst/dev_dependencies.R` that explicit lists out the libraries that are used strictly for development (related to staged dependencies?), based on this, we can probably remove the follow (red-dots) from the `DESCRIPTION` like how we did the styler?
![image](https://github.com/pharmaverse/admiral/assets/43018762/efcac680-1671-42b5-818e-62577bfcc657)

**Comment by bundfussr** [comment]
Do we still need `inst/dev_dependencies.R`? According to the comment in the file it was added to support creation of `renv.lock`. But we moved `renv.lock` creation to admiralci.

What is meant by "package dependencies that we don't need"?

**Comment by bms63** [comment]
I think we can remove the `inst/dev_dependecies` and point new developers (which we do) to the use of our `.Rprofile/renv.lock` set ups for different versions of R.

@ddsjoberg also pointed out that some of imports automatically load in other imports, e.g. `dplyr` brings in `magrittr` and I believe `tibble` and we could do away with the doubling of efforts.
