### ISSUE TITLE
General Issue: Browse Hackathon Code

### ISSUE THREAD

**Issue by StefanThoma** [pharmaverse/admiral#1947]
### Background Information

Look through the code uploaded by hackathon participants. 
Identify usages which differ from our intended usage of `admiral`. 
Can we generate new use cases / ideas from that usage?
Should documentation be adjusted / clarified?

Contact me to get access to the files. 

### Definition of Done

Write a summary of insights and remarks gained from the admiral hackathon files. 
Identify discussion points and bring them to a meeting. 
Discuss whether any changes / updates are required.

**Comment by bms63** [comment]
Could you put these files into the Phuse teams site.  Maybe the backlog group could review these?  @bundfussr @zdz2101 @manciniedoardo

**Comment by bms63** [comment]
Moving this to a discussion - as it is a big topic.
