### ISSUE TITLE
Documentation:  Follow the deprecation process the functions deprecated in previous version

### ISSUE THREAD

**Issue by sadchla-codes** [pharmaverse/admiral#1950]
### Please select a category the issue is focused on?

Function Documentation, Other

### Let us know where something needs a refresh or put your idea here!

- **Following functions need to be removed for the next version of {admiral}**

- [x] derive_var_disposition_status()
- [x] derive_vars_disposition_reason()
- [x] format_eoxxstt_default()
- [x] format_reason_default()
- [x] derive_var_worst_flag()

- **Following functions need to follow the next deprecation phase**
- [x] derive_param_extreme_event()
- [x] derive_vars_last_dose()
- [x] derive_var_last_dose_amt()
- [x] derive_var_last_dose_date()
- [x] derive_var_last_dose_grp()
- [x] derive_var_basetype()
- [x] derive_var_merged_cat() 
- [x] derive_var_merged_character()

- **The following argument(s) need to follow the next deprecation phase**
- [x] filter argument in derive_extreme_records()
- [x] aval_fun argument of derive_param_exist_flag()

**Comment by bms63** [comment]
Linking this to #1944
