### ISSUE TITLE
Feature Request:  missing `ref_end_date` consideration in `derive_var_ontrtfl()` 

### ISSUE THREAD

**Issue by kaz462** [pharmaverse/admiral#1984]
### Feature Idea

 `derive_var_ontrtfl()` doesn't flag the following records for `ONTRTFL`, should they be flagged instead?

``` r
library(lubridate)
#> 
#> Attaching package: 'lubridate'
#> The following objects are masked from 'package:base':
#> 
#>     date, intersect, setdiff, union
adcm <- tibble::tribble(
  ~USUBJID, ~ASTDT,            ~TRTSDT,           ~TRTEDT,    ~AENDT,
  "P01",    ymd("2020-03-15"), ymd("2019-01-01"), NA,      ymd("2022-12-01"),
  "P02",    ymd("2020-04-30"), ymd("2019-01-01"), NA,      ymd("2022-03-15"),
  "P03",    ymd("2020-04-30"), ymd("2019-01-01"), NA,      NA,
)

admiral::derive_var_ontrtfl(
  adcm,
  start_date = ASTDT,
  end_date = AENDT,
  ref_start_date = TRTSDT,
  ref_end_date = TRTEDT,
  span_period = "Y"
)
#> # A tibble: 3 × 6
#>   USUBJID ASTDT      TRTSDT     TRTEDT AENDT      ONTRTFL
#>   <chr>   <date>     <date>     <lgl>  <date>     <chr>  
#> 1 P01     2020-03-15 2019-01-01 NA     2022-12-01 <NA>   
#> 2 P02     2020-04-30 2019-01-01 NA     2022-03-15 <NA>   
#> 3 P03     2020-04-30 2019-01-01 NA     NA         <NA>
```

<sup>Created on 2023-06-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by bundfussr** [comment]
It is not mentioned in the documentation how a missing end of treatment date is handled. So I assume this case was not considered when the function was implemented.

I would consider a missing end of treatment date as an ongoing treatment, i.e., the records should be flagged. Most likely the Roche standard handles it in the same way (the specs are not 100% clear).

@pharmaverse/admiral , any thoughts?

**Comment by rossfarrugia** [comment]
I think no harm to update and flag in these cases as seems the most logical assumption, but its also technically dirty data in my mind (as if there were valid EX treatments to populate TRTSDT then TRTEDT shouldn't be missing either) and we can't always cover all possible implausible data scenarios in our functions.

**Comment by kaz462** [comment]
Thanks for the quick turnaround on this issue! 
could you please check the following case? ONTRTFL is now flagged when `ref_start_date` is missing (was not flagged before the updates)
```r
adcm <- tibble::tribble(
    ~USUBJID, ~ASTDT,            ~TRTSDT,   ~TRTEDT, ~AENDT,
    "P03",    ymd("2020-04-30"), NA,        NA,      NA,
)

admiral::derive_var_ontrtfl(
    adcm,
    start_date = ASTDT,
    end_date = AENDT,
    ref_start_date = TRTSDT,
    ref_end_date = TRTEDT,
    span_period = "Y"
)
# A tibble: 1 × 6
  USUBJID ASTDT      TRTSDT TRTEDT AENDT ONTRTFL
  <chr>   <date>     <lgl>  <lgl>  <lgl> <chr>  
1 P03     2020-04-30 NA     NA     NA    Y  
```

**Comment by rossfarrugia** [comment]
@kaz462 good spot - that seems like a bug to me as if patient received no treatment then all records should have this NULL really.

**Comment by bms63** [comment]
@ddsjoberg could you look into this issue please.
