### ISSUE TITLE
Documentation:  Provide support to users for understanding quoting ((`!!`, `!!!`, `expr_c`, ...)

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1990]
### Please select a category the issue is focused on?

User Guides

### Let us know where something needs a refresh or put your idea here!

We make use of (`!!`, `!!!`, `expr_c`, ...) in our function examples and vignettes, but never attempt to explain or link out to the use of these.  We should make a single source of information around quoting ((`!!`, `!!!`, `expr_c`, ...) and link back to this document/section in our vignettes/document.

This should be developed in tandem with the admiral development documents issue around quoting: https://github.com/pharmaverse/admiraldev/issues/233 for new developers as the work will overlap.

Strongly encouraged to link out to existing resources as this is well-documented.

## Definition of Done

- [ ] A section is developed in admiral that discusses quoting and its use in admiral (FAQs might be best location, but up to you) - focus is on users
- [ ] A section is developed in the programming strategy that discusses quoting - focus is on new developers.

**Comment by ddsjoberg** [comment]
hey @bms63 ! 

What do you think of updating examples to _not_ use these tools? Expressions and the bang-bangs are pretty advanced topics. I think we expect most users to be new to R, and when possible, we can keep the examples and documentation straight-forward.

**Comment by bms63** [comment]
I'm not sure how much work that would be to re-work the examples/functions to not use them.

While they are advanced topics, I still feel like giving users a glimpse to them could be worthwhile.  At some point the new users become the veterans and will expect more power and flexibility from R and admiral.

Also, I believe that there are only use a few times we use the !!, !!! in our functions examples, but I could be mistaken.  

@pharmaverse/admiral thoughts??

**Comment by manciniedoardo** [comment]
@bms63 @ddsjoberg one really important use case is the TA-extension packages. There, we have programmers who may not have much initial familiarity with R/admiral, but that are faced with developing admiral-like functions for their extension packages. It would be very nice if they could fall back on some guidance in order to learn more about bang-bang, exprs, etc. I've seen this use case arise in admiralophtha and admiralvaccine.

**Comment by bundfussr** [comment]
For users who just want to call admiral functions the documentation should be quite simple. I think we have only one use case in our templates/vignettes:
You need to use a list of variables in several function calls. You use
```
adsl_vars <- exprs(TRTSDT, TRTEDT, TRT01A, TRT01P)
```
to save the list and then use the `adsl_vars` name in the function calls:
```
advs <- derive_param_map(
  advs,
  by_vars = exprs(STUDYID, USUBJID, !!!adsl_vars, VISIT, VISITNUM, ADT, ADY, VSTPT, VSTPTNUM),
  set_values_to = exprs(PARAMCD = "MAP"),
  get_unit_expr = VSSTRESU,
  filter = VSSTAT != "NOT DONE" | is.na(VSSTAT)
)
```
All users need to know is: "Use `exprs()` to quote a list of variables and `!!!` to unquote it."

This is very simple but R newcomers may not know it. Thus I think it would be helpful to provide this information. (The tricky bit is to identify a place where users find it.)

I am not aware of a better solution for this use case. @ddsjoberg , how would you implement this use case without `exprs()` and `!!!`?

Developers of admiral-like functions need to know more: a bit of lazy-evaluation and quosures. I think providing some examples of the most common use cases like handling an argument which expects a single variable, handling an argument which expects a list of variable, ... in the programming strategy would be useful. In the past developer/contributors were struggling at this point.

**Comment by ddsjoberg** [comment]
One way to do this action without a triple bang is to `c()` instead:

``` r
adsl_vars <- rlang::exprs(TRTSDT, TRTEDT)

rlang::exprs(USUBJID, !!!adsl_vars)
#> [[1]]
#> USUBJID
#> 
#> [[2]]
#> TRTSDT
#> 
#> [[3]]
#> TRTEDT

c(rlang::exprs(USUBJID), adsl_vars)
#> [[1]]
#> USUBJID
#> 
#> [[2]]
#> TRTSDT
#> 
#> [[3]]
#> TRTEDT
```

<sup>Created on 2023-07-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>


If we go with tidyselect, then users could use the syntax they already know from dplyr

```r
adsl_vars <- c("TRTSDT", "TRTEDT", "TRT01A", "TRT01P")

c(USUBJID, all_of(adsl_vars)))
```

**Comment by bundfussr** [comment]
Thanks, I was not aware of the `c()` option. I think we should mention it in the documentation.

I am not convinced regarding the tidyselect option. I think it is the most challenging part of the tidyverse because it depends on the context which expressions work and which not. For example `adsl_vars <- c(STUDYID, USUBJID)` does not work but `select(adsl, c(STUDYID, USUBJID))` works.

If I define `adsl_vars <- c("STUDYID", "USUBJID")`, calling `select(adsl, adsl_vars)` works. (Shouldn't it throw an error though?)
However, calling `arrange(adsl, adsl_vars)` results in
```
Error in `arrange()`:
! Problem with the implicit `transmute()` step.
✖ Problem while computing `..1 = adsl_vars`.
✖ `..1` must be size 306 or 1, not 2.
```

**Comment by ddsjoberg** [comment]
The benefit of tidyselect is that it is a consistent experience for users across admiral and the tidyverse. Whether or not we personally prefer working with lists of expressions vs tidyselect is not the main point from my POV.

> If I define `adsl_vars <- c("STUDYID", "USUBJID")`, calling `select(adsl, adsl_vars)` works. (Shouldn't it throw an error though?)

tidyselect does not error with this syntax, but it provides a note about the correct syntax

``` r
column_names <- c("mpg", "am")

mtcars |> dplyr::select(column_names) |> invisible()
#> Warning: Using an external vector in selections was deprecated in tidyselect 1.1.0.
#> ℹ Please use `all_of()` or `any_of()` instead.
#>   # Was:
#>   data %>% select(column_names)
#> 
#>   # Now:
#>   data %>% select(all_of(column_names))
#> 
#> See <https://tidyselect.r-lib.org/reference/faq-external-vector.html>.
#> This warning is displayed once every 8 hours.
#> Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
#> generated.
```

<sup>Created on 2023-07-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by bms63** [comment]
Since users have yet to identify this as an issue - we think this should be closed.
