### ISSUE TITLE
Pre-release v0.12.0 tasks

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiral#1995]
### Background Information

@pharmaverse/admiral 

We have a few tasks that we should be doing prior to each release. Some can be done ahead of time, while some should be done close to the release date. I've included some that  I can think of in the checklist below, but feel free to edit this comment and add to the checklist. please put your name next to an item that you wish to cover.
- [x] update list of conference presentations - @manciniedoardo 
- [ ] release video
- [ ] release blogpost on linkedin

### Definition of Done

Exhaustive checklist set up above, with assignees for each task.

**Comment by bms63** [comment]
- [ ] Post of slack channels
- [ ] Change upcoming schedule on Readme
