### ISSUE TITLE
Bug: compute_age_years does not handle missing values for age.

### ISSUE THREAD

**Issue by millerg23** [pharmaverse/admiral#2001]
### What happened?

get an ERROR if `compute_age_years()` function is passed in missing values for age unit, also function sets age unit to "years" for all observations., even if age missing We need a check to see if AGE is missing, and only if it is non-missing should we convert age to years and populate age unit with "years".

### Reproducible Example

Below code fails, AAGE and AAGEU calculated correctly with missing date, but `derive_var_age_years` fails
```
test <- tibble::tribble(
  ~ RANDDT,           ~BRTHDT,
  "2022-12-31",  "1975-12-15",
  NA_character_, "1976-12-13",
) %>% 
  mutate(
    RANDDT = lubridate::ymd(RANDDT),
    BRTHDT = lubridate::ymd(BRTHDT)
  ) %>% 
  derive_vars_aage() %>% 
  derive_var_age_years(AAGE, new_var = temp_age)
```
Code below workls with no missing information
```
test <- tibble::tribble(
  ~ RANDDT,           ~BRTHDT,
  "2022-12-31",  "1975-12-15",
  "2022-11-30",  "1976-12-13",
) %>% 
  mutate(
    RANDDT = lubridate::ymd(RANDDT),
    BRTHDT = lubridate::ymd(BRTHDT)
  ) %>% 
  derive_vars_aage() %>% 
  derive_var_age_years(AAGE, new_var = temp_age)
```

**Comment by manciniedoardo** [comment]
While I'm at it, I will also change `unit` argument in `derive_vars_aage` to `age_unit` to align with other functions as suggested by @zdz2101
