### ISSUE TITLE
General Issue: `derive_var_shift()` change `na_val` arugment to `missing_value`

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#2014]
### Background Information

All of our functions use `missing_values` or `missing_value` when `NAs` need to be filled in.  This function is not following this convention and should be updated.

![image](https://github.com/pharmaverse/admiral/assets/10111024/ba36313c-99d1-4e95-9281-365dc528b456)

### Definition of Done

- [x] Function argument and description updated
- [x] Deprecation process followed for arguments
- [x] Tests updated

**Comment by sophie-gem** [comment]
Reminder (for self) to check vignettes and example code in case updates needed.
