### ISSUE TITLE
Add roxygen2 template for common arg names/descriptions

### ISSUE THREAD

**Issue by ddsjoberg** [pharmaverse/admiral#2034]
### Please select a category the issue is focused on?

Function Documentation

### Let us know where something needs a refresh or put your idea here!

http://cran.nexr.com/web/packages/roxygen2/vignettes/rd.html

**Comment by ddsjoberg** [comment]
roxygen2 templates have been superseded.

![image](https://github.com/pharmaverse/admiral/assets/26774684/968d11e7-a10f-4104-ba13-8a121dfa1a32)

My interpretation of the suggestion is to write an internal function that will be called in-line. 

```r
param_by_var_description <- function() "A list of expressions created using `exprs()` identifying groups of records in which to look for duplicates"
```

Then the roxygen comment would look like this:

```r
#' @param by_var `r param_by_var_description()`
```

Is that how you're reading the suggestion as well? @pharmaverse/admiral ?

**Comment by bundfussr** [comment]
Yes, I would read it in the same way.

Maybe we need some conventions for such documentation functions, e.g., where to store them, how to name them, ....
Do we need unit tests for them?

**Comment by ddsjoberg** [comment]
Thanks @bundfussr ! I'll put together a draft PR with one or two description updates. Once we're all aligned, I'll complete the updates.

**Comment by bms63** [comment]
Another nice to have for standard text that isn't `param` related but we want to only update in one place.

See discussion here: https://github.com/pharmaverse/admiral/pull/2118#discussion_r1334526596
