### ISSUE TITLE
Update `admiral.test` to `pharmaversesdtm` 

### ISSUE THREAD

**Issue by kaz462** [pharmaverse/admiral#2040]
### Background Information

After copying data from `admiral.test` to `pharmaversesdtm`, new naming convention is used for dataset name:

- Datasets that are TA-agnostic: same as SDTM domain name (e.g., dm, rs)
- Datasets that are TA-specific: domain_TA_others, others go from broader categories to more specific ones (e.g., oe_ophtha, rs_onco, rs_onco_irecist).

### Definition of Done

- replace `admiral.test` by `pharmaversesdtm`
- update dataset name accordingly, e.g. input data in template 
- check if everything runs fine

**Comment by kaz462** [comment]
@jeffreyad thanks for checking. Is this function used somewhere? 

I did a thorough search in the `R/`, `vignettes/`, `inst/` folders only found it's mentioned in the argument description 

https://github.com/pharmaverse/admiral/blob/a2b224a1d54afcc58ad7f06cfa60011415b02d4e/R/create_query_data.R#L815

**Comment by jeffreyad** [comment]
I think it is used in the example on that page.

https://github.com/pharmaverse/admiral/blob/a2b224a1d54afcc58ad7f06cfa60011415b02d4e/R/create_query_data.R#L148

**Comment by kaz462** [comment]
@jeffreyad I see, thanks! I searched for "get_terms(" and missed it. Copied `get_terms()` from `{admiral.test}` in this PR:  https://github.com/pharmaverse/pharmaversesdtm/pull/50

**Comment by kaz462** [comment]
@jeffreyad `get_terms()` from `admiral.test` is available in `pharmaversesdtm` devel now
