### ISSUE TITLE
General Issue: Typo in the example `impute_dtc_dt`

### ISSUE THREAD

**Issue by ynsec37** [pharmaverse/admiral#2053]
### Background Information

The code in line 707 may be `impute_dtc_dt`
https://github.com/pharmaverse/admiral/blob/a2b224a1d54afcc58ad7f06cfa60011415b02d4e/R/derive_date_vars.R#L701-L707

**Comment by bms63** [comment]
Wow!!  Thanks @ynsec37 !!  Are you on pharmaverse slack?

**Comment by bms63** [comment]
Also - do you mind fixing this?
