### ISSUE TITLE
General Issue: Remove `print.duplicates()`

### ISSUE THREAD

**Issue by zdz2101** [pharmaverse/admiral#2054]
### Background Information

![image](https://github.com/pharmaverse/admiral/assets/43018762/2c989c46-51c3-4296-83b8-c8bc98f9ded3)
![image](https://github.com/pharmaverse/admiral/assets/43018762/9de45853-9e9a-4d10-ab8d-62926bc6c68d)

Messaging in print function is redundant, instead of traditional deprecation process as there is no suitable substitution proposal is to remove, as it exists nowhere else in our code base as well, unlikely users are using either as this was primarily for development-utility

### Definition of Done

Remove `print.duplicates()` and from codebase

**Comment by bms63** [comment]
Anyone have a memory of this function @millerg23, @rossfarrugia, @bundfussr.  I'm keen just to kick it out since there is no replacement for it.

**Comment by rossfarrugia** [comment]
Probably best to wait for @bundfussr to come back from holiday as he'd remember. My vague understanding was this function was useful as you get a console message telling you your data has unexpected duplicates and then you'd use this to print them so that you can investigate further and debug.

**Comment by bms63** [comment]
Sounds good.

**Comment by bundfussr** [comment]
We should not remove the print function. It is not called in admiral but it is called by the users. If duplicates are found, an S3 object of class `duplicates` is stored in the package environment and the user can retrieve it by calling `get_duplicates()`. The print function ensures that the `duplicates` object is printed nicely.

**Comment by zdz2101** [comment]
Closing for misinterpretation of what the print function does, in favor of completing original issue/task of making appropriate unit test for the `print.duplicates()` function in #1466
