### ISSUE TITLE
General Issue: `get_duplicate_records()`

### ISSUE THREAD

**Issue by ddsjoberg** [pharmaverse/admiral#2059]
### Background Information

From @thomas-neitmann #2019

User feedback:

> "This function is absolutely cool. It would be great to create a message which dataset is being printed by this function. For example, there may be a situation where you have duplicates in your dataset. Then:
> 1. you run get_duplicates_dataset()
> 2. you identify a duplicate
> 3. you fix a duplicate
> 4. you run signal_duplicate_records()
> 5. you no longer see a duplicate
> 6. you run get_duplicates_dataset()
> 7. The initial dataset is still being printed. 
> It may bring some confusion, so it would be cool to either reset it back to NULL (if the former function hasn't spotted any issue) once the call of a function shows no issues or to simply notify a user which dataset is being printed in the message log. A minor thing. Overall, this is an EXTREMELY useful function and having an ability to quickly spot duplicates by a desired key is BEYOND awesome; "

Based upon that I think we should implement the following:

1. When you call `get_duplicated_dataset()` information about which call generates this dataset should be printed.
2. The duplicates dataset should be "reset" the next time `signal_duplicates_records()` is called.

**Comment by ddsjoberg** [comment]
One way around this would be to print the code to run to see the duplicate values.
(Rather than including this complex call to `duplicated()`, we could wrap it in a simple fn.)

``` r
# create a data frame with duplicates
df <- data.frame(USUBJID = c(letters, letters[1:2]))
columns_to_check <- "USUBJID"

cli::cli_warn(
  c("!" = "Duplicate values were found in columns {.val {columns_to_check}}",
    "i" = "Run {.run df[duplicated(df[{shQuote(columns_to_check)}]), {shQuote(columns_to_check)}, drop = FALSE]} to print the duplicate rows.")
)
#> Warning: ! Duplicate values were found in columns "USUBJID"
#> ℹ Run `df[duplicated(df['USUBJID']), 'USUBJID', drop = FALSE]` to print the
#>   duplcicate rows.

df[duplicated(df['USUBJID']), 'USUBJID', drop = FALSE]
#>    USUBJID
#> 27       a
#> 28       b
```

<sup>Created on 2023-08-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

CAVEAT: If we won't the name (ie the symbol) of the data frame we're checking, the code printed would need to replace the data frame name with something the user would need to replace.

**Comment by zdz2101** [comment]
![image](https://github.com/pharmaverse/admiral/assets/43018762/5999dbab-ae82-4bd4-9712-ee8487a6d7e2)


Would adding something like 
`
if (nrow(duplicate_records) == 0) {
 admiral_environment$duplicates <- NULL 
}
`

fix the "clearing out the old-object" issue?

**Comment by bundfussr** [comment]
> Would adding something like `if (nrow(duplicate_records) == 0) { admiral_environment$duplicates <- NULL }`
> 
> fix the "clearing out the old-object" issue?

I think it would make the issue worse. Usually an ADaM script contains several function calls which call `signal_duplicate_records()`. If one of them creates a warning due to duplicates, the users could access the duplicates datasets only if it was the last call.

**Comment by zdz2101** [comment]
> > Would adding something like `if (nrow(duplicate_records) == 0) { admiral_environment$duplicates <- NULL }`
> > fix the "clearing out the old-object" issue?
> 
> I think it would make the issue worse. Usually an ADaM script contains several function calls which call `signal_duplicate_records()`. If one of them creates a warning due to duplicates, the users could access the duplicates datasets only if it was the last call.

Isn't that already true, if it gets called multiple times, it gets overwritten anyway? It would only catch the latest/last one

**Comment by bundfussr** [comment]
> > > Would adding something like `if (nrow(duplicate_records) == 0) { admiral_environment$duplicates <- NULL }`
> > > fix the "clearing out the old-object" issue?
> > 
> > 
> > I think it would make the issue worse. Usually an ADaM script contains several function calls which call `signal_duplicate_records()`. If one of them creates a warning due to duplicates, the users could access the duplicates datasets only if it was the last call.
> 
> Isn't that already true, if it gets called multiple times, it gets overwritten anyway? It would only catch the latest/last one

Yes, but at the moment you could fix the warnings by going from the last one to the first one. With the proposed change you couldn't even access the duplicates of the last warning.

**Comment by bms63** [comment]
Since we can't really solve it - lets close the issue and discussion.
