### ISSUE TITLE
define a admiral open source strategy (12h)

### ISSUE THREAD

**Issue by koegerr** [pharmaverse/admiral#207]
goal: how to make admiral truly open source

 - publishing strategy
 - company engagement
 - user engagement

**Comment by bms63** [comment]
I think we have a strategy now?  I was looking on Box but couldn't find it.  Do you have if there is a ppt or file for us?  

Any chance we can close this issue if we have developed a strategy and a strategy doc?

**Comment by thomas-neitmann** [comment]
Well, the package **is** open-source now so I think we're good to close.
