### ISSUE TITLE
General Issue: Updates tests with Partial Dates for `compute_duration()`

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#2077]
Hi @pharmaverse/admiral 

I noticed while reviewing https://github.com/pharmaverse/admiral/pull/2075 that there is no "funny business" happening within this function's test, e.g. bad dates or missing dates. 

Is is worth it to include a few of these in this function test?  I think so, but maybe I'm missing some key information.

## Reference Material

_Originally posted by @bms63 in https://github.com/pharmaverse/admiral/pull/2075#discussion_r1307444314_
         
```
compute_duration(
      ymd("2000-02-01"),
      ymd("2001-02"),
      out_unit = "weeks",
      add_one = FALSE,
      type = "duration"
    )
```

## Definition of Done

- [ ] Investigate if additional tests are needed for compute durations, e.g. bad dates, user error, etc.
- [ ] Implement tests for function.

**Comment by ddsjoberg** [comment]
Hey @bms63 !

What kind of funny business do you want to test? The `lubridate::ymd()` function certainly has some funny behavior here, but that is independent from our `compute_duration()` function... 

``` r
lubridate::ymd("2001-02")
#> [1] "2020-01-02"
```

<sup>Created on 2023-08-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by ddsjoberg** [comment]
Date imputation is handled separately from `compute_duration()`
