### ISSUE TITLE
implement required functions for metadata (24h)

### ISSUE THREAD

**Issue by koegerr** [pharmaverse/admiral#208]
goal: implement functionality (multiple issues) dependent on #383

**Comment by bms63** [comment]
I think we can close this now as metacore is being actively worked on and I believe all the ideas/issues in #333 are implemented or will be implemented.  

We can also experiment with the [Transfer Issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository) and move metacore/metadata issues over to it?  I'm always willing to try new things!

**Comment by statasaurus** [comment]
All functions have been implemented see metatools package
