### ISSUE TITLE
GitHub Flow CI/CD Updates

### ISSUE THREAD

**Issue by ddsjoberg** [pharmaverse/admiral#2104]
We've begun the migration to GitHub Flow for the admiral packages. This has implications for the current CI/CD workflows.

The list below was created by Dinakar of items that need to be addressed:

- [ ] There are certain workflows (such as the renv.lock propagation one) which create PRs against a devel branch for most repos.
- [ ] pkgdown workflows need to be updated to exclude devel and pre-release or other odd versions.
- [ ] DevContainer configs need to be updated to not use the devel branch for anything
- [ ] The Docker images being used for the CI stuff may need to be updated to not reference devel anywhere
- [x] (From DS) We'll also need to update the R CMD Check workflow to no longer fail with NOTES, since we expect there to be notes like "Version number contains dev suffix", or something like that)

Does this change also indicate that we'll change admiraldev to GitHub flow as well? If so, then we'll need to also change the following:
- [x]  Change the default branch in admiraldev to main
- [x] Delete devel branch
- [x] Update any documentation referring to the old workflow

Do the changes to the GH Workflows have implications for admiralonco, admiralvaccine, admiraloptha ? Will this require them to also make the change to GitHub Flow?

**Comment by bms63** [comment]
@pharmaverse/admiral FYI

**Comment by bms63** [comment]
I think all admiral products should adopt GH flow strategy

**Comment by edgar-manukyan** [comment]
@cicdguy, @rammprasad, hopefully we can just use GH flow in https://github.com/pharmaverse/oak rather.

**Comment by bms63** [comment]
Just in case - some past discussion on this issue is kept here: https://github.com/pharmaverse/admiral/issues/2003

**Comment by bundfussr** [comment]
> * We'll also need to update the R CMD Check workflow to no longer fail with NOTES, since we expect there to be notes like "Version number contains dev suffix", or something like that)

Could we update R CMD Check workflow such that it ignores the version number note but fails if other notes occur?

**Comment by rammprasad** [comment]
I am inviting @dgrassellyb to the {oak} dev team meeting tomorrow to figureout how {oak} can use the GH workflow.

**Comment by bms63** [comment]
I think we have done everything on the admiral side - on admiralci docket now.
