### ISSUE TITLE
Documentation:  more documentation clarity at 'derive_var_trtemfl' function's 'end_window' argument 

### ISSUE THREAD

**Issue by skedare** [pharmaverse/admiral#2107]
### Please select a category the issue is focused on?

Function Documentation

### Let us know where something needs a refresh or put your idea here!

We were at R/Pharma workshop at Posit 2023, during {admiral} training session, I had to go through documentation  couple of times before catching the 'unit' used for 'derive_var_trtemfl' function's 'end_window' argument - which is in 'days'. I suggest to update the documentation to explicitly mention the unit as 'days' at first sentence of current documentation.

Current Docuemntation: "If the argument is specified, events starting more than the specified number of days after end of treatment, are not flagged."

**Comment by bms63** [comment]
@pharmaverse/admiral any thoughts?

**Comment by manciniedoardo** [comment]
Happy for this update to be made.

**Comment by skedare** [comment]
Sure, I would like to do it. This is my first, so I am excited as well 👍🏼 
I will open PR once updated. Thanks!

**Comment by bms63** [comment]
Awesome - I added you to the repo as a collaborator (easiest way for new folks to plug in)

There is a Dummy Issue, https://github.com/pharmaverse/admiral/issues/1839, with a video walkthrough that can give you some orientation on where things are and how to do things.  It is a little out of date, but you can get the basics from it.

You can either do the suggest dummy PR or just use this issue for your PR.  Let me know if you have any questions.

**Comment by bms63** [comment]
Hi @skedare just checking in on your progress and if you need any help.

**Comment by skedare** [comment]
@bms63 glad I started working on my first contribution, looks like I need to begin from scratch - currently struggling with R Environment - submitted a question with errors at Slack Channel.

**Comment by bms63** [comment]
Hi @skedare haven't heard from you.  Going to put this one up for the admiral devs to work on.  Thanks again for making this issue.  

@pharmaverse/admiral Hey folks - quick and easy documentation update is up for grabs.
