### ISSUE TITLE
Bug: `type` argument not available in `derive_vars_duration()`

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#2112]
### What happened?

In the last release we added the `type` argument to `compute_duration()` and changed the default behavior but we did not add it to `derive_vars_duration()`. I.e., the behavior of `derive_vars_duration()` has changed but there is no way for the users to get back the old behavior.

Thus we should add the `type` argument to `derive_vars_duration()`. Maybe we should also add it to `derive_vars_aage()`. The behavior of `derive_vars_aage()` was changed as well (most likely unintentional). At least the old behavior should be restored.

It should also checked if other functions might be affected by the change in `compute_duration()`.

**Comment by bundfussr** [comment]
@bms63 , @manciniedoardo , do we need a hotfix for this issue?

**Comment by rossfarrugia** [comment]
Also https://pharmaverse.github.io/admiral/cran-release/reference/derive_vars_aage.html still says:
![image](https://github.com/pharmaverse/admiral/assets/82581364/693924b7-e186-4b7e-b88c-758aa54bb182)

This is the type of challenge when we change default behaviours. I would always try to avoid this where possible. We have to make downstream updates now in admiralroche to change this, and also we can't even make those until this gets fixed as we can't change the type argument when using those functions. So people run the same code now but would get different results that wouldn't match our specs.

I would vote for a hotfix.

**Comment by rossfarrugia** [comment]
Note that the above details could stay if AAGE function keeps type="interval" as default as @millerg23 just suggested - i would agree with that. but user still needs the option to come through so they could change that.

**Comment by bms63** [comment]
I think we should do a hotfix for this and #2113  - is this coming from the roche testing?

**Comment by bundfussr** [comment]
> I think we should do a hotfix for this and #2113 - is this coming from the roche testing?

It comes from reviewing and preparing the upcoming admiralroche release.

**Comment by bms63** [comment]
I'm wondering if that review can be done before we release admiral.  You guys always find the goodies!

**Comment by rossfarrugia** [comment]
We do try @bms63 as we base our development on latest development versions of admiral, but as its many of the same folks involved we don't often get chance to focus too much on admiralroche until we get admiral release done first

**Comment by bms63** [comment]
I'm just wondering if there is a way we could automate admiralroche testing to get us the feedback before the release??  I guess this won't really matter once we are changing less!!!

**Comment by millerg23** [comment]
We are working on it!

**Comment by bms63** [comment]
@ddsjoberg and @cicdguy we need to do a hotifx for #2112 and #2113.  

The `main` hasn't been changed since release, but we want to act as if we have done a bunch of stuff to `main` that we don't want to release just yet.  How do we achieve this under our new GitHub Flow Strategy?  Thanks for your help!!

**Comment by ddsjoberg** [comment]
> I'm just wondering if there is a way we could automate admiralroche testing to get us the feedback before the release?? I guess this won't really matter once we are changing less!!!

If anyone from within Roche who also has a `getOption("repos")` set to a proper repo where admiralroche is stored (aka to the package manager), we can just run the revdepchecks and it will run all the reverse dependency checks on admiralroche.

**Comment by ddsjoberg** [comment]
> @ddsjoberg and @cicdguy we need to do a hotifx for #2112 and #2113.
> 
> The `main` hasn't been changed since release, but we want to act as if we have done a bunch of stuff to `main` that we don't want to release just yet. How do we achieve this under our new GitHub Flow Strategy? Thanks for your help!!

Since there have been no changes to main, I would just make the updates on a new feature branch, create a PR into main. Once the PR is reviewed and merged, make a regular release from main.

**Comment by bms63** [comment]
> > @ddsjoberg and @cicdguy we need to do a hotifx for #2112 and #2113.
> > The `main` hasn't been changed since release, but we want to act as if we have done a bunch of stuff to `main` that we don't want to release just yet. How do we achieve this under our new GitHub Flow Strategy? Thanks for your help!!
> 
> Since there have been no changes to main, I would just make the updates on a new feature branch, create a PR into main. Once the PR is reviewed and merged, make a regular release from main.

Well - I was thinking we should do it the tag(?) way where we don't want to release everything in main just yet - just for practice and understanding on how to deploy a hotfix.   I think this is needed more now as we want to disturb `admiralroche` as little as possible.  

I figured this is the best time to do it as things are clean and nice in `main` and the in the release v0.12.
