### ISSUE TITLE
Website:  Button that reroutes to our slack instead of parsing through community tab

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiral#2127]
### Please select a category the issue is focused on?

I have a new documentation idea! Yay!

### Let us know where something needs a refresh or put your idea here!

See suggestion [here](https://github.com/pharmaverse/admiral/discussions/2089#discussioncomment-6951634) by @zdz2101.

**Comment by sophie-gem** [comment]
A couple of qs:
* Do we want to remove the Slack link from under the community tab, if we're having a direct 'button'?
* Are we also wanting to include a mail button as @zdz2101 suggested (and if so, do we have a generic email)?

**Comment by manciniedoardo** [comment]
> A couple of qs:
> 
> * Do we want to remove the Slack link from under the community tab, if we're having a direct 'button'?
> * Are we also wanting to include a mail button as @zdz2101 suggested (and if so, do we have a generic email)?

* Might be nice to have both?
* Unfortunately we don't have a generic email address, so not sure how to proceed there. I actually feel it would be more productive and efficient to include a button that instantly takes you to the the new issue page on GH as that would be seen by the whole team. @pharmaverse/admiral thoughts?

**Comment by sophie-gem** [comment]
Thanks @manciniedoardo ! 
* I'll keep the two methods for getting to Slack then. 
* I agree, if we make it as 'clear/simple' as possible for giving feedback then users may be more inclined to provide it. But will wait to hear others opinions before I implement.

**Comment by bundfussr** [comment]
> > A couple of qs:
> > 
> > * Do we want to remove the Slack link from under the community tab, if we're having a direct 'button'?
> > * Are we also wanting to include a mail button as @zdz2101 suggested (and if so, do we have a generic email)?
> 
> * Might be nice to have both?
> * Unfortunately we don't have a generic email address, so not sure how to proceed there. I actually feel it would be more productive and efficient to include a button that instantly takes you to the the new issue page on GH as that would be seen by the whole team. @pharmaverse/admiral thoughts?

I agree.

By the way, should we change
```
BugReports: https://github.com/pharmaverse/admiral/issues
```
in `DESCRIPTION` to
```
BugReports: https://github.com/pharmaverse/admiral/issues/new/choose
```
?

**Comment by bms63** [comment]
> A couple of qs:
> 
> * Do we want to remove the Slack link from under the community tab, if we're having a direct 'button'?
I'd like to keep both as I'm not a big slack user and didn't even know that was the symbol till we put it into a project I was working on lol

> * Are we also wanting to include a mail button as @zdz2101 suggested (and if so, do we have a generic email)?
Reluctant as I don't want to monitor the email.

**Comment by bms63** [comment]
> > > A couple of qs:
> > > 
> > > * Do we want to remove the Slack link from under the community tab, if we're having a direct 'button'?
> > > * Are we also wanting to include a mail button as @zdz2101 suggested (and if so, do we have a generic email)?
> > 
> > 
> > 
> > * Might be nice to have both?
> > * Unfortunately we don't have a generic email address, so not sure how to proceed there. I actually feel it would be more productive and efficient to include a button that instantly takes you to the the new issue page on GH as that would be seen by the whole team. @pharmaverse/admiral thoughts?
> 
> I agree.
> 
> By the way, should we change
> 
> ```
> BugReports: https://github.com/pharmaverse/admiral/issues
> ```
> 
> in `DESCRIPTION` to
> 
> ```
> BugReports: https://github.com/pharmaverse/admiral/issues/new/choose
> ```
> 
> ?

@ddsjoberg we need your sage advice here on changing up the issues/bug link in the `DESCRIPTION`.  See any "issues"?

**Comment by ddsjoberg** [comment]
> @ddsjoberg we need your sage advice here on changing up the issues/bug link in the DESCRIPTION. See any "issues"?

1. "issues" lol 😆 @bms63 
2. It's typical to add the link to the issues page, but I don't think there is anything wrong with linking to the "new issue" page. While I think it's largely a non-issue, I would vote in favor of linking to the issues page, so someone could more easily see if there was already an open issue for the bug they are about to report.
