### ISSUE TITLE
Check if error messages are descriptive enough

### ISSUE THREAD

**Issue by thomas-neitmann** [pharmaverse/admiral#213]
Please refer to the "Questions and Comments" document on Box.

**Comment by esimms999-gsk** [comment]
This is from feedback collected on 10Jun2021 in https://exbpbox.box.com/s/2c8wp5wb93kkq53e9tuhwca2el38c4je 

- Q: Which features are you missing in admiral?    
- A: more meaningful error messages (`exprs` vs `expr`)

This is very general and is something which needs constant attention in the same manner as "Ensure vignettes make sense." I recommend that we close this issue.
