### ISSUE TITLE
Documentation:  Adding an RStudio style cheatsheet

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiral#2130]
### Discussed in https://github.com/pharmaverse/admiral/discussions/2018

<div type='discussions-op-text'>

<sup>Originally posted by **zdz2101** October 24, 2022</sup>
### Please select a category the issue is focused on?

User Guides

### Let us know where something needs a refresh or put your idea here!

Would be interesting to create an RStudio-style cheatsheet for admiral, especially popularly used functions/family of functions:

https://github.com/rstudio/cheatsheets/blob/main/README.md</div>

# Definition of Done

- [x] Create cheatsheet
- [ ] Find home for the cheatsheet
- [ ] Add to Website
- [ ] Add link to Readme

**Comment by bms63** [comment]
@manciniedoardo can we close this as there is a cheatsheet now

**Comment by manciniedoardo** [comment]
maybe keep open for the edit to the website readme once we add it there too?

**Comment by bms63** [comment]
K I added some checklist items - feel free to add additional if needed.
