### ISSUE TITLE
Feature Request:  Handle potential floating point issues by using function signif()

### ISSUE THREAD

**Issue by millerg23** [pharmaverse/admiral#2134]
### Feature Idea

Whilst developing DAIDS grading criteria it was discovered that R is susceptible to floating point issues, and as such the grading metadata was updated to use the `signif()` function when comparing 2 variables.
ie `AVAL > ANRHI` was changed to `signif(AVAL, 15) > signif(ANRHI, 15)` the value of 15 is passed into function `derive_vars_atoxgr_dir`.
We need to look if any other occurences need a similar solution, for example function `derive_var_anrind()`.

Also, should the number of signficant digits we use in admiral be stored in a general option, thus making it easier for a company/study to change in a central place? (Perhaps a separate issue).

**Comment by bms63** [comment]
@StefanThoma might be of interest to you

**Comment by StefanThoma** [comment]
Thanks, @bms63

**Comment by bms63** [comment]
We should link @StefanThoma blog post in the changelog https://github.com/pharmaverse/blog/pull/92
