### ISSUE TITLE
Bug: Time imputation flag incorrect

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#2146]
### What happened?

In the following case the time imputation flag is not derived correctly.
```
> compute_tmf("2022-05--T00:00", ymd_hms("2022-05-15T23:59:59"))
[1] "S"
```
It should be `"H"` as the hours were changed.

**Comment by bundfussr** [comment]
> ummm...this is unfortunate. Can we hold off until `1.0` ? CRAN gets a little testy when we re-submit the package frequently.

Yes, it's a rare edge case.

**Comment by ddsjoberg** [comment]
I can take a look at this one: I like a fun regex! But i have a question about the function. The function's description is 

> Derive the time imputation flag (`'--TMF'`) comparing a date character vector (`'--DTC'`) with a Datetime vector (`'--DTM'`).

I am not sure what the comparison part is. Anyway, if anyone has time to talk through the intent of the function, I can updated the regex. Otherwise, someone who knows the function can just do it too :)

**Comment by bundfussr** [comment]
> I can take a look at this one: I like a fun regex! But i have a question about the function. The function's description is
> 
> > Derive the time imputation flag (`'--TMF'`) comparing a date character vector (`'--DTC'`) with a Datetime vector (`'--DTM'`).
> 
> I am not sure what the comparison part is. Anyway, if anyone has time to talk through the intent of the function, I can updated the regex. Otherwise, someone who knows the function can just do it too :)

The character vector (`dtc`) is the collected date and the datetime vector (`dtm`) is the imputed date. The function should determine the "highest" time component (`"H"`, `"M"`, or `"S"`) where collected and imputed date differ.
> 
> Also, the number of hyphens is confusing me. Are hyphens used to separate years, months, days, as well as representing a missing day/month/year?

Yes
> 
> ```r
> dates <- (
>   "2019-02",
>   "2019",
>   "2019",
>   "2019---07",
>   ""
> )
> ```
