### ISSUE TITLE
Shorten dev version install instructions

### ISSUE THREAD

**Issue by ddsjoberg** [pharmaverse/admiral#2151]
When we switch to using `Remotes:` in place of staged dependencies, let's also simplify the installation instructions for the dev version of admiral. At the moment, the far-less used instructions are given a bit too much real estate on the home page. 

What is looks like now:
![image](https://github.com/pharmaverse/admiral/assets/26774684/9a8aa918-d721-4693-a7ea-47e3003de26e)

Proposal:
1. Use a code block for `install.packages("admiral")` instead of `code formatting`.
2. Update the code block for dev version to something like this

```r
# install.packages("devtools")
devtools::install_github("pharmaverse/admiral")
```

**Comment by bms63** [comment]
Can the two (staged.dependencies and remotes) exists at the same time?

**Comment by ddsjoberg** [comment]
@bms63 there is no reason they can't coexist.

**Comment by bms63** [comment]
If they can co-exist, then I think we can make this update in the Description and update the instructions?
