### ISSUE TITLE
Some deprecated arguments are not using the lifecycle badge

### ISSUE THREAD

**Issue by ddsjoberg** [pharmaverse/admiral#2175]
- https://github.com/pharmaverse/admiral/blob/9bdd50cfdc7478343751078c9f7a9ea358434e76/R/derive_expected_records.R#L9
- https://github.com/pharmaverse/admiral/blob/9bdd50cfdc7478343751078c9f7a9ea358434e76/R/derive_locf_records.R#L9
- https://github.com/pharmaverse/admiral/blob/9bdd50cfdc7478343751078c9f7a9ea358434e76/R/derive_vars_aage.R#L38

See the file [R/derive_var_extreme_date.R](https://github.com/pharmaverse/admiral/blob/main/R/derive_var_extreme_date.R) for an example on how to add a badge for an argument

![image](https://github.com/pharmaverse/admiral/assets/10111024/dc75a9ec-4eb1-4ee2-a596-8b60d85457a7)

# Definition of Done

- [ ] Add badges to the arguments identified above
- [ ] Review changleog to see if any other deprecated arguments are missing

**Comment by bms63** [comment]
@sadchla-codes will you be able to complete this before our release on December 4th?

**Comment by sadchla-codes** [comment]
> @sadchla-codes will you be able to complete this before our release on December 4th?

Hi @bms63 , yes!

**Comment by ddsjoberg** [comment]
Yes, i'll be backup 🚚

**Comment by manciniedoardo** [comment]
Just spoke to @sadchla-codes who has study pressure, @ddsjoberg please feel free to work on this  - there should already be a branch set up by Sadchla.
