### ISSUE TITLE
Feature Request: Implement `derive_vars_computed()`

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#2178]
### Feature Idea

Implement
```
derive_vars_computed( 
  dataset, 
  dataset_add, 
  by_vars, 
  parameters, 
  new_vars, 
  filter_add = NULL, 
  constant_by_vars = NULL, 
  constant_parameters = NULL, 
  keep_nas = FALSE 
) 
```
The function should provide the same functionality as `derive_param_computed()` but instead of adding the computed values as new parameter they should be added as new variable.

**Comment by bms63** [comment]
Hi Gayatri - I'd like to get this out in `1.0` release.  Do you think you can make this feature the week before December 4th?  We will need to time to review

**Comment by gg106046** [comment]
> Hi Gayatri - I'd like to get this out in `1.0` release. Do you think you can make this feature the week before December 4th? We will need to time to review

Hi Ben! Yes I can. I've started working on it.

**Comment by bms63** [comment]
@romainfrancois I saw you made a branch on this - did you want to work on this?

**Comment by gg106046** [comment]
Hi @bundfussr! Are you expecting parameters like 'BMI', 'MAP' (from the examples of `derive_param_computed()`) to be added as new variables in this function or were you thinking of a different example altogether. Asking this for the documentation/example part.

**Comment by bundfussr** [comment]
> Hi @bundfussr! Are you expecting parameters like 'BMI', 'MAP' (from the examples of `derive_param_computed()`) to be added as new variables in this function or were you thinking of a different example altogether. Asking this for the documentation/example part.

The function should add variables. For example, it could be called to add a variable for the baseline value of BMI to ADSL:
```
derive_vars_computed( 
  dataset = adsl, 
  dataset_add = advs, 
  by_vars = exprs(USUBJID), 
  parameters = c("WEIGHT", "HEIGHT"), 
  new_vars = exprs(BMIBL = compute_bmi(height = AVAL.HEIGHT, weight = AVAL.WEIGHT)), 
  filter_add = ABLFL == "Y"
)
```

**Comment by bms63** [comment]
@gg106046 just checking in on progress.  Do you think you can have something for us to review by the end of the week.  We are trying to release on December 4th.

**Comment by gg106046** [comment]
> @gg106046 just checking in on progress. Do you think you can have something for us to review by the end of the week. We are trying to release on December 4th.

Hi @bms63 ! I'll create a PR for it by tomorrow EOB.
