### ISSUE TITLE
General Issue: why filter_add argument does not work in my function.

### ISSUE THREAD

**Issue by secondbookwormai** [pharmaverse/admiral#2180]
### Background Information

why my filter_add does not work. 
In the admiral packages, filter_add argument for a function is used widely. 
the following is my example :
df = data.frame(x = letters[1:3])
get.filtered.df = function(df, filter_add){
  df %>% filter(filter_add)
} 
get.filtered.df(df=df, filter_add =x == 'a') 
[1] x
<0 rows> (or 0-length row.names)

how come it does not work ?

**Comment by manciniedoardo** [comment]
Hi @secondbookwormai thanks for reaching out. In your specific example, you need `assert_filter_cond` and `filter_if` from `{admiraldev}`. The first function checks that what you pass to the `filter_add` argument is a filtering condition, and the second function then performs the filtering. I've fixed your example below.
```
library(admiraldev)

df = data.frame(x = letters[1:3])

get.filtered.df = function(df, filter_add){
  
  filter_add <- assert_filter_cond(enexpr(filter_add), optional = TRUE)
  
  return(admiraldev::filter_if(df, filter_add))
}

get.filtered.df(df = df, filter_add = x == 'a')
```
I will now close this issue as this is not an issue about the `{admiral}` package itself.
