### ISSUE TITLE
Feature Request:  `keep_source_var` to be applicable across appropriate family of functions

### ISSUE THREAD

**Issue by zdz2101** [pharmaverse/admiral#2185]
### Feature Idea
https://github.com/pharmaverse/admiral/discussions/2010#discussioncomment-6659822 

https://pharmaverse.slack.com/archives/C028SJ83KM1/p1692633891115359

In our slack post, we have a proposal to make the argument `keep_source_var` consistent across all selection functions which add new observations.

**Comment by zdz2101** [comment]
> Didn't we implement it in #1697?

Think we missed some, I have a draft for `derive_param_tte()` for example

**Comment by bms63** [comment]
It was decided to not implement this feature.  See here for discussion - https://github.com/pharmaverse/admiral/pull/2215#discussion_r1388401569
