### ISSUE TITLE
Bug Link on pkgdown site

### ISSUE THREAD

**Issue by ddsjoberg** [pharmaverse/admiral#2208]
I missed last week's meeting (and unfortunately will miss this week's meet as well) and perhaps it was already discussed.

The new bug link on the site is very cute! But there is a link right below it for the same thing. In the spirit on minimalist design, should we remove the second link?
![image](https://github.com/pharmaverse/admiral/assets/26774684/9409c6a6-02fc-415e-8a83-11fa01a25632)

**Comment by manciniedoardo** [comment]
If no qualms about this request from anyone in @pharmaverse/admiral , @sophie-gem could you take this please?

**Comment by bundfussr** [comment]
I would not remove the link.

If we have both the text link and the icon, it is easier to find for the users.

**Comment by bms63** [comment]
We should keep the bug.  

![image](https://github.com/pharmaverse/admiral/assets/10111024/4303c3da-5407-476a-8b2d-558265c978ae)
