### ISSUE TITLE
Update navbar "Reference" link

### ISSUE THREAD

**Issue by ddsjoberg** [pharmaverse/admiral#2217]
We will update this link to a dropdown with one link to the reference page and one to the admiraldiscovery table. This will occur after admiraldiscovery has made it's first release

**Comment by bms63** [comment]
What about in User Guides at the top?  Just so we don't deviate too much from other pkgdown sites with a Reference tab as a dropdown?  

Also, maybe link to the Cheatsheet should go in under it as well.

![image](https://github.com/pharmaverse/admiral/assets/10111024/a14dd908-5d84-4acd-8acd-50f2c21269bf)

**Comment by ddsjoberg** [comment]
@ddsjoberg and @bms63 met to discuss
- [ ] Get Started will be a drop down with the getting started vignette, admiral discovery link, and the cheatsheet
- [ ] Remove the community drop down menu form nav bar

**Comment by bms63** [comment]
@ashachakma  are you all good with working on this update?  We need it a week before Dec 4th

**Comment by bms63** [comment]
Hey @ashachakma  can you confirm that you can work on this issue.  I think deadline is end of this week/early next week. 

One thing is I want to make sure the contribution vignette is linked on the Readme.  Can discuss more once you get started.

**Comment by ashachakma** [comment]
Hi Ben, sorry for replying late, didn't check gmail notification for long. I am starting to work on it today and I will try to finish it by early next week.

**Comment by ashachakma** [comment]
@bms63 @ddsjoberg for the community drop down, are we entirely removing the community from the nav bar or just the drop downs of community? If Its only the drop down, then which link will go with this nav bar?? Is the contribution-model or slack or the pharmaverse one?

**Comment by bms63** [comment]
We want to remove the community drop down from the top.
