### ISSUE TITLE
Add DTHCGR1 and DTHCAUS to ADSL template

### ISSUE THREAD

**Issue by khatril** [pharmaverse/admiral#2218]
### Background Information

Please add death variables DTHCAT and DTHCAUS to the admiral ADSL templates, this is to support the creation of death outputs using {pharmaverseadam} in the TLG-catalog.

### Definition of Done

see above

**Comment by bundfussr** [comment]
`DTHCAT`  is not a CDISC variable but a Roche specific variable. Unfortunately, it is not CDISC compliant because CDISC suggests `DTHCGRy` for groupings of cause of death. Therefore I would add `DTHCGR1` instead of `DTHCAT`.

**Comment by bms63** [comment]
@pharmaverse/admiral shall we add this into the `1.0` release?

**Comment by bundfussr** [comment]
> @pharmaverse/admiral shall we add this into the `1.0` release?

I think it is not so important for admiral. But if it is not included in 1.0, it can not be implemented before mid of next year because we change to a six months release cycle.

**Comment by bms63** [comment]
We can also do a small minor release if something is critical for a downstream package

**Comment by bms63** [comment]
@gg106046 this might be a good one for Azra
