### ISSUE TITLE
Documentation:  Rehab the Reference Page

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#2220]
### Please select a category the issue is focused on?

Function Documentation

### Let us know where something needs a refresh or put your idea here!

As we push to `1.0` we are trying to reduce the number of functions visible in our documentation that are not helpful for users.

For theses eleven functions:  8 will be completely removed and 3 will be exported but have keywords/family changed to internal.

* Remove:  We no longer should export this functions and so `@export` is removed and keywords and family removed
* Export, but change keyword to internal:  These functions should still be exported, but their keyword and family changed to internal so they no longer appear on our reference page.  

[assert_db_requirements()](https://pharmaverse.github.io/admiral/dev/reference/assert_db_requirements.html) - Remove
[assert_terms()](https://pharmaverse.github.io/admiral/dev/reference/assert_terms.html) - Remove
[assert_valid_queries()](https://pharmaverse.github.io/admiral/dev/reference/assert_valid_queries.html) - Remove
[extend_source_datasets()](https://pharmaverse.github.io/admiral/dev/reference/extend_source_datasets.html) - Remove
[filter_date_sources()](https://pharmaverse.github.io/admiral/dev/reference/filter_date_sources.html) - Remove
[format(<basket_select>)](https://pharmaverse.github.io/admiral/dev/reference/format.basket_select.html) - Export, but change keyword to internal
[validate_basket_select()](https://pharmaverse.github.io/admiral/dev/reference/validate_basket_select.html) - Remove
[validate_query()](https://pharmaverse.github.io/admiral/dev/reference/validate_query.html) - Remove
~~[chr2vars()](https://pharmaverse.github.io/admiral/dev/reference/chr2vars.html) - Remove~~
~~[signal_duplicate_records()](https://pharmaverse.github.io/admiral/dev/reference/signal_duplicate_records.html) - Export, but change keywords to internal~~
[extract_duplicate_records()](https://pharmaverse.github.io/admiral/dev/reference/extract_duplicate_records.html) - Export, but change keywords to internal

# Definition of Done

- [x] All 11 functions documentation updated
- [ ] Check vignettes and templates are NOT using the 11 functions
- [x] Update to News to list out what we have removed/suppressed - no need to do any deprecation process.
- [x] Check that no extension packages might be using these 11 functions.
- [ ] Proceed with normal PR.

Hi @pharmaverse/admiral another nice one!!

**Comment by bundfussr** [comment]
@bms63 , should we create an issue in admiraldev to update the programming strategy?

**Comment by bms63** [comment]
Yes!  Good call.  I will make an issue

**Comment by bms63** [comment]
> @bms63 , should we create an issue in admiraldev to update the programming strategy?

@bundfussr https://github.com/pharmaverse/admiraldev/issues/346

**Comment by sophie-gem** [comment]
I can pick this up and do this tomorrow morning.

**Comment by sophie-gem** [comment]
Note to self: 4 templates (from ADPP) and vignettes left to check.

**Comment by sophie-gem** [comment]
Hi @bms63 , @bundfussr , in terms of checking the admiral extension packages for this...have I remembered all below:

- [ ] admiraloptha
- [ ] admiralonco
- [ ] admiralvaccine

Also, is anyone able to check your company specific admiral packages: admiralroche, admiralgsk, etc?

**Comment by bundfussr** [comment]
> Hi @bms63 , @bundfussr , in terms of checking the admiral extension packages for this...have I remembered all below:
> 
> * [ ]  admiraloptha
> * [ ]  admiralonco
> * [ ]  admiralvaccine
> 
> Also, is anyone able to check your company specific admiral packages: admiralroche, admiralgsk, etc?

@sophie-gem , you remembered the extensions packages correctly.

I have checked admiralroche. It uses `chr2vars()` and `signal_duplicates_records()`.

**Comment by bms63** [comment]
> > Hi @bms63 , @bundfussr , in terms of checking the admiral extension packages for this...have I remembered all below:
> > 
> > * [ ]   admiraloptha
> > * [ ]   admiralonco
> > * [ ]   admiralvaccine
> > 
> > Also, is anyone able to check your company specific admiral packages: admiralroche, admiralgsk, etc?
> 
> @sophie-gem , you remembered the extensions packages correctly.
> 
> I have checked admiralroche. It uses `chr2vars()` and `signal_duplicates_records()`.

Then we should still export chr2vars but use internal? @bundfussr

**Comment by bundfussr** [comment]
> > > Hi @bms63 , @bundfussr , in terms of checking the admiral extension packages for this...have I remembered all below:
> > > 
> > > * [ ]    admiraloptha
> > > * [ ]    admiralonco
> > > * [ ]    admiralvaccine
> > > 
> > > Also, is anyone able to check your company specific admiral packages: admiralroche, admiralgsk, etc?
> > 
> > 
> > @sophie-gem , you remembered the extensions packages correctly.
> > I have checked admiralroche. It uses `chr2vars()` and `signal_duplicates_records()`.
> 
> Then we should still export chr2vars but use internal? @bundfussr

I would export both and also list them on the reference page.

**Comment by sophie-gem** [comment]
So given what @bundfussr said above, I will retract the changes to `chr2vars()` and `signal_duplicates_records()` and check the 3 admiral extensions (R functions, templates, and vignettes) for any of these functions.

**Comment by bms63** [comment]
Awesome thanks @sophie-gem !!

**Comment by sophie-gem** [comment]
Note to self: No templates contain these functions. Rest of vignettes left to check from bds_finding onwards.

**Comment by bms63** [comment]
Hey @sophie-gem can you finish this by the end of the week?

**Comment by sophie-gem** [comment]
Ah, so sorry - dropped off the planet again! Yes, I will aim to get this done by EOB Friday. Is that ok?

**Comment by bms63** [comment]
> Ah, so sorry - dropped off the planet again! Yes, I will aim to get this done by EOB Friday. Is that ok?

yes no problem!
