### ISSUE TITLE
Loss of the variable labels after using `restrict_derivation()`

### ISSUE THREAD

**Issue by kaz462** [pharmaverse/admiral#2227]
the variable labels are missing after using `restrict_derivation()`
``` r
library(pharmaversesdtm)
library(dplyr)
library(admiral)
data("vs")
attributes(vs$STUDYID)
#> $label
#> [1] "Study Identifier"
test <- vs %>%
  restrict_derivation(
    derivation = derive_var_extreme_flag,
    args = params(
      by_vars = exprs(USUBJID, VSTESTCD, VISIT),
      order = exprs(VSTPTNUM),
      new_var = LASTFL,
      mode = "last"
    ),
    filter = VISIT != "BASELINE"
  )
attributes(test$STUDYID)
#> NULL
```

<sup>Created on 2023-11-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by bundfussr** [comment]
At the moment, we do not care about variable labels. I assume other admiral functions lose the variable labels as well.

In the vignettes we add labels in the last step.

I am not sure if we should change this. It could be a lot of work to preserve the labels. Maybe we should just point out that admiral functions do not preserve variable labels.

@pharmaverse/admiral , what do you think?

**Comment by manciniedoardo** [comment]
I don't think this is worth our time. admiral doesn't really deal with labels anyway so the expectation is that you apply them at the end of your script.

**Comment by bms63** [comment]
My understanding is there are some dplyr functions stripping the labels off the variables while they are doing their fanciness.  I 
don't think there is much we can do about it except rebuild the function using base R.  Or re-apply the label post-processing for the user (which I don't think we should do).
