### ISSUE TITLE
Documentation:  Update links to templates on GitHub to recommended code `use_ad_template("ADaM")`

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#2239]
### Please select a category the issue is focused on?

User Guides

### Let us know where something needs a refresh or put your idea here!

We have these links to the templates that link to our `main` branch.  As `main` is now our **_development_** branch, these templates could be in active development with new features/re-work and so we should stop using the links.  Potential confusing for users

![image](https://github.com/pharmaverse/admiral/assets/10111024/da25fa38-fdac-4d81-ad8a-051d54cc8c1c)

Instead we should recommend the users to make use of the code that can render these templates in the package.  `use_ad_template("ADaM")`  

# Definition of Done

- [ ] All user guides have the links updated to recommended code

**Comment by bms63** [comment]
Another good one!  @pharmaverse/admiral 

@ddsjoberg in admiraldiscovery - maybe we should re-think the linkage and just recommend the code to get the template?  Although, I can't imagine things are going to so drastically change from 1.0 to 1.1 to 2.0, but just trying to think of ways to minimize user confusion.  - @pharmaverse/admiral  any thoughts?

![image](https://github.com/pharmaverse/admiral/assets/10111024/97c2d57b-9223-4f07-aadd-f10f1fffcdb8)

**Comment by ddsjoberg** [comment]
I certainly see where this is coming from, but i do agree there will be little change between versions and browsing the templates in a browser is a much better experience than opening R, running a function, and searching in a script.

Perhaps as a middle ground, we could add some text above the table saying the links are to the latest versions available, and they can use the template functions in their R session to get the template associated with their installed version. That said, I don't want to try to maintain this table for different versions of the admiral packages if things do change: only the latest and greatest will be shown here.

**Comment by bms63** [comment]
> I certainly see where this is coming from, but i do agree there will be little change between versions and browsing the templates in a browser is a much better experience than opening R, running a function, and searching in a script.
> 
> Perhaps as a middle ground, we could add some text above the table saying the links are to the latest versions available, and they can use the template functions in their R session to get the template associated with their installed version. That said, I don't want to try to maintain this table for different versions of the admiral packages if things do change: only the latest and greatest will be shown here.

Love it!!

**Comment by bundfussr** [comment]
I would not expect big changes in 1.1 but there could be major changes in 2.0 when we rename the functions to be more consistent.

I assume the links are generated automatically, i.e., the URL is defined in only one place. What about changing it from main to v1.0.0? We would need to update this for every release but it is only every six months.

**Comment by ddsjoberg** [comment]
> What about changing it from main to v1.0.0? We would need to update this for every release but it is only every six months.

What do you think of a link to the latest release, rather than a hard link. Then there is no need to update
https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases

**Comment by bundfussr** [comment]
> > What about changing it from main to v1.0.0? We would need to update this for every release but it is only every six months.
> 
> What do you think of a link to the latest release, rather than a hard link. Then there is no need to update https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases

If it is possible to link to a specific file in the latest release, that would be a better solution. However, I am not sure if it is possible. Replacing "main" by "latest" or "releases/latest" did not work.

**Comment by ddsjoberg** [comment]
I hadn't test, but I think you're correct. That extension doesn't allow us to link to a file from the latest release.

For the sake of simplicity, in admiraldiscovery i'll just add the note mentioned above that the templates link to the most recent version of the template available, and they may need to look at the template for their specific version.
