### ISSUE TITLE
General Issue: Time Units Set by Duration Functions

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#2255]
### Background Information

The following issue was reported by a user:

> Whilst creating `ADCM.LDRELTMU` I had an error with metacore that `"MINUTES"` is not in the controlled terminology. The actual value is `"min"`. Updating the derivation as below is only partly successful, as the unit also needs to be lowercased.
> ```
>   derive_vars_duration(
>    new_var = LDRELTM,
>    new_var_unit = LDRELTMU,
>    start_date = ASTDTM,
>    end_date = LDOSEDTM,
>    in_unit = "seconds",
>    out_unit = "min",
>    add_one = FALSE
>  )
>```

The following CDISC codelist was used
![image](https://github.com/pharmaverse/admiral/assets/80953585/bb77f92e-3827-4e9c-8ce1-089e1f1bb71f)

Currently, the unit variable is set to the upper case value of `out_unit`.

Possible solutions:
- Set the unit variable to the (unchanged) value of `out_unit` and accept a variety of values like `"MIN"`, `"min"`, `"MINUTES"`, `"minutes"`, `"MINUTE"`, `"minute"`, ... (Should the same values be valid for `in_unit` then?)
- Accept `"years"`, `"months"`, `"days"`, `"hours"`, `"minutes"`, `"seconds"` for `out_unit` only and add an argument for the value of the unit variable.
- Accept `"years"`, `"months"`, `"days"`, `"hours"`, `"minutes"`, `"seconds"` for `out_unit` only and add an argument expecting a function which maps the `out_unit` values to other values like the codelist values. (default value?)

@bms63 , @manciniedoardo , what do you think?

**Comment by manciniedoardo** [comment]
Decision from meeting: Go with fix number 1 (update in_unit and out_unit to accept all possible options)
