### ISSUE TITLE
Release admiral 1.0.0

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#2256]
Prepare for release:

* [ ] `git pull`
* [ ] Check [current CRAN check results](https://cran.rstudio.org/web/checks/check_results_admiral.html)
* [x] Check if any deprecation processes should be advanced, as described in [Gradual deprecation](https://lifecycle.r-lib.org/articles/communicate.html#gradual-deprecation)
* [x] [Polish NEWS](https://style.tidyverse.org/news.html#news-release)
* [x] `urlchecker::url_check()`
* [x] `devtools::check(remote = TRUE, manual = TRUE)`
* [ ] `devtools::check_win_devel()` - doesn't work with Remtoes
* [ ] `rhub::check_for_cran()`
* [x] `revdepcheck::revdep_check(num_workers = 4)`
* [ ] Update `cran-comments.md`
* [ ] `git push`
* [ ] Draft blog post

Submit to CRAN:

* [ ] `usethis::use_version('major')`
* [ ] `devtools::submit_cran()`
* [ ] Approve email

Wait for CRAN...

* [ ] Accepted :tada:
* [ ] `git push`
* [ ] `usethis::use_github_release()`
* [ ] `usethis::use_dev_version()`
* [ ] `git push`
* [ ] Finish blog post
* [ ] Tweet
* [ ] Add link to blog post in pkgdown news menu

**Comment by bms63** [comment]
@ddsjoberg :)

**Comment by bms63** [comment]
Two bad URLs, but CRAN has let these slide for a long time 
![image](https://github.com/pharmaverse/admiral/assets/10111024/d5a237d2-a7b7-4b74-800a-4962d10c4746)

**Comment by ddsjoberg** [comment]
> @ddsjoberg is there a way to do devtools::check_win_devel() with the development version of `admiraldev`?

You can try adding admiraldev to `Remotes:`. `Remotes:` is not allowed by CRAN, but I am not sure if you'll get a note saying you can't use `Remotes:` or it will fail to install and subsequently fail everywhere 🤷🏼

**Comment by bms63** [comment]
> > @ddsjoberg is there a way to do devtools::check_win_devel() with the development version of `admiraldev`?
> 
> You can try adding admiraldev to `Remotes:`. `Remotes:` is not allowed by CRAN, but I am not sure if you'll get a note saying you can't use `Remotes:` or it will fail to install and subsequently fail everywhere 🤷🏼

it don't like Remotes - oh well.  next time will be easier
