### ISSUE TITLE
Feature Request:  derive_vars_query requires TERMNUM and TERMCHAR to be in query dataset

### ISSUE THREAD

**Issue by millerg23** [pharmaverse/admiral#2264]
### Feature Idea

The function `derive_vars_query` makes `TERMNUM` and `TERMCHAR` required variables. However, `TERMNUM` is only a REQUIRED variable if there is numeric variable named in `SRCVAR`, if all variables defined in `SRCVAR` are character then `TERMNUM` should not be required (for example Roche never has numeric variables in `SRCVAR`). The same is true if all variables in `SRCVAR` are numeric variables, then `TERMCHAR` should not be available.

### Relevant Input

The check for these required variables are in function `assert_valid_queries()`

**Comment by bms63** [comment]
Is this for `1.0` or can we hold off on it till `1.1`?  We do have some wiggle room with `admiralroche` doing checks now.

**Comment by millerg23** [comment]
Hi @zdz2101 
I only got round to testing this now, it doesn't seem to work, I still get an ERROR if TERMNUM missing.

```
> actual_output <- derive_vars_query(adae, queries)
Error in `mutate()`:
ℹ In argument: `TERM_NAME_ID = case_when(...)`.
Caused by error in `case_when()`:
! Failed to evaluate the right-hand side of formula 2.
Caused by error:
! object 'TERMNUM' not found
Run `rlang::last_trace()` to see where the error occurred.
```

I think its due to this code:
```
mutate(
      tmp_col_type = vapply(dataset[SRCVAR], typeof, character(1)),
      TERM_NAME_ID = case_when(
        tmp_col_type == "character" ~ TERMCHAR,
        tmp_col_type %in% c("double", "integer") ~ as.character(TERMNUM),
        TRUE ~ NA_character_
      )
    )
```

We also need a unit test where all the variables defined in SRCVAR are all character variables (ie AEDECOD), and TERMNUM is missing from the query dataset. (In unit test for Test 1, I just removed TERMNUM, and got the ERROR).
