### ISSUE TITLE
General Issue: `dplyr::transmute()` is superseded

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#2274]
### Background Information

@manciniedoardo , noticed that `dplyr::transmute()` is superseded in favor of `mutate(.keep = "none")`.

We should update all admiral functions which are using it.
```
admiral-package.R:#'   rename_with row_number select slice semi_join starts_with transmute ungroup
derive_param_tte.R:    data[[i]] <- transmute(
derive_var_dthcaus.R:        transmute(
derive_var_extreme_date.R:    add_data[[i]] <- transmute(
duplicates.R:    transmute(!!!by_vars)
```

**Comment by bms63** [comment]
Hi @gg106046,

just checking in on progress for this issue.  Do you think you can finish in the next week or so?

**Comment by gg106046** [comment]
> Hi @gg106046,
> 
> just checking in on progress for this issue. Do you think you can finish in the next week or so?

Hi Ben! Yes, it'll be done by end of this week
