### ISSUE TITLE
Final pre 1.0 release site review

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiral#2277]
### Background Information

Final pre 1.0 release site review

### Definition of Done

Full review of contents of dev site ahead of 1.0 release.

**Comment by bms63** [comment]
I think we need to look at the contribution model stuff.  We removed the community tab as it was redundant, but im not sure if the vignette is still appropriate or accessible.  I feel like we should just use the https://pharmaverse.github.io/admiral/CONTRIBUTING.html for giving folks advice on how to get involved.

**Comment by bms63** [comment]
https://github.com/pharmaverse/admiral/blob/main/vignettes/contribution_model.Rmd

**Comment by bms63** [comment]
> > I think we need to look at the contribution model stuff. We removed the community tab as it was redundant, but im not sure if the vignette is still appropriate or accessible. I feel like we should just use the https://pharmaverse.github.io/admiral/CONTRIBUTING.html for giving folks advice on how to get involved.
> 
> Agree, I think [this page](https://pharmaverse.github.io/admiral/CONTRIBUTING.html) is enough and is nicely linked here (among other places). I don't think the contribution model page is accessible anymore - will delete the vignette.

Can we move some of the content from the vignette to the .md page?

**Comment by manciniedoardo** [comment]
Sure I can check for anything missed.
