### ISSUE TITLE
Supersede `derive_var_merged_exist_flag()`

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiral#2303]
_Originally posted by @kaz462 in https://github.com/pharmaverse/admiral/discussions/2191#discussioncomment-7634596, suggesting to deprecate rather than superseding_

## Supersede `derive_var_merged_exist_flag`
the new function [derive_var_merged_ef_msrc](https://github.com/pharmaverse/admiral/issues/1728) covers the functionality of [derive_var_merged_exist_flag()](https://pharmaverse.github.io/admiral/cran-release/reference/derive_var_merged_exist_flag.html) - so we can supersede `derive_var_merged_exist_flag()` .

## Definition of done
The function `derive_var_merged_exist_flag()` should be superseded (note: this is different from [deprecation](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#deprecation) because we just direct users to use a newer function but do not remove the older one) so that it appears [here](https://pharmaverse.github.io/admiral/reference/#superseded)). See an example of how this has been done for [derive_var_dthcaus()](https://github.com/pharmaverse/admiral/blob/01b819a2a2bf6aa82dafb996f328d7db7123ca93/R/derive_var_dthcaus.R#L4) in the `@description`, `@family` and `@keywords` field.

**Comment by manciniedoardo** [comment]
A cursory review of the usage of `derive_var_merged_exist_flag()` showed that we don't use it that often in our code/repo. So I am happy for this to be superseded in favour of `derive_var_merged_exist_flag()`. I see no reason to deprecate at the moment due to our 1.1 strategy. 

We would also want to replace mentions of the former with the latter anywhere they appear, and try make sure this also happens across extension packages.

**Comment by bundfussr** [comment]
Is this a general decision? I.e., should we supersede all functions with a single source if a corresponding function for multiple sources is available? For example, `derive_vars_extreme_event()` covers `derive_vars_merged()`.

**Comment by manciniedoardo** [comment]
@bundfussr no not a general decision `derive_vars_merged()` is a nice simple function so i wouldn't supersede it. It can be ok to have overlaps in functionality within admiral.

**Comment by bms63** [comment]
I'm actually a little confused on what is the purpose of the issue.  It reads as a question currently.  Is this Issue to discuss this or are we going to really supersede the function. ?

Could the original issue to be updated with what we are trying to accomplish here please?  Definition of Done.  Since we have good first issue tagged - we should at least link the dev documents on our supersede/deprecation strategy for new folks and provide any other helpful tips for this task.

**Comment by manciniedoardo** [comment]
@bms63 good points, i was a bit hasty while making the issue. I made some updates.

**Comment by rossfarrugia** [comment]
Is there anything to be said about optimisation here? e.g. I imagine `derive_var_merged_exist_flag()` runs quicker than `derive_var_merged_ef_msrc()` as its simpler. I remember that was an argument for keeping `derive_vars_merged()` when `derive_vars_joined()` first came, as technically the joined functions could have been used here all the time. Just one thing to consider from past old discussions around deprecation strategy I remember - feel free to ignore though as this one doesn't seem major impact.

**Comment by Fanny-Gautier** [comment]
I proceeded with the updates in terms of documentation. 
Does it also need to be updated in the functions wherever it is used? I mean to replace `derive_var_merged_exist_flag()` calls by `derive_var_merged_ef_msrc()` calls, e.g. as in below screenshot.
![image](https://github.com/pharmaverse/admiral/assets/157114584/a8077b98-be3a-461c-85a6-5410f9a43c66)

**Comment by Fanny-Gautier** [comment]
I have been through the deprecation [discussion](https://github.com/pharmaverse/admiral/discussions/2329#discussion-6188313). Could you please confirm whether I should also add some warnings regarding the future deprecation of the `derive_var_merged_exist_flag()` function ? Thanks.

**Comment by bms63** [comment]
- [ ] The vignettes using `derive_var_merged_exist_flag()` need to be updated to use the new function
- [ ] The stuff with `@inheritparams` that is a bit tricky - can you look to make sure that the new function has all the same arguments.  We either will update to use the new function, replace with relevant arguments, or pull from similar function
- [ ] The other two functions in screen shot looks like they use the `derive_var_merged_exist_flag()` under the hood.  Can you see if the new function can replace that without impacting anything?

As far as deprecation.  This function should emit a message for the next two years.  In the third year we will start to emit a warning and at the end of the third year we will fully remove the function.  I'm actually unsure how we should approach that at this moment.  I will  get back to you.  

The above three tasks are a bit involved.  Let me know if anything needs to be clarified.

**Comment by Fanny-Gautier** [comment]
How `derive_var_merged_ef_msrc()` can replace `derive_var_merged_exist_flag()`, while `derive_var_merged_exist_flag()` is used within `derive_var_merged_ef_msrc()` ?

![image](https://github.com/pharmaverse/admiral/assets/157114584/02cd0d6d-4191-4fd5-9587-246206776cd5)

Does `derive_var_merged_exist_flag()` still need to be deprecated in the future ?

**Comment by bms63** [comment]
Well there we go - I'm not sure there is grounds then to supersede or deprecate the function :)

**Comment by bms63** [comment]
@manciniedoardo what was the rationale for the supersede/deprecation?  I don't think we should go ahead with this one

**Comment by manciniedoardo** [comment]
@bms63 the original rationale came from [this comment](https://github.com/pharmaverse/admiral/discussions/2191#discussioncomment-7634596) by @kaz462. Thanks for investigating this further @Fanny-Gautier - I agree that, on review, it would be best not to go ahead with this supercession given is used within `derive_var_merged_ef_msrc()` itself depends on `derive_var_merged_exist_flag()`.
