### ISSUE TITLE
General Issue: Add unit tests for `get_summary_records()`

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#2304]
### Background Information

Since admiral 1.0.0 the test coverage for `get_summary_records()` is 0%. (Before it was covered by the unit tests of `derive_summary_records()` but it does no longer call `get_summary_records()` to avoid that it depends on a superseded function.)

### Definition of Done

Unit tests for `get_summary_records()` are added.

**Comment by bundfussr** [comment]
@bms63 , could this cause issues on GSK side?
When validating admiral 1.0.0 at Roche it was raised as an issue. Fortunately they accepted our explanation.

**Comment by bms63** [comment]
No impact for GSK.  thanks for flagging!!

**Comment by bms63** [comment]
@pharmaverse/admiral_comm @pharmaverse/admiral hey all - this is a great issue to tackle for those looking for a low to medium challenge.
