### ISSUE TITLE
General Issue:  Remove `renv` from admiral

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#2306]
### Background Information

It has been decided to remove renv from how to develop the admiral R package.  

renv did help establish a common framework for us all to work in, but added a lot of complications to our processes as well as was a bit of a hurdle for new developers coming onboard - either new to pgk dev or coming form other R packages

### Definition of Done

* Remove the `renv` folder
* Remove the `renv.lock` file
* Please make a blurb in the news as it is a big milestone for us.
* Investigate any issues that come up from renv removal and report back to the team

@pharmaverse/admiral @pharmaverse/admiral_comm A simple file/folder deletion with a quick blurb in the news.  There might be some unknown downstream issues we might have to investigate...but that will be probably not be apart of this Issue/PR

**Comment by bms63** [comment]
> @bms63 , we should also have a related issue in admiraldev to update the vignettes, e.g., `programming_strategy` and `rcmd_issues`.

yes!! good call!!  as well as admiraltemplate and extension packages.

**Comment by dgrassellyb** [comment]
> @bms63 , we should also have a related issue in admiraldev to update the vignettes, e.g., `programming_strategy` and `rcmd_issues`.

I think we could refer as well sections from `admiralci` doc (about github artifacts containing local dependencies informations, to be able to reproduce github workflow env)
