### ISSUE TITLE
update ADPP/ADPC template

### ISSUE THREAD

**Issue by kaz462** [pharmaverse/admiral#2308]
### Background Information

Issues from pharmaverseadam: https://github.com/pharmaverse/pharmaverseadam/issues/57

### Definition of Done

- [x] ADPP.AVISIT/AVISITN variables are empty  - update [adpp template]( https://github.com/pharmaverse/admiral/blob/main/inst/templates/ad_adpp.R) to populate them 
     
- [x] AVALU is currently missing in ADPP/ADPC, consider to derive this from PPORRESU/PCORRESU in [adpp template]( https://github.com/pharmaverse/admiral/blob/main/inst/templates/ad_adpp.R) and [adpc template]( https://github.com/pharmaverse/admiral/blob/main/inst/templates/ad_adpc.R)

**Comment by bms63** [comment]
@pharmaverse/admiral @pharmaverse/admiral_comm hey all - this is a pretty quick fix.

nice spot @kaz462!!

**Comment by jeffreyad** [comment]
@kaz462 looks like AVALU is populated in ADPC.  I will update it in ADPP.

**Comment by jeffreyad** [comment]
`VISIT` and `VISITNUM` are not in PP, which is not unusual.  I defined `AVISIT` based on `ADY` which I think is reasonable.  I did set `VISIT` and `VISITNUM` to the same values but these variables are not necessary in ADPP so they could be dropped if desired.
