### ISSUE TITLE
Bug: `derive_vars_query()` changes the AE terms to upper case

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#2311]
### What happened?

`derive_vars_query()` changes the AE terms to upper case, i.e., if the terms in AE and in the query dataset are mixed case, no terms are flagged.

There are two options to solve the issue:
- The case of the terms is not changed.
- The case of the terms is changed in both `dataset` and `dataset_queries`.

@pharmaverse/admiral , what do you think? Which option should be implemented?

### Reproducible Example

```
library(admiral)

smq99 <- query(
  prefix = "SMQ06",
  id = auto,
  add_scope_num = TRUE,
  definition = basket_select(
    name = "Peripheral neuropathy (SMQ)",
    scope = "BROAD",
    type = "smq"
  )
)

# The get_terms function from admiralroche is used to get SMQ terms from OCEAN
aag_smq <- create_query_data(
  queries = list(smq99),
  get_terms_fun = admiralroche::get_terms,
  version = "26.1"
) %>%
  # version (VERSION) - add required prefix
  mutate(VERSION = paste0("MedDRA v", "26.1"))

test <- tibble::tribble(
  ~USUBJID, ~AEDECOD,
  "001", "Paraesthesia",
  "002", "Phrenic nerve paralysis",
)

test1 <- test %>% 
  derive_vars_query(
    aag_smq)
  )
```
does not flag any terms.
If
```
test1 <- test %>% 
  derive_vars_query(
    aag_smq %>% mutate(TERMCHAR = stringr::str_to_upper(TERMCHAR))
  )
```
is used, the terms are flagged correctly.

**Comment by millerg23** [comment]
My preference would be for the flags to be added without being case sensitive. So internally uppercase both the terms in `dataset` and `dataset_queries` before merging, both datasets would remain unchanged as far as user is concerned.

**Comment by millerg23** [comment]
It looks like this was introduced in version `1.0.0`, when I look in version `0.12.3` both sides are uppercased.

**Comment by rossfarrugia** [comment]
Agree with @millerg23 - any reason why this changed? I was wondering the same as to why the past users hadn't found this issue.

We're going to have to priority hofix this one (sorry CRAN!) and we should also add an additional unit test to catch this in future.
