### ISSUE TITLE
General Issue: test being skipped

### ISSUE THREAD

**Issue by esimms999-gsk** [pharmaverse/admiral#2316]
### Background Information

Empty test (only creates a tibble and does not test anything) results in test summary having everything "Pass" except for one "Skip".

![image](https://github.com/pharmaverse/admiral/assets/85294667/ca87c8e4-1bc0-44e9-8a12-d95099ca446a)

### Definition of Done

Remove the empty test or add code to test something.

**Comment by bms63** [comment]
Is this you taking this on and alerting me to its existence?  No need to assign me - i receive every notification on admiral...my cross to bear!!

**Comment by esimms999-gsk** [comment]
@bms63  Sure, I will take this on. And I was not sure you would be notified, which is why I assigned you, too. Sorry about that!

**Comment by bms63** [comment]
![gfyi1wao](https://github.com/pharmaverse/admiral/assets/10111024/5d6789fe-46bf-4059-ab4b-a6392ff1aadf)

**Comment by esimms999-gsk** [comment]
The derive_var_shift.R code no longer has a parameter named na_val and has replaced it with a parameter named missing_value. 

From NEWS for 0.12.0:
![image](https://github.com/pharmaverse/admiral/assets/85294667/e6a8a2a5-cd7b-42f1-9939-03d61947a193)

And from NEWS for (development version):
![image](https://github.com/pharmaverse/admiral/assets/85294667/aa8766d3-3115-4ddb-84c3-fe6e1d7dddfa)

My understanding: once we reach the end of the deprecation process, we no longer tell the user that something has changed (e.g. _The `na_val` argument of `derive_var_shift` was deprecated in admiral 0.12.0 and is now defunct.
Please use the `missing_value` argument instead._) but just let R inform the user that na_val is an unused parameter.

The test which is being skipped was probably a placeholder that was intended to test the deprecation message. At this point, such a deprecation message and test of such are no longer needed. I will remove the test.

I will also update a comment in the function which mentions na_val; I will change that to missing_value.
