### ISSUE TITLE
Documentation:  Enhancing "Period Reference Dataset" portion of Visit and Period Variables vignette

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiral#2321]
### Please select a category the issue is focused on?

User Guides

### Let us know where something needs a refresh or put your idea here!

I think this vignette would benefit from a small section before the [Creating ADSL Periods/Subperiods/Phases section](https://pharmaverse.github.io/admiral/articles/adsl.html#periodvars ). 

Consider the case of a programmer creating ADSL for a study with multiple periods/subperiods - when they start consulting this page, the text assumes that they already have a period reference dataset or know how to create one. But really, they will always have to create this dataset from scratch - it is only _after_ you have created ADSL that you can use the info in ADSL for period derivations in later ADaMs.

Though the steps to create the period reference dataset can be executed with general tidyverse commands, I think it would still be good to enhance the above section with a toy example, showing a schematic from eg.  a crossover study with two periods, and then how that would define how to create the period reference dataset. Expanding my example, for a 24 week study with crossover at week 12, that would be tidyverse code to manipulate to extract from EX the Day 1 and Week 12 dose dates and create the appropriate APERSDTM/APEREDTM variables.

**Comment by bms63** [comment]
Great idea!!  @pharmaverse/admiral @pharmaverse/admiral_comm Nice issue to make some dummy data and enhance our ADSL vignette.  I would imagine this task would take about 3 hours to get more familiar with the vignette and workflow and make relevant dummy data.  

@manciniedoardo did you mean to link this section - https://pharmaverse.github.io/admiral/articles/adsl.html#periodvars the other one goes to internal roche.

- [ ] We might want to see if the template should be updated as well?

**Comment by manciniedoardo** [comment]
> @manciniedoardo did you mean to link this section - https://pharmaverse.github.io/admiral/articles/adsl.html#periodvars the other one goes to internal roche.

cheers, now fixed
