### ISSUE TITLE
update ADLB template: PARAMCD has two corresponding PARAM values

### ISSUE THREAD

**Issue by kaz462** [pharmaverse/admiral#2327]
### Background Information

Issues raised by @botsp from `pharmaverseadam`: https://github.com/pharmaverse/pharmaverseadam/issues/58

PARAMCD in ("BASO", "LYMPH") has two corresponding PARAM values
```r
# A tibble: 4 × 4
  PARAMCD PARAM                    PARAMN     n
  <chr>   <chr>                     <dbl> <int>
1 BASO    Basophils (10^9/L)            6  2477
2 BASO    Basophils Abs (10^9/L)        6    21
3 LYMPH   Lymphocytes (10^9/L)         25  2479
4 LYMPH   Lymphocytes Abs (10^9/L)     25    19
```

Hi @millerg23 , are `Basophils` and `Basophils Abs` the same? can we change `Basophils Abs (10^9/L)` to `Basophils (10^9/L)`

**Comment by millerg23** [comment]
Hi @kaz462 ,
Yes they are the same, I would keep the label with "Abs" included for clarity, and remove the other one.

Regards,
Gordon,

**Comment by kaz462** [comment]
@millerg23 Thanks!
