### ISSUE TITLE
Clean up easy `if()` and `else if()` code chunks in datetime/date codebase

### ISSUE THREAD

**Issue by zdz2101** [pharmaverse/admiral#2342]
To reduce cyclomatic complexity in the datetime/date functions, there are two functions:
1. `get_imputation_target_date()`
2. `get_imputation_target_time()` 
that can be easily compressed into a `case_when()` statement reducing the complexity and making code more ledgible. Anywhere else that is found to be an "easy" swap/replacement can be applied too

Defintion of done:
Research and apply changes to respective functions and anywhere else that seems that appropriate

**Comment by zdz2101** [comment]
Draft of `get_imputation_target_date()` here to get started:

```
get_imputation_target_date <- function(date_imputation, month) {
  target <- vector("list", 3)
  names(target) <- c("year", "month", "day")

  target <- case_when(
    date_imputation == "first" ~ list(year = "0000", month = "01", day = "01"),
    date_imputation == "mid" ~ list(year = "xxxx", month = "06", day = if_else(is.na(month), "30", "15")),
    date_imputation == "last" ~ list(year = "9999", month = "12", day = "28"),
    TRUE ~ list(year = "xxxx", month = str_sub(date_imputation, 1, 2), day = str_sub(date_imputation, 4, 5))
  )

  return(target)
```

**Comment by Fanny-Gautier** [comment]
It is labeled as "documentation". Could you please clarify which documentation should be updated for this issue ? Thanks.

**Comment by bms63** [comment]
@Fanny-Gautier I think documentation label is incorrect.  Might be more appropriate to call this a refactor of the code base.  I'll make a new label

**Comment by zdz2101** [comment]
> It is labeled as "documentation". Could you please clarify which documentation should be updated for this issue ? Thanks.

Yes my mistake @Fanny-Gautier , main task here is refactor the two `get_imputation_target_xxx()` functions to not use as many `if()` chunks, and use `case_when()` . If you happen to see anywhere else where it can be easily swapped, feel free to do so too

**Comment by Fanny-Gautier** [comment]
@zdz2101, by "see anywhere else where it can be easily swapped" do you meant in any other functions not related to datetime/date as suggested in the title of this issue ? In that case I could find only 4 functions where it could be swapped:

1.  `derive_param_wbc_abs()`
![image](https://github.com/pharmaverse/admiral/assets/157114584/c33ff2da-2b34-43fe-8e4f-8893697ca57e)
2. `derive_vars_period()`
![image](https://github.com/pharmaverse/admiral/assets/157114584/e6c06fb4-f2cc-4d5d-b350-233b43393d87)
3. `compute_bsa()
![image](https://github.com/pharmaverse/admiral/assets/157114584/6e5600d6-7f44-43de-bf17-e6940cc1ae14)
4. `filter_relative()`
![image](https://github.com/pharmaverse/admiral/assets/157114584/c56d39fe-30a0-41d4-8696-918c74a27542)

Could you please confirm whether I should proceed with these 4 functions or create the PR for the datetime/date functions only ? Thank you.

**Comment by bms63** [comment]
Hi @Fanny-Gautier.  

I think we are only scoped to dt/dtm functions right now.  However, if you want to make a general refactor Discussion thread that would be helpful!!
