### ISSUE TITLE
Clean up documentation on datetime/date flagging functions, e.g. `compute_dtf()`/`compute_tmf()` to make development/maintenance easier

### ISSUE THREAD

**Issue by zdz2101** [pharmaverse/admiral#2343]
The intuition/documentation behind the code of `compute_dtf()` and `compute_tmf()` can be modified to be more "human-readable" and reduce "code smells" 

Definition of done:

1. Add code comments where appropriate
  2.  tmf is in need of some help! 
3. Add notes in roxygen documentation such that any "new developer" in the codebase can quickly pickup and contribute
4. Add context to where and when this function is used

**Comment by bms63** [comment]
Current comments and documentation is sufficient.  A diagram of the process might be created for future developers to get a hadnle on the situation
