### ISSUE TITLE
Website Package version number is illegible due to the text colour

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiral#2360]
### Background Information

![image](https://github.com/pharmaverse/admiral/assets/82581364/f3a6c3b4-f500-4e9f-8f5c-335be327f0a8)

**Comment by bms63** [comment]
I can't remember...was it ever readable...I feel like it was

**Comment by rossfarrugia** [comment]
> I can't remember...was it ever readable...I feel like it was

yep, i had an old screenshot in some training slides and it used to be.

**Comment by manciniedoardo** [comment]
I believe it just happened when going from 1.0.1 to 1.0.2?

**Comment by rossfarrugia** [comment]
not sure sorry!

**Comment by Fanny-Gautier** [comment]
It must be default colour, but it seems feasible to change it. This might be defined with the [development mode](https://pkgdown.r-lib.org/reference/build_site.html#development-mode).

**Comment by rossfarrugia** [comment]
@Fanny-Gautier this seems a good article: https://pkgdown.r-lib.org/articles/customise.html. Would you be interested in self-assigning this one and having an explore to see if you can get it looking cleaner?

**Comment by Fanny-Gautier** [comment]
Here are the different colors that we can get with the following options (mode: automatic):

- development:
  - mode: auto
  - version_label: default
![image](https://github.com/pharmaverse/admiral/assets/157114584/f056bbfb-4bf0-4a42-ab6b-90966482ab7c)
  - version_label: info
![image](https://github.com/pharmaverse/admiral/assets/157114584/0f9b9c2f-d2ae-4a1b-9f05-fb9f6a6bafdb)
  - version_label: warning
![image](https://github.com/pharmaverse/admiral/assets/157114584/1ef53398-8457-479a-b55e-ea93a5114dc1)
  - version_label: danger
![image](https://github.com/pharmaverse/admiral/assets/157114584/548feac1-329a-49c3-83e7-c1373d334b91)


For the release, I guess that the mode has been updated to "release" ? In that case the version gets the default color. 
![image](https://github.com/pharmaverse/admiral/assets/157114584/a90f13cf-ccf4-4199-91ac-783962c48648)
I am trying to see the default colors of the "bootswatch: flatly" theme, and if we can change them without having to customize the entire theme.

**Comment by rossfarrugia** [comment]
thanks Fanny! the default you show there was how it used to be and that light grey colour was fine but for some reason it now went to dark grey which conflicts with the background. light grey or white would be best as the other colours look confusing, like the red one would make me assume the package is not ready.

**Comment by Fanny-Gautier** [comment]
I am well getting the version number in black with the release mode with the below setting: 
- development:
  - mode: release
  - **no** version_label defined:
![image](https://github.com/pharmaverse/admiral/assets/157114584/be3e54b5-d48a-4d34-a655-6cc9ba6c2e50)


We can force it with the light grey color by setting the version_label to "default" as per below statements:
- development:
  - mode: release
  - version_label: default  
![image](https://github.com/pharmaverse/admiral/assets/157114584/8b5037de-ded1-45fd-80f9-eeee272fac08)


Could you please confirm that I should force it to "default" in the _pkgdown.yml file, whatever the mode (auto/release) ? It means that the version number does not appear in red anymore when we work on development branches.
![image](https://github.com/pharmaverse/admiral/assets/157114584/9b4fc911-394a-42c2-9049-06638e8634d3)
 Otherwise it needs to be updated for the official **release only**, when the mode is set to **release**.

**Comment by manciniedoardo** [comment]
> Otherwise it needs to be updated for the official **release only**, when the mode is set to **release**.

Ideally, it would be red for the dev site, and then grey/white for the main site (this is how it was before)

**Comment by Fanny-Gautier** [comment]
> Ideally, it would be red for the dev site, and then grey/white for the main site (this is how it was before)
 Is _pkgdown.yml file updated and the current mode updated from "auto" to "release" for the official release ? What is the process for the official releases ?

**Comment by bms63** [comment]
Here is some rough guidance on how we do it.  https://pharmaverse.github.io/admiraldev/dev/articles/release_strategy.html

You would need to inspect the CI action for pkgdown as well in the admiralci repo

**Comment by Fanny-Gautier** [comment]
@cicdguy, could you please check if this issue get resolved while fixing the "404 errors - previous versions of admiral website" ?
If not I'll investigate a bit more. Thank you.

**Comment by bms63** [comment]
I guess this is confusing as the version number used to be a different color and has only recently changed to be unreadable. can we hold off on this @Fanny-Gautier until multi-versions is re-implemented please.

**Comment by ddsjoberg** [comment]
> reverting the workflows to when the multiversion pkgdown docs were working (before then introduction of the custom solution that @ddsjoberg has implemented), and restoring the previous versions from the git history.

@cicdguy to be clear, all updates to admiral workflows were done by the IDR team. I added an article to the pkgdown site that links to the websites.

**Comment by ddsjoberg** [comment]
there's no need to modify the plans we made in our meeting yesterday

**Comment by bms63** [comment]
@cicdguy said there is progress on it and should be available mid-Mayish.  Thanks for checking!!

**Comment by bms63** [comment]
Thanks @cicdguy !!

I noticed in the dev mode of the site that the dropdowns have turned dark.  Not sure if was due to the update?  
![image](https://github.com/pharmaverse/admiral/assets/10111024/4476e5d4-e392-4354-948d-229c9862673d)

**Comment by bms63** [comment]
Thanks all - I've been paying attention to color stuff more since the version number went dark on us 6 months ago.  I couldn't remember if this dark menu had always been present or not.  Thanks for checking.

**Comment by Fanny-Gautier** [comment]
I also see it with light color in dev mode:
![image](https://github.com/pharmaverse/admiral/assets/157114584/3b4cf326-e725-4e8c-b291-47ec9ef6162a)

**Comment by Fanny-Gautier** [comment]
I am working on it today. But I find difficult to understand which  _--bs-_ variable is used in the [CSS](https://github.com/pharmaverse/admiral/blob/gh-pages/dev/deps/bootstrap-5.3.1/bootstrap.min.css) file when the `version_label` is NULL / Not defined in [_pkgdown.yml](https://github.com/pharmaverse/admiral/blob/main/_pkgdown.yml).
For now it seems that _data-bs-theme="light"_ applies for _development: mode:  auto_ and _development: mode:  release_.
But I don't find the reason why it is _--bs-danger_ which applies for `version_label:` NULL/Not defined for _development: mode: auto_ and I don't know which _--bs-_ variable applies for `version_label:` NULL/Not defined for _development: mode: release_

**Comment by bms63** [comment]
> I am working on it today. But I find difficult to understand which _--bs-_ variable is used in the [CSS](https://github.com/pharmaverse/admiral/blob/gh-pages/dev/deps/bootstrap-5.3.1/bootstrap.min.css) file when the `version_label` is NULL / Not defined in [_pkgdown.yml](https://github.com/pharmaverse/admiral/blob/main/_pkgdown.yml). For now it seems that _data-bs-theme="light"_ applies for _development: mode: auto_ and _development: mode: release_. But I don't find the reason why it is _--bs-danger_ which applies for `version_label:` NULL/Not defined for _development: mode: auto_ and I don't know which _--bs-_ variable applies for `version_label:` NULL/Not defined for _development: mode: release_

@cicdguy should we be going down this path?  Is it possible for the CI action for the pkgdown build to take care of this type of thing for us?  I don't remember us messing with the stuff when the pkg version was a white color so unclear when or why this dark color started to appear.

**Comment by ddsjoberg** [comment]
I think this is coming from this line in the CSS with `text-muted`

```html
<small class="nav-text text-muted me-auto" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Released version">1.0.2</small>
```

The tricky part will be overriding the default. A couple of things I would try (and apologies if this is already suggested above, it didn't read the whole thing 🤷🏼 )
1. Modifying the text-muted tag in the `_pkgdown.yml` under the bslib section.
2. We can inject custom CSS into our site following the instructions here: https://pkgdown.r-lib.org/articles/customise.html#additional-html-and-files . I am way out of my depth here, but maybe we could redefine `text-muted`? IDK!

**Comment by Fanny-Gautier** [comment]
> I think this is coming from this line in the CSS with `text-muted`
> 
> ```
> <small class="nav-text text-muted me-auto" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Released version">1.0.2
> ```

Yesterday, I saw a previous post from you on a forum and tried to search for that line, but I could not find it in the [CSS](https://github.com/pharmaverse/admiral/blob/gh-pages/dev/deps/bootstrap-5.3.1/bootstrap.min.css) file. Did I look at the wrong place?

**Comment by Fanny-Gautier** [comment]
The easiest solution that I have for now it to manually force it as suggested a few times ago in __pkdown.yml_ as following and at releases time:
![image](https://github.com/pharmaverse/admiral/assets/157114584/310fc058-3f65-4d14-b5a3-b9b2857d28c5)
![image](https://github.com/pharmaverse/admiral/assets/157114584/87ecb710-4adf-4c78-8d31-48c6ebcb1d88)


And set it back to danger color (red) after the release and for the auto mode as it currently is set:
![image](https://github.com/pharmaverse/admiral/assets/157114584/63d875b2-b89c-4e96-8941-815da312a41b)
![image](https://github.com/pharmaverse/admiral/assets/157114584/8a4b5034-909a-409b-98f3-39f5591e6148)

**Comment by bms63** [comment]
Shall we just give it a try now?

**Comment by Fanny-Gautier** [comment]
> Shall we just give it a try now?

I have created the feature branch and pushed the updates. Shall I create a PR or is it fine for you to try from the corresponding feature branch?

**Comment by bms63** [comment]
Could you branch off the latest release?  I wanted to re-release admiral to try out the fix, but not have any of the new stuff visible.

https://stackoverflow.com/questions/10940981/how-to-create-a-new-branch-from-a-tag

**Comment by Fanny-Gautier** [comment]
Ok, I'll create another branch from tag v1.0.2. thanks.
Did you realize that the color is also different when not on the index/main page ?
![image](https://github.com/pharmaverse/admiral/assets/157114584/315ae6ff-ec45-44f8-9a71-8a8b5af0ef5b)

**Comment by bms63** [comment]
The plot thickens!

**Comment by Fanny-Gautier** [comment]
@bms63 I have created 2360_website_package_version_number_color_tag_v1-0-2 as per your suggestion.
Testing it before you can proceed with an official test, I am facing a funny thing... 🙃 
When the following is run:
![image](https://github.com/pharmaverse/admiral/assets/157114584/159859a6-7987-4bf4-bd0e-e935f01ccb9a)
I well get the number 1.0.2.9012 in red color
![image](https://github.com/pharmaverse/admiral/assets/157114584/b627a75d-a4b8-47e7-90ae-63b2594b5ff5)
But if I click on Reference page, it switches to 1.0.2.9035 in green 😵
![image](https://github.com/pharmaverse/admiral/assets/157114584/965ffbe3-43c8-4ffc-8fb8-a21a8f463977)

I thought that it was due to the other statements commented out (#mode: release + #version_label: success) so I deleted them, but it does not matter. still switching to green now on other pages than the index one 😵😵😵

**Comment by bms63** [comment]
> @bms63 I have created 2360_website_package_version_number_color_tag_v1-0-2 as per your suggestion. Testing it before you can proceed with an official test, I am facing a funny thing... 🙃 When the following is run: ![image](https://private-user-images.githubusercontent.com/157114584/333647725-159859a6-7987-4bf4-bd0e-e935f01ccb9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NjYwMTMsIm5iZiI6MTcxNjU2NTcxMywicGF0aCI6Ii8xNTcxMTQ1ODQvMzMzNjQ3NzI1LTE1OTg1OWE2LTc5ODctNGJmNC1iZDBlLWU5MzVmMDFjY2I5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQxNTQ4MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDMxOTdkYjQ5YTAwNGJlOTEzZTVkMmY0NmY4YmIwZjAwZTNlNDJiMjdmNDllMzFiYWNkZjg3ZThjODg2NjNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gyXramkYD7qbfaqvavZruVS753aNDFG2aauKON82q1s) I well get the number 1.0.2.9012 in red color ![image](https://private-user-images.githubusercontent.com/157114584/333647870-b627a75d-a4b8-47e7-90ae-63b2594b5ff5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NjYwMTMsIm5iZiI6MTcxNjU2NTcxMywicGF0aCI6Ii8xNTcxMTQ1ODQvMzMzNjQ3ODcwLWI2MjdhNzVkLWE0YjgtNDdlNy05MGFlLTYzYjI1OTRiNWZmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQxNTQ4MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NmQ2OGE1YjY2MTI2Y2FjNjNkNjUzMDM3MjlmYzgwMDBhODJmNzVhNmVmYjZhNmJiYmRjMTFhMGFlMDk1Yjg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sFo_vos8MTeq0jZVXlnxckoym-H-qENonsu4HNpvQSk) But if I click on Reference page, it switches to 1.0.2.9035 in green 😵 ![image](https://private-user-images.githubusercontent.com/157114584/333648131-965ffbe3-43c8-4ffc-8fb8-a21a8f463977.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NjYwMTMsIm5iZiI6MTcxNjU2NTcxMywicGF0aCI6Ii8xNTcxMTQ1ODQvMzMzNjQ4MTMxLTk2NWZmYmUzLTQzYzgtNGZmYy04ZmI4LWEyMWE4ZjQ2Mzk3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQxNTQ4MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNmFhMDgzNWVmOGU1NWYxMmQ3YWNhNGI2ODhkZGFmZTBlMDdiMDJjYmRjZjQ0ZmQxZjYxYzEwMTJmOWRhNGVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jwTxbul3n9vaHPpY2m8fBjk95_TEQOr87T5eIkmx6u8)
> 
> I thought that it was due to the other statements commented out (#mode: release + #version_label: success) so I deleted them, but it does not matter. still switching to green now on other pages than the index one 😵😵😵

that is interesting behavior...but i don't really mind it if the version label goes back to white.

**Comment by Fanny-Gautier** [comment]
I can see Edoardo's updates in admiral.Rmd on that new branch... something went wrong when I created the new branch from tags v1.0.2...

**Comment by Fanny-Gautier** [comment]
I have restarted R, and will run build_site() instead of build_articles()... I keep you in touch once it's ready for you to test an official release.

**Comment by Fanny-Gautier** [comment]
I am getting some errors with build_site(). I have to go now, sorry, I'll continue on monday
![image](https://github.com/pharmaverse/admiral/assets/157114584/7438a845-5cf7-4cc3-943e-ae94f7d69041)
![image](https://github.com/pharmaverse/admiral/assets/157114584/eb5ee872-6f44-4df7-a42c-61852d303075)

**Comment by Fanny-Gautier** [comment]
Hi @bms63 ,
It works well on the main branch (green for all pages with version_label: success, and red for all pages with version_label: danger), but on the branch _2360_website_package_version_number_color_tag_v1-0-2_, I am unable to build the site. I get the following error message:
![image](https://github.com/pharmaverse/admiral/assets/157114584/f49b19e0-99da-4c8e-88d1-115500fe180d)

**Comment by Lina2689** [comment]
@Fanny-Gautier @bms63 It's running fine for on branch 2360_website_package_version_number_color_tag_v1-0-2.

**Comment by Fanny-Gautier** [comment]
@bms63 Is it possible that I face the errors due to the admiraldev package version ? Lina is having 1.0.0.9011 while I have 1.0.0.9027.
![image](https://github.com/pharmaverse/admiral/assets/157114584/55f51849-df67-4f4c-9dc6-f8091ff375e8)
thanks

**Comment by Fanny-Gautier** [comment]
Hi @bms63, I tried again while installing {admiraldev} v1.0.0 and it works fine again.
You can now try the official release from the branch _2360_website_package_version_number_color_tag_v1-0-2_. Thank you.

Thanks @Lina2689 for all the tests done from your end ;-)

**Comment by bms63** [comment]
> Hi @bms63, I tried again while installing {admiraldev} v1.0.0 and it works fine again. You can now try the official release from the branch _2360_website_package_version_number_color_tag_v1-0-2_. Thank you.
> 
> Thanks @Lina2689 for all the tests done from your end ;-)

Okay!  It finally made sense to me why we needed to install v1.0.0 for admiraldev...this is admiral 1.0.2  

It looks fine to me.  Can we change it to the light gray and just merge to main from a non-tagged branch.  I'm not going to have time to test it out with a mini-release...will just do it live!! :)
