### ISSUE TITLE
Documentation:  There is a small error in an example for function derive_locf_records

### ISSUE THREAD

**Issue by janardhanswami** [pharmaverse/admiral#2389]
### Please select a category the issue is focused on?

Function Documentation

### Let us know where something needs a refresh or put your idea here!

<img width="531" alt="Screenshot 2024-03-23 220610" src="https://github.com/pharmaverse/admiral/assets/104511207/cca7a693-6bf4-4ae7-9bb9-3de9651a1b80">

In the example there is a small mistake in ADVS tribble part in second row the AVISITN is 2 but AVISIT is given as "WEEK 6"  which should be "WEEK 2"  this is relatively small but this can create some confussion in the user mind. I've highlighted the mistake part in the screenshot.

**Comment by bms63** [comment]
Thanks @janardhanswami !!  would you like to make the update?  #1839 gives some tips on how to make PRs in admiral.  If not, we will find someone.

Thanks again for giving us feedback! :)

**Comment by janardhanswami** [comment]
I would love to update this. But I'm quite new to these things any help will be appreciated @bms63

**Comment by bms63** [comment]
Hi @janardhanswami - Check out #1839.  There is a Youtube video (linked in the issue) that walks you through how to set things up and make a Pull Request.  I will add you to the repo so you have write access.
