### ISSUE TITLE
General Issue: DAIDS-related URLS are failing

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#2396]
### Background Information

![image](https://github.com/pharmaverse/admiral/assets/10111024/cb009632-8354-4d74-a1bc-22ef79178a9e)

### Definition of Done

- [ ] Update failing URLs

**Comment by bms63** [comment]
@millerg23 these urls are failing.  Do you mind investigating and seeing if this can be fixed?

**Comment by millerg23** [comment]
Thats odd I can click on the links without issue. @bms63 can you open the links also?

**Comment by bms63** [comment]
Yes they open for me too when I cut and paste!  Not sure what is going on?  Do they work form the reference page/vignettes for you?

**Comment by bms63** [comment]
Let's just add these to lycheeignore so it doesn't trip up others.

**Comment by millerg23** [comment]
OK I can do that.
