### ISSUE TITLE
Documentation: Clarify `event(keep_source_vars = NULL)` in `derive_extreme_event()`

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#2398]
### Please select a category the issue is focused on?

Function Documentation

### Let us know where something needs a refresh or put your idea here!

If `keep_source_vars = NULL` is used for an event in `derive_extreme_event()` the value of the `keep_source_vars` argument of `derive_extreme_event()` is used. This is not documented. Thus users may expect that nothing is kept.

**Comment by ProfessorP-beep** [comment]
I can grab this.
