### ISSUE TITLE
General Issue: Adopt data and data-raw conventions in admiral

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#2427]
### Background Information

The convention for creating custom data in an R package is to create and store R scripts for the custom data in the `data-raw` folder.  The data is then stored in the `data` folder.  Currently we have a hodgepodge of ways of doing this!  

The https://github.com/pharmaverse/pharmaversesdtm has a good example of following the preferred convention.

### Definition of Done

- [ ] Create `data-raw` folder
- [ ] Identify Scripts and Datasets that need to aligned to the `data/data-raw` convention
- [ ] Move Scripts to `data-raw` folder
- [ ] Move data to `data` folder, if not already!
- [ ] Keep an eye on what we have made available to users for documentation, links, etc

**Comment by bms63** [comment]
@jimrothstein this will get you in the weeds, but not super complicated.

**Comment by jimrothstein** [comment]
Will start;  should learn a lot:
#2427 conventions for data and data-raw
