### ISSUE TITLE
Documentation:  Updating the release schedule

### ISSUE THREAD

**Issue by sadchla-codes** [pharmaverse/admiral#2429]
### Please select a category the issue is focused on?

Other

### Let us know where something needs a refresh or put your idea here!

<img width="764" alt="image" src="https://github.com/pharmaverse/admiral/assets/112789549/e3fd3539-3446-403f-abf0-93c51ba7f496">

**Comment by bms63** [comment]
Thanks @sadchla-codes.  I have all this in a Discussion thread - https://github.com/pharmaverse/admiral/discussions/2394.  Do you mind taking a look and seeing if anything is missing or needs more explanation.
