### ISSUE TITLE
Reconsider presence/need of AVALC in ADaMs with only numeric parameters

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiral#2442]
### Background Information

Originally discussed [here](https://github.com/pharmaverse/admiral/pull/2402#issuecomment-2069865760).

According to CDISC guidance (3.3.4.2 of the ADaMIG v1.3), ADaMs with only numeric parameters should not have AVALC as a variable. Currently {admiral} does not follow this guidance in ADVS (and maybe other ADaMs too).

@nbrucken17 tagging you for awareness - thanks for flagging.
@Fanny-Gautier @Lina2689 tagging you in case this is relevant for {admiralpeds}.
@kaz462 tagging you as this will require an update to the {pharmaverseadam} labelling spec if any vars are removed.

### Definition of Done

- [ ] Review ADVS template and vignette and identify whether we are actually following CDISC guidance re: AVALC. If not needed, remove.
- [ ] Identify impact of removing AVALC - are we breaking any checks/codelists?
- [ ] Identify any other ADaMs where same discussion applies - e.g. ADLB?

**Comment by bms63** [comment]
Could we try and get this out for the release?  Any takers @pharmaverse/admiral @pharmaverse/admiral_comm

**Comment by StefanThoma** [comment]
I would agree with removing AVALC from the ADVS vignette: 
https://pharmaverse.github.io/admiral/articles/bds_finding.html

Also, I would remove it from the template, but would leave the part commented out probably, so if there was a value where AVALC is relevant this would be easy to put back in. WDYT @manciniedoardo ?

I'd be up to do this until next week.

**Comment by bms63** [comment]
Are you able to complete this issue this week?  We have a release on June 2nd.

**Comment by StefanThoma** [comment]
Notes: 
ADLB does not need to be adjusted, as COLOR is non numeric in AVALC

**Comment by StefanThoma** [comment]
I guess my question is; 
Should AVALC (e.g. in ADEG) look more like this:

![Screenshot 2024-05-29 at 10 26 12](https://github.com/pharmaverse/admiral/assets/40463122/676e3f61-a179-47cd-a8a0-a43f936b7b13)

Or more like this: 
![Screenshot 2024-05-29 at 10 30 23](https://github.com/pharmaverse/admiral/assets/40463122/16099e56-fe1f-446d-943f-a240d24ea6c5)

**Comment by bms63** [comment]
> I guess my question is; Should AVALC (e.g. in ADEG) look more like this:
> 
> ![Screenshot 2024-05-29 at 10 26 12](https://private-user-images.githubusercontent.com/40463122/334720250-676e3f61-a179-47cd-a8a0-a43f936b7b13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5ODQxNzgsIm5iZiI6MTcxNjk4Mzg3OCwicGF0aCI6Ii80MDQ2MzEyMi8zMzQ3MjAyNTAtNjc2ZTNmNjEtYTE3OS00N2NkLWE4YTAtYTQzZjkzNmI3YjEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDExNTc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYzI2ZTE5NTA1NzQ4M2JmNTRhMmIzZTA4ZTYxNTlmNTFlNDJiYzU0Y2JkNTI4MTA2OTNhZTBkYjMyODQ3OWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0uRqjR64xndjiVy9ERokLs-mjJbLSP3DZf06-6kDt6o)
> 
> Or more like this: ![Screenshot 2024-05-29 at 10 30 23](https://private-user-images.githubusercontent.com/40463122/334721635-16099e56-fe1f-446d-943f-a240d24ea6c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5ODQxNzgsIm5iZiI6MTcxNjk4Mzg3OCwicGF0aCI6Ii80MDQ2MzEyMi8zMzQ3MjE2MzUtMTYwOTllNTYtZmUxZi00NDZkLTk0M2YtYTI0MGQyNGVhNmM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDExNTc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyODEwYzU4ZDA1OGUxZmY5ZDAwNjM5YjAxMjRiOWFiZTM4M2QxZTRiNmZkOWI1YTEyZTgxMmM5MDEwNThlYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ten9-xu1I1mqKQTJ0Wwl8W3IpegtJ0mUS0femkutAXg)

Yes this is how it should be used.

**Comment by StefanThoma** [comment]
> > I guess my question is; Should AVALC (e.g. in ADEG) look more like this:
> 
> > 
> 
> > ![Screenshot 2024-05-29 at 10 26 12](https://private-user-images.githubusercontent.com/40463122/334720250-676e3f61-a179-47cd-a8a0-a43f936b7b13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5ODQxNzgsIm5iZiI6MTcxNjk4Mzg3OCwicGF0aCI6Ii80MDQ2MzEyMi8zMzQ3MjAyNTAtNjc2ZTNmNjEtYTE3OS00N2NkLWE4YTAtYTQzZjkzNmI3YjEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDExNTc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYzI2ZTE5NTA1NzQ4M2JmNTRhMmIzZTA4ZTYxNTlmNTFlNDJiYzU0Y2JkNTI4MTA2OTNhZTBkYjMyODQ3OWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0uRqjR64xndjiVy9ERokLs-mjJbLSP3DZf06-6kDt6o)
> 
> > 
> 
> > Or more like this: ![Screenshot 2024-05-29 at 10 30 23](https://private-user-images.githubusercontent.com/40463122/334721635-16099e56-fe1f-446d-943f-a240d24ea6c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5ODQxNzgsIm5iZiI6MTcxNjk4Mzg3OCwicGF0aCI6Ii80MDQ2MzEyMi8zMzQ3MjE2MzUtMTYwOTllNTYtZmUxZi00NDZkLTk0M2YtYTI0MGQyNGVhNmM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDExNTc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyODEwYzU4ZDA1OGUxZmY5ZDAwNjM5YjAxMjRiOWFiZTM4M2QxZTRiNmZkOWI1YTEyZTgxMmM5MDEwNThlYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ten9-xu1I1mqKQTJ0Wwl8W3IpegtJ0mUS0femkutAXg)
> 
> 
> 
> Yes this is how it should be used.

Which one of the two? This is not clear to me given the ADaM IG.

**Comment by bms63** [comment]
The second one

**Comment by nbrucken17** [comment]
If you're referring to the 2 screenshots that Stefan originally included (I'm not able to see the ones in the more recent posts), neither is correct, according to the ADaMIG.  The only times that both AVAL and AVALC are expected to be populated on the same record are when there is a code-decode relationship between them, or when AVAL is used to control the sort order for AVALC.  I would not expect to see AVALC populated with either the formatted character representation of a numeric value or with "NA" if the analysis value is numeric- it should be left blank in those cases.

Thanks,
    Nancy

**Comment by StefanThoma** [comment]
> If you're referring to the 2 screenshots that Stefan originally included (I'm not able to see the ones in the more recent posts), neither is correct, according to the ADaMIG. The only times that both AVAL and AVALC are expected to be populated on the same record are when there is a code-decode relationship between them, or when AVAL is used to control the sort order for AVALC. I would not expect to see AVALC populated with either the formatted character representation of a numeric value or with "NA" if the analysis value is numeric- it should be left blank in those cases.
> 
> Thanks, Nancy

Hi Nancy, 

Thanks for checking in, I am working on this one right now. 
I am not sure I understand correctly: 
In the second screenshot I populate the AVALC variable only because there is information is EGSTRESC that is not available in EGSTRESN: i.e. when EGSTRESC  is "NORMAL". 
All other rows are left blank, represented here as `NA`.
What output would you expect here?

**Comment by nbrucken17** [comment]
Hi Stefan,

If the "NA" are intended to represent blanks, that's fine.  When EGSTRESC=NORMAL, I'd expect AVALC to be "NORMAL", and AVAL to be left missing, unless there's a need to assign a numeric code to it for sorting or additional analysis.  Conversely, if EGSTRESC contains an actual numeric measurement, I'd expect AVAL to be contain the numeric result and AVALC to be left missing.

Since "NA" is often stored as an actual character value, I'm concerned that people will see this and think that they have to populate both AVAL and AVALC all the time, which is a misconception that the ADaM team has been working to dispel for many years now.  However, if "NA" is R's way of representing a missing value, that's fine, but then it will probably confuse any SAS programmers looking at this.  If that's the case, could it be noted somewhere?

Thanks,
   Nancy

**Comment by StefanThoma** [comment]
> Hi Stefan,
> 
> If the "NA" are intended to represent blanks, that's fine. When EGSTRESC=NORMAL, I'd expect AVALC to be "NORMAL", and AVAL to be left missing, unless there's a need to assign a numeric code to it for sorting or additional analysis. Conversely, if EGSTRESC contains an actual numeric measurement, I'd expect AVAL to be contain the numeric result and AVALC to be left missing.
> 
> Since "NA" is often stored as an actual character value, I'm concerned that people will see this and think that they have to populate both AVAL and AVALC all the time, which is a misconception that the ADaM team has been working to dispel for many years now. However, if "NA" is R's way of representing a missing value, that's fine, but then it will probably confuse any SAS programmers looking at this. If that's the case, could it be noted somewhere?
> 
> Thanks, Nancy

Hi Nancy, 

Thanks again for the clarification, looks like it is working as intended.
In R, `NA` represents a missing value. 
Please note that this is not the same as `"NA"`, which would be a string, but is indeed missing. 

All the best, 
Stefan
