### ISSUE TITLE
General Issue: Clean up and alphabetize `admiral-pacakges.R`

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#2446]
The https://github.com/pharmaverse/admiral/blob/main/R/admiral-package.R is getting a bit messy.  There are duplicated packages with one or two functions listed, which should be consolidated.  The file is also a bit hard to read as nothing is alphabetize.

![image](https://github.com/pharmaverse/admiral/assets/10111024/09a35966-3401-4ac8-976e-d55c381625ff)

Pervious discussion
_Originally posted by @bms63 in https://github.com/pharmaverse/admiral/pull/2362#discussion_r1613492532_

Definition of Done

- [ ] Consolidate duplicated packages into one
- [ ] Alphabetize functions

Quick win for anyone interested!  @pharmaverse/admiral @pharmaverse/admiral_comm

**Comment by gg106046** [comment]
@bms63 I can take this up!
