### ISSUE TITLE
General Issue: Numbered unit tests

### ISSUE THREAD

**Issue by sadchla-codes** [pharmaverse/admiral#2447]
### Background Information

Numbering the test units so that it's consistent across all of the test.
<img width="823" alt="Screenshot 2024-05-28 at 1 58 24 PM" src="https://github.com/pharmaverse/admiral/assets/112789549/64936776-7eb5-4ef4-bf12-bf1fe9d39053">

**Comment by bms63** [comment]
I'm putting this issue into a discussion https://github.com/pharmaverse/admiral/discussions/2453 as it might be part of a larger update
