### ISSUE TITLE
Documentation:  Invalid value passed to argument `out_unit` in `derive_vars_duration()` under "Usage" section

### ISSUE THREAD

**Issue by gg106046** [pharmaverse/admiral#2464]
Function Documentation

![1](https://github.com/pharmaverse/admiral/assets/103511237/c9a6b540-5df6-45aa-990d-568abd1f06d3)

The value passed to `out_unit` argument in `derive_vars_duration()` function should be in lowercase instead of up case.

**Comment by bundfussr** [comment]
I think uppercase is fine. For the calculation the value is handled case-insensitive. However, the unit variable is set to the specified value (without changing the case). As far as I remember we are using `"DAYS"` as default value because it is the value defined in the CDISC codelist C71620.

**Comment by gg106046** [comment]
I think for the calculation, the value of `out_unit` is case-sensitive as I get the following error:

![image](https://github.com/pharmaverse/admiral/assets/103511237/5e7f9b0e-67e2-40d3-975e-af853fab28d3)

But when `out_unit` is set to a lower-case unit, the unit variable comes up as an up-case unit (`YEARS"/"DAYS"`) by default in the dataset.

**Comment by bundfussr** [comment]
Are you using an old version of admiral? We changed it in admiral 1.0.0.

I get
```
> derive_vars_duration(data,
+                      new_var = ADURN,
+                      new_var_unit = ADURU,
+                      start_date = ASTDT,
+                      end_date = AENDT,
+                      out_unit = "days"
+ )
# A tibble: 4 × 5
  USUBJID ASTDT      AENDT      ADURN ADURU
  <chr>   <date>     <date>     <dbl> <chr>
1 P01     2021-03-05 2021-03-02    -3 days 
2 P02     2019-09-18 2019-09-18     1 days 
3 P03     1985-01-01 NA            NA NA   
4 P04     NA         NA            NA NA   
> derive_vars_duration(data,
+                      new_var = ADURN,
+                      new_var_unit = ADURU,
+                      start_date = ASTDT,
+                      end_date = AENDT,
+                      out_unit = "DAYS"
+ )
# A tibble: 4 × 5
  USUBJID ASTDT      AENDT      ADURN ADURU
  <chr>   <date>     <date>     <dbl> <chr>
1 P01     2021-03-05 2021-03-02    -3 DAYS 
2 P02     2019-09-18 2019-09-18     1 DAYS 
3 P03     1985-01-01 NA            NA NA   
4 P04     NA         NA            NA NA   
```

**Comment by gg106046** [comment]
> Are you using an old version of admiral? We changed it in admiral 1.0.0.
> 
> I get
> 
> ```
> > derive_vars_duration(data,
> +                      new_var = ADURN,
> +                      new_var_unit = ADURU,
> +                      start_date = ASTDT,
> +                      end_date = AENDT,
> +                      out_unit = "days"
> + )
> # A tibble: 4 × 5
>   USUBJID ASTDT      AENDT      ADURN ADURU
>   <chr>   <date>     <date>     <dbl> <chr>
> 1 P01     2021-03-05 2021-03-02    -3 days 
> 2 P02     2019-09-18 2019-09-18     1 days 
> 3 P03     1985-01-01 NA            NA NA   
> 4 P04     NA         NA            NA NA   
> > derive_vars_duration(data,
> +                      new_var = ADURN,
> +                      new_var_unit = ADURU,
> +                      start_date = ASTDT,
> +                      end_date = AENDT,
> +                      out_unit = "DAYS"
> + )
> # A tibble: 4 × 5
>   USUBJID ASTDT      AENDT      ADURN ADURU
>   <chr>   <date>     <date>     <dbl> <chr>
> 1 P01     2021-03-05 2021-03-02    -3 DAYS 
> 2 P02     2019-09-18 2019-09-18     1 DAYS 
> 3 P03     1985-01-01 NA            NA NA   
> 4 P04     NA         NA            NA NA   
> ```



> Are you using an old version of admiral? We changed it in admiral 1.0.0.
> 
> I get
> 
> ```
> > derive_vars_duration(data,
> +                      new_var = ADURN,
> +                      new_var_unit = ADURU,
> +                      start_date = ASTDT,
> +                      end_date = AENDT,
> +                      out_unit = "days"
> + )
> # A tibble: 4 × 5
>   USUBJID ASTDT      AENDT      ADURN ADURU
>   <chr>   <date>     <date>     <dbl> <chr>
> 1 P01     2021-03-05 2021-03-02    -3 days 
> 2 P02     2019-09-18 2019-09-18     1 days 
> 3 P03     1985-01-01 NA            NA NA   
> 4 P04     NA         NA            NA NA   
> > derive_vars_duration(data,
> +                      new_var = ADURN,
> +                      new_var_unit = ADURU,
> +                      start_date = ASTDT,
> +                      end_date = AENDT,
> +                      out_unit = "DAYS"
> + )
> # A tibble: 4 × 5
>   USUBJID ASTDT      AENDT      ADURN ADURU
>   <chr>   <date>     <date>     <dbl> <chr>
> 1 P01     2021-03-05 2021-03-02    -3 DAYS 
> 2 P02     2019-09-18 2019-09-18     1 DAYS 
> 3 P03     1985-01-01 NA            NA NA   
> 4 P04     NA         NA            NA NA   
> ```

Ah yes. I was using an older version. My bad! This issue can be closed then.
