### ISSUE TITLE
Feature Request: Implement `derive_vars_crit_flag()`

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#2468]
### Feature Idea

Implement `derive_vars_crit_flag()` which derives the variables `CRITy`, `CRITyFL`, and `CRITyFLN` (for a specific value of `y`). The derivation of these variables is very simple. However, there are some requirements which many programmers and specs authors are not aware of. For example, that the derivation must rely on variables from the current records only and the relation of the values of `CRITy` and `CRITyFL` (e.g., if `CRITyFL` is set to `"Y"` or `"N"`, `CRITy` must be populated for all records with the same value).

The function should cover all use cases of the `CRIT` variables. I.e., if a `CRIT` variable can not be derived with the function, the derivation is not ADaM compliant. 

### Reproducible Example/Pseudo Code

```
adxx <- adxx %>% derive_vars_crit_flag(
  crit_nr = 1,
  condition = AVAL > 50,
  description = paste(PARAM, "> 50"),   # CRITy is set to the specified value
  values_yn = FALSE,                    # should values "Y", "N", and NA be used?
  create_numeric_flag = TRUE            # should CRITyFLN be created?
)
```

**Comment by bms63** [comment]
I think this looks useful!

Do we want to use `_flag` at the end to keep in line with other flag related functions?

Also, we have the hy's law vignette which discusses Crit flags - maybe opportunity to update with this function?
 
https://pharmaverse.github.io/admiral/articles/hys_law.html

What do you think @pharmaverse/admiral and @pharmaverse/admiral_comm?  Any takers?   I think this could be a fun one to implement for those eager to do some function building for admiral!!

**Comment by bundfussr** [comment]
> Do we want to use `_flag` at the end to keep in line with other flag related functions?

Yes, seems reasonable to me.

**Comment by manciniedoardo** [comment]
Looks reasonable to me as well, thanks for the suggestion @bundfussr.

Just for general awareness, in admiralophtha we have `derive_var_bcvacrtixfl()` - see [here](https://pharmaverse.github.io/admiralophtha/reference/derive_var_bcvacritxfl.html) for reference. But to be honest I wouldn't mind absorbing its functionality inside a new {admiral} function and then either superseding it or turning it into a wrapper for the {admiral} function.

On another note, could we couple this effort with a similar function for `AVALCATx`?

**Comment by bundfussr** [comment]
> On another note, could we couple this effort with a similar function for `AVALCATx`?

@manciniedoardo , what do you have in mind? Should it derive `AVALCATx` only or also similar variables like `CHGCATy` or `AGEGRy`? What is expected as input?

**Comment by manciniedoardo** [comment]
> > On another note, could we couple this effort with a similar function for `AVALCATx`?
> 
> @manciniedoardo , what do you have in mind? Should it derive `AVALCATx` only or also similar variables like `CHGCATy` or `AGEGRy`? What is expected as input?

Actually it was just a passing thought, I haven't looked in the IG yet to see if AVALCAT/CHGCAT have as stringent guidelines. My thought was that if yes, maybe we could also develop `derive_var_avalcat()` and similar.

**Comment by nbrucken17** [comment]
AVALCATy has a restriction that it can only be derived using values of AVAL or AVALC.  CHGCATy is under a similar restriction- it can only be derived using values of CHG.  AGEGRy should only be derived based on values of age, but which age variable is used is up to the producer, since multiple age variables are possible in ADSL.

**Comment by manciniedoardo** [comment]
> AVALCATy has a restriction that it can only be derived using values of AVAL or AVALC. CHGCATy is under a similar restriction- it can only be derived using values of CHG. AGEGRy should only be derived based on values of age, but which age variable is used is up to the producer, since multiple age variables are possible in ADSL.

Thanks @nbrucken17 - if that is all maybe this is not a good idea, as you may just as well derive them inside a mutate statement!

**Comment by bundfussr** [comment]
While updating the Roche templates I noticed that the numeric flag created by `derive_vars_crit_flag()` is of type double. Should it be integer?

@bms63 , @manciniedoardo , @millerg23 , what do you think?

**Comment by millerg23** [comment]
> While updating the Roche templates I noticed that the numeric flag created by `derive_vars_crit_flag()` is of type double. Should it be integer?
> 
> @bms63 , @manciniedoardo , @millerg23 , what do you think?

I would have thought it should be type integer.
https://www.cdisc.org/kb/examples/adam-basic-data-structure-bds-using-crit-80283859

**Comment by bms63** [comment]
I think it should be integer.  This is nice when comparing to a production dataset done in SAS

The derive_var_obs_number does the same thing actually.  I always have to do an as.integer so compare is clean - not a big deal - but maybe another update?
