### ISSUE TITLE
General Issue: `CHG` and `PCHG` populated for Baseline and pre-baseline records in the templates 

### ISSUE THREAD

**Issue by Fanny-Gautier** [pharmaverse/admiral#2484]
### Background Information

While working on the ADVS template of {admiralpeds} we were surprised to see `CHG` and `PCHG` populated at baseline and pre-baseline records in some templates such as {admiral} ADVS template. We would have expect `NA` as default value for these records.

### Definition of Done

Use `restrict_derivation()` in the templates while deriving `CHG`and `PCHG` and explain the rational in the corresponding vignettes. As default, `CHG` and `PCHG` should not be populated for Baseline and pre-baseline records.

**Comment by bms63** [comment]
@pharmaverse/admiral @pharmaverse/admiral_comm this is a good one to snag - easy update but get to play around with a really cool function.

**Comment by nbrucken17** [comment]
Hi all,

Just felt obligated to note that there is nothing in the ADaMIG stating whether CHG and PCHG should or should not be populated for baseline and pre-baseline records.  That's entirely a sponsor decision.

Thanks,
   Nancy

**Comment by Fanny-Gautier** [comment]
> Just felt obligated to note that there is nothing in the ADaMIG stating whether CHG and PCHG should or should not be populated for baseline and pre-baseline records. That's entirely a sponsor decision.

Then it could be added as a comment or a note in the template that is it currently populated and it remains a sponsor decision ... Just to make it clear.

**Comment by bms63** [comment]
> Updated ADVS template to use restrict_derivation() with filter AVISITN > 0 for CHG and PCHG derivations, comments were also revised to mention post-baseline.

Could you create a Pull Request please?
