### ISSUE TITLE
General Issue: Move deprecated arguments and functions to next phase or remove

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#2487]
### Background Information

These function arguments should be further deprecated or removed

![image](https://github.com/user-attachments/assets/49dac966-6b9f-4efb-943f-f734a76f15dd)

Please follow this guidance when deprecating https://pharmaverse.github.io/admiraldev/dev/articles/programming_strategy.html#deprecation

### Definition of Done

- [ ] Functions or arguments being removed should be documented in the changelog
- [ ] Function or arguments being removed based on their phase of deprecation should also be documented
  - [ ] Bonus points if you split them up as Phase 1, 2, 3 so easier to track!
- [ ] Be sure functions/argument documents are appropriately updated and/or removed
- [ ] Be sure unit tests appropriately capture deprecation where appropriate
- [ ] Remove any old deprecation unit tests no longer relevant

@pharmaverse/admiral @pharmaverse/admiral_comm this is a good one to knock out!!  Very helpful to us to do this in the beginning of the cycle!

**Comment by StefanThoma** [comment]
I'll take this one :)

**Comment by bms63** [comment]
Are you still able to complete this?

**Comment by StefanThoma** [comment]
Yeah planning to do it by the end of the month. 
Does that work for you?

**Comment by bms63** [comment]
> Yeah planning to do it by the end of the month. Does that work for you?

Perfect!

**Comment by StefanThoma** [comment]
@bms63 

There is one function that has been superseded but does not call the deprecate_warn or deprecate_error directly, only via deprecated arguments: 

#' Create Summary Records
#'
#' @description
#'
#' `r lifecycle::badge("superseded")`


Should I remove this function?

**Comment by bms63** [comment]
> @bms63
> 
> There is one function that has been superseded but does not call the deprecate_warn or deprecate_error directly, only via deprecated arguments, `get_summary_records`:
> 
> #' Create Summary Records #' #' @description #' #' `r lifecycle::badge("superseded")`
> 
> Should I remove this function?

We are leaving that function in for a long time even though it has been replaced.  It can just keep the superseded badge.
