### ISSUE TITLE
Feature Request from `pharmaverseadam`: add `AVALU` to ADEG

### ISSUE THREAD

**Issue by kaz462** [pharmaverse/admiral#2490]
### Background Information

https://github.com/pharmaverse/pharmaverseadam/issues/78

### Definition of Done

Derive `AVALU = EGSTRESU` in [ADEG template](https://github.com/pharmaverse/admiral/blob/main/inst/templates/ad_adeg.R)

**Comment by kaz462** [comment]
@pharmaverse/admiral @pharmaverse/admiral_comm good first issue

**Comment by millerg23** [comment]
I don't think `AVALU` is a CDISC variable in `ADLB`, `ADVS` and `ADEG` up intil now as unit is included in `PARAM`, we have only created CDISC derivations in `admiral`. We originally created them, but then removed `AVALU`

**Comment by nbrucken17** [comment]
AVALU is not a standard CDISC variable, as Gordon noted, because units are expected to be contained in PARAM. However, it has made its way into several FDA Tech Specs and ADNCA, due to regulatory requests or software needs. There has been a proposal to change the variable name to PARAMU for ADaM 3.0, since it’s really an attribute of the parameter itself, not the value, but that’s a few years away. So, my suggestion would be to not routinely include it in ADEG or ADVS, unless it’s really needed for a specific reason.

Thanks,
   Nancy

**Comment by kaz462** [comment]
@millerg23 @nbrucken17 Thank you for the background information! 
I think it's a good idea to maintain the rule of "only creating CDISC derivations in `admiral`". In this case, the following variables requested by @edelarua will not be added, @pharmaverse/admiral do you agree? 

- `ADCM.ATIREL` from https://github.com/pharmaverse/pharmaverseadam/issues/77
- `AVALU` and `WORS02FL` from https://github.com/pharmaverse/pharmaverseadam/issues/78

**Comment by bms63** [comment]
Can you add them on in the data package?  This is a request from nest correct?

**Comment by kaz462** [comment]
> Can you add them on in the data package?

The data in `pharmaverseadam` is generated by running the `admiral` template  

> This is a request from nest correct?

Yes, see https://github.com/insightsengineering/scda.test/issues/133

**Comment by bms63** [comment]
Could the action in the data package run the template(s) and then add these variables as part of the action?

**Comment by bundfussr** [comment]
> Could the action in the data package run the template(s) and then add these variables as part of the action?

I'm not sure if this is a good idea. If we add extra derivations to `data-raw/create_adams_data.R`, it could become quite complex. Furthermore, for the users it would be hard to understand how the additional variables are derived. At the moment they can have a look at the template. But if the dataset contains variables which are not in the template, it could confuse the users.

Maybe we should create a separate dataset like `adeg_nest` which contains the additional variables. The script which creates `adeg_nest` could read in `adeg` and add the additional variables. The script could be stored in one of the nest packages. Then we could use the same approach as for the admiral extension packages.

@bms63 , what do you think?

**Comment by manciniedoardo** [comment]
I tend to agree with @bundfussr - would rather keep the pharmaverseadam action to a simple rerun. Additionally I think `adeg_nest` is way overkill from us - if NEST needs extra variables for internal Roche purposes then why should we add them to admiral open source? Rather I think they should add those variables in their preprocessing.

**Comment by bms63** [comment]
I am all for simple!

I guess I thought the purpose of nest using pharmaverseadam was a one-stop shop for the ADaMs they need.  So a user could grab the data just from one package that is being used in the Apps.

But yes all for simple.  So pass it on to nest.  :)

**Comment by esimms999** [comment]
Ool


Sent from Yahoo Mail for iPhone


On Sunday, August 18, 2024, 8:46 PM, Ben Straub ***@***.***> wrote:




I am all for simple!

I guess I thought the purpose of nest using pharmaverseadam was a one-stop shop for the ADaMs they need. So a user could grab the data just from one package that is being used in the Apps.

But yes all for simple. So pass it on to nest. :)
