### ISSUE TITLE
Update Lab Grading Criteria Metadata 

### ISSUE THREAD

**Issue by kaz462** [pharmaverse/admiral#2492]
# Grading Criteria Metadata  NCI-CTCAEv5

1. From [lab_grading/assumptions-made-when-grading](https://pharmaverse.github.io/admiral/articles/lab_grading.html#assumptions-made-when-grading-1): 
    >  For BASE to be abnormal we compare it with the Upper Limit of Normal (ULN) ANRHI, i.e. BASE > ANRHI
     

     - I encountered a situation where ANRHI differs within a subject and lab test due to data from different lab vendors. Should we consider changing the use of ANRHI to BNRIND when determining whether the baseline is normal/abnormal?

2. Some CTCAE grade definitions contain two sets of units, but only one is provided in the current grading metadata. For example, `TERM=Hypoalbuminemia` has only one row for `unit = g/L`, so it's not be able to grade for `unit = g/dL` 
![image](https://github.com/pharmaverse/admiral/assets/47867131/4a1c0845-2c52-4919-b4fe-1de8828495ad)
can we add more rows to the metadata to cover different units?

_Originally posted by @kaz462 in https://github.com/pharmaverse/admiral/discussions/2191#discussioncomment-8074207_

**Comment by bms63** [comment]
Hey @millerg23 just checking on the progress for this issue

**Comment by millerg23** [comment]
@bms63 you OK if we spit this into 2 separate issues? One for using BNRIND (I just created a pull request for this), and another issue for handling different units?

**Comment by bms63** [comment]
I always love breaking things into smaller things and finishing them quickly!  What ever makes sense here for you I am okay with!
