### ISSUE TITLE
Update use of data("sdtm") to sdtm <- pharmaverse::sdtm in templates and vignettes

### ISSUE THREAD

**Issue by jimrothstein** [pharmaverse/admiral#2498]
## Documentation Update

Update use of data("sdtm") to  sdtm <- pharmaverse::sdtm

### QUESTION about lazy loading db:

In section 7.1 of R-pkgs book (https://r-pkgs.org/data.html#sec-data-data),  the use of data() is discouraged  when `lazy loading` is used (This is case for `admiral`,  `pharamversesdtm' and others, see DESCRIPTION, `LazyData: true`)

> It is important to note that lazily-loaded datasets do not need to be pre-loaded with utils::data() and, in fact, it’s usually best to avoid doing so. Above, once we did library(nycflights13), we could immediately access flights. There is no call to data(flights), because it is not necessary.

Is use of data()  still necessary?

Thx.

### Definition of Done

- [ ] All Vignettes have been updated to use sdtm <- pharmaverse::sdtm convention
- [ ] All Templates have been updated to use sdtm <- pharmaverse::sdtm convention
- [ ] Review Examples to see if any updates are needed as well if it makes sense to update (discuss once first two are completed)

**Comment by bms63** [comment]
@pharmaverse/admiral any thoughts?

**Comment by bundfussr** [comment]
Is this regarding using `data()` in our templates?

Technically we could remove the section with the `data()` calls from our templates. However, I think this would make the templates less readable because it wouldn't be clear where objects like `ae` or `ex` come from when they are used the first time. Maybe we could replace calls like `data(ae)` with `ae <- pharmaversesdtm::ae`. Then it is clear where the data comes from and the users who want to use their own data could easily replace `pharmaversesdtm::ae` with their source of data.

**Comment by bms63** [comment]
> Is this regarding using `data()` in our templates?
> 
> Technically we could remove the section with the `data()` calls from our templates. However, I think this would make the templates less readable because it wouldn't be clear where objects like `ae` or `ex` come from when they are used the first time. Maybe we could replace calls like `data(ae)` with `ae <- pharmaversesdtm::ae`. Then it is clear where the data comes from and the users who want to use their own data could easily replace `pharmaversesdtm::ae` with their source of data.

oh man...I think we used to do this 3 years ago lol.  

I like `<-` method more as it is better for new folks.

**Comment by bms63** [comment]
@jimrothstein was your concern for the vignettes?  If so, I wanted to make this into an actionable issue for someone to work on this update.  Probably just hijack this issue and change it up.

**Comment by jimrothstein** [comment]
| re: vignettes

Is this the new consensus?

Replace: 
`
data(ae)
`

With:
`
ae <- pharmaversesdtm::ae
`
I am too new to have strong opinions.   This is still repetetive (ae <- pharamverse::ae) but if it it brings clarity and everyone is happy,  then I am fine, too.

I can make the these changes, unless you fell I should focus on `data/data-raw standard`, which still has much work to do.

**Comment by bms63** [comment]
> | re: vignettes
> 
> Is this the new consensus?
> 
> Replace: `data(ae)`
> 
> With: `ae <- pharmaversesdtm::ae` I am too new to have strong opinions. This is still repetetive (ae <- pharamverse::ae) but if it it brings clarity and everyone is happy, then I am fine, too.
> 
> I can make the these changes, unless you feel I should focus on `data/data-raw standard`, which still has much work to do.

yes I like that more than `data(ae)` .  All my programs have ae <- read_sas(...) in them so this looks more familiar to me.  

@pharmaverse/admiral any strong objections to this update - feel like the `data(ae)` was adopted 2 years ago...around the merry go round we go!!

**Comment by ddsjoberg** [comment]
I feel like the `data()` convention is old-school style, meant to save bytes and bytes of RAM by not loading the data by default when a package is attached.

**Comment by StefanThoma** [comment]
No objections from my side either. 
`ae <- pharmaversesdtm::ae`  is more natural to me as well.

**Comment by StefanThoma** [comment]
This could be a `good first issue`
