### ISSUE TITLE
Bug: The text on our Authors page about authors and contributors does not show anymore

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiral#2511]
### What happened?

[admiral 1.1.1 site](https://pharmaverse.github.io/admiral/authors.html):
![image](https://github.com/user-attachments/assets/f0a2e8e6-8394-486a-8f1f-6e9afde4602d)

[admiral 1.1.1.9009 dev site:](https://pharmaverse.github.io/admiral/dev/authors.html)
![image](https://github.com/user-attachments/assets/f94a9ca9-23c9-45d5-af62-4e585114516b)

### Session Information

NA

### Reproducible Example

NA

**Comment by bms63** [comment]
I see it here?

![image](https://github.com/user-attachments/assets/29d54b62-466f-4517-92f2-b42594d888a9)

**Comment by manciniedoardo** [comment]
Do you see it at https://pharmaverse.github.io/admiral/dev/authors.html?

**Comment by bms63** [comment]
@cicdguy should we worry that things are disappearing in our dev site ?

**Comment by bms63** [comment]
@manciniedoardo they have addressed it in pkgdown - shall we close?
