### ISSUE TITLE
Feature Request from `admiralmetabolic`: Wrapper for `derive_param_calculated()` to derive Ratio parameters

### ISSUE THREAD

**Issue by yurovska** [pharmaverse/admiral#2514]
## Background

A discussion (see below) and in admiralmetabolic around creating more wrapper functions.  It was decided to not create additional wrapper function in admiral.  However, we want to easily surface the word Ratio in our search bar so users know that `derive_param_computed()` can be used for ratio calculations.

## Definition of Done

* Create additional examples that calculate different types of rations
* Insert wording into Details Section and other helpful areas to help surface the word ratio
* Verify this in the search bar when creating local pkgdown site.

#### Feature Idea (Old Discussion)

During development of the functions for waist/hip and waist/height ratio in `admiralmetabolic` a more generic `derive_param_ratio()` appeared that can actually derive any Ratio parameter. So this is just to move the code from the extension to the core as it can be used for any TA. Metabolism-specific derivations are going to use it as a dependency.

See discussion here: https://github.com/pharmaverse/admiralmetabolic/issues/31

**Comment by bms63** [comment]
@pharmaverse/admiral @pharmaverse/admiral_comm what do people think?  The PR is already moving fast!!  Thanks @yurovska !!

**Comment by bundfussr** [comment]
> @pharmaverse/admiral @pharmaverse/admiral_comm what do people think? The PR is already moving fast!! Thanks @yurovska !!

Please see my comment in https://github.com/pharmaverse/admiralmetabolic/issues/31#issuecomment-2385899540.

**Comment by bms63** [comment]
Closing as being done in admiralmetabolic
