### ISSUE TITLE
Templates: Spruce up ADSL

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#2517]
### Background Information

ADSL template needs a little love

The comment needs to be updated for input datasets -

![image](https://github.com/user-attachments/assets/b331e006-e92e-4b9b-bb51-b82c46650ba9)

and these source objects should be removed as the `derive_vars_extreme_event()` function replaced this method

![image](https://github.com/user-attachments/assets/ca2081c9-819a-4e47-bff8-c1b2f58d3a39)

### Definition of Done

Comment updated and legacy code removed.

Great issue for @pharmaverse/admiral_comm and wanting to keep your admiral skills fresh :)

**Comment by jimrothstein** [comment]
I can take a look
