### ISSUE TITLE
General Issue: Increase test coverage

### ISSUE THREAD

**Issue by jeffreyad** [pharmaverse/admiral#2522]
### Background Information

Our test coverage is currently 97%. Could we increase towards 100%?
![image](https://github.com/user-attachments/assets/6ecb57b7-f078-4954-9957-1ec47aea3ce5)

See also #2520 and #2521 

### Definition of Done

Write new tests to increase level of coverage.

Use `devtools::test_coverage()` to reproduce the report

**Comment by bms63** [comment]
FYI - Some of these could be very challenging.  Please make sub-issues on ones that you would like to write tests for.

**Comment by bms63** [comment]
Actually is anyone from @pharmaverse/admiral or @pharmaverse/admiral_comm willing to go through and make new issues for these missing test coverages that haven't already been created?  Its a bit tedious work, but might be really nice for the R/Pharma new folks who want to lend a hand to admiral or just get those cool internet points for doing a Pull Request!!  

Some of the tests might be tough to write and I was hoping we could identify them and label them as Intermediate/Advance.  So folks don't lose interests and we can steer them appropriately.

Any volunteers?  Great way to contribute back and get new blood in the pool!! Spooky times!

**Comment by bms63** [comment]
Closing as @manciniedoardo has started to do this
