### ISSUE TITLE
Documentation:  Add more keywords to descriptions of `derive_param_computed()` and `derive_vars_computed()`

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiral#2529]
### Let us know where something needs a refresh or put your idea here!

A user gave feedback that they were looking to implement a derived parameter that was a ratio of two other parameters and they searched for the keyword "ratio" in the website searchbar. This did not redirect them to `derive_param_computed()`.

From a searchability perspective it could be beneficial to add a few of keywords to the description of these functions so that users may be redirected to them. Possible words:
- sum
- difference
- product/mutliplication
- division/ratio
- exponent(iation)
- logarithm

It's a little brute force-y but may be a quick and easy improvement.

**Comment by bms63** [comment]
I am going to save this for R/Pharma
