### ISSUE TITLE
Update {admiral} presentation list

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiral#2540]
I will be updating the [Presentation Archive](https://pharmaverse.github.io/admiraldiscovery/articles/presentation_archive.html) in early December 2024.

@pharmaverse/admiral @pharmaverse/admiral_comm please could you edit this comment and add any presentations missed: 

### useR 2024

- @manciniedoardo @StefanThoma {admiral} - _the {dplyr} of the pharmaceutical industry_ (video may be published [here](https://www.youtube.com/@useRConference_global/videos) - @StefanThoma can we somehow provide slides?

### Phuse EU Connect 2024

- @manciniedoardo - _Two hats, one noggin: Perspectives on working as a developer and as a user of the admiral R package for creating ADaMs_  ([slides](https://phuse.s3.eu-central-1.amazonaws.com/Archive/2024/Connect/EU/Strasbourg/PRE_OS07.pdf), [paper](https://phuse.s3.eu-central-1.amazonaws.com/Archive/2024/Connect/EU/Strasbourg/PAP_OS07.pdf))
- Yirong Cao. Yi Yan: _Insights of Using {admiralonco} at BMS: Facilitating Oncology Efficacy ADaM Datasets_ ([slides](https://phuse.s3.eu-central-1.amazonaws.com/Archive/2024/Connect/EU/Strasbourg/PRE_SM05.pdf), [paper](https://phuse.s3.eu-central-1.amazonaws.com/Archive/2024/Connect/EU/Strasbourg/PAP_SM05.pdf))
- @federicobaratin  - _admiralvaccine Project JouRney_ ([slides](https://phuse.s3.eu-central-1.amazonaws.com/Archive/2024/Connect/EU/Strasbourg/PRE_OS08.pdf), [paper](https://phuse.s3.eu-central-1.amazonaws.com/Archive/2024/Connect/EU/Strasbourg/PAP_OS08.pdf))

**Comment by bms63** [comment]
@zdz2101 just did a presentation at CDISC - Zelos can you link here?

@Fanny-Gautier, you, me, @sadchla-codes did a workshop at R/Pharma.  Presentation here: https://pharmaverse.github.io/rpharma-2024-ADaM-workshop/#/title-slide.  Repo here: https://github.com/pharmaverse/rpharma-2024-ADaM-workshop

**Comment by StefanThoma** [comment]
Hey @manciniedoardo I just published our slides. 
https://stefanthoma.github.io/useR_2024_admiral

Let me contact the UseR2024 people about the video, I was under the impression that they do publish it, but I cannot find it still.

**Comment by manciniedoardo** [comment]
> @zdz2101 just did a presentation at CDISC - Zelos can you link here?

@zdz2101 reminder to please provide link

**Comment by manciniedoardo** [comment]
Now merged - as @ddsjoberg noted, we'll do a release of admiraldiscovery in Jan.
