### ISSUE TITLE
Feature Request: Implement transform_range()

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiral#2571]
### Feature Idea

From suggestion by @bundfussr: 

_to help with ADQS programming, it would be convenient to implement a function which provides the same transformation arguments as `compute_scale()`:_

```
transform_range <- function(value,
                            source_range = NULL,
                            target_range = NULL,
                            flip_direction = FALSE,
                            outside_range = "NA"
)
```

_The `outside_range` argument determines how values outside the source range are handled. Options are setting to `NA`, issuing an error, or issuing a warning. (The new function could also be called by `compute_scale()`.) I would expect that it could be useful for other questionnaires as well._

### Relevant Input

See [here](https://pharmaverse.github.io/admiral/reference/compute_scale.html?q=compute_scale#null) for `compute_range()` inputs.

### Relevant Output

A transformed value

### Reproducible Example/Pseudo Code

```
transform_range(
  value = 2,
  source_range = c(1:5),
  target_range = c(0:100),
  flip_direction = FALSE,
  outside_range = NA
)
```
Should return `25`.

```
transform_range(
  value = 3,
  source_range = c(1:6),
  target_range = c(0:100),
  flip_direction = TRUE,
  outside_range = NA
)
```
Should return `60` i.e. `100 - 40`.

```
transform_range(
  value = 300,
  source_range = c(1:6),
  target_range = c(0:100),
  flip_direction = TRUE,
  outside_range = NA
)
```
Should return `NA`.

**Comment by manciniedoardo** [comment]
@bundfussr please double check logic above, thanks

**Comment by bundfussr** [comment]
> @bundfussr please double check logic above, thanks

@manciniedoardo , looks good to me. Thanks for creating the issue.
