### ISSUE TITLE
Enhance test coverage for `get_summary_records()`

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiral#2576]
### Background Information

It would be great to get `{admiral}`'s test coverage to 100%. However, this should **not** come at the expense of development time/effort from `{admiral}` core developers. As such, I have made a set of issues tagged "Unit Tests" (such as this one for `get_summary_records()`) where users who wish to dip their feet into the `{admiral}` ecosystem can:

- Learn a bit about unit testing for R packages
- Make a meaningful contribution to {admiral}

by adding or modifying unit tests to account for lines not previously covered.

**Important note: Given the above, this issue is for newcomers to `{admiral}` or users who wish to contribute to the package, and should not be taken on by core `{admiral}` developers.**

### Definition of Done

- [ ] Unit test(s) added/modified to test the lines in red in `get_summary_records()`:
![image](https://github.com/user-attachments/assets/753df451-09e0-487c-9a7f-37a645b9d512)

**Comment by bms63** [comment]
So - working on deprecation this is one that has been deprecated.  Going to see if I can just add a blanket #nocov here and be done with this one

**Comment by bms63** [comment]
Actually - we seem to be good on this one.  Going to close 
![image](https://github.com/user-attachments/assets/d8e093ca-ff58-4eab-be44-a7565c8f32b6)
