### ISSUE TITLE
Documentation:  Questionnaires vignette intro needs updating

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiral#2586]
### Please select a category the issue is focused on?

User Guides

### Let us know where something needs a refresh or put your idea here!

The intro to the [Questionnaires ADaM](https://pharmaverse.github.io/admiral/dev/articles/questionnaires.html) User Guide reads:

_At the moment, [admiral](https://pharmaverse.github.io/admiral/) does not provide functions or metadata for specific questionnaires nor functionality for handling the vast amount of questionnaires and related parameters, e.g. a metadata structure for storing parameter definitions and functions for reading such metadata. We plan to provide it in future releases._

I don't think this is accurate anymore. I propose to just cut, and if anything say only that specific questionnaires are sometimes addressed in extension packages.

@bms63 thoughts?

**Comment by bundfussr** [comment]
@manciniedoardo , why do you think it is not accurate anymore?

If extension packages provide something for specific questionnaires, we could add a reference on the questionnaires vignette.

**Comment by bms63** [comment]
I be interested in highlighting some of the power of the extension packages for questionnaires!

The intro/statement still sounds true to me??

**Comment by manciniedoardo** [comment]
> @manciniedoardo , why do you think it is not accurate anymore?
> 
> If extension packages provide something for specific questionnaires, we could add a reference on the questionnaires vignette.

Sorry, I probably should have specified what I meant by not accurate. To my knowledge, this bit _"e.g. a metadata structure for storing parameter definitions and functions for reading such metadata. We plan to provide it in future releases."_  is inaccurate as we don't have plans. As you guys mention I'd rather highlight the power of ext packages.

**Comment by bms63** [comment]
ooohhh the mention of the json file for grading stuff has me thinking more on this...maybe we do have a "plan" :)

**Comment by manciniedoardo** [comment]
maybe an item for our 2025 roadmap?

**Comment by bms63** [comment]
love it!

**Comment by manciniedoardo** [comment]
Have added to my notes, will close this issue for now.

**Comment by bms63** [comment]
Is this going in a 1.3 - 2.0  Roadmap Discussion thread!?!
