### ISSUE TITLE
Documentation:  Remove `{rlang}` from `derive_basetype_records` example

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#2596]
### Let us know where something needs a refresh or put your idea here!

rlang is called in the example but it isn't necessary.  Thus it should be removed

![image](https://github.com/user-attachments/assets/b9f1b4d3-1a4c-4f61-aa51-1560c3bb6ea2)

# Definition of Done
* rlang removed from https://pharmaverse.github.io/admiral/reference/derive_basetype_records.html?q=basetype#ref-usage
* Double check no other calls to rlang occur in our examples

**Comment by bms63** [comment]
A quick one for anyone looking to contribute @pharmaverse/admiral_comm

**Comment by Brijeshthummar02** [comment]
@bms63 show me the path to the file where it should be updated.

**Comment by bms63** [comment]
> @bms63 show me the path to the file where it should be updated.

@Brijeshthummar02 this is the one - https://github.com/pharmaverse/admiral/blob/6351451ac289b17bf0530e2a7c87cdece8003fff/R/derive_basetype_records.R#L42

**Comment by Brijeshthummar02** [comment]
@bms63 go through pr #2598.
