### ISSUE TITLE
Documentation:  Typo in bds_finding vignette

### ISSUE THREAD

**Issue by Fanny-Gautier** [pharmaverse/admiral#2604]
### Please select a category the issue is focused on?

User Guides

### Let us know where something needs a refresh or put your idea here!

Minor update needed - while going through the [bds_finding](https://github.com/pharmaverse/admiral/blob/main/vignettes/bds_finding.Rmd) vignette I noticed a typo line 233: we should read here `PARCAT1` instead of `PARAMCAT1`

**Comment by bms63** [comment]
Super easy one if you want to plug back in to admiral! @pharmaverse/admiral @pharmaverse/admiral_comm
