### ISSUE TITLE
Improve missing value handling in compute_egfr()

### ISSUE THREAD

**Issue by jeffreyad** [pharmaverse/admiral#2612]
### Feature Idea

Currently if there is a missing values for `SEX` in `compute_egfr()` the error message below results.  Perhaps a warning and missing value should be returned instead.
```
Error in `mutate()`:
ℹ In argument: `CRCL = compute_egfr(...)`.
Caused by error in `compute_egfr()`:
! Argument `sex` must be <character> with values "M" and "F".
Run `rlang::last_trace()` to see where the error occurred.
```

**Comment by bundfussr** [comment]
Makes sense to me. I wonder if we need a warning. If one the other arguments like `weight` is `NA`, `NA` is returned without any warning. I think this is the usual behavior in R.
