### ISSUE TITLE
Proposal for categorization of values

### ISSUE THREAD

**Issue by aehmann-gsk** [pharmaverse/admiral#281]
Categorization of values (e.g. AGEGR1/AGEGR1N, AVALCAT1/AVALCT1N, BMIBLGR1/BMIBLGN1, etc.) 
Should we implement something similar to SAS formats? 
We could implement a function which returns a function. 
See Questions and Comments Review agenda minutes from 28JUN2021:
https://exbpbox.box.com/s/josnue7p4opxt60c2a56jvb2nu7jnej0

Decision: Alice to create an issue for a proposal

**Comment by statasaurus** [comment]
This function is completed in the metatools package
