### ISSUE TITLE
Describe a programming workflow for ADTTE (6h)

### ISSUE THREAD

**Issue by thomas-neitmann** [pharmaverse/admiral#324]
goal:
create a programming workflow to identify needed functionality. Create an issue per function.

**Comment by bundfussr** [comment]
@Roche-GSK/admiral-devs , the [ADTTE workflow](https://exbpbox.box.com/s/bvrbn2ie94nk3di3z5t52v2zgi9q9o1l) is available at box and can be reviewed.
