### ISSUE TITLE
Templates feedback (2-3h)

### ISSUE THREAD

**Issue by slamao** [pharmaverse/admiral#329]
* I would rather use `saveRDS` instead of `save` at the end of the templates. `load` (pair function to `save`) assigns by a side-effect, making it dangerous because it can overwrite existing objects without notice. `my_data <- readRDS` is safer.

* The use of `case_when` function: `!is.na` in the first case in the example below is irrelevant, it either needs to be used explicitly everywhere, or nowhere, or as a single clause:
  ```
  format_agegr1 <- function(x) {
    case_when(
      !is.na(x) & x < 18 ~ "< 18",
      x >= 18 & x < 65 ~ "18 - 65",
      x >= 65 ~ ">= 65"
    )
  }
  ```

  The two calls have the same result: 
  ```
  format_agegr2 <- function(x) {
    case_when(
      x < 18 ~ "< 18",  
      x >= 18 & x < 65 ~ "18 - 65",
      x >= 65 ~ ">= 65"
    )
  }
  format_agegr1(c(NA,10,20))
  format_agegr2(c(NA,10,20))
  ```
  See the examples of `?case_when` for further details. There are multiple cases of this throughout the package.

* We now have templates (inst/templates) and example scripts (inst/example_scripts). The difference between those two is minor so I would suggest to use templates instead of example scripts everywhere. Anyway, the example scripts are only used as a reference in vignettes and in data:
![image](https://user-images.githubusercontent.com/22340537/124899679-a5aa4580-dfe0-11eb-98d3-e097e177dd78.png)

**Comment by bms63** [comment]
> > I would rather use saveRDS instead of save at the end of the templates. load (pair function to save) assigns by a side-effect, making it dangerous because it can overwrite existing objects without notice. my_data <- readRDS is safer.
> 
> I agree, `saveRDS()` is the better option.
> 
> > The use of case_when function: !is.na in the first case in the example below is irrelevant, it either needs to be used explicitly everywhere, or nowhere, or as a single clause:
> 
> I agree, we need to be consistent. I'd prefer the second option. Looks cleaner.
> 
> > We now have templates (inst/templates) and example scripts (inst/example_scripts). The difference between those two is minor so I would suggest to use templates instead of example scripts everywhere. Anyway, the example scripts are only used as a reference in vignettes and in data:
> 
> We should remove the scripts in `inst/example_scripts` and point all internal links to the `inst/templates` folder.

*  I see the saveRDS was not implemented in the template scripts - is this somethign we should action as an issue?
* There are some strange scripts in the example_scripts folder.  The first looks like a function, but I think is used in `data.R` file and the other is used a lot in different queries examples.  Shall we action some clarification around the scripts - like a header or something?
![image](https://user-images.githubusercontent.com/10111024/150396547-550280a1-17e9-4b37-9307-974e07efbfb1.png)
