### ISSUE TITLE
Vignettes - update existing vignettes to follow the agreed best practices

### ISSUE THREAD

**Issue by kabis-ops** [pharmaverse/admiral#335]
Draft document is [here ](https://exbpbox.ent.box.com/integrations/googledss/openGoogleEditor?fileId=831779464814&trackingId=3#)

- [x] adsl vignette
- [x] bds vignette
- [x] occds vignette
- [x] date time imputation vignette
- [x] contributing vignettes

**Comment by bms63** [comment]
Hey Samia.  Can we close this issue out as it we have created all these vignettes?

**Comment by kabis-ops** [comment]
Hi Ben - yes i think the vignettes have ben updated: I have just ticked them off now.
