### ISSUE TITLE
create a concept/programming workflow for visit windowing

### ISSUE THREAD

**Issue by koegerr** [pharmaverse/admiral#375]

**Comment by bms63** [comment]
@pharmaverse/admiral  shall we close this as it is such a board and study-specific topic?  Also....it is almost a year old topic now.

**Comment by bms63** [comment]
I'm going to close this out now.

**Comment by duniek** [comment]
As Stephan (I think?) suggested in our meeting earlier today, we should then inform users, i.e. document in a vignette, that visit windowing is not going to be covered and they need to program it themselves.
@bms63 would you kindly create an issue for it? :)
