### ISSUE TITLE
Create CO to Parent domain join function

### ISSUE THREAD

**Issue by aehmann-gsk** [pharmaverse/admiral#379]
Create function to join CO (comments domain) with parent domain

Include relrec in the discussion too

**Comment by teckla-gsk** [comment]
@aehmann-gsk is this definitely a function to be developed? Should the label programming be added to it? I can probably find time to pick this up soon, if affirmative

**Comment by aehmann-gsk** [comment]
@teckla-gsk  Yes - we definitely need this function.  I had to do this join recently which reminded me of it.  I added the programming label.  Let me know if you have any questions on this.  It is similar to the SUPP join function.

**Comment by duniek** [comment]
@bms63 is checking within GSK: specificity (potentially move to GSK package or metatools)

**Comment by aehmann-gsk** [comment]
Hi @duniek - @bms63  and I discussed this.  

I think the CO function is worthwhile for GSK and are detailed in the SDTM IG.
This join should not be dependent on RELREC.  This join is detailed in section 8.5 of the SDTM IG.  I would see this function aligning with what is described in section 8.5.  I would see this particular function having similarities with the derive_vars_suppqual function.  You are allowed to add additional variables to the CO domain to facilitate a join of CO with the parent domain. 

Hamza mentioned the RELREC domain.  However, the RELREC domain is used for a different relationship/join and should not be used for joining the CO domain. The RELREC join is detailed in section 8.2 of the SDTM IG.  This particular SDTM domain describes a relationship between 2 domains.  It can be at a dataset level (this is the most common type of relationship I have seen) or at the USUBJID level.  It has been my experience that generally this is a domain that is not programmatically used unless the join is at the USUBJID level.  I think there is an opportunity to work this domain into the programming workflow. I think the RELREC join should be considered separate from the CO domain join.

After talking with @bms63, I am not sure if these 2 functions belong in the package metatools or if they are better suited for an admiral package (whether here or company specific).   I don't feel that either of these joins are based on metadata as they are clearly defined in the SDTM IG how these domains should be used/joined.  

@bms63 is going to put a question out on Slack to see if/how other companies are using these domains to assist with identifying a home for these functions and/or if they should be internalized to GSK.

**Comment by bms63** [comment]
Possible vignette created showing how to use our existing functions to do this rather than creating new functions sho?

**Comment by aefranklin** [comment]
> Might be implemented `roak` SDTM package?

Hi, I am the code owner of the `roak` package, just to confirm we don't plan to implement this feature in the `roak` package

**Comment by sadchla-codes** [comment]
> > Might be implemented `roak` SDTM package?
> 
> Hi, I am the code owner of the `roak` package, just to confirm we don't plan to implement this feature in the `roak` package

Thanks for the confirmation Amy, I was not 100% sure from my short time on roak.

**Comment by manciniedoardo** [comment]
Thanks @aefranklin. @bms63 I second using existing functionality for this if possible, and documenting it in a vignette.

**Comment by bms63** [comment]
Can we see if this is interested to the admiraldata team? @manciniedoardo @kaz462

**Comment by manciniedoardo** [comment]
> Can we see if this is interested to the admiraldata team? @manciniedoardo @kaz462

I don't see any problem adding an issue in admiraldata to create `CO` test data. 😄
