### ISSUE TITLE
`case_when` performance issues

### ISSUE THREAD

**Issue by slamao** [pharmaverse/admiral#417]
Since we have performance issues regarding the use of `dplyr::case_when`, I have done a little digging with the following results and suggestions.

It seems that `cut` is almost 3x faster than `case_when`. But it can be used only for numeric variables and the readability is not as straightforward.

For character variables, a simple mapping vector can be used (e.g. `mapping <- c("old_value_1" = "new_value_1", ...)` and then `mapping[x]`). This again outperforms `case_when`, depending on the number of branches in `case_when`. The more branches, the higher gain. One restriction is that there is no "else" (or "otherwise") with this approach (not mapped values are assigned `NA` - `ifelse` would need to be used additionally in this case).

______

If you are interested, here are the results (tibble with 1e7 rows) and the benchmark code:

### Results for numeric
* First row: `case_when`
* Second row: `if_else`
* Third row: `ifelse`
* Fourth row: `cut` with +-Inf boundaries
* Fifth row: `cut` with finite boundaries
 
The numbers are miliseconds needed to finish each function, each function was run 50 times.
![image](https://user-images.githubusercontent.com/22340537/127284572-fe17e55f-5f09-477f-9db2-696ee2bd462a.png)

### Results for character
* First row: `case_when` with 5 branches
* Second row: mapping vector
![image](https://user-images.githubusercontent.com/22340537/127288161-8a0f70b0-8146-4045-babc-516a118fb164.png)

### Benchmark code
```
library(dplyr)

# numeric

set.seed(1)
df <- tibble(x = 1:1e7)

microbenchmark::microbenchmark({
  df2 <- df %>%
    mutate(new = case_when(
      .data$x < 1e2 ~ "a",
      .data$x >= 1e2 & .data$x < 1e4 ~ "b",
      .data$x > 1e4 ~ "c",
      TRUE ~ "ddd"
    ))
}, {
  df3 <- df2 %>%
    mutate(
      new = if_else(
        .data$x < 1e2,
        "a",
        if_else(
          .data$x >= 1e2 & .data$x < 1e4,
          "b",
          if_else(
            .data$x > 1e4,
            "c",
            "ddd"
          )
        )
      )
    )
}, {
  df4 <- df2 %>%
    mutate(
      new = ifelse(
        .data$x < 1e2,
        "a",
        ifelse(
          .data$x >= 1e2 & .data$x < 1e4,
          "b",
          ifelse(
            .data$x > 1e4,
            "c",
            "ddd"
          )
        )
      )
    )
}, {
  df5 <- df2 %>%
    mutate(
      new = as.character(
        cut(
          .data$x,
          breaks = c(-Inf, 1e2, 1e4, 1e4+1, Inf),
          labels = c("a", "b", "ddd", "c"),
          right = F
        )
      )
    )
}, {
  df5 <- df2 %>%
    mutate(
      new = as.character(
        cut(
          .data$x,
          breaks = c(0, 1e2, 1e4, 1e4+1, 1e8),
          labels = c("a", "b", "ddd", "c"),
          right = F
        )
      )
    )
},
times = 50)


# character

set.seed(1)
df <- tibble(x = sample(letters, 1e7, replace = T))

microbenchmark::microbenchmark({
  df2 <- df %>%
    mutate(new = case_when(
      .data$x == "a" ~ "A",
      .data$x == "b" ~ "B",
      .data$x == "c" ~ "C",
      .data$x == "d" ~ "D",
      .data$x == "e" ~ "E"
    ))
}, {
  mapping <- c("a" = "A", "b" = "B", "c" = "C", "d" = "D", "e" = "E")
  df5 <- df2 %>%
    mutate(
      new = mapping[x]
    )
},
times = 50)

```

**Comment by bms63** [comment]
Can we close this discussion?

**Comment by thomas-neitmann** [comment]
I think so, yes.
