### ISSUE TITLE
Investigate DataFakeR

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#421]
The RWD Insights Engineering Team has created a package called [DataFakeR](https://cran.r-project.org/web/packages/DataFakeR/vignettes/main.html).

It should be investigated if this package could be used to generate test datasets for admiral.

**Comment by bms63** [comment]
Hey Stefan,

Is there a plan to open source this tool?  If not, maybe we should close this issue as only Roche people could update and/or use this tool.

But I like the idea and we could definitely use something like this!!

Ben

**Comment by bundfussr** [comment]
@bms63 , I can ask them.

**Comment by bundfussr** [comment]
The DataFakeR package was released to CRAN in September. I have updated the link in the issue description.

**Comment by rossfarrugia** [comment]
See similar discussion here: https://github.com/pharmaverse/admiral/issues/827 - we also have synthetic.cdisc.data package where test SDTMs could be added later if useful. For short term fine to just build on the CDISC pilot data where we see gaps, but I do like the idea of moving away from {admiral.test} later to some SDTM test data that can be used under pharmaverse beyond only for admiral. I don't see this being prioritised during the next 6 months though with so much work ongoing for admiral core and the TA package extensions.

**Comment by bms63** [comment]
I don; think we need this for ADLB stuff
