### ISSUE TITLE
break down QS metadata approach (1h)

### ISSUE THREAD

**Issue by thomas-neitmann** [pharmaverse/admiral#46]
- decide how to explore the metadata use for ADaM and create multiple issues on it

**Comment by bms63** [comment]
I think this is a good candidate to transfer over to metacore?

**Comment by bundfussr** [comment]
Good question!
I think the QS metadata is similar to the `--TESTCD` to `PARAMCD` mappings and normal ranges mappings. The question if it should be covered by metacore is on the last slide of https://exbpbox.box.com/s/bos49n655nqgvwk8i4hymmedqpjqi6q3.
@thomas-neitmann , @koegerr , was it discussed and decided?

**Comment by statasaurus** [comment]
same as issue #796
