### ISSUE TITLE
create an ADMH example script/template (2h)

### ISSUE THREAD

**Issue by koegerr** [pharmaverse/admiral#502]
### Create an ADMH template.
Please look at ADAE template as an example to follow.

### Input
MH and ADSL

### Output
ADMH template script that creates a sample ADMH dataset.

Add the Link of this to Occur vignette at the bottom where it shows example scripts https://pharmaverse.github.io/admiral/articles/occds.html#example-scripts-1 

Contact Gordon (@millerg23) in case of questions.

**Comment by thomas-neitmann** [comment]
@koegerr Have you started working on this?

**Comment by bms63** [comment]
We should create/update a programming workflow - https://app.box.com/file/857308976687

**Comment by yangc71** [comment]
Hi @pharmaverse/admiral ,

I started the draft ADMH script under branch 502_admh_script, but realized I'm only able to put together a very basic one (i.e. only containing analysis start date variables). The challenges for the rest of the variables are: 

1. The current "admiral_mh" in admiral.test is missing `MHENDTC`, so variables involving `MHENDTC` cannot be derived. Including: `AENDT`, `AENDTM`, `AENDTF`, `AENTMF`, `ATIREL` etc. 
2. The Roche spec for analysis flag such as `ANL01FL` uses `MHOCCUR`, which is also missing in "admiral_mh". Also derivation for `ANL01FL` can be company-specific. 
3. I'm not sure how to incorporate SMQ and CQ derivations in the script, because the example "queries" dataset in admiral.test is for AE (e.g. `TERM_LEVEL` are AEDEOCD, AELLT etc.), so cannot be directly used for ADMH. However, I'm not sure if it makes sense to manually create a queries dataset for ADMH inside this script. 
4. I assume company-specific variables (e.g. `AHIST` etc.) should not be considered here and will be implemented in the company-specific extension packages. 

Any advice on how to proceed is appreciated, thanks!

**Comment by kabis-ops** [comment]
Hi @yangc71 , 
My 2 cents on bullet 3
We usually derive SMQ/CQs for AEs, but it can also be useful for medical history. Imagine you want to know all patients having Cardiac Failure SMQ prior to the start of the trt. 
The query datasets in admiral.test could indeed not be used, Hence, it may be good to show in the vignette how to build the query datasets for MH (it should be just a matter of changing the TERM_LEVEL: AEDECOD->MHDECOD,...?)

**Comment by bms63** [comment]
> Hi @pharmaverse/admiral ,
> 
> I started the draft ADMH script under branch 502_admh_script, but realized I'm only able to put together a very basic one (i.e. only containing analysis start date variables). The challenges for the rest of the variables are:
> 
> 1. The current "admiral_mh" in admiral.test is missing `MHENDTC`, so variables involving `MHENDTC` cannot be derived. Including: `AENDT`, `AENDTM`, `AENDTF`, `AENTMF`, `ATIREL` etc.

Let's add this one in - we have modified other sdtm datasets to get what we need.

> 2. The Roche spec for analysis flag such as `ANL01FL` uses `MHOCCUR`, which is also missing in "admiral_mh". Also derivation for `ANL01FL` can be company-specific.

Let's add that one too!  Again we can just show how to derive the an01fl using mhoccur and say this is just an example

> 3. I'm not sure how to incorporate SMQ and CQ derivations in the script, because the example "queries" dataset in admiral.test is for AE (e.g. `TERM_LEVEL` are AEDEOCD, AELLT etc.), so cannot be directly used for ADMH. However, I'm not sure if it makes sense to manually create a queries dataset for ADMH inside this script.

Defer to expert Samia!  

> 4. I assume company-specific variables (e.g. `AHIST` etc.) should not be considered here and will be implemented in the company-specific extension packages.

We use `AHIST` as Assign "Past" if `MHENRF='BEFORE' `and Assign "Current" if  `MHENRF="DURING/AFTER"`. Assign "Not Assessed" if `MHSTAT="Not Done"`.  What do you all use?  We could just use this as an example in the script.  

> Any advice on how to proceed is appreciated, thanks!


I think we need to use the programming workflow for the admh script and highlight the variables we need for the admh script to work and be a meaningful example.

@PoojaKumari05 @gg106046 what do you all think?  Take a look a the programming workflow documents

**Comment by yangc71** [comment]
> > Hi @pharmaverse/admiral ,
> > I started the draft ADMH script under branch 502_admh_script, but realized I'm only able to put together a very basic one (i.e. only containing analysis start date variables). The challenges for the rest of the variables are:
> > 
> > 1. The current "admiral_mh" in admiral.test is missing `MHENDTC`, so variables involving `MHENDTC` cannot be derived. Including: `AENDT`, `AENDTM`, `AENDTF`, `AENTMF`, `ATIREL` etc.
> 
> Let's add this one in - we have modified other sdtm datasets to get what we need.
> 
Thanks @bms63! Did we previously modify datasets from within admiral.test? If so, should a separate issue be opened in admiral.test first before this can proceed? 
> > 2. The Roche spec for analysis flag such as `ANL01FL` uses `MHOCCUR`, which is also missing in "admiral_mh". Also derivation for `ANL01FL` can be company-specific.
> 
> Let's add that one too! Again we can just show how to derive the an01fl using mhoccur and say this is just an example
> 
> > 3. I'm not sure how to incorporate SMQ and CQ derivations in the script, because the example "queries" dataset in admiral.test is for AE (e.g. `TERM_LEVEL` are AEDEOCD, AELLT etc.), so cannot be directly used for ADMH. However, I'm not sure if it makes sense to manually create a queries dataset for ADMH inside this script.
> 
> Defer to expert Samia!
> 
Thanks @kabis-ops! The OCCDS already provides an example of using queries dataset for ADAE, and it may not make sense to create a separate query dataset within the ADMH script because likely users will leverage their own queries dataset already created somewhere else. Maybe we can add another example queries dataset to be used for ADMH in admiral.test, what do you think? 
> > 4. I assume company-specific variables (e.g. `AHIST` etc.) should not be considered here and will be implemented in the company-specific extension packages.
> 
> We use `AHIST` as Assign "Past" if `MHENRF='BEFORE' `and Assign "Current" if `MHENRF="DURING/AFTER"`. Assign "Not Assessed" if `MHSTAT="Not Done"`. What do you all use? We could just use this as an example in the script.
>
 I don't think Roche has this variable in our standard specs. 
> > Any advice on how to proceed is appreciated, thanks!
> 
> I think we need to use the programming workflow for the admh script and highlight the variables we need for the admh script to work and be a meaningful example.
> 
I was following the existing ADMH workflow document which already highlighted the variables that are company-specific. But we can certainly take another look to see if anything else can be added. 
> @PoojaKumari05 @gg106046 what do you all think? Take a look a the programming workflow documents

**Comment by bms63** [comment]
@yangc71 Yes we can modify the `mh` dataset in `admiral. test` to help with our efforts.  I think we should decide on which new variables are needed  https://github.com/pharmaverse/admiral.test/issues/51

I think we should set up another queries example dataset - maybe that should become a separate issue?

Probably okay to have company specific variables if they are simple to describe (ANL01FL and AHIST)  and easy to implement.  I don't see this dataset being too large...actually might be a bit dry if we don't include.

**Comment by bms63** [comment]
The OCCDS guide has some admh examples.  I was comparing our mh dataset with theirs and added a few suggested variables. https://github.com/pharmaverse/admiral.test/issues/51

[ADaM_OCCDS_Implementation_Guide v1.1.pdf](https://github.com/pharmaverse/admiral/files/8844673/ADaM_OCCDS_Implementation_Guide.v1.1.pdf)

**Comment by millerg23** [comment]
Hi,
We put together a ADMH workflow in Box a while back, and also found there wasn't much to do for ADMH, ie no new modules. Script really just creates date type variables for start and end, and also showing how SMQ baskets can be used.
Even ATIREL is not a CDISC derivation, and I think is being deprecated in {admiral} (Ross posted something), we would probably have ATIREL handled in admiralroche, and likewise AHIST handled by admiralgsk.
In Roche SAS tool, we checked if MOCCUR was there and used it, but really our ANL01FL derivation was just anything that occured within a time window. Annie please see str_vad_admh_anlflag.sas macro in STREAM (let me know if you need help finding it), for an example of ANL01FL.

**Comment by gg106046** [comment]
AOCCFL, AOCCPFL, AOCPFL, AOCPSFL, AOCPPFL are some of the general variables in the GSK spec. (AOCCFL and AOCCPFL are present in ADaM IG as well). These have been added in the "ADMH-Programming Functional Workflow" and the proposed function to derive this is 'derive_extreme_flag'. Should this be a function that should be created in a separate issue?

**Comment by gg106046** [comment]
AOCCFL, AOCCPFL, AOCPFL, AOCPSFL, AOCPPFL are variables in the GSK ADMH spec (AOCCFL and AOCCPFL are present in the ADaM IG as well). The 'ADMH-Programming Functional Workflow' in Box has a proposed function to derive these variables - 'derive_extreme_flag'. Should this be a function that should be created in a separate issue?

**Comment by thomas-neitmann** [comment]
@gg106046 `derive_extreme_flag()` is the old name of the existing function `derive_var_extreme_flag()`. So no need to create it.

**Comment by gg106046** [comment]
> @gg106046 `derive_extreme_flag()` is the old name of the existing function `derive_var_extreme_flag()`. So no need to create it.

Alright.

**Comment by bms63** [comment]
@gg106046 Do we need any additional variables for the `mh `dataset to derive these variables?

**Comment by gg106046** [comment]
> @gg106046 Do we need any additional variables for the `mh `dataset to derive these variables?

I don't think so. I'll double check on it.

**Comment by gg106046** [comment]
@yangc71 Hi Anni! Not sure if you were able to see my message on slack. Shall I work on the derivation of occurrence flags on the ADMH example script? I will be using the branch you created for this. Let me know if you're already working on it.

**Comment by yangc71** [comment]
> @yangc71 Hi Anni! Not sure if you were able to see my message on slack. Shall I work on the derivation of occurrence flags on the ADMH example script? I will be using the branch you created for this. Let me know if you're already working on it.

Hi @gg106046, thank you for checking. Apologies there are some issues with my slack so I didn't see your message. Sure, I haven't had a chance to add the occurrence flags, so please feel free to use the branch I created. Please push the codes when you finish so others will be able to see the updates. Thank you!

**Comment by gg106046** [comment]
> > @yangc71 Hi Anni! Not sure if you were able to see my message on slack. Shall I work on the derivation of occurrence flags on the ADMH example script? I will be using the branch you created for this. Let me know if you're already working on it.
> 
> Hi @gg106046, thank you for checking. Apologies there are some issues with my slack so I didn't see your message. Sure, I haven't had a chance to add the occurrence flags, so please feel free to use the branch I created. Please push the codes when you finish so others will be able to see the updates. Thank you!

Okay sure. Thank you!

**Comment by gg106046** [comment]
Hi all, the variables 'MHENRF' and 'MHSTAT' are missing in the latest SDTM MH dataset which is required to derive the 'AHIST' variable. Since 'AHIST' is a GSK specific variable , should we be adding them to the MH dataset or are we handling that in admiralgsk?

**Comment by esimms999-gsk** [comment]
@gg106046 My view is the derivation of company-specific variables should be handled in the company-specific package, e.g. admiralgsk.

**Comment by bms63** [comment]
I would say we should add them to SDTM data and derive AHIST.  This script is really short already and just have a caveat that this is a company-derived variables and not say it is GSK.  

If we don't want to have examples of using admiral functions with company-specific variables for admh then I say we just not make a admiral script for admh as it sees pretty skimpy already.
