### ISSUE TITLE
discuss and develop an idea how to read and digest metadata from existing standards (3h)

### ISSUE THREAD

**Issue by thomas-neitmann** [pharmaverse/admiral#51]
- come up with a proposal how read in Metadata from GDSR/DAP M3 and which parts we use within functions and which parts we path through

**Comment by bms63** [comment]
So metacore has been established as our method of ingesting metadata.  I'm unsure on what GDSR/DAP M3 but thinking it is a Roche specific storage area for ADaM metadata

Can we close this one out?

**Comment by statasaurus** [comment]
@thomas-neitmann I am going close this but please move this issue to the admiralRoche
