### ISSUE TITLE
discuss and develop a proposal how to create new metadata (4h)

### ISSUE THREAD

**Issue by thomas-neitmann** [pharmaverse/admiral#52]
come up with a proposal for a prototype how to create metadata for a new variable:
name, label, derivations, type, codelist 
The concept should not impact the R code for the derivation of the new variable but should function as a stand alone module(s)

**Comment by statasaurus** [comment]
Would you create a new variable before adding this information into the spec document

**Comment by statasaurus** [comment]
not for metacore
