### ISSUE TITLE
Implement subfunction for derive_summary_records

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#525]
### Idea:
A function which returns just the summary records should be implemented. It should be used in `derive_exposure_params` (replacing the `derive_summary_records()` and `filter()` call in lines 161-167) and in `derive_summary_records`.

**Details:**
Create a new subfunction which should contain all code of derive_summary_records() except the step where the new records are added to the input dataset. I.e., the subfunction returns only the new records. In derive_summary_records() this new subfunction would be called and thereafter bind_rows() to add the new records to the input dataset.
In derive_params_exposure() the derive_summary_records() call and the subsequent filter() call are replaced by calling the new subfunction.

### Pseudo code @bundfussr please check
add_data <- subset_ds %>%
filter(PARAMCD == input_code) %>%
derive_summary_records(
by_vars = by_vars,
analysis_var = !!analysis_var,
summary_fun = summary_fun,
set_values_to = set_values_to
) %>%
filter(PARAMCD == quo_get_expr(set_values_to$PARAMCD))

**Comment by duniek** [comment]
@pk505289 Hi Pavan, this issue was chosen to be included in the upcoming release (Feb 11th). Will it be possible to complete it by Wednesday 9th?

**Comment by bms63** [comment]
Sorry!  Pavan no longer has time available to work on admiral.  Hoping to get a replacement, but I think someone else will have to take on this issue.

**Comment by duniek** [comment]
@pharmaverse/admiral We have another orphaned issue tagged for the upcoming release. Is anyone available to step in and complete it by Wednesday?

**Comment by bundfussr** [comment]
I am not sure why the issue has the release tag. Maybe a left-over from the last release.

However, I think it is not urgent. It is an internal clean-up issue and does not affect the users.

Thus I would remove the release tag and focus on the other issues.

**Comment by bms63** [comment]
Release tagged removed

**Comment by alanaharris22** [comment]
@bundfussr @bms63 @rossfarrugia  - happy to pick this issue up. 
Just to check my understanding, a new function is needed based on `derive_summary_records()` without the steps where new observations are added. This will replace the current code in derive_exposure_params.R and derive_summary_records.R. 
What should the new function be called?  
All the best, 
Alana

**Comment by bundfussr** [comment]
@alanaharris22 , I would propose `get_summary_records()`. See also [my comment in the old PR](https://github.com/pharmaverse/admiral/pull/610#pullrequestreview-791600555).

**Comment by alanaharris22** [comment]
Thanks @bundfussr, will take a look through the old PR..
