### ISSUE TITLE
Implement `derive_param_tte` function

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#546]
Implement a function to derive a time-to-event parameter:
```
derive_param_tte(
  start_date = TRTSDTM,
  event_conditions = list(
    tte_cond(
     dataset = adrs,
     filter = PARAMCD == “BOR” & AVALC == "PD",
     date = ADT,
     set_values_to = vars(
       EVENTDESC = “PROGRESSION”,
       SRCDOM = “ADRS”,
       SRCVAR = “ADT”
     ),
    tte_cond(
     dataset = adsl,
     filter = DTHFL == “Y”,
     date = DTHDT,
     set_values_to = vars(
       EVENTDESC = “DEATH”,
       SRCDOM = “ADSL”,
       SRCVAR = “DTHDT”
     )
   ),
  censor_condition = list(
    tte_cond(
      dataset = adsl,
      date = LSTALVDT
      censor = 1
      set_values_to = vars(
         EVENTDESC = “LAST KNOWN ALIVE DATE”,
         SRCDOM = “ADSL”,
         SRCVAR = “LSTALVDT”
       )
     )
   ),
  set_values_to = vars(PARAMCD = “PFS”,PARAM = “Progression Free Survival”)
)
```
`ADT` is set to the first of the event dates. If there is no event, it is set to the last of the censoring dates.

**Comment by bundfussr** [comment]
Hi @aehmann-gsk ,
I would consider it as a different question and a quite important one. I think it would be helpful to provide additional information for review. I would not add it to the output dataset but would provide it separately. I am not sure how we should proceed. It would require a change of the programming strategy and a concept.

**Comment by aehmann-gsk** [comment]
Hi @bundfussr, I am wondering if we should add break this down into 2 functions, 1 to add a condition to a record and a second to create the ADTTE flag based on the condition variables added?

**Comment by bundfussr** [comment]
Hi @aehmann-gsk , I am not sure what you mean. Do you want to split `derive_param_tte()` into two functions or should the two functions be called within `derive_param_tte()`? I am also not sure what the functions should exactly do. Should the first function add a flag variable to each source dataset? What do you mean by ADTTE flag?

**Comment by bundfussr** [comment]
Hi @aehmann-gsk , I have added the `create_datetime` parameter which allows to choose if `ADT` or `ADTM` should be derived.

I have added the question if we can use expressions for the `set_values_to` parameter to the agenda of the Monday meeting. I would like to get confirmation before implementing it.

**Comment by bundfussr** [comment]
Hi @aehmann-gsk , at the moment the `dataset` parameter of `tte_source()` expects a dataset. This forces the user to define all `tte_source()`s in the ADTTE script. I think this is inefficient because usually the definitions of an event or censoring are not specific to a reporting event. It would be better to define them at a higher level (study, project, company). Some like death event, AE, event, serious AE event, ...  could even be defined by admiral.

We have the same issue with `dthcaus_source()` and `lstalvdt_source()`.

What do you think? Should we reconsider the approach?

**Comment by aehmann-gsk** [comment]
Hi @bundfussr Are you proposing we add a function called `tte_source` which creates a tte condition and user could create multiple tte objects and then these objects would be passed in to the `derive_param_tte` function?

**Comment by bundfussr** [comment]
Hi @aehmann-gsk , I have already implemented `tte_source()` in the pull request. (It is the same as `tte_cond()` in the description of the issue. I just renamed it to be in line with `dthcaus_source()` and `lstalvdt_source()`.)

The issue is that the tte objects must be created in the ADTTE script because they contain the source dataset. They can not be defined at study, company, or admiral level because the source dataset does not exist at these levels.

**Comment by thomas-neitmann** [comment]
That's a interesting issue. Indeed, being able to define these `source` objects outside the main script to re-use across studies would be very useful. I think we don't need to change much to achieve this. Rather than passing the actual dataset as input to the `source` function we could pass just the name of the dataset as a string. Inside the function that performs the actual logic, e.g. `derive_param_tte()` we would need a `source_datasets` parameter that would expect a named list of dataset where we search for the dataset name provided within each `source` object.

**Comment by bundfussr** [comment]
@thomas-neitmann , @aehmann-gsk , should we define `tte_source` objects in admiral? For example death event, last alive censoring, first AE event, first serious AE event, ...

In the affirmative, what would be the best way to do this?

**Comment by thomas-neitmann** [comment]
Thanks @bundfussr! I'm happy to take this one on.
