### ISSUE TITLE
create a programming workflow for ADLB (3h)

### ISSUE THREAD

**Issue by koegerr** [pharmaverse/admiral#552]
goal: create a programming workflow and create issues for new functions

**Comment by bms63** [comment]
Can we close one of the adlb workflows? #824 or this one?

**Comment by bms63** [comment]
@millerg23 Hey Gordon, I'm very keen on learning about this workflow process.  When you set up this meeting can you be sure to include me! :)  Also, I might be the only GSK rep in attendance.

**Comment by bms63** [comment]
- [ ] Each of us work through the advs script and modify to an adlb script
- [ ] Each of us work on updating the adlb workflow document on box

**Comment by millerg23** [comment]
I have added ADLB workflow dcument to Box, and made some initial comments.

**Comment by bms63** [comment]
#602 This discussion might be of interest for us especially around tests!

**Comment by yangc71** [comment]
Hi all,
I added some comments in the Box Doc for ADLB workflow document. I also added a column and tried to identify which part of the workflow can be addressed with existing functions, and which part needs new functions/issues created. Hope this would be helpful for the discussion tomorrow.

**Comment by millerg23** [comment]
I added some comments also, I might be a little late for meeting, so please start discussions without me.

**Comment by bundfussr** [comment]
I would add another step in the workflow for deriving `BTOXGR`, `BTOXGRL`, `BTOXGRH` and the corresponding numeric variables.

**Comment by yangc71** [comment]
Thanks Stefan for your suggestion! I added the baseline grading variables to the ADLB workflow doc. I think these can be derived using `derive_var_base()` and `mutate()` statements once we have the analysis grade functions in place, but please feel free to comment if I'm missing anything.

**Comment by bundfussr** [comment]
Thanks @yangc71 .

Why do you need `mutate()` for the baseline grade variables?

**Comment by millerg23** [comment]
Hi @yangc71 ,

Yes, we can use existing baseline function for these.
Regarding grades, I think there are 2 ways of holding the grade information:
1. ATOXGR which holds grade 1 to 4 for increases (ie. HYPER), and also holds negative values, grade -1 to -4 decreases (ie HYPO).
or 
2. ATOXGRL holds grade 1-4 for decreases (ie HYPO) and ATOXGRH for increases (ie. HYPER).

We probably need to handle both scenarios.
It doesn't stop us from what we are doing, just something to bear in mind when we are handling grading.

Regards,
Gordon

**Comment by yangc71** [comment]
Thanks @millerg23! Stefan also commented on this in the lab grade issue #945, I agree we should consider handling both scenarios. 

Hi @bundfussr, regarding your question, I thought we could use `mutate()` to create numeric grade variables based on character grade variables.
