### ISSUE TITLE
Is this an issue? functions should have cyclomatic complexity of less than 15, this has 18

### ISSUE THREAD

**Issue by kabis-ops** [pharmaverse/admiral#560]
see lintr message: https://github.com/Roche-GSK/admiral/pull/548

functions should have cyclomatic complexity of less than 15, this has xx 
assertions.R/assert_varval_list() 
utils.R/arg_name())

**Comment by aehmann-gsk** [comment]
@kabis-ops @bundfussr I believe this is the result of having too many `if/else` statements in the code.  Could we simplify or rework these 2 functions?  Can we break down the existing functions into multiple functions?

**Comment by bundfussr** [comment]
Technically it should be no problem to put some of the code into separate function to reduce the cyclomatic complexity. However, I am not sure if it improves the readability of the code.

**Comment by thomas-neitmann** [comment]
I'm only not sure what to think of this cyclomatic complexity lintr. It's indeed related to how much "branching" a function has. That included not only `if` and `else` but also logical operator like `||` and `&&`. I noticed that our assertions often exceed the limit of 15 but I do not see any value in breaking these functions apart. Thus, I'd say let's either icrease the limit to something like 20 or remove that check completly.
