### ISSUE TITLE
Test performance to find issues before the release

### ISSUE THREAD

**Issue by hamzarahal** [pharmaverse/admiral#590]
Investigate how performance (execution time and memory) could be tested upfront the release

**Comment by hamzarahal** [comment]
What if we use the profvis package https://rstudio.github.io/profvis/ with a simulated adsl for example with an escalated huge number of observations to test execution time and memory as the below example:

library(profvis)
 profvis({
    data(ae, package = "admiral")
    ae %>%
    left_join(adsl, by = "USUBJID") %>%
       derive_vars_dt(
          dtc = AESTDTC,
          new_vars_prefix = "AST",
          date_imputation = "first",
          min_dates = vars(TRTSDT),
          max_dates = vars(TRTSDT)
       )
 })

Any ideas regarding some function used with the simulated dataset?

**Comment by thomas-neitmann** [comment]
That does sounds like a good idea 👍 

We could imply run our template scripts inside profvis but enlarge the input datasets. That should give us a wide coverage of functions. Then we'll be able to detect any performance bottlenecks.

**Comment by hamzarahal** [comment]
The idea is to duplicate lines of a data table (or a tibble) using the dplyr, so the row names have a range from 1 to the number of rows of original data. I tried that with adsl and advs before applying profvis to a choosed function and it gives the following:
###adsl simulation

> new_adsl <- adsl %>% slice(rep(1:n(), each = 20))
> new_adsl <- adsl %>% slice(rep(1:n(), each = 50))
Error: cannot allocate vector of size 120 Kb

###advs simulation
> new_advs <- advs %>% slice(rep(1:n(), each = 2))
Error: cannot allocate vector of size 486 Kb

knowing that the existing advs has the following:
> dim(advs)
[1] 62237   103

I guess that we need to expect something else for advs in real data, before moving to measure  the execution time and memory when using some functions, @thomas-neitmann agree?

**Comment by thomas-neitmann** [comment]
@hamzarahal Not sure why you get this error but the following code works in duplicating the records in `adsl`.

```r
adsl_list <- lapply(1:10, function(x) adsl)
adsl_new <- dplyr::bind_rows(adsl_list)
```

Replace the second number in `1:10` with however often you want to replicate the dataset.

**Comment by hamzarahal** [comment]
@thomas-neitmann The aim behind testing performance is to figure out what’s making slowness in some of our functions. 
For that we need to identify bottlenecks in some pilot functions for profiling and measure the run-time of each line of code using realistic inputs (test or simulated datasets) or microbenchmark to measure the performance of a very small piece of code. But the blocker is how to generalize that : what if we choose some of pilot functions for that and create alternative/test functions specific for test performance?
