### ISSUE TITLE
User feedback - Update `derive_vars_dtm()`

### ISSUE THREAD

**Issue by kabis-ops** [pharmaverse/admiral#592]
Update `date_imputation`  = “mid”` such that the date is imputed as 30th June if month and day are missing and as the 15th of the month if only the day is missing.
Update documentation.

**Comment by bms63** [comment]
@kabis-ops Which function or functions is this now?  Is it still relevant?

**Comment by PoojaKumari05** [comment]
@kabis-ops - are all these functions renamed? I am not able to find impute_dtc() or derive_vars_dt(m) function in my 'R' folder?

**Comment by kabis-ops** [comment]
@PoojaKumari05 - the functions are all in the file R/derive_date_vars.R

**Comment by PoojaKumari05** [comment]
@kabis-ops yes, I explored and noticed all date functions are embedded in one, was just not sure. Thanks for confirming! :) 
Quick question - have we documented this anywhere?

**Comment by kabis-ops** [comment]
Hi Pooja, we can see that from the documentation
![image](https://user-images.githubusercontent.com/57490460/144428370-ab153c54-09bf-45e3-82fe-6c0183ebb30d.png)

**Comment by bms63** [comment]
Hey folks,

@kabis-ops , @thomas-neitmann , @bundfussr  Just want to make sure I understand this issue correctly.  

If I have the dates below.  Run them through my `impute_dtc `function with `date_imputation = "MID"` then I should get the below output?

```
dates <- c(
   "2019-07-18",
   "2019-07-18",
   "2019-07-18",
   "2019-07",
   "2019-02",
   "2019",
   "2019",
   "2019---07",
   ""
 )

impute_dtc(
  dtc = dates,
  date_imputation = "MID"
)

**_output_**
"2019-07-18T00:00:00"
 "2019-07-18T00:00:00"
"2019-07-18T00:00:00" 
"2019-07-15T00:00:00" 
"2019-02-15T00:00:00"
"2019-06-30T00:00:00"
"2019-06-30T00:00:00"
"2019-06-15T00:00:00" 
NA  
```

**Comment by bundfussr** [comment]
Your example is correct except of the imputation of `"2019---07"`. If we ignore the day part, I would impute is as `"2019-06-30T00:00:00"`. I think we should add another option which preserves all non missing parts. I.e., in your example `"2019---07"` would be imputed as `"2019-06-07"`. The ADaMIG mentions both options. Thus I think we should provide them.

**Comment by bms63** [comment]
@bundfussr So do we need an additional option for users - e.g. `preserve = TRUE`

A user wanting to preserve the non-missing parts would invoke  `preserve = TRUE` to get the preserve_true column and if they wanted to discard the parts, then they could leave that option blank or set to  `preserve = FALSE`

I believe the output would look like this

![image](https://user-images.githubusercontent.com/10111024/146808743-be00a613-f7a7-42f1-8b3d-f4dd11b9ec43.png)

**Comment by bundfussr** [comment]
@bms63 , yes, looks good.
