### ISSUE TITLE
Implement `derive_merged_vars()`-like functions

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#607]
There is the need for something like [`derive_merged_vars()`](https://github.com/Roche-GSK/admiral/blob/v0.1.0-beta/R/derive_merged_vars.R) (feedback from Clara Beck and Samia).

The reason for removing `derive_merged_vars()` was that it allowed to specify expressions for the definition of the new variable.

One option could be to categorize the expressions and implement separate functions, e.g., a function which just renames the variable, a function which converts from dtc to dt variables, a function which categorizes values, ...

**Comment by bundfussr** [comment]
@Roche-GSK/admiral-devs , to avoid allowing expressions we want to implement separate functions which merge a variable to a dataset. All function should merge a variable from a dataset to the input dataset. The functions differ in the way how the value of the merged variable are transformed. As a first step we need to collect which functions we need. Please extend the following list.
- **Merge a variable**: The value of the merged variable is not changed but it can be renamed.
  ```
  derive_var_merged(
    dataset,
    dataset_add,
    by_vars,
    order,
    new_var,
    filter_add,
    mode,
    source)
  ```
- **Merge a date variable**: The source can be a dtc, date, or datetime variable. The new variable is a date variable.
  ```
  derive_vars_merged_dt(
    dataset,
    dataset_add,
    by_vars,
    order,
    new_var,
    filter_add,
    mode,
    date,
    date_imputation,
    flag_imputation,
    min_dates,
    max_dates)
  ```
- **Merge a datetime variable**: The source can be a dtc, date, or datetime variable. The new variable is a datetime variable.
  ```
  derive_vars_merged_dt(
    dataset,
    dataset_add,
    by_vars,
    order,
    new_var,
    filter_add,
    mode,
    date,
    date_imputation,
    time_imputation,
    flag_imputation,
    min_dates,
    max_dates)
  ```

**Comment by bundfussr** [comment]
Do an experiment:
- implement `derive_vars_merged()` which merges variables without changing the value
- implement wrapper functions for `derive_vars_dt()`, `derive_vars_dtm()`, `derive_vars_cat()`, `derive_var_exst()`, `derive_var_character()`

**Comment by bundfussr** [comment]
I'm going to create a branch for the experiment.

**Comment by bundfussr** [comment]
@Roche-GSK/admiral-devs , I have implemented draft versions of the experimental merge functions as discussed on Monday. See `derive_merged.R` in the `607_merge_experiment` branch.

Please have a look.

**Comment by koegerr** [comment]
Hi,

I can see the usefulness of these functions. And sorry for coming to this with a delay. But could we have a look at this to which degree we would like to use them because they are very general and would allow to some degree the derivation of variables which should have their own function.

**Comment by bundfussr** [comment]
@koegerr , could you provide some examples where you would prefer a own function instead of calling one of the more general ones?
