### ISSUE TITLE
ADVS template findings

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiral#609]
Hi @Roche-GSK/admiral-devs 

I've been looking through our ADaM template codes starting with ADVS (to help build my own familiarity with the functions) and found few things which Thomas advised I raise an issue for:

- why do we not keep DOMAIN as default as this is a CDISC required variable?
- advs_params gets created adding the new parameter metadata from the lookup but then this doesn't get used as input in the subsequent step (advs gets used), so MAP, BMI and BSA remain with variables like PARAM blank
- something odd happens with derive_var_basetype() step as the dataset goes from 54839 obs to 32824 and we lose some parameters like TEMP completely because of this

Do we have integration testing for these template programs? As that should spot some of these, whereas function-level unit testing only proves each individual function works. I think we discussed adding some integration testing before to compliment this.

Let me know if I could be of use at all here picking up any actions from this issue, e.g. happy to help with setting up some integration test codes.

**Comment by rossfarrugia** [comment]
I would add notes for any area where the derivation is very protocol-specific or has been set up in a way just to work for the CDISC pilot data, e.g.:

  # Calculate BASETYPE _– note this is a very protocol-specific derivation and the below example is set up with relevance to the CDISC pilot data, but you would need to edit for your study_

**Comment by bms63** [comment]
Hey @millerg23 Did all these findings get resolved in your latest updates?  Can we close this one out?

**Comment by rossfarrugia** [comment]
@bms63 @millerg23 i'll do a check of this later this week and will close this issue if so. i remember Gordon had asked me to double check this

**Comment by rossfarrugia** [comment]
@millerg23 the issues i raised initially on this look good now. the outstanding points are:
- whether to add integration tests for these template programs?
- whether to either remove or add comments for any very protocol-specific example derivations included in the templates?
- tester feedback: should we add safeguards that the initial parameter lookup table actually includes at least all the tests that are included in the data?
- tester feedback: should we add a comment to explain for derive_param_xxx that only the variables that you specify in the by_vars statement are being populated?

Let me know what comes out of the Q&A meeting later on this - happy to help with any required updates.

**Comment by bundfussr** [comment]
@rossfarrugia , we managed to discuss the first and second item only. See https://exbpbox.ent.box.com/file/825439410807?s=josnue7p4opxt60c2a56jvb2nu7jnej0 for the outcome. We will discuss the other two next week.
