### ISSUE TITLE
Check usability of GitHub Project (1h)

### ISSUE THREAD

**Issue by duniek** [pharmaverse/admiral#617]
DoD:
- [x] apply for beta testing
- [ ] go through https://github.com/features/issues and check for other resources

**Comment by duniek** [comment]
I'm on waiting list for beta testing

**Comment by bms63** [comment]
Any progress on this?

**Comment by duniek** [comment]
@bms63 I got pulled into other projects but still wanted to do it as it overlaps nicely with a training I am preparing.

**Comment by koegerr** [comment]
@duniek can we close this out?

**Comment by duniek** [comment]
Closing the issue and will share the GitHub for project management training once done.
