### ISSUE TITLE
Investigate the time zone shift when using `mutate(dt = convert_dtc_to_dtm(dtm))`

### ISSUE THREAD

**Issue by thomas-neitmann** [pharmaverse/admiral#622]
Reviewer: Samia

When calling `convert_dtc_to_dtm()` inside `mutate()` the `tzone` attribute is stripped off and replaces by a seeminlgy random time zone when printing. This can lead to a shift in time comapred to the original `--DTC` variable.

**Comment by amsmith214** [comment]
@kabis-ops I'm looking into this issue-- is the assumption that all times that these functions would handle are already in the UTC timezone? Feeding ISO date times with time zone offsets throws a warning, so I want to be sure I approach this from the right angle

**Comment by amsmith214** [comment]
do we have a reprex for this specific issue? i'm unable to yield a time zone shift with

```
mhdt <- tibble::tribble(
  ~MHSTDTC,
  "2019-07-18",
  "2019-01-01") %>%
  mutate(MHSTDT=convert_dtc_to_dtm(MHSTDTC, time_imputation="FIRST")) %>%
  mutate(tz=attr(MHSTDT, "tzone"))
```
unless i'm extremely lucky this seems to return UTC every time

**Comment by kabis-ops** [comment]
@amsmith214 - (If I am not wrong,) the time are given without time zone in the `convert_dtc_to_dtm()` function: this is just a text which should be in ISO format (created with impute_dtc())
I can see some `tz="UTC"` code in the imputed_dtc function. However i am not sure this affects the result from the function which is a text?
Maybe also i dont get the question properly ;) Please let me know
cc: @thomas-neitmann , @bundfussr - who may be able to help

**Comment by amsmith214** [comment]
i think i would vote to close this. i checked with alice, who said she thought this was resolved in the latest release. unless anyone has a specific reproducible example, i have not been able to get this behavior in my own testing.

**Comment by kabis-ops** [comment]
Hi @amsmith214 , i have tried to reproduce the issue this with some study data but actually it seems everything works fine now. So, I guess we could close this issue?

**Comment by bms63** [comment]
Yes lets close!  We can reopen or start another if it comes up again.
