### ISSUE TITLE
RELREC function to link different domains for common needs

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiral#627]
Kristian from Novonordisk has interest to work on this once we open up admiral to community contributions so adding this issue as a placeholder for now.

Discussion with Kristian below from Slack:

Kristian Trøjelsgaard Nielsen Oct 21st at 2:59 PM
Hi all, just a question for the @channel.
In my company we often link information from different SDTM domains through SDTM.RELREC. As far as I understand RELREC is a an official domain, but how it is used can depend on data collection and maybe also some company specific trends.
We often link auxiliary information in relation to AE’s when crating ADAE (e.g. information about injection site reactions, medication errors, hypersensitivity etc), but we also use RELREC in many other cases.  
From my point of view I think there could be much to gain by having some wrapper functions that could handle these operations.
Therefore, do other companies frequently use RELREC and do you see this linkage between domains as something that could be standardised into one or more functions?

Ross Farrugia  8 days ago
hi Kristian, we do map RELREC as standard in our SDTM but how it's used in analysis is not currently well standardised here or part of our current SAS macro solution for ADAE. i imagine some simple function to connect conmeds with the AE they were given for could be achieved but the exact analysis needs might end up more often being study-specific there. is there anything in the ADaM IG using this? i didn't check

Kristian Trøjelsgaard Nielsen  4 days ago
Dear @Ross Farrugia
Thanks for your input.
Doing a quick search in the ADaM IG I was not able to find anything about RELREC. However, there are a couple of Phuse papers that describes the use of RELREC (although one of them is rather old)
(https://www.pharmasug.org/proceedings/2011/CD/PharmaSUG-2011-CD08.pdf and https://www.lexjansen.com/pharmasug/2017/DS/PharmaSUG-2017-DS09.pdf)
I therefore imagine that some standard could be followed at least when attempting to link some of the more common domains.

Ross Farrugia  4 days ago
@Kristian Trøjelsgaard Nielsen sounds a good potential for a community effort once we open source admiral. there's probably many gaps like this in the ADaM IG where we're all doing our own approaches (even team by team within companies) so i like the idea to attempt to provide something to standardise at least for the more common needs. feel free to raise a Github issue as a placeholder for now for this and let us know if you'd have interest to work on this later.
FYI @Thomas Neitmann @Alice Ehmann in case you have better advice here.

Kristian Trøjelsgaard Nielsen  1 day ago
Again thanks for the feedback @Ross Farrugia. I think we will most likely try to implement something like this at my organization so we might as well try to design a solution that could feed into Admiral if that is wanted . So yes, I would have the interest to work on this.

Ross Farrugia  1 day ago
absolutely, this is our vision. we're currently working up the process we will follow around contributions, so expect to see this as part of our open source release

Thomas Neitmann  1 day ago
@Kristian Trøjelsgaard Nielsen We'd love to have you contribute to admiral! Let me know if you need any help.

Kristian Trøjelsgaard Nielsen  23 hours ago
That sounds great - I will reach out @Thomas Neitmann when the time allows me to delve into this.

**Comment by thomas-neitmann** [comment]
Is there still interest in implementing something for `RELREC`? If not, we'll close this issue.

**Comment by bms63** [comment]
There is from GSK side

**Comment by thomas-neitmann** [comment]
Do we have someone to take this on?

**Comment by bms63** [comment]
We don't and honestly probably can just create a new issue when someone gets interested again.  So lets close it!!
