### ISSUE TITLE
Query datasets: SCOPE_NUM

### ISSUE THREAD

**Issue by kabis-ops** [pharmaverse/admiral#652]
### Idea
Add check on consistency of SCOPE and SCOPE_NUM (issue a warning at least)
See: https://github.com/Roche-GSK/admiral/pull/633#discussion_r746366314
Possibly use assert_one_to_one().
Check if there are any queries where SCOPE is missing but SCOPE_NUM is populated.

### Pseudo code

@kabis-ops - please review the description and add the remaining details above.

**Comment by bundfussr** [comment]
Yes, I think this would be helpful. You could use `assert_one_to_one()`.

Maybe we could also check if there are any queries where `SCOPE` is missing but `SCOPE_NUM` is populated.

**Comment by BDB14** [comment]
HackR - team Ninth Wave will take this!

**Comment by tearingmrx1** [comment]
So we need to update assert_validate_queries(). Cannot locate this program in git?

**Comment by thomas-neitmann** [comment]
@tearingmrx1 The function you're looking for is called `assert_valid_queries()` and you can find it in the `R/derive_vars_query.R` file starting at line 212.

**Comment by tearingmrx1** [comment]
I have updated the program and in process of testing. There are other functions called by this function. How can I ensure that all functions required can be accessed and called? I am getting errors regarding functions it cannot find. I initially copied and pasted these functions into my program but obviously this is cumbersome. Apologies for this obvious question.

**Comment by thomas-neitmann** [comment]
When you're in R you can run `devtools::load_all()` to load all functions that ship with admirall.

**Comment by thomas-neitmann** [comment]
@sadchla-codes @zdz2101 Can either of you take this on? It's been in a backlog for quite a while now and we don't like having stale issue 🙂
