### ISSUE TITLE
Create Draft Article for metacore, xportr and admiral usage to create submission ready data

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#659]

**Comment by bms63** [comment]
@thomas-neitmann - Is this a worthwhile activity still?  Seems like we are going to ask metacore to absorb some of the xportr functionality and hope that haven allows more control of formats, types and lengths for writing xpt files??

**Comment by thomas-neitmann** [comment]
I would put this in hold for now as we're discussing how/where to implement the various pieces. That being said, I still feel a strong need for one document which shows you the whole process from end to end.

**Comment by bms63** [comment]
Closed in favor of #703

**Comment by bms63** [comment]
Rebirth!

**Comment by thomas-neitmann** [comment]
I guess we have to expand the scope a bit. The vignette should cover the whole end-to-end process of creating a submittable ADaM in R using {metacore}, {admiral} and {xportr}.

**Comment by bms63** [comment]
New Title?

**Comment by bms63** [comment]
@statasaurus Did you ever start on this?  I'm still happy to help.  Not sure if the stuff I sent you was helpful?

**Comment by bms63** [comment]
@statasaurus  I think you are handling this so going to close this issue.
