### ISSUE TITLE
Create function to expand aggregate dosing in EX to single doese per row dataset

### ISSUE THREAD

**Issue by thomas-neitmann** [pharmaverse/admiral#660]
Reviewers: Stefan
We need a function that transforms an EX dataset that has multiple doses per row, e.g. with `EXDOSFRQ == "Q2W"`, into one that has only a single dose per row, i.e. `EXDOSFRQ == "ONCE"`.

Example:

**Source**

USUBJID | ASTDT | AENDT | EXDOSFRQ | EXDOSE
--------- | -------- | ------- | ------------ | --------
P01 | 2021-01-01 | 2021-01-07 | Q2D | 100
P01 | 2021-01-08 | 2021-01-15 | Q2D | 100

**Result**

USUBJID | ASTDT | AENDT | EXDOSFRQ | EXDOSE
--------- | -------- | ------- | ------------ | --------
P01 | 2021-01-01 | 2021-01-01 | ONCE | 100
P01 | 2021-01-03 | 2021-01-03 | ONCE | 100
P01 | 2021-01-05 | 2021-01-05 | ONCE | 100
P01 | 2021-01-07 | 2021-01-07 | ONCE | 100
P01 | 2021-01-08 | 2021-01-08 | ONCE | 100
P01 | 2021-01-10 | 2021-01-10 | ONCE | 100

**Comment by thomas-neitmann** [comment]
fyi @yangc71

**Comment by bundfussr** [comment]
@amsmith214 , please see requested changes in the [PR](https://github.com/pharmaverse/admiral/pull/779). (I think you got no notification.)
