### ISSUE TITLE
FAQ updates

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiral#666]
Hi @thomas-neitmann @koegerr 

I was looking at the FAQs page https://roche-gsk.github.io/admiral/articles/faq.html as @SuhasKiraniRavindra gave the good idea before that we should summarise the external testing feedback as part of our FAQs on our site.

So with this in mind i would suggest to add the following extra Q&A:

How has admiral been tested **externally to Roche/GSK**?
- During Sept/Oct 2021, a limited release testing was conducted with 18 other companies (and >50 individuals) in order to assess compatibility of the admiral toolkit with different company standards implementations and to test the usability of the functions, e.g. clarity, reliability, robustness, and flexibility.
- This foundational version of admiral achieved a 7.9 / 10 average score from all the survey respondents and >75% said they'd advocate using admiral for ADaM transformations in R.
- Some tester quotes:
_"Extremely easy to learn and get into, well thought and planned. Plenty of minor functions instead of aiming to create a large "jack of all trades" framework. The toolkit does not attempt to become a large one-button ADaM generator (which is fantastic)."
"It is a huge advantage for all pharma companies that we have common functions for common stuff we develop. It will be easier for the authorities when it is the same foundation in the ADaM programs. The development goes faster for every one when we develop across companies, and bug-fixing is faster as many are using same package and will most likely find potential bugs."
"I am a huge proponent of shared solutions within pharma. Overall I was VERY impressed with the admiral project -- both the design, development, documentation, and validation details are available for teams to readily adopt. Prior to participating in the testing, I was a SAS hold-out who wasn't able to see a strong need to shift to R. This project has shown me a reason to consider making the shift."_

Please anyone from the dev team feel free to suggest any alternative wordings.

**Comment by thomas-neitmann** [comment]
That looks like a great additon to me 👍

**Comment by thomas-neitmann** [comment]
fyi @Roche-GSK/admiral-devs
