### ISSUE TITLE
Handling temporary variables

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#671]
**Issue requires good R knowledge.**

In the programming strategy the following is stated.
> - If the function needs to create temporary variables in an input dataset, these variables must start with `temp_` and must be removed from the output dataset (link to **remove function**).
> - If the input dataset includes variables starting with `temp_`, an error must be issued (link to **check function**).

So far we have neither a remove function nor a check function.

@Roche-GSK/admiral-devs 

- Should we implement a function for removing temporary variables?
- Should we extend the `assert_data_frame()` function such that it issues an error if a temporary variable exists? Should there be an option to turn off the check?

**Comment by esimms999-gsk** [comment]
For discussion: 
From above, there are two functions being considered:
Should we implement a function for removing temporary variables?
Should we extend the assert_data_frame() function such that it issues an error if a temporary variable exists? Should there be an option to turn off the check?

**Comment by bundfussr** [comment]
I think we have to revise the handling of temporary variables. Consider for example `derive_last_dose()` in the `385_update_derive_last_dose_redux` branch. The temporary variable `tmp_seq_var` does not start with `temp_` because then it would be removed by the `filter_extreme()` call in line 208. Thus removing all variables starting with `temp_` at the end of the function does not work.

**Comment by thomas-neitmann** [comment]
I mentioned similar concerns to @esimms999-gsk on Slack. Let's discuss this on Monday.

**Comment by bms63** [comment]
Hi all.  

At today's stand up we brought up this issue to check in on its progress.  @bundfussr brought up that a proposal was in the works, but was unsure of its progress.  This issue might have consequences for future extension packages and that it should get resolved soon.  

@esimms999-gsk maybe you could come up with a proposal with input from us for an upcoming Monday meeting?

**Comment by koegerr** [comment]
@esimms999-gsk could this have a quick follow up in a stand up. thanks.

**Comment by esimms999-gsk** [comment]
I think this is creating more headaches than it would solve. I suggest we do not create functions to check or remove temporary variables. My view:
Programming practice for developers: clean up after your code, i.e. remove any temporary/working variables you created.
Having temporary variables on interim dataframes is not a problem; we just need to ensure any undesired variables (of any name) are not on the final ADaM dataset. This should be handled by whatever functionality is used to assign attributes, e.g. {metacore} issues warnings for any variables on the dataframe which are not in the metacore object.
The assert_dataframe function should test for a valid dataframe and not attempt to do more; it should not be responsible for notifying the user of the presence of variables such as 'temp_*'.
Removing temporary or undesired variables: no need to create functionality which can be handled by the user with a simple 'select' statement.

If we can agree on this, then we can document it and close this issue.

**Comment by bms63** [comment]
Hi Eric,

Some of this information is already in the [developer guide](https://pharmaverse.github.io/admiral/articles/programming_strategy.html) 

Perhaps tweaking vignette this can help resolve this issue quickly.

**Comment by bundfussr** [comment]
Implement:
```
get_temp_var(dataset, prefix = "temp_var")

remove_temp_vars()
```
The `get_temp_var()` function returns a variable name which does not exist in the dataset. The `remove_temp_vars()` removes all temporary variables which were created in the calling function.
For example
```
temp_date <- get_temp_var(dataset, prefix = "temp_date")
# returns symbol, e.g., temp_date_1
dataset %>%
  mutate(!!temp_date := convert_dtc_to_dt(AESTDTC)) %>%
  remove_temp_vars() # removes temp_date_1
```

**Comment by duniek** [comment]
Whoever picks this up - check with @thomas-neitmann what has been done so far.
