### ISSUE TITLE
derive_var_chg post baseline only records

### ISSUE THREAD

**Issue by Ben-White555** [pharmaverse/admiral#676]
Request that additional functionality is added to derive_var_chg so that chg is only calculated for post baseline records. This came up as part of the phuse workshop

**Comment by thomas-neitmann** [comment]
Thanks for bringing this up @Ben-White555! Sounds like a useful functionality indeed. I could imagine adding a `filter` parameter which is used to select only post baseline records. Would this be something you might be interested to implement yourself and contribute to {dmiral}?

**Comment by bundfussr** [comment]
I wonder if we should check first which functions need this functionality. If we provide this functionality for `derive_var_chg()`, it should be provided for `derive_var_pchg()` as well. For the `R2*`, `SHIFT*`, `BCHG*`, and `PBCHG*` variables, which are not implemented in admiral yet, it may also be useful. Most likely there are more derivations where this functionality makes sense.

If we identify many, it may be better to implement a function which splits the input dataset into two parts, calls a derivation for one part, and returns a dataset with both parts the modified and the unmodified one.

What do you think?

**Comment by Ben-White555** [comment]
Hi @thomas-neitmann yes defiantly would be interested in getting involved. I agree with @bundfussr that is it likely applicable to other functions.

**Comment by bundfussr** [comment]
@teckla-gsk , yes, I think it is a good idea to add it to the agenda together with https://github.com/pharmaverse/admiral/issues/701.

**Comment by bundfussr** [comment]
Closing this issue in favor of #701.
