### ISSUE TITLE
Bug in derive_vars_dtm

### ISSUE THREAD

**Issue by otts5** [pharmaverse/admiral#686]
The function derive_vars_dtm is not working as expected for parameter max_dates.
I'm guessing it's because of this line in the code:

max_dates = lapply(**min_dates**, eval_tidy, data = mask))

Should be max_dates in the lapply statement, right?

**Comment by bundfussr** [comment]
Hi @otts5 , yes, that's a bug. Thanks for spotting it.

**Comment by thomas-neitmann** [comment]
Thank you so much for spotting this @otts5! Looks like we are missing a unit test that would have detected this issue.

**Comment by otts5** [comment]
@bundfussr and @thomas-neitmann Since this function will be updated, I'm wondering if we could also implement a condition as to when the maximum is used. The reason I'm asking is that in the GDSR specs for ADAE.AENDTM it says :

_Set to the minimum timepoint between the Death date [ADSL.DTHDTC ] and the imputed end date/time if the Outcome of Adverse Event is death [ADAE.AEOUT='FATAL'] ._ 

But right now the function would always replace the date, not just for AEs with AEOUT='FATAL'. What do you think?

**Comment by bundfussr** [comment]
@otts5 , you could implement the condition like in the example [Using More Than One Imputation Rule for a Variable](https://roche-gsk.github.io/admiral/articles/imputation.html#using-more-than-one-imputation-rule-for-a-variable-1).

However, I wonder if the condition makes sense. With this condition it could happen that the imputed AE end date for a non-fatal AE is after death. Why not handling all AEs in the same way?

**Comment by otts5** [comment]
@bundfussr Ok, that's an option. Regarding the specs: I didn't write them. That's the GDSR default text. And I would assume that it was implemented like that in STREAM.

**Comment by bundfussr** [comment]
@otts5 , yes, the condition is implemented in STREAM as specified in the GDSR. I will ask Cathy about the rational for the condition.

**Comment by otts5** [comment]
@bundfussr Thanks for checking with Cathy. In case we still need the ADAE.AEOUT=FATAL condition, I guess we need to implement that into the function. The example you mentioned will not work with this function as it creates multiple variables and can't be used inside a mutate statement.
Can we also please make sure that it gets properly tested? Especially with all possible combinations for min and max dates? Thanks!

**Comment by bundfussr** [comment]
@otts5 , for the scenario where you need different imputation rules for the same variable depending on a condition like `AEOUT == "FATAL"` the idea is to use `convert_dtc_to_dtm()`, `compute_dtf()`, and `compute_tmf()` instead of `derive_vars_dtm()`.
However, we received a lot of feedback for the imputation functions. So we need to revise them and most likely they will be updated. Thus in future we may offer a better solution for your scenario.

Regarding the bug you spotted we will do a patch release soon to fix it and extend our testing.
