### ISSUE TITLE
List ADaM Variables in Function Documentation

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#688]
Tester feedback:

> if purpose documents for which ADAM variables the function is designed, then it is more helpful.

> I wish I had a bit of more context when using dedicated functions, for instance, what are the source datasets that should be used and to which datasets the created variables are destined.

Display the CDISC hierarchy keyword on the webpage, e.g., ADVS or OCCDS.

Open question:

How can we implement it such that it is searchable? I.e., that you can search for all functions which are designed to _derive_ a certain ADaM variable. The search results should not contain functions which _use_ the variable you are searching for.

**Comment by thomas-neitmann** [comment]
You can create aliases for documentation pages, e.g. you could make it such that `?CHG` opens up the documentation page of `derive_var_chg()`. I think you can have an arbitrary number of aliases.

**Comment by bundfussr** [comment]
That's a good idea but it does not work for the html documentation. Furthermore, it works only if there is only one function to derive the variable (or if all functions are documented on the same page).

**Comment by thomas-neitmann** [comment]
Alternatively we could add a table to the website which lists ADaM variables in one column and corresponding functions in the other column. Probably a pain to create since it's all manual but I could certainly see the value of having that.

**Comment by bundfussr** [comment]
That would be nice. I agree that it is a pain to create. Furthermore it is almost impossible to maintain it. Is it possible to define a new tag for the function header, e.g., `@adam_vars` and generate the table from the new tag?

**Comment by bundfussr** [comment]
This should work for transforming the new tag to a section on the page of the function. Maybe it is even possible that the function which parses the new tag updates a file with a reference of all ADaM variables and corresponding functions. Then we could create a table from this file on a "ADaM variables - functions cross-reference" vignette.

**Comment by traceyxw** [comment]
Sorry I have not had much progress on this one. I will take myself out and let someone else pick it up.

**Comment by morrishj** [comment]
I will take a look at using roxygen2 tags to implement this, as per Thomas' comment above.

**Comment by bms63** [comment]
Hey @galachad is this something we could use your roxygen skills on to create?  Any ideas?

**Comment by bms63** [comment]
@manciniedoardo

**Comment by bms63** [comment]
Going to close and open with new proposal.
