### ISSUE TITLE
Join documentation of `call_derivation()` and `params()`

### ISSUE THREAD

**Issue by thomas-neitmann** [pharmaverse/admiral#690]
These functions can only be used in conjunction so they should be put on the same help page with clear examples to showcase their usage.

**Comment by bundfussr** [comment]
I completely agree that this makes sense. However, I struggled realizing it for `create_query_data()`, where we have the same scenario. I tried `@describeIn` and `@rdname` but it results in one "Usage", "Arguments", "Details", and "Value" section for all functions, which makes the help page more or less unreadable. Thus I kept the separate help pages.

Any ideas how it could be realized?

**Comment by rossfarrugia** [comment]
Could even keep separate pages but add clearer cross reference to explain why these are linked, beyond just "See also". The descriptions could be expanded with more detail to better explain what they do to a newcomer. Just some thoughts but i'm no expert on these

**Comment by traceyxw** [comment]
I think the help page for call_derivation() is quite clear but the example used in the help page for params() is outdated. I just added the same example from call_derivation() to params() which I think would help understand the use of the two together.
