### ISSUE TITLE
Clarify purpose of `derive_worst_flag()`

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#691]
**Update:** `derive_worst_flag()` and `derive_extreme_flag()` are both deprecated. Thus, the update should be applied to their replacements - `derive_var_worst_flag()` and `derive_var_extreme_flag()`

Tester feedback for `derive_worst_flag()`:

>Seems we can get same results by using derive_extreme_flag function also and thinking this is redundent.

and for `derive_extreme_flag()`:

>The function can be used to derive ANL0xFL or ABLFL or can be used to create worst cases also. If the name is "derive_analysis_flag" then it is easy to understand for programmer. Otherwise, the name is little bit confusing as there is another function "derive_worst_flag". 

- [x] In `derive_worst_flag()` title and details should be updated to clarify the difference to `derive_extreme_flag()` (in `derive_extreme_flag()` the direction of "worst" is fixed while it depends on the parameter in `derive_worst_flag()`).
- [x] In `derive_worst_flag()` a `@seealso` tag referring to  `derive_extreme_flag()` should be added.
- [x] In `derive_extreme_flag()` a `@seealso` tag referring to  `derive_worst_flag()` should be added.

**Comment by konstantinakoukR** [comment]
`derive_worst_flag()` and `derive_extreme_flag()` are both deprecated. Thus, the update should be applied to their replacements - `derive_var_worst_flag` and `derive_var_extreme_flag`. @bundfussr and @bms63 what do you think?

**Comment by konstantinakoukR** [comment]
Thank you @thomas-neitmann :)
