### ISSUE TITLE
Join documentation of `*_source()` and accompanying derivation

### ISSUE THREAD

**Issue by thomas-neitmann** [pharmaverse/admiral#693]
`dthcaus_source()` and `derive_var_dthcaus()` as well as `lstalvdt_source()` and `derive_var_lstalvt()` should be described on the same help page as these functions can only be used in conjunction.

**Comment by w316liu** [comment]
@thomas-neitmann can you provide an example how this help page should look like?

**Comment by thomas-neitmann** [comment]
I don't have an example at hand but you want to use the `@describeIn` roxygen2 tag to put a function's documentation onto the help page of another.

**Comment by w316liu** [comment]
Combined documentation for dthcaus_source() and derive_var_dthcaus().
Didn't do for lstalvdt_source() and derive_var_lstalvt() since these two functions were deprecated.
