### ISSUE TITLE
Discuss `derive_var_atirel()`

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#697]
Tester feedback:
>is "PRIOR_CONCOMITANT" actually a proper value per CDISC standard?

and

>Not quite sure what this function is for.

It seems that `derive_var_atirel()` implements the Roche specific derivation of `ATIREL`.

Should we move it to admiral.roche or should we make it more general, e.g., parameterize the values of the new variable?

The name of the function and the documentation should be reviewed. Should we use "atirel" in the function name and documentation? Some information on the context where the function could be used (ADCM, ADMH) would be helpful.

**Comment by rossfarrugia** [comment]
@bundfussr did you ever get any feedback on this one? happy to leave it in admiral core if no objections and close this issue. even if companies have their own specific ways to do this then at least this code gives them a starting point to copy and update for their needs.

**Comment by bundfussr** [comment]
We haven't discussed this issue so far.

I would not close it without discussion.

**Comment by rossfarrugia** [comment]
ok thanks - let me know what gets decided. please raise my preference as above. my perspective on it is if i'm a new company adopting admiral then i rather have something in place to work from here as a guide even if my company rules vary.

**Comment by bundfussr** [comment]
@rossfarrugia , I have set it on the agenda for next Monday but the agenda is already quite long. So I am not sure if we will manage to discuss it.

By the way, should I invite you to the meeting?

**Comment by rossfarrugia** [comment]
sure @bundfussr - i got added to a sprint meeting (not sure if thats same thing?), but feel free to add me to anything as useful, especially to cover Robin whilst he's away.

**Comment by rossfarrugia** [comment]
@bundfussr no reply yet... i spent some time reflecting on this one and i went back and forth in my head of what to propose, and then i opened the actual code and saw it's just a simple `mutate(...case_when(...))` & i thought we're probably spending more time considering this than any user would even take to program it themselves for whatever study-specific condition they needed! plus trying to make this function more generic to cover different scenarios like ADMH would just further over-complicate a simple IF/ELSE rule.

so in the ethos of there being no "perfect" answer here and wanting to just make a decision and move forwards... here's my proposal:
- keep the function as it is in admiral core, but just add a bit extra to the documentation to clarify what this is doing (e.g. explain the conmeds possible use case) and what PRIOR_CONCOMITANT means to address the feedback above. if we remove it, then i bet someone will only ask for it later, and although it's a very specific way of deriving this with no real flexibility, for me the rule is quite sensible so some companies would be happy to follow the Roche rules here. if not nyone could take a version down to company-level or study-level using this as a starting point.
- for Roche ADMH.ATIREL let's just use mutate and case_when directly as it's an even simpler version of this derivation, and i can imagine study teams having need to change the conditions anyway in some cases.

**Comment by bundfussr** [comment]
I am not sure if we should spend more time on explaining the function.

I would deprecate it as it is too specific and at Roche use `mutate()` and `case_when()` for both ADCM.ATIREL and ADMH.ATIREL. I see your point that the specific code may be useful as a starting point. But I am concerned that if we start adding specific functions as "examples" to admiral core, it becomes hard for the users to distinguish between general functions and "example" functions.

@koegerr , @thomas-neitmann , @bms63 what do you think.

**Comment by rossfarrugia** [comment]
Fine for me @bundfussr - let's deprecate it! if anyone ever asks for it we can point to this line in the updated programming strategy: 
`If something needed for ADaM could be achieved simply via an existing tidyverse function, then we do not
wrap this into an admiral function, as that would add an unnecessary extra layer for users.`

**Comment by bundfussr** [comment]
OK, I'll deprecate it.

**Comment by thomas-neitmann** [comment]
Are we going to move this function to {admiralroche}?

**Comment by bundfussr** [comment]
No, it works for ADCM.ATIREL only but not for ADMH.ATIREL. Therefore we think it is easier just to use `mutate()` and `case_when()`.

**Comment by rossfarrugia** [comment]
agree - i cut and paste the `mutate()` and `case_when()` lines from this function into our Roche planned implementation. it will do exactly the same thing, only this simple code won't be hidden away one level deeper for users to need to dig into.
