### ISSUE TITLE
Expand worst flag derivation?

### ISSUE THREAD

**Issue by thomas-neitmann** [pharmaverse/admiral#699]
Tester feedback:
> The function has to be called twice to derive high and low flags for the same parameter. For example, SYSBP / DIABP / PULSE / WEIGHT / etc all have worst flags on both sides. Is it possible to update the function to get worst high and worst low in different columns ?

**Comment by thomas-neitmann** [comment]
Fyi @Roche-GSK/admiral-devs

**Comment by bundfussr** [comment]
I think if *all* parameters require a worst high and a worst low flag, it is better to use two `derive_extreme_flag()` calls (or call it twice using `call_derivation()`).

If some parameters require a worst high flag, some parameters require a worst low flag, and some both flags, extending `derive_worst_flag()` is an option. Another option is implementing a more general functionality (see https://github.com/Roche-GSK/admiral/issues/701).

**Comment by rossfarrugia** [comment]
Agree the new general functions and vignette tagged above will cover this case so I'll close this issue.
