### ISSUE TITLE
Refactor study day/duration derivations

### ISSUE THREAD

**Issue by thomas-neitmann** [pharmaverse/admiral#700]
Reviewer: Stefan and Thomas

Currently we have several functions to create common study day variables such as `derive_var_ady()` and `derive_var_astdy()`. These functions make use of `derive_vars_duration()` internally. I feel like we should directly expose a dedicated, parametrized function for study day creation to users. While currently this is already sort of existent in the form of `derive_vars_duration()` I feel like this function is way to complex for a simple study day derivation (a lot of parameters are not really needed for a study day derivation). Thus, I would propose to separate study day and duration derivation. If we do so we could drop the `add_one` parameter from `derive_vars_duration()`, thereby making it easier to understand. As for the studay day derivation I have two different approaches in mind.

## First Proposal

```
# Function signature
derive_var_dy <- function(dataset, new_var, reference_date, date) {
  ...
}
# Example call creating `DTHDY` 
derive_var_dy(adsl, new_var = DTHDY, reference_date = TRTSDT, date = DTHDT)
```

The downside here is that is adds a bit of boilerplate since most (all?) times `new_var` can be automatically determined from `date` by replacing the trailing `T` with `Y`. 

## Second Proposal

Alternatively, we could offer a function that does the derivation for multiple `--DT` variables in one go, similar to the existing `derive_vars_dtm_to_dt()` function.

```
# Function signature
derive_vars_dy <- function(datasets, reference_date, source_vars) {
  ...
}
# Example call creating `AENDY` and `ASTDY`
derive_vars_dy(adae, reference_date = TRTSDT, source_vars = vars(AENDT, ASTDT))
```

This assumes that the `reference_date` is the same for all (or at least most) of the `--DY` variables which I think is reasonable.

Any thoughts @Roche-GSK/admiral-devs?

**Comment by kabis-ops** [comment]
@thomas-neitmann - i like the 2nd proposal.

**Comment by bundfussr** [comment]
I would prefer the second option, too. For `source_vars` I would accept both `*DT` and `*DTM` variables.

I would not change `derive_vars_duration()` because
- the `add_one` parameter is required for durations (see the "Duration Algorithm" tab in the Roche standard specs) and
- you could use `derive_vars_duration()` for study days if the new variable name is different from the source variable name where T or TM is replaced by Y.

**Comment by thomas-neitmann** [comment]
@bundfussr Regarding your second point of explicitly renaming variables, I thought we could enable this also in the function I proposed by allowing named entries as part of `source_vars`, e.g.

```
derive_vars_dy(adae, reference_date = TRTSDT, source_vars = vars(AENDT, ASTDT, DEATHDY = DTHDY))
```

The logic would be to automatically infer the `--DY` variable name if no name is passed for an element and to used the provided name otherwise.

Should we do something similar for `derive_vars_dtm_to_dt()` and `derive_vars_dtm_to_tm()`?

Also to be in line with these two existing function I guess we should name this one `derive_vars_dt_to_dy()`?

**Comment by bundfussr** [comment]
@thomas-neitmann , I assume you meant
```
derive_vars_dy(adae, reference_date = TRTSDT, source_vars = vars(AENDT, ASTDT, DEATHDY = DTHDT))
```
I like the idea of allowing different names than the automatic ones and we should definitely make it consistent with the `derive_vars_dtm_to_*()` functions. However, using named parameters of the `source_vars` parameter does not look intuitive to me. What about replacing `source_vars` with `new_vars`? E.g.,
```
derive_vars_dy(adae, reference_date = TRTSDT, new_vars = vars(AENDY, ASTDY, DEATHDY = DTHDT))
```

I am not sure about the name. If we use `derive_vars_dt_to_dy()`, we restrict the source to `*DT` variables, which I would like to avoid.

**Comment by thomas-neitmann** [comment]
What if we do not name the parameter altogether and use `...` instead?

```
derive_vars_dy(adae, reference_date = TRTSDT, AENDY, ASTDY, DEATHDY = DTHDT)
```

**Comment by bundfussr** [comment]
I do not like it because it is not clear what `...` expects. The source variables or the new variables?

**Comment by thomas-neitmann** [comment]
@teckla-gsk Is this something you'd like to work on? Fits well with the other functins you've already developed 🙂

**Comment by teckla-gsk** [comment]
Sure, I got this will pick this up this week

**Comment by bundfussr** [comment]
Function should be named `derive_vars_dy()`. Parameter name `source_vars` vs. `new_vars` stays open questions.

**Comment by teckla-gsk** [comment]
OK , so to summarize the above;
1. name dervie_vars_dy()
2.  allows both --DTM and --DT

My comment on the below - is it worth it to split them if we are keeping the functionality in derive_vars_duration?

> I would not change `derive_vars_duration()` because
> 
> * the `add_one` parameter is required for durations (see the "Duration Algorithm" tab in the Roche standard specs) and
> * you could use `derive_vars_duration()` for study days if the new variable name is different from the source variable name where T or TM is replaced by Y.

On the question of source_vars v. new_vars, my opinion is to use source vars, one; we can check if they exist in the dataset easier, two intuitively when scripting one would start with what one has i.e. input from existent dataset flows easier and lastly not sure how many functions use either of the two but maybe an opportunity to start establishing some consistency?

**Comment by thomas-neitmann** [comment]
@teckla-gsk Yes, exactly. The name should be `derive_vars_dy()` and it should be able to handle both `--DTM` and `--DT` variables as input.

I also think having `source_vars` is more intuitive than using `new_vars`. It also is consistent with the existing `derive_vars_dtm_to_dt()` and `derive_vars_dtm_to_tm()`.
