### ISSUE TITLE
Do we need a `slice_derivation()` function?

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#701]
Do we need a function which splits the input dataset in two or more parts and calls different derivations for these parts?

This was requested for
- `CHG` and `PCHG` where the variables should not be derived for baseline or before baseline (see https://github.com/Roche-GSK/admiral/issues/676)
- imputations where different imputation rules should be used depending on a condition (see https://github.com/Roche-GSK/admiral/issues/686)

Some functions provide already a similar functionality, e.g., `derive_worst_flag()` and `derive_extreme_flag()`.

**Decision from Questions and Comments meeting**

- Implement `restrict_derivation(dataset, derivation, args, filter)`. If the derivation needs to be applied to more than one subset of the input dataset, multiple `restrict_derivation()` calls should be chained, e.g.,
  ```
  restrict_derivation(
    dataset = adae ,
    derivation = derive_vars_dtm ,
    args = params(
      dtc = AEENDTC,
      new_vars_prefix = "AEN",
      date_imputation = "last",
      time_imputation = "last",
      max_dates = vars(DTHDT)),
    filter = AEOUT == "FATAL"
  ) %>%
  restrict_derivation(
    derivation = derive_vars_dtm ,
    args = params(
      dtc = AEENDTC,
      new_vars_prefix = "AEN",
      date_imputation = "last",
      time_imputation = "last"),
    filter = AEOUT != "FATAL" or is.na(AEOUT)
  )
  ```
- remove `filter` argument from functions if possible
- add examples for `restrict_derivation()` to functions which are commonly used with `restrict_derivation()`, e.g., `derive_var_chg()`, `derive_var_pchg()`
- update documentation regarding definition of derivations (it is acceptable to split a derivation into multiple function calls) and add some examples

**Comment by bundfussr** [comment]
I had in mind that it is called directly by the user. Then 
- the functionality is available for all derivations and
- the interface is consistent (If it is implemented within the derivations, most likely the usage will differ. E.g., for `derive_extreme_flag()` you need to specify the `filter` parameter while you need to specify the `worst_high` and `worst_low` parameter for `derive_worst_flag()`.)

**Comment by thomas-neitmann** [comment]
So something like?

```
slice_derivation(
  call = derive_var_xyz(...),
  filter = SOMEVAR == "SOMETHING"
)
```

or 

```
slice_derivation(
  derivation = derive_var_xyz,
  args = params(...),
  filter = SOMEVAR == "SOMETHING"
)
```

I like the idea, let's put in on the agenda on Monday.

**Comment by bundfussr** [comment]
Yes, something like that but a bit more like `call_derivation()` to cover https://github.com/Roche-GSK/admiral/issues/686. For example
```
slice_derivation(
  dataset = adae ,
  derivation = derive_vars_dtm ,
  args = params(
    dtc = AEENDTC,
    new_vars_prefix = "AEN",
    date_imputation = "last",
    time_imputation = "last") ,
  slices = list(
    slice(
      filter = AEOUT == "FATAL",
      args = params(max_dates = vars(DTHDT))),
    slice()) # process the remaining observations using global derivation and args
```

**Comment by thomas-neitmann** [comment]
Ah, I see. So you would allow multiple "slices" in our call. I thought you'd call `slice_derivation()` multiple times in a row if you want to actually apply the same function with different arguments to different slices of your data. This certainly is more in line with `call_derivation()`.

**Comment by rossfarrugia** [comment]
Just to add a note to say i'm fully supportive of this function - i think documentation will be key though with lots of examples and sharing different possible use cases. when this gets discussed, i'd be interested to hear if the core team think it warrants it's own vignette, or maybe we just add some usage examples into the ADaM vignettes / templates so that people become more familiar with this powerful option.

**Comment by bundfussr** [comment]
Hi @koegerr , we have discussed the `slice_derivation()` function yesterday and agreed on the implementation (see description of the issue).

Please let us know if you have any objections.

**Comment by bundfussr** [comment]
I have implemented a draft of `restrict_derivation()`.

We get the warning issue discussed on Monday.
```
> restrict_derivation(
+   advs_s,
+   derivation = derive_vars_dtm ,
+   args = params(
+     dtc = VSDTC,
+     new_vars_prefix = "A",
+     time_imputation = "first") ,
+   filter = str_detect(VSTPT, "PRE|BEFORE")) %>% 
+   restrict_derivation(
+     derivation = derive_vars_dtm ,
+     args = params(
+       dtc = VSDTC,
+       new_vars_prefix = "A",
+       time_imputation = "last") ,
+     filter = !str_detect(VSTPT, "PRE|BEFORE") | is.na(VSTPT))
# A tibble: 2 x 5
  USUBJID VSDTC      VSTPT            ADTM                ATMF 
  <chr>   <chr>      <chr>            <dttm>              <chr>
1 1       2020-04-16 NA               2020-04-16 23:59:59 H    
2 1       2020-04-16 BEFORE TREATMENT 2020-04-16 00:00:00 H    
Warning messages:
1: Variable `ADTM` already exists in the dataset 
2: Variable `ATMF` already exists in the dataset 
```
I thought I could catch the warnings within `restrict_derivation()`. But this does not work because I do not know if it is the first or the second call.

We could add a `suppress_warnings` parameter but I would consider this as not user friendly.

@thomas-neitmann , @teckla-gsk , @millerg23 , @esimms999-gsk , do you have any ideas?

**Comment by millerg23** [comment]
Hi @bundfussr ,
If you added a `suppress_warnings` parameter, this would suppress all possible warnings, not just the warning about variable(s) already existing?

**Comment by koegerr** [comment]
I discussed this quickly with Thomas. No objections as long as this gets its own documentation (vignette).

**Comment by bundfussr** [comment]
@koegerr , maybe we could add it to the `call_derivation()` vignette (https://github.com/pharmaverse/admiral/issues/1047).

What do you think?

**Comment by bundfussr** [comment]
Maybe we should implement both `restrict_derivation()` and `slice_derivation()`. This would solve the issue with the warnings and we would not need to change the programming strategy.

We could also simplify the `slice_derivation()` calls by using the dot-dot-dot parameter instead of `slices`:
```
slice_derivation(
  advs_s,
  derivation = derive_vars_dtm ,
  args = params(
    dtc = VSDTC,
    new_vars_prefix = "A"),
  slice(
    filter = str_detect(VSTPT, "PRE|BEFORE"),
    args = params(time_imputation = "first")),
  slice(
    args = params(time_imputation = "last"))
)
```
@thomas-neitmann , @teckla-gsk , @millerg23 , @esimms999-gsk , what do you think?

**Comment by millerg23** [comment]
So use `restrict_derivation` for the simple filter, like populating BASE or CHG/PCHG. And have `slice_derivation` for multiple filters, like the example above calling `derive_vars_dtm` ? The `slice_derivation` call above looks simpler, to what we saw before, I would be in favour of just having `slice_derivation`, btu could live with having both restrict and slice fuinctions.

**Comment by thomas-neitmann** [comment]
I'm in favor of implementing **both** `restrict_derivation()` and `slice_derivation()`. The former can be used for the simple case where you have to apply a derivation just to a **single** subset of your data. The latter on the other hand is reserved for the case where you need to call the same derivation on **multiple** subsets of the data with different arguments.

As far as documentation goes I would suggest to create a new vignette "Higher Order Functions in {admiral}" (a higher order function is a function that takes another function as input). We'll have to make an effort to demostrate the **why** and **how** of these functions. Providing lots of examples will be key. I would always contrast the higher order function way to the "usual" way to showcase the rationale behind these functions. Maybe we can have some community members review this vignette to ensure that everything makes sense to them.

@bundfussr Regarding catching the warning we should use the `class` parameter of `rlang::warn()` inside `warn_if_vars_exist()` such that the warning has a unique class that we can catch inside `slice_derivation()`, something like

```r
slice_derivation <- function(...) {
  withCallingHandlers(
    expr = derive_xyz(...),
    warning = function(w) {
      if (inherits(w, "our_special_warning_class") {
        invokeRestart("muffleWarning")
      }
    }
  )
}
```
This will suppress only this specific warning rather than the much more generic `suppressWarnings()`.

**Comment by bundfussr** [comment]
@thomas-neitmann , thanks for the feedback.

For `slice_derivation()` we do not need to catch any warnings. This was only necessary for subsequent `restrict_derivation()` calls.

**Comment by thomas-neitmann** [comment]
Even better 👍

**Comment by bundfussr** [comment]
@rossfarrugia , I agree that we should add this example but I am not sure if the `slice_derivation()` documentation is the best place. I think users who need to implement this would rather look at the OCCDS vignette or the imputation vignette than the `slice_derivation()` documentation.

**Comment by thomas-neitmann** [comment]
I think it's worth adding this example to the documentation page of `derive_vars_dt()` and `derive_vars_dtm()` directly.

**Comment by rossfarrugia** [comment]
I wouldn't personally @thomas-neitmann or otherwise the date and time imputation vignette starts to lose benefit if it just repeats all the same info.
