### ISSUE TITLE
Metacore, Spec Files, datasets, p21 pseudocode and flow diagram

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#703]
Pseudo Code and Flow Diagram for the propsoed flow of moving from a Metacore object, Spec Files, datasets to a submission ready dataset(s).

How does it all come together?  Where do checks (what checks) come in before saying it is submission ready?? 

Does haven have a role to play here?  Does xportr have a role to play here?

**Comment by rossfarrugia** [comment]
@bms63 thanks for opening this. we have a call scheduled with Atorus next week to start to discuss more. Mike mentioned that for xportr they are investigating replacing sasxport usage with haven, once the request they made updated and tested: https://github.com/tidyverse/haven/issues/650

my 2 cents from seeing the external tester feedback would be over time good if we can add 2 vignettes for admiral site:
- how to create xpt files that can be used for eSub, e.g. if we recommend xportr here
- all the metadata pieces with metacore
maybe these could be 1 vignette in the end, but personally i would separate.

**Comment by rossfarrugia** [comment]
we have this covered with https://github.com/pharmaverse/pharmaverse/issues/80 as a work in progress for pharmaverse site
