### ISSUE TITLE
Add derivation of ASEQ to ADCM script and OCCDS vignette

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#720]
In the newest version of the OCCDS IG the `ASEQ` variable was added for the case that `--SEQ` is not unique. In ADCM this can happen due to the ATC levels. Thus the derivation of `ASEQ` should be added to the template script and the OCCDS vignette.

**Comment by stefonishin-parexel** [comment]
Hi @bundfussr , I would like to pick up this issue

**Comment by thomas-neitmann** [comment]
Awesome, thanks for taking this on @stefonishin-parexel 👍 

Let us know if you need any assistance. We're happy to help 🙂

**Comment by thomas-neitmann** [comment]
Please move the issue into "Sprint - In Progress" once you get started.

**Comment by bundfussr** [comment]
@thomas-neitmann , @bms63 , @millerg23 , at the moment the ATC variables are not derived in the ADCM template. I assume that is due to not having FACM in admiraltest. Should we change this, either by adding FACM to admiraltest or adding commented out calls to the template?

What do you think?
