### ISSUE TITLE
Improve documentation of `derive_vars_query()`

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#724]
Testers feedback:
> Not quite sure what this function is for.

I would propose
- to add some context on the function (for which datasets and CDISC variables it is intended for) and
- to add a link to the "Queries Dataset Documentation" vignette.

**Comment by PoojaKumari05** [comment]
@slamao @shimenghuang @bms63 - I picked up this issue seeing the "documentation" tag, but I believe there is more input required from the developer's perspective before we update the documentation. Can someone help me understand this in details. In my experience at GSK I have not worked on this type of "query" dataset, so any small input will be appreciated. Thanks.

**Comment by bundfussr** [comment]
@PoojaKumari05 , the function is intended for deriving the CDISC variables `SMQzzNAM`, `SMQzzCD`, `SMQzzSC`, `SMQzzSCN`, and `CQzzNAM` in ADAE. It can also be used to derive similar variables for standardized drug grouping (SDGs) in ADCM.

The "query" dataset defines which variables should be derived and how they should be derived. See the "Queries Dataset Documentation" vignette for a description of this dataset. The structure of the dataset is defined by admiral but the contents is study-specific. Users can create the dataset manually or using the helper function `create_query_data()`.

Please let me know if you need more information or if you have any questions.
