### ISSUE TITLE
Should we enhance `derive_extreme_flag()`

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#725]
Testers feedback:
> Could be useful set to "N" records not selected (e.g. if "Y" is selected as first obs, "N" could be the value for other obs)

Open questions:
- Should we add a parameter to specify the value for non-flagged observations?
- Do we need to distinguish between observations which were not flagged because they are not the first one and those which were excluded by the `filter` parameter?

**Comment by rossfarrugia** [comment]
I don't personally find N's that interesting in these cases and at Roche we would usually leave null. If anyone wanted N then they could easily add an extra step at the end using dplyr, so I'm happy to close out this one given how many other issues and updates we're working through. if anyone disagrees and has a strong passion to add this then feel free to re-open.
