### ISSUE TITLE
Review unit tests: do they follow Unit Test Guidance

### ISSUE THREAD

**Issue by millerg23** [pharmaverse/admiral#729]

**Comment by millerg23** [comment]
Create ticket to combine all unit tests for fuinctions in file derive_advs_params - update TESTTHAT title at same time.

**Comment by koegerr** [comment]
question @millerg23 : is that a good issue that is achievable?

**Comment by millerg23** [comment]
Unit tests checking now part of QC work in PR. Also possible plug in to automatically convert unit tests to conform to unit test guidance. CLosing this issue.
