### ISSUE TITLE
create a vignette to document all "merger" functions 

### ISSUE THREAD

**Issue by koegerr** [pharmaverse/admiral#734]
## Background Info
see: derive_merged_vars() #607

## Definition of Done
 * Needs a catchy title
 * Summarize the spirit of the core merge function and why you would use it.
 * Scenarios of Using Merger Functions (Reference in Get Started Document)
 * This Vignette would live in the User Guide on website

![image](https://user-images.githubusercontent.com/10111024/170278890-1abdf5a7-2b31-4f5e-8144-af9d9ac713ff.png)

Note: _dt and _dtm are deprecated!

**Comment by bundfussr** [comment]
What should be the content of the vignette (except a list of all "merger" functions)?

**Comment by koegerr** [comment]
The user might have difficulties to find these functions, or assume the existence. These are more helper functions than specifically to derive a certain variable.
I don't know if an own category or a vignette is better. When we discussed this (Thomas and myself) we thought it might be good to have them listed in a vignette with some introduction and description what the intention of these functions are.

**Comment by bundfussr** [comment]
Maybe we need both a vignette and a new tag with a corresponding section on the "Reference" page. Usually the search strategy of the users differ. Some may prefer the "Reference" page and others the vignettes.

**Comment by rossfarrugia** [comment]
Hi @yohannomnes @sgorm123 how's it going with this vignette? Let us know when you have a first draft you're happy with. The reason i message is that we've been discussing in the core team maybe extending the purpose of this vignette to help findability of some of our other more generic functions, as it's not always easy in admiral to know which function is the right tool for the job when you're creating specific derivations. So one of us will get involved taking your draft and adding some further examples.

**Comment by thomas-neitmann** [comment]
@rossfarrugia First draft is available in PR https://github.com/pharmaverse/admiral/pull/1407.

**Comment by rossfarrugia** [comment]
awesome - i missed that! @pharmaverse/admiral if anyone wants to add their name and help extend this vignette as we've been discussing then please do, otherwise i could take this on in a couple of weeks time when get time.

**Comment by yohannomnes** [comment]
Hi @rossfarrugia, the vignette is ready for your review. Please let us know if you need anything else. Best, Yohann

**Comment by rossfarrugia** [comment]
Appreciate your support Yohann! I'll try and get on to this next week,

**Comment by rossfarrugia** [comment]
FYI @yohannomnes - i'm going to be picking this up on Monday. hope ok if i take your branch and make further commits to extend the scope of your vignette so far, and then will share the PR with some core dev team members to review all in one go.

**Comment by yohannomnes** [comment]
> FYI @yohannomnes - i'm going to be picking this up on Monday. hope ok if i take your branch and make further commits to extend the scope of your vignette so far, and then will share the PR with some core dev team members to review all in one go.

Yes sure, thanks Ross.

**Comment by rossfarrugia** [comment]
FYI @yohannomnes & @sgorm123 this one is now completed - thanks for all your efforts on this!!
