### ISSUE TITLE
Add unit tests for assertions

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#735]

**Comment by bms63** [comment]
@JMcGavigan32 This might be a good one to get familiar with unit tests and how they are used in the function.    You can use `devtools::test_coverage()` to get a nice lookup of where the coverage is lacking for the `assertions.R`.  We can use this issue to track which functions we might need be able to add more coverage to.  Some might just be too difficult  

![image](https://user-images.githubusercontent.com/10111024/159562851-019cf9dc-5218-4539-863e-d069ea162131.png)

**Comment by JMcGavigan32** [comment]
Nice one. Thanks @bms63!
