### ISSUE TITLE
Update `derive_var*` naming convention

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#738]
At the moment the programming strategy requires:
>Please note that var prefix should be used only if the function name includes the name of the variable (e.g. derive_var_ady()). It should not be used if the variable name is supplied as an argument (e.g. derive_baseline(), which has a new_var argument).

- [ ] The programming strategy should be updated such that `derive_var_*` is used for all functions which create a single variable and `derive_vars_*` for all functions which create more than one variable regardless of whether the functions provides a `new_var` parameter or not.
- [ ] Functions which do not follow this convention should be renamed, e.g., `derive_baseline()` should be renamed to `derive_var_baseline()`.

**Comment by amsmith214** [comment]
In the case of functions that optionally create more than one variable, do we wish to classify them as `derive_var_*` or `derive_vars_*`? E.g., `derive_disposition_reason` creates one variable by default but can be tasked to create two by changing a default argument value.

**Comment by thomas-neitmann** [comment]
We should use `derive_vars_*` in these cases. An existing example is `derive_vars_duration()`.

**Comment by amsmith214** [comment]
I feel like I am being hyper-pedantic so apologies, still tuning my mind to admiral: what about functions that create a variable as a consequence of an action that's not direct variable creation?  `derive_summary_records` can create DTYPE, but I'm not sure that's the primary purpose of the function.

**Comment by thomas-neitmann** [comment]
`derive_summary_records()` certainly doesn't fit into this naming scheme. I'd leave it as it. I case a function adds one variable plus optionaliy `tracibility_vars` I'd still use `derive_var_*` as prefix.

**Comment by amsmith214** [comment]
when the package is checked via github actions, does that count as a fresh instance of R? i ask because it looks like i'm failing a check that is coded correctly but not throwing the deprecation warning because it hits the warning verbosity cooldown. when run as 
`rlang::with_options(lifecycle_verbosity="warning", {
  derive_obs_number(
  input,
  by_vars = vars(USUBJID),
  order = vars(AVISITN, AVAL)
  )
})
`

i get the intended (and passing) behavior.

**Comment by thomas-neitmann** [comment]
All unit tests are run in the **same** R session. {lifecycle} implements its warnings in a way that they are only displayed every 8 hours within a single session.
