### ISSUE TITLE
Function to create dummy treatment group

### ISSUE THREAD

**Issue by teckla-gsk** [pharmaverse/admiral#741]

**Comment by teckla-gsk** [comment]
@rossfarrugia I have given this some thought and yes, I agree, anything I come up with that is generic is a bit too simple to include in admiral and the other stuff would be too protocol specific. Happy to close and put document this decision or see what other team members think?

**Comment by bundfussr** [comment]
I think a function for creating dummy treatment groups fits rather into a test data generation package than into admiral.

**Comment by rossfarrugia** [comment]
yes agree - thanks both, will close this issue.
