### ISSUE TITLE
Update most date functions to be explicit of a date or character var is necessary

### ISSUE THREAD

**Issue by teckla-gsk** [pharmaverse/admiral#743]
We can either update the programming strategy requiring a conversion before date functions are used, be explicit in the documentation or update date functions for consistency

**Comment by bundfussr** [comment]
Did the tester mention for which functions the information is missing? I checked some and did not find any where it was not stated if a date, datetime, or character variable is expected.

**Comment by rossfarrugia** [comment]
Example i found: see https://pharmaverse.github.io/admiral/reference/derive_vars_dtm.html min_dates and max_dates arguments. DTM can be used here as well as DT but its not clear from the documentation

**Comment by rossfarrugia** [comment]
as a good example here i like https://pharmaverse.github.io/admiral/reference/derive_vars_duration.html which says for start_date / end_date: "A date or date-time object is expected.". We could just copy this over to any doc pages that doesn't have it clearly shown for date arguments.

**Comment by VD766** [comment]
@rossfarrugia - I am new to this, I will take a look at the derive_vars_dtm for updating the documentation. I'll take a look at other functions that may have this issue and update the documentation.

**Comment by rossfarrugia** [comment]
thanks @VD766 - much appreciate your contribution!

also if you get chance can you update the below on github to help us keep track of all our contributors:

![image](https://user-images.githubusercontent.com/82581364/160194034-1a2980a7-7285-4138-b5bb-ef948a3d0f59.png)
