### ISSUE TITLE
Generalize `derive_var_lstalvdt()`

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#753]
Enhance `derive_var_lstalvdt()` such that the name of the new variables can be specified and the mode (first or last) can be set. It derives a datetime variable:
```
 derive_var_extreme_dtm(dataset, new_var, ... , subject_keys, mode)
```
For deriving a date variable implement `derive_var_extreme_dt()` as wrapper function calling `derive_var_extreme_dtm()` and `mutate(date())`.

**Comment by thomas-neitmann** [comment]
Just one note, I would put `mode` **before** `subject_keys`. In all functions which have a `subject_keys` parameter it is the last one.

**Comment by teckla-gsk** [comment]
see closed issue 437
