### ISSUE TITLE
Contribution guidance vignette extra details needed for newcomers

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiral#765]
During my testing out the contribution model yesterday I found some gaps in the guidance vignettes which I think would help newcomers (i.e. those brand new to software dev in R) as follows:

[Git usage](https://roche-gsk.github.io/admiral/articles/git_usage.html)

1. we should mention under pull requests to link the issue to the pull request, so that it automatically closes upon merging of the PR.
2. reminder needed to run devtools::document() and add the updated DESCRIPTION, NAMESPACE, and files in man/ to the pull request - i assume this is only if you've updated some header that impacts the site documentation right?
3. add a note on updating the Changelog (NEWS.md)
4. would it be useful to have a short paragraph here around the R-CMD and lintr checks that run automatically on your pull request - is the developer meant to review these? i have to say when my first attempt got failures i couldn't make much sense of the messages, but i didn't spend too long looking.

[Programming strategy](https://roche-gsk.github.io/admiral/articles/programming_strategy.html)
5. i found the deprecation section is missing necessary detail: i would suggest to add clearer guidance of how we include the old function with deprecate_warn and then how we pass the input arguments to the new function, and maybe give an example here like derive_var_base.R (although even with the example i made mistakes here). also there should be a test case in tests/testthat/deprecation.R that checks whether a warning is issued when using the old function

@bundfussr @thomas-neitmann FYI 

p.s. i'd be happy to take the updates for this on as i'd like to try out updating a vignette next but i would need advice on the R-CMD/lintr bit around what to add

**Comment by bundfussr** [comment]
Thanks @rossfarrugia , I think these are all good points, which we should add.

Regarding 2.: You need to run `devtools::document()` if you have
- changed a header,
- renamed a .R file, created a new one, or deleted one, or
- updated admiral-package.R

Regarding 4.: Yes, the developer should review the issues from R-CMD and lintr checks. Ideally before requesting review. On the [Pull Request Review Guidance](https://roche-gsk.github.io/admiral/articles/pr_review_guidance.html#common-r-cmd-check-issues-1) is some guidance how to solve such issues.

I am not sure if we should add all of the points 1. to 4. to the git usage vignette. I think at the moment the information on what to do when implementing an issue is distributed across the vignettes. I would propose to create a "Development Process" vignette which list all the steps required for implementing an issue. It should provide an overview of the steps and link to the corresponding sections of other vignettes for details.

What do you think?

**Comment by rossfarrugia** [comment]
@bundfussr i like the idea. like a step by step high level guide that links to each vignette for more details where needed. if you both agree i'm happy to start drafting this on our box folder for now and if you both review there then we could make a new page on our site later? 

the above more details will still need to be added to the respective vignettes but i like the idea of one step by step guide to tie it altogether, as i did find it difficult to flick between all the different pages.

**Comment by bundfussr** [comment]
Makes sense to me.

@thomas-neitmann , do you agree?

**Comment by thomas-neitmann** [comment]
Yes!

**Comment by rossfarrugia** [comment]
@koegerr FYI what comes from this I noticed could supersede this section of https://roche-gsk.github.io/admiral/articles/contribution_model.html:
![image](https://user-images.githubusercontent.com/82581364/146534453-7caf4fa3-5790-409f-a24c-6b4f49612fce.png)

We could just link to the Development Process

**Comment by rossfarrugia** [comment]
@bundfussr @thomas-neitmann - what do you think of this Development Process first draft: https://exbpbox.ent.box.com/file/896889277657? please add any comments directly. my feeling is best to add this as a new vignette and link it in the contribution page instead of the first 3 bullets shown in the screenshot above.

with this i personally feel points 1-4 above would be taken care of, and then for point 5 i'll make a PR with an attempted update of what to add there and will include you both as reviewers.

**Comment by bundfussr** [comment]
Thanks @rossfarrugia , looks great. I have added some comments and suggestions.

**Comment by rossfarrugia** [comment]
thanks @bundfussr - i accepted all your changes. @thomas-neitmann there's one open comment left around who deletes the branch after the merge - i'm okay with the suggestion but please double check when you review this doc.

**Comment by bms63** [comment]
Hey all.  A little off topic - but I'm having trouble remember all the steps!  For example, I forgot the news.md file as to go through and fix my lintr checks.  The green check for lintr is a bit misleading as there are issues in there!

Anyways, is there a way to have a template checklist for Pull Request for our purposes.   

- [ ] Updated Changelog/News
- [ ] Addressed all lintr checks 
- [ ] Did you run devtools:document for updated documentation
- [ ] Units Tests completed - See Unit Test Guide
- [ ] Other stuff, etc

Sorry @thomas-neitmann you got me fascinated with actions/automation stuff...it is almost magic to me.  But this could help to mitigate reviewers having to check this kind of stuff.  

Here is some links on folks implementing these checklists:

- https://jemurai.com/2019/08/15/github-pr-checklist/  

- https://stackoverflow.com/questions/25272215/how-to-automatically-add-a-checklist-to-new-github-prs

**Comment by rossfarrugia** [comment]
@bms63 had a very similar chat with Thomas last week and suggested the core team have some brainstorms in the new year around ways in which it can be made easier for any developer (core or from community) or reviewer to remember all the steps. any automated checks in these areas would be a big plus! nice suggestions above.

**Comment by thomas-neitmann** [comment]
Thanks @bms63, some very good points! I agree we need to become much better in this area and automate as much as possible.

For starter I've updated our lintr workflow to actually throw an error when any lints are detected [here](https://github.com/Roche-GSK/admiral/pull/774).

Regarding documentation, I'm thinking of creating a new GitHub action that automatically runs `devtools::document()` and commits any changes files whenever a branch is merged into either `devel` or `master`. That way a developer would never have to think about running `devtools::document()` locally.

The checklist is really neat and I certainly want to have something like that. I didn't know this was a thing. Thanks a lot for bringing this to my attention!

**Comment by rossfarrugia** [comment]
That would be awesome @thomas-neitmann! working through your PR comments now... thanks!
