### ISSUE TITLE
Clarify purpose of `format_reason_default`

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#767]
Tester feedback:
> Not sure where to use this format as DCTREASP is created from derive_disposition_reason. Hence not checked this function

It should be clarified that it is not intended that the function is called directly but that it is used as input to `derive_disposition_reason()`.

A "See also" section should be added, too.

**Comment by tomratford** [comment]
This is also one of the functions without an example as mentioned in #745

I'll make this update in that branch
