### ISSUE TITLE
Create Issue Checklist Template

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#794]
Issue Template has come out of discussion from #786 around creating a Pull Request Checklist that has automation around it.

You can see this on my personal gitub repo - [https://github.com/bms63/pr_template_demo/issues/new/choose](https://github.com/bms63/pr_template_demo/issues/new/choose)

There is lots of cool customization here around issues!  Very cool.    

1.   We can have simple markdown files that auto populate.
2.   Or have Fancy Forms that have nice boxes for people to fill out with added in labels.

A developer could select the form they wish to fill out - or just open a blank issue if they can't find the right form.

![image](https://user-images.githubusercontent.com/10111024/147123826-e5b4a928-de25-49d9-8c48-84ab1dbdae9e.png)

### Simple Form

* Just uses text with markdown syntax for areas to fill out.  
* No assignment of labels

![image](https://user-images.githubusercontent.com/10111024/147123909-c9da9c79-0fb6-49db-9e43-e61f2288a270.png)

### Fancy Form

* Nicer form to fill out
* Auto assigns labels
![image](https://user-images.githubusercontent.com/10111024/147123967-9c4f40dd-48c3-4c1e-9a97-9f64f62bd22e.png)

### Links to articles
[Configuring issue templates for your repository](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)
[Syntax for issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)

**Comment by thomas-neitmann** [comment]
That's really cool stuff!

**Comment by rossfarrugia** [comment]
looks really good @bms63 and i like the auto-assigning of labels if not too much extra work to achieve this.

**Comment by bms63** [comment]
Posted on an update on [slack ](https://pharmaverse.slack.com/archives/C028SJ83KM1/p1643222485137579)-
