### ISSUE TITLE
Create vignette showcasing metadata usage

### ISSUE THREAD

**Issue by thomas-neitmann** [pharmaverse/admiral#796]
The vignette should explain how to apply metadata to ADaM dataset: taking your specs, putting it into metacore format, apply "computations" based on metadata to the dataset (deriving predecessors, sort rows, order columns) using admiral functions, adding labels, length etc. using xportr and export to XPT file.

**Comment by rossfarrugia** [comment]
i guess we'd also add a link to this new vignette in each of the other specific ADaM vignettes like ADSL, TTE, BDS, OCCDS? as when they're looking through these guides to the derivations they also need to be aware of the e2e steps to create an ADaM.

would we include these in the template programs as well? my feeling would be yes if we want to encourage that this is the best way to use admiral, and users could always change if they have some other metadata solution they prefer in their company.

**Comment by thomas-neitmann** [comment]
> i guess we'd also add a link to this new vignette in each of the other specific ADaM vignettes like ADSL, TTE, BDS, OCCDS? as when they're looking through these guides to the derivations they also need to be aware of the e2e steps to create an ADaM.

Yes, definitely! Questions revolving around the E2E process are amont the most common ones we get so we need to make sure that finding this information is as easy as possible.

> would we include these in the template programs as well? my feeling would be yes if we want to encourage that this is the best way to use admiral, and users could always change if they have some other metadata solution they prefer in their company.

I would suggest to do so, yes. Again that would make it very obvious how the various pieces fit together.

**Comment by duniek** [comment]
This E2E workflow could better belong in Pharmaverse.org than in admiral related websites.
An issue to cinsider is maintainability.

**Comment by rossfarrugia** [comment]
I would prefer admiral site for this @duniek as pharmaverse site is so broad covering across all of clinical reporting, whereas i feel anyone wanting to create an ADaM e2e would come directly to admiral site and then it should show you here how it can be achieved by using several packages together. just like at Roche how for NEST their one AgileR site shows you how to use tern/teal/rtables/etc in conjunction to create a TLG.

**Comment by statasaurus** [comment]
I think you could have a link from the admiral site to a central place where this is located. Because at lot of this information will be needed for SDTM dataset as well. So that way this one guide would be able to cover ADaM and SDTM. If you look at Hadley's advice for [vignettes](https://r-pkgs.org/vignettes.html#vignette-advice) he does recommend keeping your vignettes about your package rather than creeping into other packages.

**Comment by rossfarrugia** [comment]
Makes sense - same topic came up briefly in a pharmaverse call today with Michael R and Mike S and there's probably no perfect answer as pros and cons with each. We were talking of the need for the pharmaverse site to cover the e2e picture and how the packages fit together, but I'd maybe originally anticipated this as higher level than a step-by-step user vignette. In reality as long as it's well linked from admiral to this central place then i'm happy, and let me know what the "metadata sub-team" come up with here as their preferred proposal, and if it's pharmaverse site then sure we could find a place there.

**Comment by koegerr** [comment]
Is there a decision now where this vignette is placed?

**Comment by rossfarrugia** [comment]
yes, pharmaverse site (see https://github.com/pharmaverse/pharmaverse/issues/80) but would need to be linked to from our admiral vignettes to make it easy for users to find.

**Comment by statasaurus** [comment]
The repo for these end to end vignettes can be found [here](https://github.com/pharmaverse/end_to_end_examples). If anyone wants to add additional vignettes outside of adsl please feel free. I am still working on adsl (code is written but instructions need adding)

**Comment by bms63** [comment]
@esimms999-gsk It looks like Christina made the vignettte! 

@statasaurus Is the expectation that we download repo and render the example?  Is it possible to render the html onto the `gh-pages` website and link it just so we can take an easy look? Or is it render somewhere else?  
![image](https://user-images.githubusercontent.com/10111024/154506553-36012cdb-847d-44ed-8633-a855e27b60fa.png)

**Comment by rossfarrugia** [comment]
@statasaurus i have the same question as Ben above - how easiest would you suggest to render the e2e ADSL example to make it easier to review and give feedback on? Also maybe when you're ready make a PR for this at https://github.com/pharmaverse/end_to_end_examples so easier for us to go through and add review comments to the code. I have some general comments like some typos in the comments and i would like to suggest some Intro text at the top to discuss what each of the packages is covering here, so people are clear on the impact of say if they chose not to use 1 of the 4 pharmaverse packages. Happy to look in more depth though.

**Comment by statasaurus** [comment]
Yes sorry I got it good enough and then got sucked into some other projects. I think we probably need a meeting between you, me and James. I can just render it, but I think @epijim wants to be able to render the examples to a couple different version of packages etc. To allow people to select what version of R they on and then see what examples there are for that. If we go down that route we don't want to have it pre-render necessarily, and probably need to setup some actions to render them against different docker images

**Comment by koegerr** [comment]
we close since this seems to exist now under pharmaverse
