### ISSUE TITLE
provide feedback on metadata concept

### ISSUE THREAD

**Issue by duniek** [pharmaverse/admiral#797]
Definition of done:
- [ ] review [the presentation](https://exbpbox.box.com/s/47dlvlp0ommbgusaztty7r8n9qky9om0) about the scope of each package related to metadata functionalities and provide feedback

**Comment by rossfarrugia** [comment]
@duniek i'm confused on this one sorry as the link is to slides last edited Dec 9th which was the working version @koegerr used for the Roche/GSK/Atorus call on this topic, so i don't see any new details to review. i was hoping to open up and see something like:
- metacore will cover functionality xxx - _updates needed: yyy_
- admiral will cover functionality xxx - _updates needed: yyy_
- xportr will cover functionality xxx - _updates needed: yyy_
_- <NEW PACKAGE> will cover xxx (if the team agrees this is best strategy)_

With the above we could start to visualize the e2e flow of creating an ADaM using these packages together and it could be the starting point of creating such a vignette for users, as was requested in the external testing feedback and past discussions.

**Comment by bundfussr** [comment]
Should the "NEW PACKAGE" include only metadata related functionality or all functionality which could be used for both SDTM and ADaM creation, e.g., study day derivation?

**Comment by rossfarrugia** [comment]
@bundfussr only metadata. for SDTM we have the Oak R package in Roche which we're planning to open source. it has some differences in set-up to admiral but that team is aware of this so i'm sure there has been some re-use of code for common needs like this, without having to partition into a separate dependency.

**Comment by koegerr** [comment]
Hi,

I agree with Ross that we need a detailed XYZ is created in package ZXY list. I set up a call with Mike Christina, Ben and Thomas to kick this off.

**Comment by statasaurus** [comment]
This has been agreed and actioned in the metatools package
