### ISSUE TITLE
GitHub org move -> pharmaverse

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiral#803]
@Roche-GSK/admiral-devs FYI we discussed today with the sponsors/leads that we should move our admiral and admiral.test repos over to https://github.com/pharmaverse around the time of CRAN release (~by end Q1), as this will make it easier to get other companies involved in co-creating TA package extensions if we give it a more neutral home than "roche-gsk". Similarly we could create any new metadata packages under pharmaverse too if working across Roche/GSK/Atorus.

I know this will be a pain with links and documentation etc, but we agreed it will be a worthwhile step and @thomas-neitmann will explore how easiest to achieve this and things like auto-redirects for anyone using old bookmarked links that get changed.

**Comment by thomas-neitmann** [comment]
Repo is now available from https://github.com/pharmaverse/admiral/.
