### ISSUE TITLE
Explanation of why we use certain R versions and certain packages on website

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#818]
Hi all,

I've had this question asked to me a few times and I don't think I have the best answer.

Currently I understand that we don't use **R version >3.6** because certain package versions are not backwards compatible with those versions.   Is that correct?

Is something we should discuss on the **pacakgdedown site** in one of the developers guides?

Is there a path forward to addressing this issue?  I'm happy to write up an explanation for this for the next sprint, but I think I don't actually fully understand the issue.  

Can someone help me to understand?

I looked around in box to see if there was a document, but couldn't find anything.

**Comment by yangc71** [comment]
I actually had the same confusion about the R version and remember opening up a similar issue when I first joined the project. Should we also clearly indicate on the admiral site which R version should be used for both the developers and the users for the current admiral version?

**Comment by thomas-neitmann** [comment]
So, just to get this straight: the package does **not** require any specific R version. For development we're using 3.6.3 but our `R CMD check` workflow runs on 3.5, 3.6 and whatever the latest R version at the time is (currently 4.1 I believe). That way we have a rather broad coverage of versions which we can confidently say {admiral} works with.

The rationale of using 3.6.3 for development initally was that Roche's validated R environment had that version installed. But the more important reason for having a uniform R version (along with package versions) is that we as the dev team can reproduce each others environment and any potential issues that may arise.

We should certainly explain this somewhere in our dev guides but also add a short sentence or two in the `README`.

**Comment by rossfarrugia** [comment]
FYI in the PHUSE EU workshop slides we included:
- R Platform / Environment: no explicit requirements. Suggest R ≥ v3.5.

Feel free to copy that into the README

**Comment by bundfussr** [comment]
A related question is when we will move to newer package versions. I experienced it more than once that I found a suitable function in a package documentation but could not use it because it was not available in the version of the package we are using. In some cases we even reimplemented functions of other packages to work around the issue, e.g., for the lifecycle package or `as_name()` in a recent PR.

**Comment by thomas-neitmann** [comment]
That is a good questions indeed. The {tidyverse} makes an effort to be backward compatible with the five most recent minor R versions (which currently are 4.1, 4.0, 3.6, 3.5 and 3.4). While we may not need that much coverage I do feel that we need to be careful of backward compatibility as upgrading validated R environments is not something you do over night so I assume many pharmas are somewhat "stuck" with a past version.

**Comment by bundfussr** [comment]
Maybe we should have a rule like "a new admiral version uses the most recent version available x months ago of all required packages". Then we are not stuck with old package versions and the companies have enough time to upgrade their validated R environments.

**Comment by kieranjmartin** [comment]
This is an interesting question (@rossfarrugia tagged me in this). Ultimately I would guess that supporting different R versions is not super hard, as long as you take actions such as making sure options where defaults have changed between versions of R have been explicitly defined (I'm thinking of string_as_factors=FALSE in R 4). The bigger challenge would be supporting companies which will be running earlier versions of packages.

I think @bundfussr is right here. I would say that each version of Admiral should be pegged to a version of R, and a suite of versions of packages, and the description should explicitly outline those with >=. 

One note is that if you ever put admiral on cran and you have any tidyverse dependencies, then you will need to update those packages to deal with incompatibilities with new tidyverse releases; this occurred with diffdf in the past where were using a fairly obscure bit of tibble functionality which got modified, and had to make a new release on cran to deal with it

**Comment by bms63** [comment]
So the actions coming out of this discussion (I can make into issues)

1) Insert language into **dev topic guide that explain why we benchmark certain R versions and use certain R package (.renv)**

2) Insert language into **Readme** on why we benchmark certain R versions and use certain R package (.renv)

3) Define a rule and strategy for moving to more updated packages within admiral development

4) Define a rule and strategy  for guides/readme that says "a new admiral version uses the most recent version available x months ago of all required packages". Then we are not stuck with old package versions and the companies have enough time to upgrade their validated R environments. (Maybe this is same as 3)

5) Define rule and/or strategy around tidyverse dependenices and admiral release to CRAN

Missing anything?  Maybe these kind of exist in the issue tracker, but good discussion!!  Thank you for clarifying!

**Comment by esimms999-gsk** [comment]
I apologize in advance but I am confused and concerned about needing to worry over versioning of R and R Packages; I need to step through it as I try to get some clarity. 

If I understand Thomas' comments, a USER of admiral (as opposed to a DEVELOPER) has nothing to worry about. So I though I would test it out and I think everything worked OK.  I would appreciate it if someone could take a look at my findings wrt R 4.1.2 in the attached file:

[Loading_admiral_as_a_USER.docx](https://github.com/pharmaverse/admiral/files/8092161/Loading_admiral_as_a_USER.docx)

I will do a similar test but acting in the role of a DEVELOPER; I will post my findings once I complete the process.

**Comment by esimms999-gsk** [comment]
For PARAM/AVALU problem, see Issue 960.

**Comment by esimms999-gsk** [comment]
Acting as a DEVELOPER, I made use of R 4.1.2 to make a change to derive_param_bsa.R based on Issue 960 and created PR 965. I would appreciate it if someone could take a look at my findings in the attached file:

[Loading_admiral_as_a_DEVELOPER.docx](https://github.com/pharmaverse/admiral/files/8100186/Loading_admiral_as_a_DEVELOPER.docx)

**Comment by bms63** [comment]
Hey Eric,

Following up on today's Stand up.

I think if folks want to make contributions to admiral then they should be expected to follow some bare minimum developer guidelines for their setup.  

The first being to use the version of R that we are all currently all developing in.  This  ensures that way we all work in the same environment across different companies.  

The second being we develop with the same packages versions.  Again consistent development environment.

Unfortunately, we do need to put some burden onto the potential developers just so we can have some semblance of continuity across our amorphous team.  I understand this can cause some pain points for potential developers, and I'm all for making development easier, but I also don't want to sacrifice our needs just to make a few others have less of a burden.  

Also, I feel like if they are interested in developing in admiral, then they will figure out how to get access to the different R versions and different packages at their respective companies or home PCs.  I think if they are frustrated by R versions and package versions (which is the name of the game!) then they probably won't stick around long anyways even if somehow lessen the restrictions.

**Comment by esimms999-gsk** [comment]
Thanks Ben and others. I was hoping that I was misunderstanding something, but it all looks clear now:

- To make use of admiral: install.packages("admiral") on any version of R >= 3.6.3 and all should work as expected.
- To contribute to admiral: it is required that R 3.6.3 is used in order to ensure all development is done on the same R version. In addition, renv::restore() will ensure that all package versions are as expected.

Ben, you mentioned you would be creating issues related to this. Please add me as a reviewer to those issues.

**Comment by thomas-neitmann** [comment]
Just to re-iterate: you **can** develop {admiral} using a different R version and even different package versions. However, it makes devlopment much easier if everyone uses the same environment such that we can re-produce each others issues.

While we are currently using R v3.6.3 for devlopment we could certainly update to a more recent version. This is somehow related to the discussion in #986. My proposal is to test on the latest R version as well as the two prior versions going forward. As of writing, this would mean v3.6.3, v4.0.5 and the latest one. We could have a rule such as "development always occurs on the latest version".

**Comment by bundfussr** [comment]
I think at the moment we need to agree which version we use for development because the generation of the files in `man` depends on the version. Once we have automated the generation of the man files we no longer need this agreement and can leave it up to the developer which version she/he uses.

I would use rather the oldest than the latest version for development because most packages are backward compatible for a certain number of versions but not forward compatible. I.e., code developed for the oldest version will work most likely for the latest version but not the other way around.

**Comment by thomas-neitmann** [comment]
> I would use rather the oldest than the latest version for development because most packages are backward compatible for a certain number of versions but not forward compatible. I.e., code developed for the oldest version will work most likely for the latest version but not the other way around.

Very good point @bundfussr 👍 

THat would mean we're sticking with 3.6.3 for the time being.

**Comment by esimms999-gsk** [comment]
Where do we stand with this issue at this time? I did a find in all files for "3.6.3" and all I find is:

![find_all_363](https://user-images.githubusercontent.com/85294667/156197816-bf7739f5-cec2-4e8e-8aee-001f2ddcfccc.jpg)

**Comment by duniek** [comment]
Just to say that new non-core contributors need to have this info available. This question came up today and I'm sure will be asked every time new people join.
Have we decided where this will be documented and who will work on it?

**Comment by esimms999-gsk** [comment]
I jump at the chance to review the explanation written by an expert. :)

**Comment by bms63** [comment]
I think this information should be put into the FAQs section vignette, Readme and Development Process Vignette.  Probably would not hurt to link out to what a .renv lock file is https://rstudio.github.io/renv/articles/lockfile.html
