### ISSUE TITLE
Update package website links

### ISSUE THREAD

**Issue by thomas-neitmann** [pharmaverse/admiral#820]
Since migrating our repo from `Roche-GSK` to `pharmaverse` the link of our website has changed to https://pharmaverse.github.io/admiral/index.html. The old link does **not** re-direct to the new one so we have to manually change the links, most importantly in the README but potentially in other places as well.

**Comment by rossfarrugia** [comment]
Will work my way through this on friday and will catch as many as i can!

**Comment by rossfarrugia** [comment]
@thomas-neitmann besides the obvious links in vignettes etc i also updated as FYI:
- in README: the code coverage score link which makes it now go to unknown as no commits made to main yet in the new repo location
- DESCRIPTION, _pkgdown.yml and RENV.lock for admiral.test new location
- R/data.R
- pull_request_template.md

Let me know if i should put any back to Roche-GSK link or if its fine.

I used Github search "roche-gsk in:file" to find all these so i think i have them all but just shout if ever anyone spots any i missed.
