### ISSUE TITLE
Cdisc Pilot limitation - Discussion for the core team

### ISSUE THREAD

**Issue by RealSlimMahdi** [pharmaverse/admiral#827]
Hi all,

I had a brief discussion with @kabis-ops and @bms63 about this, and they suggested I create a new issue.

I started the development of PK datasets: to get familiarized with Admiral, I started with ADPP, which is supposed to be easier, but one of the hurdles I experienced was the CDISC Pilot limitation(s). 

For instance, Admiral is using Cdisc Pilot data to derive the base datasets like ADSL, and Pk datasets (PC & PP) are missing so even if I create for myself a set of anonymized data, I also have to align with the existing observations from ADSL (i.e Cdisc Pilot). It also creates overwhelming questions for someone less into R (like where do I put this data, can I use it legally, etc...) which could be intimidating.

I have the feeling that the developer experience might be improved here, as very senior (and/or) busy programmer(s) who want to contribute are maybe less interested in dummy data generation (but some might because it is also a great topic 😉) and it would overall ease contribution/testing, etc.

Thanks,
Mahdi

**Comment by rossfarrugia** [comment]
I see a few options:

1.  we create an issue for someone to create some dummy PC and PP datasets in line with the CDISC pilot DM etc data _- we have links with CDISC via COSA so we could even then offer to provide these back to them to include in their repo if ever anyone needed in future_
2. we explore creating our own synthetic SDTM catalogue for admiral in our admiral.test package 
3. we look to extend an existing open source package that started at Roche which currently contains ADaM synthetic data which was used for rtables development and testing - see https://github.com/Roche/synthetic.cdisc.data. If we added SDTM here it would have benefits beyond only admiral

My short term preference would be 1 given how much we already have on our roadmap for 2022, but the ideal longer term solution is 3 and this would be then recommended from pharmaverse site.

Note that personal data shouldn't be used for testing even if anonymised. One of my colleagues co-authored this useful paper recently on the topic: https://link.springer.com/article/10.1007/s44163-021-00016-y - it also gives lots of great advice on methods around synthetic data generation.

Any thoughts from the core team developers?

**Comment by bms63** [comment]
I think creating dummy pc and pp dataset would be very handy for testing and future vignettes.  The current dm dataset I believe uses the cdisc pilot study data. 

Could we link the pc and pp datasets with the dm and others cdisc pilot study?

**Comment by mstackhouse** [comment]
@rossfarrugia is this something we could mock with the Roche [synthetic.cdisc.data](https://github.com/Roche/synthetic.cdisc.data) package?

**Comment by rossfarrugia** [comment]
yes i'm thinking same @bms63 - we need someone who could take the cdisc pilot dm data and create some realistic enough synthetic data for pc and pp so that @RealSlimMahdi can work on what's required for the PK ADaMs. I created an issue in {admiral.test} repo for this: https://github.com/pharmaverse/admiral.test/issues/1, so will close this issue.

longer term i do think extending synthetic.cdisc.data would be a good aim, but we have so many other priorities on for first half of this year.

**Comment by bundfussr** [comment]
Maybe the DataFakeR package could be helpful for creating test data (see https://github.com/pharmaverse/admiral/issues/421).

**Comment by rossfarrugia** [comment]
Possibly but i saw it's internal to Roche, so then only one of our developers would be able to make the pc and pp. I'll share the issue on Slack as could be a good issue for someone new to admiral contributions to pick up assuming they've worked with pk data in the past

**Comment by rossfarrugia** [comment]
FYI - I closed this issue as the PK test data needs are being picked up by Antonio at https://github.com/pharmaverse/admiral.test/issues/1
