### ISSUE TITLE
Update derive_vars_aage to add option of numeric component (ordering) AGEGRPxN

### ISSUE THREAD

**Issue by millerg23** [pharmaverse/admiral#830]
This shouldf ber optional, some kind of TRUE/FALSE switch to enable creation of numeric order of age groupings.

**Comment by bms63** [comment]
@millerg23 do you mind filling out this issue a little more so someone can take it on?

**Comment by millerg23** [comment]
age group functions have been deprecated, so this ticket can be closed with no action.
