### ISSUE TITLE
Finalize Onboarding Procedures for non-Core Contributors

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#831]
Hi all,

We met with Tom from Veramed on Monday to discuss their involvement with admiral.  There seemed to be some confusion between how much access he would have as a non-Core Contributor.  Is there a decision/process around this?  In my discussion with Samia I was very unclear on this.

Is it possible to just give full access?  Later if we have a deluge of outside contributors (low probability), then we could revisit this, but it would make it a lot easier if we didn't have tier-levels of contributor access.  

This does beg the question if we should be doing a purging of contributors every 6 months or so.

**Comment by thomas-neitmann** [comment]
To directly push code to our repo "Write" access is required. As `main` and `devel` are protected branches anyway I don't see an issue granting this permission to non-core contributors. So, basically they would get the same rights as core contributors but not admin rights 😉

**Comment by bms63** [comment]
Can we give access to Tom Ratford then?  @kabis-ops IS there anything else we need to do to onboard Tom?  We can get his Github user name and add to repo if everyone is happy with having a non-Roche/GSK person contributing.

**Comment by thomas-neitmann** [comment]
@bms63 Feel free to do so [here](https://github.com/pharmaverse/admiral/settings/access).
