### ISSUE TITLE
Scrub references to roche-gsk Github organization

### ISSUE THREAD

**Issue by mstackhouse** [pharmaverse/admiral#832]
There are several links throught {admiral} that still reference the old home on GitHub. These need some cleaning :)

**Comment by rossfarrugia** [comment]
thanks @mstackhouse - hoping i got most of them with #820  but anyone please shout if you spot any more after we merge that to main. i'm hoping this will be by end of the month

**Comment by mstackhouse** [comment]
@rossfarrugia you want me to close this?

**Comment by rossfarrugia** [comment]
i got it @mstackhouse
