### ISSUE TITLE
Re-install checklist app from marketplace for PR Template

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#835]
I think when we moved the repos we lost the app from the marketplace for the PR Template

**Comment by thomas-neitmann** [comment]
@rossfarrugia As an admin of pharmaverse only you can do this. Please follow [this link](https://github.com/marketplace/task-list-completed) and install this actionfor the pharmaverse org.

**Comment by rossfarrugia** [comment]
@bms63 check now and if OK please close the issue

**Comment by bms63** [comment]
Seems to be resolved 
![image](https://user-images.githubusercontent.com/10111024/150988982-86e75277-4315-40ea-88e3-b4a88bb3e2fe.png)

**Comment by thomas-neitmann** [comment]
Thanks a lot, @rossfarrugia!
