### ISSUE TITLE
Onboard Ojesh U - GSK

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#836]
- [x] box
- [x] github
- [x] slack admiral
- [x] slack admiral_dev
- [x] meeting invites
- [ ] Team ways of working intro
- [x] technical intro
- [ ] Experience the wonders of a Pull Request

**Comment by bms63** [comment]
@thomas-neitmann Can you add Ojesh Upadhyay to the Repo.  Github user name is **upadhyor**.  Ojesh is the new business lead for admiral from the GSK side.

**Comment by upadhyor** [comment]
@bms63, not sure if all of the above, but I know I have received quite a few invites of late, so hopefully am ok.

**Comment by bundfussr** [comment]
I have invited Ojesh to the Questions and Comments meeting. Could we update the Team Roster in box? I could not find him there.

**Comment by bms63** [comment]
@upadhyor I have a very small task that could get you the feel of doing a Pull Request and requires no interaction with RStudio, since this requires a lot of setup on your end.  

We can create an issue for the simple task and I can have you work on it.   Maybe 2 hours top.  This way you get a feel of how we work and experience a Pull Request.

**Comment by upadhyor** [comment]
@bms63 Sounds great.  Please let me know next steps for me.

**Comment by upadhyor** [comment]
@duniek I have not gone through the "Team ways of working intro" yet.  Please let me know next steps for this.
