### ISSUE TITLE
writing_vignettes.Rmd mentions _pkgdown.yml - should this be pkgdown.yml ?

### ISSUE THREAD

**Issue by esimms999-gsk** [pharmaverse/admiral#837]
writing_vignettes.Rmd mentions "_pkgdown.yml" in the "General Conventions" section- should this be "pkgdown.yml" ?

**Comment by bms63** [comment]
Hi Eric, 

I believe this is fine.  It is a standard file created when you want to have a more customizable site
![image](https://user-images.githubusercontent.com/10111024/150867006-f4ab781f-dd42-49ca-bc20-896738fc2c88.png)

and we have it in our directory:
![image](https://user-images.githubusercontent.com/10111024/150866485-a3e78740-8e55-4efb-b989-b0beccf684a1.png)

For more information check out:
https://pkgdown.r-lib.org/articles/pkgdown.html

**Comment by thomas-neitmann** [comment]
`_pkgdown.yml`, i.e. with the leading underscore, is the expected name for this file.
