### ISSUE TITLE
Create ADNCA a superset of ADPC

### ISSUE THREAD

**Issue by RealSlimMahdi** [pharmaverse/admiral#851]

**Comment by bms63** [comment]
See #602 for previous discussion

**Comment by bms63** [comment]
@jeffreyad and @RealSlimMahdi it looks like @rossfarrugia wants this completed for next release.  Do you all have bandwidth to complete this?  Can you fill out issue if not and maybe we can get others to work on it??

**Comment by jeffreyad** [comment]
> @jeffreyad and @RealSlimMahdi it looks like @rossfarrugia wants this completed for next release. Do you all have bandwidth to complete this? Can you fill out issue if not and maybe we can get others to work on it??

Yes, I have bandwidth.  This should be able to be closed with #1432 this template creates a template program that creates a dataset suitable for both ADNCA and/or ADPC.

**Comment by rossfarrugia** [comment]
@jeffreyad no pressure if anything slips into the next release in June for this one. Good to have us much as possible in March release from Roche perspective but not the end of the world if any of this one comes bit later.

**Comment by jeffreyad** [comment]
> @jeffreyad no pressure if anything slips into the next release in June for this one. Good to have us much as possible in March release from Roche perspective but not the end of the world if any of this one comes bit later.

@rossfarrugia no problem I'd like to see it in March release as well
