### ISSUE TITLE
pre-CRAN release check (2h)

### ISSUE THREAD

**Issue by koegerr** [pharmaverse/admiral#852]
- [x] go through documentation and try to spot gaps/issues/not up to date items (Thomas creates list of items)
- [x] test all links (is there a link tester program?) 
- [x] create issues for things that need to be fixed
- [x] description check
- [x] spelling check?
- [x] RCMD check
- [x] all authors are listed (description file)
- [x] double check copyright

**Comment by konstantinakoukR** [comment]
Hi @bms63! Thank you so much for the inclusive list you provided!
@koegerr, pretty helpful checklist! It seems that we have a clear strategy to start with!
Thank you both!

**Comment by bms63** [comment]
I was playing around with this linkchecking program in RStudio.  You have to run the python kernal as it is a python package. 
 https://pypi.org/project/LinkChecker/.  It has spotted a few broken links, but it is not catching them all.  Maybe something to look into more for automated checks on links.

**Comment by konstantinakoukR** [comment]
Regarding the spelling check, I had a look in the `spelling` package [here](https://cran.r-project.org/web/packages/spelling/spelling.pdf). You can perform a spell check on specific document files or package description, documentation, and vignettes. There is option of setting CMD check as well. Maybe we can have a more detailed look into this.

**Comment by bms63** [comment]
Hi all,

We have done all the pre-release checks for the task list.  Everything is in Pull Request Review.  Going to close this thread since it is not tied to a PR.  Please re-open if you have concerns
