### ISSUE TITLE
Update `derive_var_agegr_*()` documentation

### ISSUE THREAD

**Issue by thomas-neitmann** [pharmaverse/admiral#855]
Mention in the `derive_var_agegr_fda()` and `derive_var_agegr_ema()` documentation how age is split into groups, e.g. `< 18`, `18-6`, `> 65`.

**Comment by rossfarrugia** [comment]
See https://github.com/pharmaverse/admiral/issues/829 - I think this issue is covered there and so maybe this one can be closed? @millerg23 @tomratford - let us know what you think?

**Comment by tomratford** [comment]
I can make this update in the branch for #829 so I think we can close this issue also

**Comment by rossfarrugia** [comment]
Thanks Tom!
