### ISSUE TITLE
Document Issue Closing Process

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#859]
The following process should be documented in the “Reviewing/Closing an Issue” section on the git vignette.

Issues are not closed until they are released. If no work is required for an issue, it should be moved to “Sprint Done” without closing it.

**Comment by bms63** [comment]
We should probably announce this on the dev slack channel.  I've been closing the issue when my Pull Request is moved into devel.

**Comment by bundfussr** [comment]
@bms63 , yes, good idea. I have posted it on slack.

**Comment by thomas-neitmann** [comment]
Let's make sure to include this in our next sprint.

**Comment by bms63** [comment]
Should we make a "sprint" to get all the links fixed, documents updated, website polished before the release?  Like, make sure all that stuff is in this sprint before release?
