### ISSUE TITLE
Typo in Pull Request template

### ISSUE THREAD

**Issue by RealSlimMahdi** [pharmaverse/admiral#861]
There is a small typo in the PR template:

I think it should be `devtools::document()` and not `devtools::documents()`

<img width="903" alt="CleanShot 2022-02-01 at 10 23 30@2x" src="https://user-images.githubusercontent.com/36238571/151942752-1791e965-3677-4dbc-b6d5-db8663bd9bb7.png">

**Comment by thomas-neitmann** [comment]
Indeed. Good catch, thanks for spotting 👍

**Comment by thomas-neitmann** [comment]
You cannot even commit directly to `main` 😉 Please open a PR. ALso, I think we should avoid PRs towards `main` as much as possible. Let's direct this at `devel`. We'll release soon anyway.
