### ISSUE TITLE
admiral.test rename - impact to admiral

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiral#873]
See https://github.com/pharmaverse/admiral.test/issues/9 and https://github.com/pharmaverse/admiral.test/pull/10 

Anywhere admiral references {admiral.test} (e.g. templates) would need to change to {cdiscdata} after the above PR is merged.

**Comment by rossfarrugia** [comment]
may no longer be needed now... see https://github.com/pharmaverse/admiral.test/pull/10

**Comment by statasaurus** [comment]
probably should still be open but just changed to safetyData instead as it already is exists, it is the same data, and is already on CRAN

**Comment by rossfarrugia** [comment]
admiral.test will also have PC, PP, RS, TU, and TR created by admiral user community and whatever further SDTMs we need over time to build TA extension packages. i guess we could reach out to the developer and try to merge efforts at some point - once we get past the upcoming admiral release. shame they went with the name incl "safety" though.
