### ISSUE TITLE
Tag Good First Issue Label to relevant issues before Feb 11 Release

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#874]
Go through and add good first issue label to relevant issues.  Then Ross can use these as good examples for admiral meeting and folks can get involved quickly! :)

**Comment by bundfussr** [comment]
I went through our issues and identified the following candidates for the "good first issue" label:
https://github.com/pharmaverse/admiral/issues/747, https://github.com/pharmaverse/admiral/issues/761, https://github.com/pharmaverse/admiral/issues/735, https://github.com/pharmaverse/admiral/issues/724, https://github.com/pharmaverse/admiral/issues/723, https://github.com/pharmaverse/admiral/issues/720, https://github.com/pharmaverse/admiral/issues/691, https://github.com/pharmaverse/admiral/issues/652, https://github.com/pharmaverse/admiral/issues/525, https://github.com/pharmaverse/admiral/issues/788, https://github.com/pharmaverse/admiral/issues/822

What do you think?

**Comment by rossfarrugia** [comment]
Had a quick look through and i'm OK with all of them @bundfussr - if anyone disagrees we can always take the label off later. at least it gives lots of options for them to consider

**Comment by bundfussr** [comment]
Thanks @rossfarrugia . Then I'll add the labels.
