### ISSUE TITLE
Update  derive_param_tte(), derive_var_trtedtm(), and derive_var_trtsdtm() to use preserve argument

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#880]
derive_date_vars.R has a new preserve argument #592 and see #813 for implementation so far for keeping partial dates.

Example, 2022---07 with date_imputation set to mid would become 2022-06-30.  However, a user could invoke the preserve argument and 2022-06-30.

This will be done when these three functions calls have the preserve argument implemented and all other PR checklist issues are resolved.

**Comment by bundfussr** [comment]
We decided in the "Questions and Comments" meeting last week that functions requiring dates as input should accept numeric date variables only. I.e., only the functions in `derive_date_vars.R` will accept imputation parameters in the future. Thus we can close this issue.
