### ISSUE TITLE
Investigate `derive_disposition_status()` for subjects failing screening

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#885]
Investigate `derive_disposition_status()` for subjects failing screening

**Comment by wqrena** [comment]
@bundfussr, this function is used in ADSL creation. However, usually we does not expect screen failure patients in the input dataset `DS`. As far as I know, screen failure patients are not mapped to SDTM domains. For tester who encountered this issues, we need to understand how screen failure patients are mapped to the `DS` before we can tackle this issue.

**Comment by wqrena** [comment]
@bundfussr, I will be OOO next week, and will follow up with you on this on the week of Jun13. Thanks!

**Comment by wqrena** [comment]
@bundfussr,
It seems that not many companies/users have screening-failure patients mapped to SDTM.DS. After asking around in SLACK, only one user claimed that screening-failure patients are mapped to SDTM for some of her studies. In her case, screening patients are mapped as DSDECOD = 'SCREEN FAILURE' and DSCAT = 'DISPOSITION EVENT'. She mentioned that the purpose of this mapping in her studies is just to include counts in a disposition table.

I would suggest  to leave `derive_var_disposition_status()` function as is without any updates. Here is my rationale:
- Only a few companies/studies have screening-failure patients mapped to SDTM, and it is not widely used for reporting.
- In ADaMIG v1.3, ADSL.EOSSTT has controlled terms (COMPLETED, DISCONTINUED, ONGOING). The current function aligns well with the CDISC guidance. I do not think screening failure patients fit in any of these terms.
- In case a user needs to report screening failure patients, `derive_var_disposition_status()` has  the flexibility to define the parameter `format_new_var` to fit into the study-specific needs.

If you agree with me, let's close this issue.

**Comment by bms63** [comment]
> It seems that not many companies/users have screening-failure patients mapped to SDTM.DS. After asking around in SLACK, only one user claimed that screening-failure patients are mapped to SDTM for some of her studies. In her case, screening patients are mapped as DSDECOD = 'SCREEN FAILURE' and DSCAT = 'DISPOSITION EVENT'. She mentioned that the purpose of this mapping in her studies is just to include counts in a disposition table.

We do this at GSK

**Comment by wqrena** [comment]
> 

Hi Ben, good to know this. So in GSK, how do you assign EOSSTT for screening-failure patients?

**Comment by wqrena** [comment]
@bundfussr This makes sense and is a very good suggestion! Instead of asking users to define themselves, the new default covers all the scenarios without conflict. 
Once @bms63 let us know how GSK assign the standard term of EOSSTT for screen failure patients, I will go ahead and update it.

**Comment by bms63** [comment]
I sent a query to our ADaM Focus Group.  Hoping to hear back soon!

**Comment by bms63** [comment]
Okay.  So gsk does not do this screen failure stuff with EOSSTT - I was mistaken.  We use a different variable to help with summarizing information on Screen Failures.   Stefan's suggestion looks good to me!

**Comment by wqrena** [comment]
OK. So I will update the default to assign EOSSTT as "NOT STARTED" for screen failure patients as shown in Stefan's suggestion. Thanks for the discussion.

**Comment by wqrena** [comment]
I was about to update the function. Then I noticed that our ADSL template has already addressed screen failure patients with a user-defined value for EOSSTT. 
```
format_eosstt <- function(DSDECOD) {
  case_when(
    DSDECOD %in% c("COMPLETED") ~ "COMPLETED",
    DSDECOD %in% c("SCREEN FAILURE") ~ NA_character_,
    !is.na(DSDECOD) ~ "DISCONTINUED",
    TRUE ~ "ONGOING"
  )
}
```
It seems to be a good solution as well because users can assign EOSSTT values for screen failure patients that is specific for their studies. Just wanted to call your attention on this... to see if most of you still prefer to update the default.
