### ISSUE TITLE
Update `derive_disposition_reason()`

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#886]
`derive_disposition_reason()` should be updated such that there is an option for not populating DSREASP for all values, e.g., only for DSDECOD = 'OTHER'.

**Comment by wqrena** [comment]
`derive_disposition_rerason()` is deprecated and replaced by `derive_vars_disposition_reason()`. So I will update `derive_vars_disposition_reason()` instead. 

Based on ADaMIG_v1.3, ADSL.DCSREASP is defined as Additional detail regarding subject's discontinuation from study (e.g., description of "other"). Therefore, let's update to only populate DSREASP when DSDEOD='OTHER'.  Here is the planned updates:
- Update `derive_vars_disposition_reason()`
- Update the documentation. eg. man/derive_vars_disposition_reason
- Update unit test

**Comment by wqrena** [comment]
@bundfussr Hi Stefan, I will work on this issue. Thanks!

**Comment by wqrena** [comment]
@bundfussr @bms63, I have completed all the 5 updates (programming and documentation) as listed above. Can you please help to review?  Thanks!
