### ISSUE TITLE
Extend description for date parameters

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#888]
For parameters which expect a date a reference to `derive_vars_dt()` should be added.

**Comment by wqrena** [comment]
Hi Stefan, here is the steps that I am planning to do:
- find all the functions containing a parameter expecting a date object.
- In the header, For "@param [date]" ...,  add  "Refer to `derive_var_dt()` to impute and derive a date from a date character vector to a date object".

Please confirm if this will address the issue? Thanks

**Comment by bundfussr** [comment]
I would add the sentence rather to the description of the parameter than the "Details" section.

**Comment by wqrena** [comment]
If would be repetitive if we add the sentence to each of the parameter description. For example, `compute_duration()` has 2 date parameter (eg. start_date, end_date).  How about adding the sentence to the "Description" section as a general guidance to the user?

**Comment by bundfussr** [comment]
I would repeat the sentence if a function has more than one date parameter because then it is more likely that the users find the information.

**Comment by wqrena** [comment]
That makes sense. I will update as suggested.

**Comment by wqrena** [comment]
Here is the steps:
- Find all .R files that contains a date parameter using grep "@param" *.R| grep "date".
- Go through the functions and add the sentence below to the date parameter expecting a date object.

"Refer to `derive_var_dt()` to impute and derive a date from a date character vector to a date object."
