### ISSUE TITLE
Add more details and examples to documentation of `derive_vars_duration` `compute_duration()`

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#889]
Add more details and examples to documentation of `derive_vars_duration()` and `compute_duration()`, e.g., examples for relative day, duration of AE or treatment with different units.

Add to compute duration a note and a corresponding example that DTC variables have to be converted to date via `convert_dtc_to_dt()`.

https://github.com/pharmaverse/admiral/issues/1013 should be merged before working on this issue.

**Comment by rossfarrugia** [comment]
@bundfussr could this issue be suitable for good first issue label if you add a bit more detail to help a new contributor?

**Comment by bundfussr** [comment]
@rossfarrugia , yes, added.

**Comment by bms63** [comment]
Close as part of version 8 release
