### ISSUE TITLE
Adding functions to convert units 

### ISSUE THREAD

**Issue by statasaurus** [pharmaverse/admiral#890]
Has there been debate about adding in a function to convert units? I am not sure if you would want to just have a function that just converts to SI unit or allow people to select units, but it would be nice to have and maybe both. If it just want to SI units then you could theoretically convert a column of different units which would be very nice. I am not sure if this would live in admiral or not. Would you ever convert units going from the eCRF to SDTM? Or only SDTM to ADaM? 

@pharmaverse/core-team 
@pharmaverse/admiral

**Comment by millerg23** [comment]
The unit conversions are normally done at SDTM creation, not usually when creating ADaM. Its a lot of work to maintain these conversions, as there can also be a lot of synonyms.
In saying that, in some of the lab grading the grade criteria can be in US/CV units and I've had to convert to SI unit, but this is rare.

**Comment by bundfussr** [comment]
We convert units for deriving the age grouping variables (`derive_var_age_years()`). We discussed implementing unit conversion for derived parameters like BMI or BSA and decided not to implement it because of the complexity.

I think a unit conversion function would be useful (for SDTM and ADaM) but as Gordon pointed out it is a lot of work to implement and maintain it.

**Comment by rossfarrugia** [comment]
sounds like a good potential for a new dedicated pharmaverse package. will raise with council reps. we're still figuring out how best to advertise such gaps to allow individuals or companies to register interest to help develop

**Comment by esimms999-gsk** [comment]
There must already be a package on CRAN which does this? For example: https://cran.r-project.org/web/packages/units/vignettes/measurement_units_in_R.html

**Comment by rossfarrugia** [comment]
FYI all interested - when Oak (SDTM R package from Roche) open sources later in the year there are some functions for this:

oak_import_lab_conversion_factors.R, oak_import_lab_unit_thesaurus.R, oak_merge_lab_with_conversion_factors.R, oak_merge_lab_with_unit_thesaurus.R.

A question we can then ask down the line is whether beneficial for other pharmaverse packages if we split these into their own dedicated package. It won't be highest priority for that team but as I say something for down the line.
