### ISSUE TITLE
Package Authors/Contributors in DESCRIPTION file

### ISSUE THREAD

**Issue by thomas-neitmann** [pharmaverse/admiral#895]
We should make sure that all authors/contributors are listed in the `DESCRIPTION` file. So far the following are included:

## Author(s)
**Maintainer**: Thomas Neitmann [thomas.neitmann@roche.com](mailto:thomas.neitmann@roche.com)

Authors:

- Alice Ehmann [alice.x.ehmann@gsk.com](mailto:alice.x.ehmann@gsk.com)

- Stefan Bundfuss [stefan.bundfuss@roche.com](mailto:stefan.bundfuss@roche.com)

- Samia Kabi [samia.kabi@roche.com](mailto:samia.kabi@roche.com)

- Vignesh Thanikachalam

- Ondrej Slama [ondrej.slama@roche.com](mailto:ondrej.slama@roche.com)

- Shimeng Huang

- Robin Koeger

- Gordon Miller

- Teckla Akinyi

- Eric Simms [eric.m.simms@gsk.com](mailto:eric.m.simms@gsk.com)

- Michael Thorpe [michael.thorpe.mt1@roche.com](mailto:michael.thorpe.mt1@roche.com)

- Pavan Kumar [pavan.10.kumar@gsk.com](mailto:pavan.10.kumar@gsk.com)

- Hamza Rahal

Other contributors:

- F. Hoffmann-La Roche AG [copyright holder, funder]

- GlaxoSmithKline LLC [copyright holder, funder]

We are missing @konstantinakoukR, @rossfarrugia and @tomratford as far as I can tell. Did I miss anyone else @pharmaverse/admiral?

So far everyone is listed as an "Author". However, I think we should start discerning between Authors and Contributors. R's documentation defines an author as someone "[...] who have made substantial contributions to the package and should show up in the package citation.", whereas a contributor is defined as someone "[...] who have made smaller contributions (such as code patches etc.) but should not show up in the package citation". I'm not sure where a substantial contribution starts, but I'd consider anyone who wrote a new function to have made a substantial contribution. With that in mind I would change some people roles from author to contributor.

I would also suggest to remove the Email addresses of anyone but myself (the maintainer **must** have an Email adress listed).

**Comment by thomas-neitmann** [comment]
@bms63 is missing as well 😱

**Comment by rossfarrugia** [comment]
sounds good Thomas!

other contributors i can think of:
@yangc71, @toni-1991 (Antonio Rodríguez - who has supported the PK work), @RealSlimMahdi

**Comment by bms63** [comment]
We should add @amsmith214 and do we want to add Tom Ratford?

**Comment by bms63** [comment]
Going to close this as it was in release 0.6.0
