### ISSUE TITLE
Typos in release

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#899]
Hey all,

I was thinking of just inserting all the typos we find in one issue?  Maybe we could have others release-based mega-issues?

## News 
* Should be: A user
![image](https://user-images.githubusercontent.com/10111024/153210810-b6cfa972-36b2-4c3f-a4af-b4a8baa0c940.png)

**Comment by konstantinakoukR** [comment]
### pr_review_guidance.Rmd

- It should be "acknowledgment"
![image](https://user-images.githubusercontent.com/57364385/153224302-6e96ae78-acca-4a6d-992c-7007a616e5ae.png)

**Comment by bms63** [comment]
# News
Sometimes we use periods  and sometimes we dont
![image](https://user-images.githubusercontent.com/10111024/153226715-222d256c-8fcf-4fc0-95ef-4195cde67861.png)

**Comment by konstantinakoukR** [comment]
### unit_test_guidance.Rmd
- It should be "traceability"
![image](https://user-images.githubusercontent.com/57364385/153227090-ce823c62-af44-46d5-b6bd-90fa667fd71d.png)

**Comment by konstantinakoukR** [comment]
### faq.Rmd
Sometimes we use capitalization and sometimes we don't.
![image](https://user-images.githubusercontent.com/57364385/153228281-a8a3db7f-c97d-4a21-868b-9fe526f08158.png)
.......................................
![image](https://user-images.githubusercontent.com/57364385/153228471-4f497cb3-c270-4ec9-9b97-b5398a86f6fe.png)

**Comment by bms63** [comment]
> 

I think we should use Pharma

**Comment by konstantinakoukR** [comment]
Capitalization inconsistencies:
![image](https://user-images.githubusercontent.com/57364385/153234475-89454f17-9064-4eb6-a5d7-c4717f2e2ade.png)
...........................................................
...........................................................
![image](https://user-images.githubusercontent.com/57364385/153234680-b2a83780-e6cc-4521-a916-8d344ce9b0cc.png)
...........................................................
...........................................................
![image](https://user-images.githubusercontent.com/57364385/153235557-fc4a00a8-7c92-44e2-a479-f60a36fb0f03.png)
...........................................................
...........................................................
![image](https://user-images.githubusercontent.com/57364385/153235726-0a2f1df4-3b16-4216-ad0d-36ebf0ae5b9c.png)
...........................................................
...........................................................
![image](https://user-images.githubusercontent.com/57364385/153235891-9e46817f-1ea6-451e-8053-e69db5a469a0.png)
...........................................................
...........................................................
![image](https://user-images.githubusercontent.com/57364385/153236347-a7c5bc90-5a04-4732-a999-a5ef2f5fe2b0.png)
...........................................................
...........................................................
![image](https://user-images.githubusercontent.com/57364385/153236704-00fd75ea-57bd-404d-8066-f8d020b9143f.png)
...........................................................
...........................................................
![image](https://user-images.githubusercontent.com/57364385/153237254-4a8e6c28-0d7f-405b-b0c0-9f1cb094b78d.png)

**Comment by bms63** [comment]
Is the rule for the Titles of the functions that words such as

- a
- the
-  an
-  in
-  of
- and
- for

should be lowercase unless starting the Title?

**Comment by bms63** [comment]
# Reference

## one or more

![image](https://user-images.githubusercontent.com/10111024/153296753-f2c6cc5c-9555-4c0d-8235-8d5e6470593b.png)

**Comment by bms63** [comment]
# Query Dataset Documentation

Do we want sub-bullets here?

![image](https://user-images.githubusercontent.com/10111024/153297490-9c276c50-44e8-4b1a-b88e-5725a3ec9ce0.png)

**Comment by bms63** [comment]
Should all references to admiral in text be presented as `{admiral}`

![image](https://user-images.githubusercontent.com/10111024/153297940-3f4285e9-dee9-42a2-9dc0-6b2a60c601dc.png)

**Comment by bms63** [comment]
# Creating a BDS Time-to-Event ADaM

Are these now in `admiral.test`??

![image](https://user-images.githubusercontent.com/10111024/153299893-3a45083d-5441-402c-84fb-b893be825686.png)

**Comment by yangc71** [comment]
### derive_summary_records.R
Sorry for randomly jumping in, I just saw this typo when clicking through the site and thought to add it here.

Under `filter` parameter description example, `filter_rows` is mentioned instead of `filter`. 
![Screen Shot 2022-02-09 at 3 26 41 PM](https://user-images.githubusercontent.com/90733000/153308041-e845ce8c-4bfc-4806-9888-8f553b3336cd.png)

**Comment by yangc71** [comment]
### Get Started
I don't think we have a `derive_param_os()` function so this piece of code is not linking to any function. Update the example to reference another `derive_param_` function? 
![Screen Shot 2022-02-09 at 3 41 37 PM](https://user-images.githubusercontent.com/90733000/153309557-27a695a5-0ab1-4b6d-9462-4d9991ba3c95.png)

**Comment by rossfarrugia** [comment]
on Konstantina's NEWS.md spot and extract above there's also a case of "the the" i spotted

**Comment by thomas-neitmann** [comment]
> Is the rule for the Titles of the functions that words such as
> 
> * a
> * the
> * an
> * in
> * of
> * and
> * for
> 
> should be lowercase unless starting the Title?

@bms63 All titles should be in title case, i.e. `tools::toTitleCase()`, which indeed leaves the words you mentioned in lower case.

**Comment by thomas-neitmann** [comment]
> ### Get Started
> I don't think we have a `derive_param_os()` function so this piece of code is not linking to any function. Update the example to reference another `derive_param_` function? ![Screen Shot 2022-02-09 at 3 41 37 PM](https://user-images.githubusercontent.com/90733000/153309557-27a695a5-0ab1-4b6d-9462-4d9991ba3c95.png)

@yangc71 @bms63 Yes, let's change to `derive_param_bmi()` which will link to an actual function.

**Comment by thomas-neitmann** [comment]
> # Creating a BDS Time-to-Event ADaM
> Are these now in `admiral.test`??
> 
> ![image](https://user-images.githubusercontent.com/10111024/153299893-3a45083d-5441-402c-84fb-b893be825686.png)

Yes, all SDTM datasets are now in {admiral.test}.

**Comment by thomas-neitmann** [comment]
> Should all references to admiral in text be presented as `{admiral}`
> 
> ![image](https://user-images.githubusercontent.com/10111024/153297940-3f4285e9-dee9-42a2-9dc0-6b2a60c601dc.png)
> 
> We go back and forth in our documents

@bms63 That would be ideal.

**Comment by thomas-neitmann** [comment]
> # News
> Sometimes we use periods and sometimes we dont. Please update to be consistent ![image](https://user-images.githubusercontent.com/10111024/153226715-222d256c-8fcf-4fc0-95ef-4195cde67861.png)

Let's remove periods unless there are actually multiple sentences belonging to one bullet point.

**Comment by amsmith214** [comment]
> > > # Creating a BDS Time-to-Event ADaM
> > > Are these now in `admiral.test`??
> > > ![image](https://user-images.githubusercontent.com/10111024/153299893-3a45083d-5441-402c-84fb-b893be825686.png)
> > 
> > 
> > Yes, all SDTM datasets are now in {admiral.test}.
> 
> Please note that for time-to-event no SDTM datasets are used. I.e., we should not change "{admiral}" to "{admiral.test}" but we could remove "CDISC Pilot SDTM and ".

noted

**Comment by amsmith214** [comment]
> # Reference
> ## one or more
> ![image](https://user-images.githubusercontent.com/10111024/153296753-f2c6cc5c-9555-4c0d-8235-8d5e6470593b.png)

chalk it up to my ignorance: where is this index.html file? i know it's going to be a purloined letter scenario but i cannot find it

**Comment by bms63** [comment]
@amsmith214 that is in the _pkgdown.yml file
