### ISSUE TITLE
Create a skeleton News Files for 0.7.0 Release

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#900]
USing 0.6.0 as a guide.  Create a skeleton News section for release 0.7.0

For examples:  

## etc....see previous news file

**Comment by rossfarrugia** [comment]
@bms63 hope OK if i take this one on as i'd like to use a simple issue for the demo at the community meeting later?

**Comment by rossfarrugia** [comment]
closing this issue (as forgot to use closes keyword so github does it automatically later when merged to main, but i figure leaving this one open is of no use to anyone as its such a trivial update!) :)
