### ISSUE TITLE
Broken links in release

### ISSUE THREAD

**Issue by konstantinakoukR** [pharmaverse/admiral#903]
Hi all,

Another release-related mega-issue to capture the broken links that we spot.

**Comment by konstantinakoukR** [comment]
### Creating an OCCDS ADaM
Source: [vignettes/occds.Rmd](https://github.com/pharmaverse/admiral/blob/main/vignettes/occds.Rmd)

"Derive/Impute End and Start Analysis Date/time and Relative Day" doesn't redirect anywhere.

![image](https://user-images.githubusercontent.com/57364385/153241092-8ab0dd39-e450-4005-9645-215ae48cc3ae.png)

**Comment by konstantinakoukR** [comment]
### FAQ
Source: [vignettes/faq.Rmd](https://github.com/pharmaverse/admiral/blob/main/vignettes/faq.Rmd)

"Unit testing" link doesn't work.

![image](https://user-images.githubusercontent.com/57364385/153249501-0184934a-b2ca-4988-9833-d5e0f07b66f5.png)

**Comment by bundfussr** [comment]
On git_usage.Rmd the link below is broken as well.
![image](https://user-images.githubusercontent.com/80953585/153254726-7b47a0f0-87d5-47c1-9d76-6cdf42443e98.png)

**Comment by konstantinakoukR** [comment]
### Unit Test Guidance
Source: [vignettes/unit_test_guidance.Rmd](https://github.com/pharmaverse/admiral/blob/main/vignettes/unit_test_guidance.Rmd)

The following link is broken.

![image](https://user-images.githubusercontent.com/57364385/153258351-95fc86bc-751d-4304-b3e6-4f0fad8d8be5.png)

**Comment by konstantinakoukR** [comment]
### Derive a Disposition Reason at a Specific Timepoint
Source: [R/derive_vars_disposition_reason.R](https://github.com/pharmaverse/admiral/blob/main/R/derive_vars_disposition_reason.R)

The link for `derive_vars_disposition()` is not active.

![image](https://user-images.githubusercontent.com/57364385/153265934-15654800-43ce-40c6-b799-f069a409f0e8.png)

**Comment by konstantinakoukR** [comment]
### Derive BASETYPE Variable
Source: [R/derive_var_basetype.R](https://github.com/pharmaverse/admiral/blob/main/R/derive_var_basetype.R)

The following is broken.

![image](https://user-images.githubusercontent.com/57364385/153266086-5dcaaa0b-92a7-4034-9f25-bd949285163d.png)

**Comment by bms63** [comment]
# Creating a BDS Time-to-Event ADaM

When I click these type functions in this vignette

![image](https://user-images.githubusercontent.com/10111024/153300379-f1f4833d-fb3f-4d1d-92c9-b23d55ba7b2f.png)

they go out here

![image](https://user-images.githubusercontent.com/10111024/153300490-c0a91374-063b-479d-aeea-78cf69d9165c.png)

they should be internal.

**Comment by bms63** [comment]
# Creating a BDS Time-to-Event ADaM

We don't call View() in other vignetters - maybe just remove??

![image](https://user-images.githubusercontent.com/10111024/153300771-1e983825-39b1-4096-a477-bf8d0e0d3891.png)

**Comment by rossfarrugia** [comment]
hi all, i'll start working through the fixes for this now but keep any new ones you find coming on this issue...

**Comment by PaulinaaRak** [comment]
I would recommend updating the Slack link in the "Contribution to admiral section ", to this one https://join.slack.com/t/pharmaverse/shared_invite/zt-yv5atkr4-Np2ytJ6W_QKz_4Olo7Jo9A

The one which is there currently redirects to "unknown-channell" 
![image](https://user-images.githubusercontent.com/99408917/153421286-61c1bcdf-8a39-4e50-9fce-cbf1bc7064cd.png)

**Comment by rossfarrugia** [comment]
Thanks @PaulinaaRak - will fix this

**Comment by bundfussr** [comment]
Could we update the link text to "admiral Slack channel" to make clear which channel should be used. I think the link provided by @PaulinaaRak just points to pharmaverse.

**Comment by bms63** [comment]
Thanks @PaulinaaRak!  Ross caught that one in his PR.  #909 

![image](https://user-images.githubusercontent.com/10111024/153440215-b3aca67e-0e19-440a-94a7-d3ba5c837d5b.png)
