### ISSUE TITLE
derive_param_os in Get Started Document

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#906]
Could we have an actual example here.  What is the OS parameter?  Could we use derive_param_map here

## Text from the Get STarted document

The most important functions in admiral are the [derivations](https://7a8f691bc703452e84c2311c905228d5.app.rstudio.cloud/files/docs/reference/index.html#section-derivations). These functions start with derive_. The first parameter of these functions expects the input dataset. This allows us to string together derivations using the [%>%](https://dplyr.tidyverse.org/reference/reexports.html) operator.

Functions which derive a dedicated variable start with derive_var_ followed by the variable name, e.g., [derive_var_trtdurd()](https://7a8f691bc703452e84c2311c905228d5.app.rstudio.cloud/files/docs/reference/derive_var_trtdurd.html) derives the TRTDURD variable.

Functions which derive a dedicated parameter start with derive_param_ followed by the parameter name, e.g., derive_param_os() derives the OS parameter

![image](https://user-images.githubusercontent.com/10111024/153294446-d0cbdfa6-8cca-48dd-b054-3f784de6f993.png)

**Comment by rossfarrugia** [comment]
this one exists here too: https://github.com/pharmaverse/admiral/issues/899

**Comment by rossfarrugia** [comment]
fixed in https://github.com/pharmaverse/admiral/pull/910
