### ISSUE TITLE
Update Date and Time Imputation Vignette with preserve and ignore_seconds examples

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#907]
The functions showcased in this vignette have been updated to have preserve and ignore seconds arguments.  #589 #592   This issue will be done when examples showcasing those updated arguments are presented.

**Comment by rossfarrugia** [comment]
Adding extra requests to this issue from #727 :
- We also need to add an example to the date and time imputation vignette where date_imputation=”06-15” is used. 
- Include an example using new slice_derivation function, e.g. when AE onset partial date/time before first dose, it will impute last day of year or month. when AE onset partial date/time after first dose, it will impute first day of year or month.

**Comment by bundfussr** [comment]
The third item is covered by #701

**Comment by rossfarrugia** [comment]
great - thanks @bundfussr! one less job
