### ISSUE TITLE
Pre-Release Strategy Going Forward

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#913]
Hey all,

Just wanted to have a thread for Pre-Release Strategy going forward and can bring up in the Retrospective.  Feel free to drop your concerns, what went well, what you thought is not sustainable, etc into this thread.  Just want to keep if fresh for the upcoming Retrospective!!

Current Strategy
- Mega Issue Threads for Typos and Links 
- Big PR of `devel` into `main` to focus in on what was changed from previous release
- Frantic plea on Slack about needing help

What went well
- `{admiral}` core dev team being amazing and making updates!
-  Great feedback from reviewers and timely updates
- Identified issues on themes, syntax, layout in documentation

Concerns/Ideas for the Release Strategy
- Link checking program should be created/found to reduce burden on dev team for checking links
- News File should have standard skeleton template in `devel` going forward
- Felt a bit frantic at times

@pharmaverse/admiral 
@pharmaverse/admiral-devs

**Comment by bundfussr** [comment]
Having a link checking program would definitely be great.

I also like the NEWS skeleton.

We found a lot of issues in the pre-release phase. However, most of them were minor but we spent a lot of time on it.

I would propose not to re-review all the changes in the pre-release phase but rely on the feature branch reviews and automated checks. In case something important was missed we can do a hot fix.

**Comment by yangc71** [comment]
Thank you Ben! I just had a minor thought about typos. I wonder if it's too time-consuming to check and review new typos during the pre-release? Can we maybe create an issue for typos and add to it at an ongoing basis if any is identified, and fix them at once before a release? If any are missed, we can just address during the next release. Just so team can focus on the more major issues during the pre-release phase.

**Comment by thomas-neitmann** [comment]
@yangc71 This should proably become part of a PR check. There are tools to automate the cheking (e.g. `devtools::spell_check()`) so we could automate this with a GH actions workflow. That way we shift the work upstream which means less stress when preparing a release.

**Comment by bms63** [comment]
@yangc71 I think a lot of the typos were picked up from a wide view of all the documentation - for example formatting was brought up in the thread - we use {admiral}, admiral and `{admiral}` interchangeably in our documentation.  But I agree that a release shouldn't have to go through a typo or formatting check again as it gets a little arbitrary and too much on us.

Yes to more Pull Request auto-checks!  

Perhaps a recurring every 4th sprint we have a health check on formatting and typos that could be assigned to someone.  Until the package gets more stable and releases are reduced.  

Also, we might want to investigate having a more codified styling guide for our documentation - this would hopefully extend to dependent packages.

**Comment by duniek** [comment]
### Notes from Sprint meeting retrospective:
- hyperlinks: for release only full-links are accepted, but during development relative links are needed. Is there a tools that would do it for us?
- programs to check links: create issue to investigate which tool is best
- release checklist: devtools provides this, although at times may be too general
- typos: try to add words to the dictionary, so that we can run a spell-check. [Wordlist file here](https://github.com/pharmaverse/admiral/blob/main/inst/WORDLIST)
- typos: include checking for typos as part of code review
- add release date in the change log: this is automatically added for CRAN releases
- ```admiral``` style convention - pending (?)

**Comment by thomas-neitmann** [comment]
I created a separate issue to update our dictionary in #957.
