### ISSUE TITLE
CRAN Submission failed

### ISSUE THREAD

**Issue by thomas-neitmann** [pharmaverse/admiral#918]
Dear maintainer,

package admiral_0.6.0.tar.gz does not pass the incoming checks automatically, please see the following pre-tests:
Windows: <https://win-builder.r-project.org/incoming_pretest/admiral_0.6.0_20220211_124511/Windows/00check.log>
Status: 1 WARNING
Debian: <https://win-builder.r-project.org/incoming_pretest/admiral_0.6.0_20220211_124511/Debian/00check.log>
Status: 1 ERROR, 1 WARNING

Please fix all problems and resubmit a fixed version via the webform.
If you are not sure how to fix the problems shown, please ask for help on the R-package-devel mailing list:
<https://stat.ethz.ch/mailman/listinfo/r-package-devel>
If you are fairly certain the rejection is a false positive, please reply-all to this message and explain.

More details are given in the directory:
<https://win-builder.r-project.org/incoming_pretest/admiral_0.6.0_20220211_124511/>
The files will be removed after roughly 7 days.

No strong reverse dependencies to be checked.

Best regards,
CRAN teams' auto-check service
Flavor: r-devel-windows-x86_64
Check: CRAN incoming feasibility, Result: WARNING
  Maintainer: 'Thomas Neitmann <[thomas.neitmann@roche.com](mailto:thomas.neitmann@roche.com)>'

  New submission

  Possibly misspelled words in DESCRIPTION:
    ADaM (3:8, 29:56)
    CDISC (29:40)

  Strong dependencies not in mainstream repositories:
    admiral.test

  Found the following (possibly) invalid URLs:
    URL: https://codecov.io/gh/Roche-GSK/admiral?branch=main (moved to https://app.codecov.io/gh/Roche-GSK/admiral?branch=main)
      From: README.md
      Status: 200
      Message: OK

  Found the following (possibly) invalid file URIs:
    URI: programming_strategy.html
      From: inst/doc/admiral.html
    URI: contribution_model.html
      From: inst/doc/development_process.html
    URI: git_usage.html
      From: inst/doc/development_process.html
    URI: programming_strategy.html
      From: inst/doc/development_process.html
    URI: pr_review_guidance.html
      From: inst/doc/development_process.html
    URI: programming_strategy.html
      From: inst/doc/development_process.html
    URI: programming_strategy.html
      From: inst/doc/development_process.html
    URI: git_usage.html
      From: inst/doc/development_process.html
    URI: git_usage.html
      From: inst/doc/development_process.html
    URI: pr_review_guidance.html
      From: inst/doc/development_process.html
    URI: ../articles/development_process.html
      From: NEWS.md
    URI: ../articles/pr_review_guidance.html
      From: NEWS.md
    URI: ../articles/contribution_model.html
      From: NEWS.md
    URI: ../articles/unit_test_guidance.html
      From: NEWS.md
    URI: ../reference/index.html
      From: NEWS.md
    URI: ../articles/bds_tte.html
      From: NEWS.md
    URI: ../articles/queries_dataset.html
      From: NEWS.md
    URI: ../articles/writing_vignettes.html
      From: NEWS.md
    URI: ../articles/faq.html
      From: NEWS.md
    URI: ../articles/adsl.html
      From: NEWS.md
    URI: ../articles/bds_finding.html
      From: NEWS.md
    URI: ../articles/occds.html
      From: NEWS.md

Flavor: r-devel-linux-x86_64-debian-gcc
Check: CRAN incoming feasibility, Result: WARNING
  Maintainer: 'Thomas Neitmann <[thomas.neitmann@roche.com](mailto:thomas.neitmann@roche.com)>'

  New submission

  Possibly misspelled words in DESCRIPTION:
    ADaM (3:8, 29:56)
    CDISC (29:40)

  Strong dependencies not in mainstream repositories:
    admiral.test

  Found the following (possibly) invalid URLs:
    URL: https://codecov.io/gh/Roche-GSK/admiral?branch=main (moved to https://app.codecov.io/gh/Roche-GSK/admiral?branch=main)
      From: README.md
      Status: 301
      Message: Moved Permanently
    URL: https://eudract.ema.europa.eu/result.html
      From: man/derive_agegr_fda.Rd
            man/derive_var_agegr_fda.Rd
      Status: Error
      Message: server certificate verification failed. CAfile: none CRLfile: none
                (Status without verification: OK)

  Found the following (possibly) invalid file URIs:
    URI: programming_strategy.html
      From: inst/doc/admiral.html
    URI: contribution_model.html
      From: inst/doc/development_process.html
    URI: git_usage.html
      From: inst/doc/development_process.html
    URI: programming_strategy.html
      From: inst/doc/development_process.html
    URI: pr_review_guidance.html
      From: inst/doc/development_process.html
    URI: programming_strategy.html
      From: inst/doc/development_process.html
    URI: programming_strategy.html
      From: inst/doc/development_process.html
    URI: git_usage.html
      From: inst/doc/development_process.html
    URI: git_usage.html
      From: inst/doc/development_process.html
    URI: pr_review_guidance.html
      From: inst/doc/development_process.html
    URI: ../articles/development_process.html
      From: NEWS.md
    URI: ../articles/pr_review_guidance.html
      From: NEWS.md
    URI: ../articles/contribution_model.html
      From: NEWS.md
    URI: ../articles/unit_test_guidance.html
      From: NEWS.md
    URI: ../reference/index.html
      From: NEWS.md
    URI: ../articles/bds_tte.html
      From: NEWS.md
    URI: ../articles/queries_dataset.html
      From: NEWS.md
    URI: ../articles/writing_vignettes.html
      From: NEWS.md
    URI: ../articles/faq.html
      From: NEWS.md
    URI: ../articles/adsl.html
      From: NEWS.md
    URI: ../articles/bds_finding.html
      From: NEWS.md
    URI: ../articles/occds.html
      From: NEWS.md

Flavor: r-devel-linux-x86_64-debian-gcc
Check: package dependencies, Result: ERROR
  Package required but not available: 'admiral.test'

  See section 'The DESCRIPTION file' in the 'Writing R Extensions'
  manual.

**Comment by epijim** [comment]
Hey @thomas-neitmann - note the 'automated validation on rocker' based on our autovalidate R is also failing, I believe due to the issue where you import `admiral.test`, and you can't import a package that doesn't exist on CRAN (at least without using a CRAN-like rather than CRAN).

**Comment by thomas-neitmann** [comment]
@epijim Thanks, that makes sense. We actually submitted {admiral.test} to CRAN as well last week. We got some minor comments which we are currently addressing. Once resubmtted it should be accepted and then this issue will be resolved.
