### ISSUE TITLE
autovalidate issues

### ISSUE THREAD

**Issue by thomas-neitmann** [pharmaverse/admiral#927]
- [x] `pkgdown` is used in `R/dataset_vignette.R`. `pkgdown` is not available on enableR 4.0.4 so it should be removed from this file. Replace `pkgdown::in_pkgdown` with `identical(Sys.getenv("IN_PKGDOWN"), "true")`.

- [x] `pkgdown` can't be temporarily installed on enableR 4.0.4 because of a system dependency issue. All suggested packages must be temporarily installed to pass the validation so this causes an issue. The two solutions are to remove it from Suggests or to add a note in `cran-comments.md` justifying why this issue can't be resolved. I will bring this up in our Tuesday meeting and get back to you with our advice.

- [ ] There are test failures at `test-derive_param_exposure.R:81:3` and `test-derive_param_tte.R:600:3`. Both have the same problem of a date-time column not having a timezone attribute.

```
x |   3 1     | derive_param_exposure [0.2 s]     
──────────────────────────────────────────────────
Failure (test-derive_param_exposure.R:81:3): new observations are derived correctly for AVAL
Differences found between the objects!

A summary is given below.

There are columns in BASE and COMPARE with differing attributes !!
All rows are shown in table below

  ===============================================
   VARIABLE  ATTR_NAME  VALUES.BASE  VALUES.COMP 
  -----------------------------------------------
    AENDTM     tzone       NULL          UTC     
    ASTDTM     tzone       NULL          UTC     
  -----------------------------------------------

x |  10 1     | derive_param_tte [1.5 s]          
──────────────────────────────────────────────────
Failure (test-derive_param_tte.R:600:3): new observations analysis datetime based on DTC variables are derived correctly
Differences found between the objects!

A summary is given below.

There are columns in BASE and COMPARE with differing attributes !!
All rows are shown in table below

  ===============================================
   VARIABLE  ATTR_NAME  VALUES.BASE  VALUES.COMP 
  -----------------------------------------------
     ADTM      tzone                     UTC     
  -----------------------------------------------
```

- [x] Remove `hms` from Imports because it is not used anywhere in the package.

- [x] Move `admiral.test` from Imports to Suggests because it isn't used in the package functions.

- [x] Remove cross-links like "[ae]" from `R/data.R` file, they cause a few issues so if they are not absolutely needed they should be removed.

- [x] All exported functions need to be covered by at least one test. 5 functions are not covered by any test. I am also getting a warning that the reexported functions in `R/reexports.R` don't have any tests. This can be solved by adding a single test for each but I will discuss with my team what the best way to handle this is.
    - `dataset_vignette` is not covered by any test
    - `derive_agegr_fda` is not covered by any test
    - `derive_var_worst_flag` and/or `derive_worst_flag` are not covered by any test
    - `get_many_to_one_dataset` is not covered by any test
    - `get_one_to_many_dataset` is not covered by any test

**Comment by thomas-neitmann** [comment]
Some further comments:

> - Nothing needs to change with `pkgdown`, it can stay in Suggests
> - You don't need to add tests for reexported functions

**Comment by thomas-neitmann** [comment]
@dgkf-roche I cannot re-produce the failing tests due to a missing timezone attribute (neither locally nor on CI plus CRAN did not detect those either). Any ideas?

**Comment by dgkf-roche** [comment]
Thanks @thomas-neitmann - let me double check on this. My suspicion is that this is dependent on the environment variable `TZ`. The system that I'm testing this against has `TZ` unset.

It's probably uncommon that `TZ` is unset on a system, so this is probably a rare test issue. Whether set or not, it looks like this test may fail if `TZ` is ever a location that falls outside of `UTC`. In any case, it might be a good idea to set a fixture for this envvar to constrain the test.

**Comment by dgkf-roche** [comment]
Okay, I did a bit more investigation and found that it's not related to the `TZ` envvar at all. It's stemming from `bind_rows` - likely due to an outdated package on my end.

Tracing the variable attributes through the error, they make it up until this `bind_rows` call:
https://github.com/pharmaverse/admiral/blob/346733b012df8bb64a2b7708ea769faeae29223c/R/derive_param_exposure.R#L210

I _think_ this boils down to needing an updated version of `vctrs`, but I need to dot more digging to pin down the point of failure. Surprisingly, doing a simple `bind_rows` on two `POSIXct` columns does not drop this attribute, and I'm still trying to pinpoint what is unique about the example that is causing the attributes to get dropped. 

For the record, I'm running 

```
dplyr 1.0.5
vctrs 0.3.7
rlang 0.4.10
```

**Comment by dgkf-roche** [comment]
And, finally a reproducible example that distills this issue:

Debugging the `bind_rows` call, I see that `expo_data` has an extra `iso_dtm` subclass
https://github.com/pharmaverse/admiral/blob/346733b012df8bb64a2b7708ea769faeae29223c/R/derive_param_exposure.R#L210

```r
Browse[1]> attributes(dataset$AENDTM)
# $class
# [1] "POSIXct" "POSIXt" 
# 
# $tzone
# [1] "UTC"

Browse[1]> attributes(expo_data$AENDTM)
# $tzone
# [1] "UTC"
# 
# $class
# [1] "iso_dtm" "POSIXct" "POSIXt" 
```

Similarly, if I just create two minimal tibbles to try to join, I see the same thing

```r
t <- ymd_hms("2020-02-22T00:00:00")
l <- tibble(x = t)
r <- tibble(x = admiral::as_iso_dtm(t))

attr(l$x, "tz")
# [1] UTC

attr(r$x, "tz")
# [1] UTC

attr(dplyr::bind_rows(l, r)$x, "tz")
# NULL

attr(vctrs::vec_rbind(l, r)$x, "tz")  # vec_rbind called internally by bind_rows
# NULL
```

As far as I can tell, there aren't other moving pieces to break down. `bind_rows` seems to be primarily dependent on `vctrs::vec_rbind` behavior, and `vec_rbind` just calls out to some C code. I tried running this against the latest `vctrs` release as well to no avail.

Let me know if there's anything more I can do to chase this one down.
