### ISSUE TITLE
Documentation:  Clarify usage of `%>%` for computations

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#933]
### Please select a category the issue is focused on?

Other

### Let us know where something needs a refresh or put your idea here!

Clarify usage of `%>%` for computations, i.e., it can not be used for comptations. To be added to the Computations section of the get started page.

**Comment by wqrena** [comment]
@bundfussr, I would like to pick up this issue. 
Let's add the clarification sentence such as "This computation function can not be used with `%>%` ". Can you clarify where is the best place to put this clarification sentence, in the manual description, or in the manual details?

**Comment by bundfussr** [comment]
@wqrena , thanks for picking this up.

I would put the sentence into the details section. Maybe it should say "Usually this computation function can not be used with `%>%`." because technically you could use `%>%` but in most cases it does not make sense.

Could you also add a sentence to the "Computations" section on the "Get started" page?
