### ISSUE TITLE
Documentation:  Add reference to ECG for `derive_param_qtc` and `derive_param_rr()`

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#934]
### Please select a category the issue is focused on?

Function Documentation

### Let us know where something needs a refresh or put your idea here!

Documentation:  Add reference to ECG for `derive_param_qtc` and `derive_param_rr()` and explain meaning of acronyms RR and QT if possible.

**Comment by traceyxw** [comment]
I am not sure if it is necessary to explain these two acronyms as RR refers to the time interval between two successive R-waves and QT refers to the time interval from Q-wave to the end of T wave.

**Comment by thomas-neitmann** [comment]
Probably not worth it. Unless you know what a Q or T wave it this does not add any information. Just adding that this is ECG related seems to suffice to me.
