### ISSUE TITLE
Documentation:  Add comment regarding ONTRTFL to ADCM template

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#935]
### Please select a category the issue is focused on?

Other

### Let us know where something needs a refresh or put your idea here!

Add comment about the option span_period = "Y"/NULL to ADCM templates and OCCDS vignette. For CM, also medications that started prior drug intake are being considered as on-treatment (but non treatment emergent). It can vary accross organizations, at the least the option is present in the function to perform both.

**Comment by rossfarrugia** [comment]
@bundfussr i'll try this update and will ask you to review when ready. i understand it as you're asking for a comment to be added to explain the option, but not to update the template code itself with this - as currently it doesn't have this option set:

```
  derive_var_ontrtfl(
    start_date = ASTDT,
    end_date = AENDT,
    ref_start_date = TRTSDT,
    ref_end_date = TRTEDT
  ) 
```

Correct me if I'm wrong and you're asking for the code itself to make this the default option too though.

**Comment by rossfarrugia** [comment]
@bundfussr also i noticed in https://pharmaverse.github.io/admiral/reference/derive_var_ontrtfl.html, the following should be ref_start_date:
![image](https://user-images.githubusercontent.com/82581364/157680710-ab83e34d-a7af-4361-a7ae-63ce5ceb6ed2.png)


As per this section:
![image](https://user-images.githubusercontent.com/82581364/157680659-e3619e54-b02c-4e9c-8d74-ed7303898924.png)


Will update this too as well as highlighting of code sections.

**Comment by bundfussr** [comment]
@rossfarrugia , Yes, you are right.

The issue is related to the following tester feedback.

> template program for adcm : 
1/ ONTRTFL : suggest to update template call to derive_var_ontrtfl : have a comment about the option span_period = "Y"/NULL. In my experience, for CM, also medications that started prior drug intake are being considered as on-treatment (but non treatment emergent). It can vary accross organizations, at the least the option is present in the function to perform both.
