### ISSUE TITLE
Documentation:  Clarify variables populated by `derive_param_*()` functions

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#939]
### Please select a category the issue is focused on?

Function Documentation, User Guides, Other

### Let us know where something needs a refresh or put your idea here!

Mention in the vignettes, in the `by_vars` description, and in the template scripts that `derive_param_*()` functions populate only those variables from the input dataset which are specified for the `by_vars` parameter.

**Comment by sophie-gem** [comment]
Hi @bundfussr, happy to pick up this issue (will be a good one for me to start with). Do you have any further information you could provide which would get me up to speed? No problems if not - I shall just start by making a list of all the `derive_param_*()` functions, templates etc. which I can identify as needing this and go from there.

**Comment by sophie-gem** [comment]
Believe these are all the relevant functions (minus those which are depreciated):
- [ ] `derive_derived_param`
- [ ] `derive_param_bmi`
- [ ] `derive_param_bsa`
- [ ] `derive_param_doseint`
- [ ] `derive_param_exposure`
- [ ] `derive_param_map`
- [ ] `derive_param_qtc`
- [ ] `derive_param_rr`
- [ ] `derive_param_tte`

**Comment by thomas-neitmann** [comment]
That looks about right @sophie-gem!

**Comment by thomas-neitmann** [comment]
What we're aiming for is that it's clear to everyone that unless you specify a variable in the `by_vars` parameter its values will **not** be retained in the newly created records.

**Comment by sophie-gem** [comment]
Right ok, that makes sense. Thanks very much @thomas-neitmann!

**Comment by bundfussr** [comment]
`derive_param_tte()` behaves differently than the other functions. The new parameter is not based on existing parameters of the input dataset. Thus you can not use the `by_vars` parameter to retain variables. If you need to retain information from the source datasets like imputation flag or visit, you can use the `set_values_to` field of the `event_source()` or `censor_source()` class. See https://pharmaverse.github.io/admiral/articles/bds_tte.html#handling-subjects-without-assessment for an example (date imputation flag is retained for the `start` censoring event).

**Comment by sophie-gem** [comment]
Many thanks @bundfussr , this makes sense. I have altered the above list and will bare this in mind.

**Comment by sophie-gem** [comment]
Template scripts that need this:
- [ ] ad_adeg.R
- [ ] ad_adex.R
- [ ] ad_advs.R

Vignettes that need this:
- [ ] bds_finding.Rmd
- [ ] bds_exposure.Rmd

**Comment by sophie-gem** [comment]
Hi @thomas-neitmann 

In the `bds_finding.Rmd` vignette, there is a typo in the following code block (lines 345-351):
```
adeg <- derive_param_qtcf(
  adeg,
  by_vars = vars(USUBJID, VISIT, ADT),
  set_values_to = vars(PARAMCD = "QTCFR")
)
```

There is no function called `derive_param_qtcf` and I am assuming that this should be `derive_param_qtc`. Are you happy for me to alter this here or should I open a new issue?

**Comment by sophie-gem** [comment]
@bundfussr / @thomas-neitmann 

With regards to making the documentation clear, I have currently inserted (yellow highlighted text):

![image](https://user-images.githubusercontent.com/90790226/159172709-e0fc9fd1-d2cd-4e31-88dd-ec655cf52907.png)

However, I was wondering whether a note should also be made in the 'Details' or 'Value' sections of the documentation, or whether that would be overkill?

**Comment by bundfussr** [comment]
I would add a note to the values section because not all `derive_paam_*` function have a "Details" section.

**Comment by thomas-neitmann** [comment]
> Hi @thomas-neitmann
> 
> In the `bds_finding.Rmd` vignette, there is a typo in the following code block (lines 345-351):
> 
> ```
> adeg <- derive_param_qtcf(
>   adeg,
>   by_vars = vars(USUBJID, VISIT, ADT),
>   set_values_to = vars(PARAMCD = "QTCFR")
> )
> ```
> 
> There is no function called `derive_param_qtcf` and I am assuming that this should be `derive_param_qtc`. Are you happy for me to alter this here or should I open a new issue?

Please go ahead and alter this directly here.

**Comment by koegerr** [comment]
@sophie-gem is this still ongoing? Ben will check in with you in the next stand up.

**Comment by sophie-gem** [comment]
Hi @koegerr ,

Apologies, yes this is still ongoing. I have been very busy with project work recently but I will aim to get this finished on Friday (I have a full day set aside for pharmaverse contribution). Is this okay or is it required sooner? 

Many thanks.

**Comment by thomas-neitmann** [comment]
No rush @sophie-gem, we just wanted to check whether you're still on track. Having it by Friday would be great 🙂

**Comment by sophie-gem** [comment]
Just fyi - I'm now close to opening a PR. There just seem to be a few issues which I need to figure out how to resolve:

- [ ] `pkgdown::build_site()`  warning message "Deprecated: markdown_github. Use gfm instead."  
- [ ] "Warning message:
Topics missing from index: 
* +,iso_dtm,Period-method
* adeg
* assert_db_requirements
* ex_single
* get_terms_from_db
* print.tte_source
* queries
* validate_query
* validate_sdg_select
* validate_smq_select" (Also from `pkgdown::build_site()`)
- [ ] Also in the locally-built site, the vignettes seem to only show the first line or the left hand side of an assignment.
- [ ] `devtools::check()` WARNING: Rtools is required to build R packages, but the version of Rtools previously installed in C:/rtools40 has been deleted.
Please download and install Rtools custom from http://cran.r-project.org/bin/windows/Rtools/.
- [ ] `devtools::check()` N  checking R code for possible problems (8.1s)
   derive_param_exposure: warning in derive_vars_merged(dataset_add =
     dates, by = by_vars): partial argument match of 'by' to 'by_vars'
   derive_var_disposition_dt: no visible binding for global variable
     'temp_DT'
   derive_var_merged_cat: no visible binding for global variable
     'temp_match_flag'
   derive_var_merged_character: no visible binding for global variable
     'temp_match_flag'
   Undefined global functions or variables:
     temp_DT temp_match_flag
- [ ]  WARNING  'qpdf' is needed for checks on size reduction of PDFs

**Comment by sophie-gem** [comment]
Will get this done asap either at the weekend or next week.

**Comment by sophie-gem** [comment]
Hi @thomas-neitmann / @bundfussr , I was wondering if either of you have come across the issues above before? Do you have any recommendation on how I attempt to resolve this?
