### ISSUE TITLE
Feature Request:  Add PARAMCD from lookup table and output where obs not mapped

### ISSUE THREAD

**Issue by millerg23** [pharmaverse/admiral#940]
### Feature Idea

Read in look up table with PARAMCD/PARAM mappings, and left join the PARAMCD/MAPPING, for those observations with no PARAMCD added, output the records for user to review.

### Relevant Input

ADVS/ADEG/ADLB CDISC data with lookup table for PARAMCD as we have in ADVS script (or BDS Vignette).

### Relevant Output

ADVS/ADEG/ADLB with PARAMCD/PARAM added, and if no mapping found for observations then output to another data frame, controlled user.

### Reproducible Example/Pseudo Code

See VS script with lookup table and LEFT JOIN statements, just need to add in checking for missing PARAMCD, and output thse records somewhere.

**Comment by bms63** [comment]
* Could this be metadata driven or data-driven 
* Messaging around mappings not complete
* Some scenarios where we might have to make up own paramcds - if it was data-driven
* How does a company create a look-up table?
* CDISC dummy data versus company-specific data
* #552

**Comment by bms63** [comment]
Hey @konstantinakoukR just checking on where you are at with this issue.  We have till May 13th to get this one done :)

**Comment by bms63** [comment]
My understanding is it would be a function with a user-defined table.  A user would have their PARAMCD/PARAM mappings and then using the function join it onto the dataset.  If things are not mapped correctly or missing params then you get a warning message and results to review.  @millerg23 is that correct?

**Comment by millerg23** [comment]
> My understanding is it would be a function with a user-defined table. A user would have their PARAMCD/PARAM mappings and then using the function join it onto the dataset. If things are not mapped correctly or missing params then you get a warning message and results to review. @millerg23 is that correct?

Yes, thats correct, so function would have the following inputs as a minimum:
input data set (ie ADLB)
LOOK-UP table
BY_VARS for merging ADLB and LOOK-UP table

The function would return the dataframe with the variables in the look-up table added.
If there were observations in the new dataframe where PARAMCD missing then a WARNING would be triggered with the unique entries for the variables (from BY_VARS).
So if BY_VARS was LBTESTCD, LBMETHOD, then the WARNING would display the unique entries of LBTESTCD, LBMETHOD where PARAMCD was missing.

The function would call `derive_vars_merged` I think, then check for missing PARAMCD.

**Comment by konstantinakoukR** [comment]
Hi @bms63 , @millerg23 and @yangc71 ! I think I got an initial draft ready. Just a couple of things:
- where should we store the function? In the `R` folder?
- how the function should be called? What about `derive_adlb_lookup`?

**Comment by bms63** [comment]
Yes R folder for sure.  

 I would take a look at the https://pharmaverse.github.io/admiral/articles/programming_strategy.html to make that call and see if there are other lookup tables already available?

![image](https://user-images.githubusercontent.com/10111024/164456395-6fad4e0f-4f25-4a6b-8a8f-64bf70cb6278.png)

**Comment by konstantinakoukR** [comment]
Thank you @bms63 ! Based on Programming Strategy I proposed the `derive_adlb_lookup`, since `derive_` takes a dataset as input and returns a new dataset as output. I don't think there are any other lookup tables available already but maybe I'm missing something.

**Comment by bms63** [comment]
Ummm...thinking if this is only for adlb or can it be generalize for other datasets?  adeg?

**Comment by konstantinakoukR** [comment]
Good point! Maybe we can have a more general name like `derive_lookup_table` but for now we can have it limited to ADLB as first PR/testing?

**Comment by bundfussr** [comment]
Shouldn't we use the `vars` fragment as it adds variables to the input dataset?

**Comment by bms63** [comment]
So `derive_vars_lookup_table`  ?

**Comment by konstantinakoukR** [comment]
But it doesn't derive any new variable really :/ It merges the two datasets together and gives a new dataset with the records that PARAMCD is empty. Happy to use `derive_vars_lookup_table` though! :)

**Comment by millerg23** [comment]
To me, this is similar to other `derive_vars_merge_xxxx` functions we have, that all call `derive_vars_merged` function.
Maybe, `derive_vars_merge_lookup` or `derive_vars_merge_lookup_table` (maybe too long a name!)?

**Comment by yangc71** [comment]
Hi all, I tried to move forward with this issue and linked a pull request (#1298). Currently the function optionally outputs a message showing a table of unique `by_vars` values that are not mapped. Could you please take a look and let me know if it's the right approach? Thanks.
