### ISSUE TITLE
Feature Request: derive_var_analysis_ratio()

### ISSUE THREAD

**Issue by yangc71** [pharmaverse/admiral#943]
### Feature Idea

`derive_var_analysis_ratio()` should calculate the ratio of analysis value to the reference value (e.g. baseline, analysis range upper limit, analysis range lower limit etc.). Could be used to derive variables such as R2BASE, R2ANRHI, R2ANRLO. 

Related discussion #552, [ADLB Workflow Doc](https://exbpbox.ent.box.com/file/913378017585)

### Relevant Input

BDS structure dataset (e.g. ADLB) containing AVAL and reference value variable (e.g. BASE, ANRHI, ANRLO). 

### Relevant Output

Dataset with the new ratio variable added. 

### Reproducible Example/Pseudo Code

draft example call: derive_var_analysis_ratio(dataset = ADLB, analysis_var = AVAL, ref_var = BASE, new_var = R2BASE, ...)

**Comment by yangc71** [comment]
@konstantinakoukR not sure if you want to work on this one :)?

**Comment by bms63** [comment]
Hi @konstantinakoukR  is it okay if I work on this??

**Comment by bms63** [comment]
Since this is deriving potential 3 variables - should it be derive_vars_analysis_ratio()
