### ISSUE TITLE
Feature Request:  function(s) for lab grade variables

### ISSUE THREAD

**Issue by yangc71** [pharmaverse/admiral#945]
### Feature Idea

Function (e.g. `derive_vars_lab_grade()`) should derive grading related variables (e.g. ATOXGR). Might need additional functions/ways to supply the grading criteria (for example, a grading metadata dataset based on different grading criteria such as NCI-CTCAE v5 metadata)? 

Related discussion #552, [ADLB workflow doc](https://exbpbox.box.com/s/kylmsmes456mdanj6sn1j3twka5hmer1)

### Relevant Input

BDS structure dataset.
Might need grading criteria metadata as input. 

### Relevant Output

Dataset with grading variable added.

**Comment by bundfussr** [comment]
ADaM IG offers two ways of grading variables:

- `ATOXGR`: high and low grades are stored in the same variable
- `ATOXGRL` and `ATOXGRH`: separate variables for high and low grades

There are also variables `ATOXDSCL` and `ATOXDSCH` for description of high and low toxicity. I think the structure of the grading metadata should allow to provide these descriptions.

**Comment by bms63** [comment]
Starting small with a subset of tests.  Start off with a pseudo function that does a couple of tests and push out to slack channel for discussion.

**Comment by bms63** [comment]
Should someone be able to override our spreadsheet of metadata or should they be able to override small sections of code?

**Comment by bms63** [comment]
@millerg23 Be sure to link out the spec document you were sharing in our meeting.

**Comment by bundfussr** [comment]
- Do we need the "VAR CHECK" column? Couldn't we use `extract_vars()` to extract the variables from the condition in the "ADMIRAL IMPLEMENTATION" column?
- For user specific updates: Would it be possible that the user provides a spreadsheet/dataset which contains only the user specific terms and the functions combines the standard definitions and user definitions (user definition is taken for terms where both is provided)?

**Comment by millerg23** [comment]
> * Do we need the "VAR CHECK" column? Couldn't we use `extract_vars()` to extract the variables from the condition in the "ADMIRAL IMPLEMENTATION" column?
> * For user specific updates: Would it be possible that the user provides a spreadsheet/dataset which contains only the user specific terms and the functions combines the standard definitions and user definitions (user definition is taken for terms where both is provided)?

Yes good idea regarding `extract_vars()` I wasn't aware of this. Although maybe it adds transparency to user to see what vars are required in the metadata itself. I was thinking the metadata would also be the source of any documentation as well, so vars required could be surfaced in documentation using `extract_vars()`.
Regarding, user-specific updates: yes this could be an option, does add a level of complexity, but if you only want to update one lab tests criteria, then makes sense to just pass in that 1 update. Also we could have some kind of report/output/log to say whats been overwritten.

**Comment by yangc71** [comment]
Hi @millerg23, thank you for sharing the documents.
1. I'm not too clear on the first step of mapping PARAMCD with TERM: are ATOXDSCL/H coming from the user-defined lookup table (i.e. in the lookup table users would define which PARAMCD corresponds to e.g. ATOXDESCL = Anemia)? Maybe we should also briefly define what a lookup table should look like to be used as an input. 
2. We could also add a column in the metadata sheet to flag the grading criteria that involve other clinical assessments (i.e. criteria that do not just use lab values) and output the list in the end, so users can decide whether to apply any additional processing to those.
