### ISSUE TITLE
Address CRAN comments

### ISSUE THREAD

**Issue by thomas-neitmann** [pharmaverse/admiral#946]
> Thanks,
If there are references describing the methods in your package, please
add these in the description field of your DESCRIPTION file in the form
authors (year) <doi:...>
authors (year) <arXiv:...>
authors (year, ISBN:...)
or if those are not available: <https:...>
with no space after 'doi:', 'arXiv:', 'https:' and angle brackets for
auto-linking.
(If you want to add a title as well please put it in quotes: "Title")
Please add \value to .Rd files regarding exported methods and explain
the functions results in the documentation. Please write about the
structure of the output (class) and also what the output means. (If a
function does not return a value, please document that too, e.g.
\value{No return value, called for side effects} or similar)
Missing Rd-tags in up to 35 .Rd files, e.g.:
      assert_list_element.Rd: \value
      assert_one_to_one.Rd: \value
      assert_varval_list.Rd: \value
      ...
You have examples for unexported functions.
Please either omit these examples or export these functions.
Used ::: in documentation:
      man/arg_name.Rd:
         test_fun <- function(something) {
  admiral:::arg_name(substitute(something))
}
etc..
Please fix and resubmit.

**Comment by thomas-neitmann** [comment]
@pharmaverse/admiral-devs I need your help with the second point, i.e.

> Please add \value to .Rd files regarding exported methods and explain the functions results in the documentation. Please write about the structure of the output (class) and also what the output means. (If a function does not return a value, please document that too, e.g. \value{No return value, called for side effects} or similar).

We have to find **all** exported functions which do not have a "Value" heading in the documentation page (which means it does not have a `@return` tag in the function header). If you find such a function please add it in a comment here.

**Comment by bundfussr** [comment]
All man files without `\value{`:

```
adae.Rd
adcm.Rd
add.Rd
adex.Rd
admiral-package.Rd
adsl.Rd
advs.Rd
arg_name.Rd
assert_list_element.Rd
assert_one_to_one.Rd
assert_varval_list.Rd
backquote.Rd
compute_map.Rd
convert_blanks_to_na.Rd
dataset_vignette.Rd
default_qtc_paramcd.Rd
derive_baseline.Rd
derive_params_exposure.Rd
derive_var_basec.Rd
derive_var_basetype.Rd
enumerate.Rd
expect_dfs_equal.Rd
ex_single.Rd
extract_duplicate_records.Rd
extract_unit.Rd
extract_vars.Rd
filter_if.Rd
get_duplicates_dataset.Rd
get_many_to_one_dataset.Rd
get_one_to_many_dataset.Rd
grapes-notin-grapes.Rd
list_all_templates.Rd
negate_vars.Rd
print.tte_source.Rd
queries.Rd
quo_c.Rd
reexports.Rd
signal_duplicate_records.Rd
squote.Rd
tte_source_objects.Rd
use_ad_template.Rd
vars2chr.Rd
warn_if_invalid_dtc.Rd
warn_if_vars_exist.Rd
what_is_it.Rd
```

**Comment by thomas-neitmann** [comment]
Thanks a lot @bundfussr! How did you discover this so quickly?

**Comment by bundfussr** [comment]
I called `grep -L '\\value{' *.Rd` in the man folder.

**Comment by thomas-neitmann** [comment]
I have to seriously improve my command line skills 😅 

Furtunately I asked and didn't skin through all pages manually...
