### ISSUE TITLE
Start open monthly admiral meetings with a focus on onboarding new contributors

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiral#948]
To cover:
- Informal open Q&A for any users
- Onboarding of new contributors (core or non-core*) - centralised into one session instead of many of us covering these individually. Expectation would be running through the [onboarding checklist](https://github.com/pharmaverse/admiral/blob/main/.github/ISSUE_TEMPLATE/05_onboard.yml) and introducing to the main vignettes etc that need reading, instead of bombarding newcomers with lots of links and access emails to Box/Slack/Github/etc.

_* The distinction for non-core for Roche/GSK contributors would be that those without a dedicated % assigned time to join admiral could still contribute without having to attend all the scrum ceremonies. Also there are many ways to contribute beyond just developing (see our contribution vignette), e.g. testing package out & raising bugs/feature requests_

There would be a monthly rota from the core team to take it turns each month to host this meeting, and advertise it via the admiral Slack channel each month to garner interest.

@duniek are you ok to take this one on? we discussed it at the leads/sponsor call today so i can provide more detail as needed

**Comment by duniek** [comment]
### Here's the schedule of our monthly contributor onboarding meetings:
**Dates and hosts:**
March 4th: Samia and ...
April 8th:
May 6th:
June 3rd:
