### ISSUE TITLE
Documentation:  How to create new admiral package extensions?

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiral#949]
### Please select a category the issue is focused on?

Other

### Let us know where something needs a refresh or put your idea here!

See Robin's slides: https://exbpbox.box.com/s/wx023zszjxb4owcld5rqn8uqdotzamg7

We discussed that we need a way such as a GitHub template and a vignette (/bitesize videos?) to help new teams setting up any admiral package extensions whilst still keeping consistent with how we've built admiral (e.g. issue templates, PR checklist, CI/CD checks, etc). This doesn't need to cover general R package creation training or anything like that, but just gives very easy and concise ways to set new packages up in line with admiral core, so that it becomes easier to do this rather than diverge.

@bms63 @thomas-neitmann probably one of you makes most sense to take this on given you were part of the discussion, but if anyone better feel free to change assignees.

**Comment by bms63** [comment]
I think Thomas and I should consult on this document, but **someone else** should be one who creates it, updates it and maybe helps to enforce its standards?   Good leadership opportunity for someone(s) new or in the background and that way more people get familiar with the setup, but also helps to update/maintain the document as we evolve and take the responsibility off the two of us.  @thomas-neitmann feel free to take this on, but we seem to be a bit busy!

I'm very interested in this alignment, orchestration of the admiral(s), e2e support packages, but if we want this soon, then I can not do it.  :)

**Comment by rossfarrugia** [comment]
@thomas-neitmann - let us know what you think? we kick off onco Friday so we're going to need our github repo set up in next couple of weeks, so this actually is quite pressing. or maybe someone could set this repo up and then write the document later to help future packages?

**Comment by bundfussr** [comment]
I would prefer text with screenshots rather than videos. As a user it is easier to skim through a text and you can copy from text, e.g., commands or URLs. As an author text is easier to maintain. To update a part of a video, e.g., update a URL, you need to rerecord the complete video.

**Comment by rossfarrugia** [comment]
I will take this on later after PHUSE US - i'll compile all the learnings do far and anything from slide decks for admiralonco, and will get this all set up in a couple of months ready for the next package extension to start, e.g. virology or ophtha, when the timing is right.

**Comment by bundfussr** [comment]
Outcome of discussion regarding package versions in extension packages:

admiral extension packages must use the same versions of packages that admiral core uses. Additionally packages can be used but they must not depend on newer versions of other packages (always reply “no” if updates are suggested during installation.)

**Comment by dinakar29** [comment]
Hi all, let me know if and when a barebones repository is available for this template. I will begin adding a centralized/common set of CI/CD workflows.

Also - what is this -> https://github.com/pharmaverse/pharmaverse_templates? Can that be used for admiral extensions? Trying to align efforts here, so we don't reinvent the wheel.

**Comment by rossfarrugia** [comment]
@dinakar29 you can start using that repo you mentioned above. See the discussion here as FYI https://github.com/pharmaverse/pharmaverse/issues/121. I need to have a think whether this should be renamed to be more admiral specific as then we can put more pieces in that are relevant to admiral package extensions, and any new pharmaverse collaboration could still use this as a starter if beneficial. I'm probably going to get onto this early next week so happy to work in parallel and keep each other updated.

**Comment by bundfussr** [comment]
@dinakar29 , I just notice one issue in admiralonco. For development of admiralonco we use the development version of admiral. Could this be considered in the R-CMD checks? I.e., for pull requests and pushes to `devel` the development version of admiral should be used by the checks. For PRs and pushes to `main` the latest released version of admiral should be used.

I would expect that all extension packages handle it this way.

**Comment by dinakar29** [comment]
@bundfussr - yes that can be easily done. That's part of the staged.dependencies workstream. Will let you know when that's in place.

@rossfarrugia - Yes let me know when you get to it, we can pair/collab accordingly.

**Comment by bms63** [comment]
> Hi all, let me know if and when a barebones repository is available for this template. I will begin adding a centralized/common set of CI/CD workflows.
> 
> Also - what is this -> https://github.com/pharmaverse/pharmaverse_templates? Can that be used for admiral extensions? Trying to align efforts here, so we don't reinvent the wheel.

Hi @dinakar29 That is just something I was playing around with that @rossfarrugia asked me to experiment with.  I was able to use the template and was able to have barebones "admiral" infrastructure set up.  Very cool!  Feel free to throw away, rename or delete.

**Comment by rossfarrugia** [comment]
ok guys, i started this today and woah... as i started drafting more and more came out and don't hate me but i've drafted a 21 step guide for review :D here https://exbpbox.ent.box.com/file/961272617425. take a look and add comments any time after the release goes out and @dinakar29 i'll get you access. i'm sure we can evolve and improve this over time as we learn from further package extensions experience.

**Comment by rossfarrugia** [comment]
See https://github.com/pharmaverse/admiraltemplate/blob/main/README.md for this guidance.

@bundfussr are you able to help with the [github template](https://github.com/pharmaverse/admiraltemplate) set-up as per the instructions linked above in the README file?

There's a list in this README file of all the pieces we expect to have a consistent set-up to admiral for, but please question from your experience of admiral and admiralonco whether other pieces should be added to the list. e.g. in step 14 we talk of setting up a project board but maybe this could be included as part of the template itself too. To get all the required folders we might need to add a dummy file in each, e.g. `inst/templates/ad_adXX.R`

@dinakar29 offered support for this step before and could help with any support for the CI/CD checks etc.

**Comment by bundfussr** [comment]
If we need to create folders, I would rather add a `README.md` file than a dummy `ad_adXX.R` file. Then it does not need to be removed or renamed and the `README.md` file could be used to describe the purpose of the folder.

I wonder how we keep admiraltemplate up to date. Maybe admiraltemplate could provide a `synchronize()` function which copies workflows, templates, renv.lock file, ... directly from the admiral core repo.

How should dependencies to other admiral packages be handled? Should other admiral packages added to the renv.lock file? If we add them with a hash, we need to update the renv.lock file frequently.

**Comment by bundfussr** [comment]
Response from @rossfarrugia :
> If we need to create folders, I would rather add a README.md file than a dummy ad_adXX.R file. Then it does not need to be removed or renamed and the README.md file could be used to describe the purpose of the folder.

Fine by me! Nice way to help new devs get up to speed with what goes where.

> I wonder how we keep admiraltemplate up to date. Maybe admiraltemplate could provide a synchronize() function which copies workflows, templates, renv.lock file, ... directly from the admiral core repo.

I was thinking the same thing earlier today! I’m sure there must be an automation solution for this like you suggest as this must be a common challenge.

> How should dependencies to other admiral packages be handled? Should other admiral packages added to the renv.lock file? If we add them with a hash, we need to update the renv.lock file frequently.

My thinking is admiral package extensions will only ever depend on admiral and admiral.test from the admiral family, along with the other admiral dependencies like the tidyverse packages. This will be consistent for them all, so I don’t foresee having to keep updating the dependencies often in the template repo. For example, I wouldn’t like the idea of say admiralophtha depending on admiralonco - as that would suggest whatever function we needed to re-use from onco should really be moved to admiral core.

**Comment by bms63** [comment]
`I wonder how we keep admiraltemplate up to date. Maybe admiraltemplate could provide a synchronize() function which copies workflows, templates, renv.lock file, ... directly from the admiral core repo.`

@dinakar29 is there magic for synchronizing repos?

**Comment by dinakar29** [comment]
@bms63 - yes it is possible to add a synchronizer where we can have a centralized location of these files and then sync them to other repos. We can add the synchronizer to the template package itself.

**Comment by bundfussr** [comment]
For `renv.lock` we would need more than a simple synchronize. It should synchronize with admiral core but take admiral extension package specific packages into account. For example in admiralroche we use the `renv.lock` from admiral but add `ROracle` package. If `renv.lock` in admiral is updated, the `renv.lock` in admiralroche should be updated without removing the `ROracle` package.

**Comment by bms63** [comment]
ummm... could admiral-core just have `ROracle` in its `renv.lock` file for simplicity and any others needed for extension packages?  I can't imagine we would diverge that much from each other.  There are lots of dependency packages in the lock file that I'm fuzzy on for admiral-core so having a few others wouldn't hurt anyone...I think.

**Comment by bms63** [comment]
Does the lock files diverge that greatly between `admiralroche` and `admiral`?   I don't see  `admiralroche` on GH so can't compare.   

Only a few differences for renv files between admiralonco and admiral-core:

```*** renv_core.txt	2022-06-07 12:38:03.988463813 +0000
--- renv_onco.txt	2022-06-07 12:38:35.788519883 +0000
***************
*** 65,80 ****
        "Repository": "CRAN",
        "Hash": "f3ca785924863b0e4c8cb23b6a5c75a1"
      },
-     "admiral": {
-       "Package": "admiral",
-       "Version": "0.7.0",
-       "Source": "GitHub",
-       "RemoteType": "github",
-       "RemoteHost": "api.github.com",
-       "RemoteRepo": "admiral",
-       "RemoteUsername": "pharmaverse",
-       "RemoteRef": "devel"
-     },
      "admiral.test": {
        "Package": "admiral.test",
        "Version": "0.2.0",
--- 65,70 ----
***************
*** 83,89 ****
        "RemoteHost": "api.github.com",
        "RemoteRepo": "admiral.test",
        "RemoteUsername": "pharmaverse",
!       "RemoteRef": "devel"
      },
      "askpass": {
        "Package": "askpass",
--- 73,81 ----
        "RemoteHost": "api.github.com",
        "RemoteRepo": "admiral.test",
        "RemoteUsername": "pharmaverse",
!       "RemoteRef": "devel",
!       "RemoteSha": "4f3bdd59a5a01bd0314a42e1d3ef32ca4d1745fe",
!       "Hash": "8378c5762f6be5a61854e880d6a8a223"
      },
      "askpass": {
        "Package": "askpass",
***************
*** 134,146 ****
        "Repository": "CRAN",
        "Hash": "56ae7e1987b340186a8a5a157c2ec358"
      },
-     "cachem": {
-       "Package": "cachem",
-       "Version": "1.0.6",
-       "Source": "Repository",
-       "Repository": "CRAN",
-       "Hash": "648c5b3d71e6a37e3043617489a0a0e9"
-     },
      "callr": {
        "Package": "callr",
        "Version": "3.7.0",
--- 126,131 ---- ```

Ah well if they are not publicly available then that makes my proposal not very feasible anyways!
.

**Comment by rossfarrugia** [comment]
hi all, can we get the template repo ready for admiralophtha to try out by end of next week please? i have the following as being involved here and i granted you all write access:
- @jj1994 (Julian) - will add the project board (as he's scrum master for onco and ophtha)
- @dinakar29 - could add any CI/CD and workflow pieces & look into any option to auto-sync pieces with the core repo
- @bms63 & @bundfussr - could add the required files/folders for admiral core consistency - knowing that this doesn't have to be perfect and sure we'll evolve it over time (e.g. all the renv.lock discussions above), but it should just give a decent headstart

**Comment by bms63** [comment]
Okay made a bunch of random issues for us to tackle.  

I think the end goals should be:

Template Repo when copied and with minimum changes: 
- Can successfully build package locally
- Pkgdown site successfully builds locally
- A PR successfully runs all workflow checks (R-CMD, lintr, tests, spelling, man)
- gh-pages site builds
- Others??

I think the minimal changes would be updating description file.  Populating man folder (maybe we do this with dummy function instead) and a few others...

**Comment by bms63** [comment]
Steps so far:  

1)  Click Use this Template and name your package extension repo
2)  Download Repo to RStudio and run` renv::restore()` - you will see a prompt and this will take a few minutes
3)  Update `DESCRIPTION` file with your package name, authors, etc
4)  Run `devtools::load_all()`  - debug
5)  Run `devtools::check()` - debug
6)  Run `pkgdown::build_site()`

Some success so far with minimal tweaks - will update in the repo
![image](https://user-images.githubusercontent.com/10111024/172871986-c927cd2d-668c-439a-99c6-84744d42b40b.png)
![image](https://user-images.githubusercontent.com/10111024/172872189-3729bce0-6ab6-4884-bc27-9f0de6e5ef8b.png)

**Comment by bundfussr** [comment]
I would add a list of all files which need to be renamed and/or updated. For examples `tests/testthat.R` needs to be updated and `R/admiralext-package.R` needs to be renamed and updated.

I would also shorten the imports in the `DESCRIPTION` and `admiralext-package.R` file and only import very basic functions like `%>%`, `mutate()`, `select()`. And we should add admiral to both files.

Adding `R/globals.R` with a comment regarding the intention of this file would be helpful as well.

**Comment by bms63** [comment]
Hi all,

* I added `R/globals.R` and put in a short blurb about what it is
* Made  A Quick Start Guide on what to update and what to run
* Added a TOC to readme
* Brought over pharmaverse logo and appended to readme and for the site
* Updated R-CMD workflow
* I tried making a gh-pages for us to showcase the template to those inrested but not rendering correctly (@dinakar29) do you mind looking into

To-Do
* Update spelling workflow and file
* Update linter workflow and file
* Update man workflow
* Section on workflows and what they do and why it is important
* Set up devel branch
* add branch protection

**Comment by bms63** [comment]
Ha!  It worked.  

![image](https://user-images.githubusercontent.com/10111024/173139415-44e567a5-f194-4622-92ac-bc91240d7074.png)

**Comment by rossfarrugia** [comment]
great stuff @bms63!! <3

**Comment by bms63** [comment]
Hey @rossfarrugia.  Since we have a repo which contains all these issues and can capture the discussion there, can we just close this one out?

**Comment by bundfussr** [comment]
I have added some issues to [admiraltemplate](https://github.com/pharmaverse/admiraltemplate/issues) based on my experience with admiralonco and admiralroche.

**Comment by rossfarrugia** [comment]
@bms63 & @dinakar29 - appreciate if you could take a look over the new issues Stefan added: https://github.com/pharmaverse/admiraltemplate/issues/21
