### ISSUE TITLE
Documentation:  Update Team Roster

### ISSUE THREAD

**Issue by duniek** [pharmaverse/admiral#952]
### Please update your time allocation to each admiral package

**Comment by bms63** [comment]
@pharmaverse/admiral 

@thomas-neitmann I see we have a few pharmaverse teams floating around.  Is the one I am tagging above the one we should be using?  Do we need to add this to the onboarding checklist, i.e. add new member to github teams?  That way we can tag everyone in a discussion issue?

**Comment by rossfarrugia** [comment]
good spot Kamila! it should be `pharmaverse/admiral-devs` according to https://pharmaverse.github.io/admiral/articles/development_process.html, but check out https://github.com/orgs/pharmaverse/teams where it shows "admiral" team has most people in and "admiral-devs" only has Thomas.
@thomas-neitmann do you want to fix that so all are in devs and remove the "admiral" one, or do i need to as a pharmaverse admin?

also i'll update team roster sheet for admiralonco now.

**Comment by bms63** [comment]
I think we need to add Annie @yangc71, Samia @kabis-ops , Teckla @teckla-gsk to the github teams so we can tag them in discussion easier.

What about Rea, Tracey and Anna from Roche do they need to be added?

@upadhyor Did you have chance to update Team Roster?  Is Vince and Vinnod going to come onboard?

**Comment by rossfarrugia** [comment]
I'd suggest for Rena, Tracey and Anna that its fine not to add them to the github team. Rena and Tracey are contributing to the core admiral for a certain time to build up experience of how this works so that they can focus towards helping build an Ophtha package extension later, and Anna is doing this as a temporary initiative.

**Comment by bms63** [comment]
This seems like in good order.  Going to close out.
