### ISSUE TITLE
Onboaring:  Gillian Yin and Cloris Xue - Roche

### ISSUE THREAD

**Issue by yangc71** [pharmaverse/admiral#953]
### Onboarding tasks for Core (Roche-GSK) Team Members

- [ ] Given a tour of Github from a Core member
- [ ] Understand how to Create Issues and do a Pull Request
- [ ] Understand the Programming Strategy
- [ ] Read and understand [Developer Guides Articles](https://pharmaverse.github.io/admiral/index.html)
- [ ] Invited to all relevant meetings - Stand Ups, Retrospective, Sprint Planning, Question/Comments, Backlog, Community Meeting
- [ ] Given access to Box and relevant documents
- [ ] Given write access to Github Repository
- [ ] Slack channel invites to admiral and admiral_dev
- [ ] Introduction to Teams ways of working

### Onboarding tasks for non-Core Team Members

- [x] Given a tour of Github from a Core member
- [x] Understand how to Create Issues and do a Pull Request
- [x] Understand the Programming Strategy
- [x] Read and understand [Developer Guides Articles](https://pharmaverse.github.io/admiral/index.html)
- [x] Invited to all relevant meetings - Question/Comments, Community Meeting
- [x] Given write access to Github Repository
- [x] Slack channel invites to admiral
- [x] Introduction to Teams ways of working

**Comment by rossfarrugia** [comment]
@yangc71 - please can you onboard Cloris Xue at the same session as Gillian?

**Comment by bms63** [comment]
Their  first issue could be fixing the spelling mistake in onboarding tasks! .github/ISSUE_TEMPLATES

![image](https://user-images.githubusercontent.com/10111024/154481950-ee09b0e0-9d69-4ce5-a687-657b13f50222.png)
