### ISSUE TITLE
Turn codecov comments on 

### ISSUE THREAD

**Issue by statasaurus** [pharmaverse/admiral#956]
https://github.com/pharmaverse/admiral/blob/346733b012df8bb64a2b7708ea769faeae29223c/codecov.yml#L1

if we change this to at least 
`comment:
  require_changes: true
`
Then it will create a comment on a pull request if the code coverage changes. That will make it easier for people to see when there is a drop in coverage (i.e. people are putting in untested code)

**Comment by statasaurus** [comment]
For more information about the options you can read the [documentation ](https://docs.codecov.com/docs/pull-request-comments)

**Comment by thomas-neitmann** [comment]
That looks like a nice additon, indeed. Do you want to go ahead and implement this @statasaurus?

**Comment by thomas-neitmann** [comment]
@makropoa @wqrena @traceyxw This is another good first issue to pick up and get used to our dev process.

**Comment by thomas-neitmann** [comment]
I think only when the coverge changes is sufficient.
