### ISSUE TITLE
Change all references to <admiral.new> to <admiralnew>

### ISSUE THREAD

**Issue by statasaurus** [pharmaverse/admiral#968]
### Please select a category the issue is focused on?

Function Documentation, User Guides, Developer Guides

### Let us know where something needs a refresh or put your idea here!

We need to change all reference from _admiral.xxx_ to _admiralxxx_ (i.e. remove the dot) in order to align with the agreed upon package naming convention. **The impact will be if you search our repo for any mentions of admiral.test, admiral.onco or admiral.hiv - and then delete the dot from all of them.**

**Comment by rossfarrugia** [comment]
Also impacts ADaM templates that use admiral.test, and whoever takes on please also make an issue here https://github.com/pharmaverse/admiral.test/issues and update for this package which is a dependency of admiral. let's sync the updates before next releases and then update on CRAN also.

**Comment by rossfarrugia** [comment]
Added the good first issue to hopefully attract a contributor to take this on, as would be good to have this and the corresponding admiraltest issue (https://github.com/pharmaverse/admiral.test/issues/25) updated ready for next release end of April.
