### ISSUE TITLE
Documentation:  Typo in function naming

### ISSUE THREAD

**Issue by raqpau** [pharmaverse/admiral#969]
### Please select a category the issue is focused on?

User Guides

### Let us know where something needs a refresh or put your idea here!

There is a typo in: Creating ADSL ->Disposition Reason(s) (e.g. DCSREAS, DCSREASP)
[https://pharmaverse.github.io/admiral/articles/adsl.html#disposition_reason]

Function which is currently available in admiral is: [derive_var**s**_disposition_reason]

We have  's' missing in the vars in section which appears just after : 
The customized mapping function format_dcsreas() can now be passed to the main function:
derive_var_disposition_reason -> should be:  derive_vars_disposition_reason
with active link to the function

![image](https://user-images.githubusercontent.com/99408917/154967334-5b8b7d3e-901a-4e10-b9ad-4f6075d57e8f.png)

**Comment by thomas-neitmann** [comment]
@wqrena Please do *not* clsoe issues that are fixed by a PR manually. We decided to have them automatically be closed once they make it into the `main` branch, i.e. once the next version will be released.
