### ISSUE TITLE
Documentation:  derive_var_age_years output type of number

### ISSUE THREAD

**Issue by raqpau** [pharmaverse/admiral#970]
### Please select a category the issue is focused on?

Function Documentation

### Let us know where something needs a refresh or put your idea here!

derive_var_age_years  documentaion does not specify what is the format of the output variable (comparing to AAGE where it is stated it will be integer). 

In this function the result is a number with decimal places - in case if it is intended then in my opinion it should be specified why, I was expecting an integer as an output, not really sure why it is not (in the code we round tolower only the unit_var but not the new_var )

Link to: 
See also -> derive_vars_duration() 
should be added in the function documentation, the  derive_var_age_years is actually doing the same but the output is not integer

**Comment by bms63** [comment]
Include format here:  
![image](https://user-images.githubusercontent.com/10111024/215520015-aa934beb-d406-4b0e-8793-e38403c85d25.png)

**Comment by bms63** [comment]
@traceyxw still have time for this issue??

**Comment by bms63** [comment]
@pharmaverse/admiral can someone pick this up please?

**Comment by sophie-gem** [comment]
@bms63 I can pick this one up

**Comment by sophie-gem** [comment]
Can I just confirm - the output of `new_var` is currently numeric including decimal places. Are we wanting the result to be integer? Or just update the documentation to clearly state that the result is a decimal number?

**Comment by bundfussr** [comment]
@sophie-gem , it is intended that the result may be not integer. Thus just an update of the documentation is needed.

The function is intended to help deriving age categories. For categories like `"0-27 days (Newborns)"`, `"28 days to 23 months (Infants and Toddlers)"` the result should not be integer.

**Comment by sophie-gem** [comment]
Aha, right ok - this makes sense. Thanks @bundfussr!
