### ISSUE TITLE
Feature Request:  Provide summary of warnings

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#971]
### Feature Idea

Create a function which provides a list of all warnings and errors and the functions which issued them.

### Relevant Input

R script

### Relevant Output

console output or md file

### Reproducible Example/Pseudo Code

We love example code and it will speed up the process! REMINDER: no patient level data or company sensitive information should be shared via this open public issue

**Comment by bundfussr** [comment]
May be related to https://github.com/pharmaverse/admiral/issues/694

**Comment by bms63** [comment]
I think this could be done in a separate package - maybe a new one or a part of `timber `package?  I'd imagine you would want this to be a report for all the study's datasets and not just your own.  Sort of like an easy to look at validation report we have for the R packages.  

Also - if you use a log capturing package like `timber`, then it would have all the warnings, messages, and errors that happened when you run the program.

**Comment by thomas-neitmann** [comment]
Agree with @bms63. This seems out of scope for admiral but is certainly a great feature to have for clincial reporting. Have you tried {timber} @bundfussr? It captures all messages, warnings and errors along with `sessionInfo()`. Quite a useful log if you ask me.

**Comment by bms63** [comment]
Perhaps a vignette!  Showing how to use admiral interacting with timber.  that could generate feedback for additional enhancements to timber or build out a new more specific package for what you are envisioning @bundfussr

**Comment by thomas-neitmann** [comment]
This sounds like something I would expect to be covered in the oharmaverse end-to-end vignette. Fyi @statasaurus.

**Comment by thomas-neitmann** [comment]
Closing as out of scope for {admiral}.
