### ISSUE TITLE
Documentation:  Clarify constant_parameter and constant_by_vars in derive_derived_param()

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#972]
### Please select a category the issue is focused on?

Function Documentation

### Let us know where something needs a refresh or put your idea here!

Clarify `constant_parameter` and `constant_by_vars` in `derive_derived_param()`.
For example:
- move example from `constant_by_vars` to `constant_parameters`
- provide more details for `constant_parameters` either in the parameter description of in the details section
- reference the second example in the description of `constant_parameters` and `constant_by_vars`.

**Comment by rossfarrugia** [comment]
@bundfussr could this issue be suitable for good first issue label if you add a bit more detail to help a new contributor?

**Comment by bundfussr** [comment]
@rossfarrugia , I have added some details. However, I have implemented the function. So it is hard for me to identify what is missing in the description of the parameters. Most likely this is easier for a new contributor.
