### ISSUE TITLE
Documentation:  logo in .png format

### ISSUE THREAD

**Issue by pawelru** [pharmaverse/admiral#975]
### Please select a category the issue is focused on?

Other

### Let us know where something needs a refresh or put your idea here!

.jpg logo just looks bad on the dark-theme
![image](https://user-images.githubusercontent.com/12943682/155148076-52e24a78-7fa1-4c83-ba47-3bbad1f68cee.png)

as opposed to e.g. `dplyr` logo:
![image](https://user-images.githubusercontent.com/12943682/155148172-2bb6dd9a-c4f8-4afd-8db5-9ac955619db5.png)

**Comment by thomas-neitmann** [comment]
That looks quite poor indeed. The issue is not the file format (it actually it png) but rather the non-transparent background, though.

@rossfarrugia If your admin (who initially created the logo) can send me the butterfly image then I can re-create the logo directly in R and save as a scalable vector graphic with transparent background.

**Comment by rossfarrugia** [comment]
Sent @thomas-neitmann a couple of options by email. let me know if any work

**Comment by PoojaKumari05** [comment]
![favicon](https://user-images.githubusercontent.com/90273880/168225472-ead9dc4a-b5fc-4185-bd57-6a137303c8e1.png)
Hi @bms63 @thomas-neitmann - I have edited from an online site, let me know  your views - if this is what we were expecting, and also the quality.

**Comment by bms63** [comment]
This looks promising.  Can you embed into the Readme in a branch so we can take a look at it?

**Comment by PoojaKumari05** [comment]
![logo](https://user-images.githubusercontent.com/90273880/168727345-08f2fca1-bf15-42c7-bd0c-695f216c642d.png)

**Comment by PoojaKumari05** [comment]
> ![logo](https://user-images.githubusercontent.com/90273880/168727345-08f2fca1-bf15-42c7-bd0c-695f216c642d.png)

@rossfarrugia @bms63 @thomas-neitmann - this is the best resolution I could come up with online free tool. It's 600 dpi as per the site guide. Let me know what yours thoughts.

**Comment by rossfarrugia** [comment]
thanks Pooja - i'm fine to go with this.

**Comment by bms63** [comment]
Lets do it!
