### ISSUE TITLE
Feature Request:  compute_framingham

### ISSUE THREAD

**Issue by aehmann-gsk** [pharmaverse/admiral#977]
### Feature Idea

I am happy to help program function; 

#' Function to derive Framingham equation
#' #' 

### Relevant Input

Smoking flag, Treated for Hypertension flag, diabetes flag, age, sex, SBP, Total Chol, and HLDDIR

### Relevant Output

Framingham calculated result

### Reproducible Example/Pseudo Code

compute_framingham <- function(smokefl, trthypfl, diabetfl, 
                               age, sex, sbp, tchol, hdldir) {

  smokefn <-  if_else(smokefl == "Y", 1, 0, missing = 0)
  diabetfn <- if_else(trthypfl == "Y", 1, 0, missing = 0)
  sbpt <- if_else(trthypfl == "Y", sbp, 1, missing = 1)
  spbu <- if_else(trthypfl == "N", sbp, 1, missing = 1)
  
  logtc <- log(tchol)
  loghdl <- log(hdldir)
  logsbpt <- log(sbpt)
  logsbpu <- log(sbpu)
  
  aval <- case_when(
    sex == "F" ~ 1 - (0.95012 ^ exp((2.32888 * logage)
                                    + (1.20904 * logtc) 
                                    - (0.70833 * loghdl) 
                                    + (2.76157 * logsbpu) 
                                    + (2.82263 * logsbpt) 
                                    + (0.52873 * smokefn) 
                                    + (0.69154 * diabetfn) 
                                    - 26.1931)),
    sex == "M" ~ 1 - (0.88936 ^ exp((3.06117 * logage) 
                                    + (1.12370 * logtc) 
                                    - (0.93263 * loghdl) 
                                    + (1.93303 * logsbpu) 
                                    + (1.99881 * logsbpt) 
                                    + (0.65451 * smokefn) 
                                    + (0.57367 * diabetfn) 
                                    - 23.9802)))
  
  aval
  
}

**Comment by thomas-neitmann** [comment]
Thanks @aehmann-gsk! That looks interesting. Which ADaM dataset is this applicable to? We'd also need an accompaying `derive_param_framingham()` function.

**Comment by aehmann-gsk** [comment]
@thomas-neitmann We have a cardio risk factors dataset which is BDS where this is calculated at a visit level.  However, this is also used as a baseline calculation in ADSL (sometimes used as a baseline covariate in modeling or shown as a baseline characteristic).

**Comment by aehmann-gsk** [comment]
@thomas-neitmann Here is the CDISC CT for it:
![image](https://user-images.githubusercontent.com/82041175/155327165-7d3a10e3-7c40-4519-920d-beabffe04d69.png)

**Comment by aehmann-gsk** [comment]
@thomas-neitmann I have time today/tomorrow.  Is it ok if I create a pull request and draft this function with an associated derive_param?

**Comment by koegerr** [comment]
We won't have this in the latest release

**Comment by bundfussr** [comment]
@bms63 , why did you close it? It seems that it is not merged yet.

**Comment by bms63** [comment]
done in mistake.  i closed any with linked PRs
