### ISSUE TITLE
Bug: remove the spread function

### ISSUE THREAD

**Issue by statasaurus** [pharmaverse/admiral#982]
### What happened?

Not sure if this is techinically a bug, but the spread function has been [superseded](https://tidyr.tidyverse.org/reference/spread.html) we should move away from it now. As there is a decent chance it will be deprecated at some point 

### Session Information

Place the console output here

### Reproducible Example

Please give us as many details as you can! The faster we can recreate the bug, the faster we can get a fix in the works.  Warning, Error Messages and Screenshots are also great.

**Comment by bms63** [comment]
Is it the same for the gather function?

**Comment by statasaurus** [comment]
> Is it the same for the gather function?
yes

**Comment by bundfussr** [comment]
As far as I remember we can not replace these functions because the new functions `pivot_wider()` and `pivot_longer()` are not available for all R versions which are used in the R-CMD checks for admiral.

See also discussion in https://github.com/pharmaverse/admiral/issues/818.

**Comment by thebioengineer** [comment]
Hey @bundfussr - the tidyverse team tends to make sure their code is back-compatible, so in general that shouldn't be a concern.  As @thomas-neitmann mentioned in that thread you linked, tidyverse is compatible back to 3.4, and admiral only checks back to 3.5  Is there specific evidence for pivot_wider() failing in testing for admiral?

**Comment by thomas-neitmann** [comment]
@thebioengineer We not only test on older R versions but also install package versions available at the release date of the respective version using MRAN snapshots. So on R v3.5 we're currently testing with package versions from 2018 (which pre-dates the `pivot_*()` functions). We'll likely drop testing on v3.5 going forward (see discussion in #986) so we might be able to get rid of `spread()` and `gather()`.

**Comment by thebioengineer** [comment]
Interesting choice, thanks for sharing @thomas-neitmann . I appreciate the efforts to ensure back compatibility. Dropping the past versions and relooking at how much support for older packages with Admiral is definitely a good thing to think about. If an org is still using such old software (R3.5, packages from 2018), what is the likelihood of them updating their validated environment to include admiral? And at that point, it would make sense to update all the dependencies of Admiral or just go through the effort of another validation, depending on the pains of a full system validation vs amendment, (my opinions)
