### ISSUE TITLE
R CMD check

### ISSUE THREAD

**Issue by thomas-neitmann** [pharmaverse/admiral#986]
Currently we are running `R CMD check` on R version 3.5, 3.6 and the latest release (currently 4.1) along with package versions from the time the respective R version was released. Keeping the backward compatibility with the v3.5 environment (with package versions from 2018) is increasingly proving to be difficult.

I've asked which R versions people are using in their GxP environments in our Slack channel. v3.5 only got a single vote so it's probably safe to "discard".

I would suggest that going forward we test on

- 3.6.3 with package versions from 2020-02-29
- 4.0.5 with package versions from 2021-03-31
- 4.1.x with latest package versions

Any thoughts @pharmaverse/admiral-devs

**Comment by bundfussr** [comment]
That's a good idea.

For the future I would propose a rule like "admiral does not support R and package versions older than two years". Then it is clear when GxP environments need to be updated to be able to use the latest admiral version.

**Comment by thomas-neitmann** [comment]
I would have suggested to always support the latest 3 versions such that once R v4.2 is out we would only test on v4.0, v4.1 and v4.2.

**Comment by bundfussr** [comment]
Makes sense.

We should add it to our documentation.

**Comment by bms63** [comment]
For documentation - We are adding this to Readme and somewhere else - Developer Guide and maybe FAQs?

I feel like this is a pharmaverse best practice that we should codify across all packages.  #929

**Comment by thomas-neitmann** [comment]
We should definitely make this clear in our documentation. Certainly should also be added as an expectation in our README.
