### ISSUE TITLE
Documentation:  New Issue template

### ISSUE THREAD

**Issue by duniek** [pharmaverse/admiral#996]
### Please select a category the issue is focused on?

Other

### Let us know where something needs a refresh or put your idea here!

I suggest to add a new issue template for general issues with two headers as below. Default label: <not ready>, default project: <admiral core board>, default triage: backlog column. 

### Definition of Done:
- [ ]

**Comment by bms63** [comment]
I'm fine with adding a General Issue Template.  You can also just create a regular issue using 

![image](https://user-images.githubusercontent.com/10111024/157742821-1d5d9e93-1871-4c8f-aa81-8f285133ab95.png)

@pharmaverse/admiral Any thoughts?
