### ISSUE TITLE
Documentation:  Guidance for tagging pharmaverse/admiral-devs in PR review

### ISSUE THREAD

**Issue by amsmith214** [pharmaverse/admiral#997]
### Please select a category the issue is focused on?

User Guides

### Let us know where something needs a refresh or put your idea here!

Add a line to pr_review_guidance vignette (https://pharmaverse.github.io/admiral/articles/pr_review_guidance.html) describing the exact tag for the admiral dev team (pharmaverse/admiral-devs) to use when new contributors would like their PR reviewed and don't already have someone lined up.

**Comment by bms63** [comment]
Already in the Development Process vignette 
![image](https://user-images.githubusercontent.com/10111024/156814946-8450f556-5b12-4bf7-8873-bfa3da56a187.png)

**Comment by amsmith214** [comment]
what's the WR for shortest issue lifespan?
